INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_austin-austin-mahjong-social', 'Austin Mahjong Social', 'austin-austin-mahjong-social', 'Austin American Mahjong social community offering classes, private lessons, events and leagues.', (SELECT id FROM City WHERE name = 'Austin' AND state = 'TX'), NULL, 'https://austinmahjongsocial.net/', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, 175, 'Fall 2026 daytime/evening leagues; classes and private lessons.', 'https://austinmahjongsocial.net/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_austin-mahj-house-austin', 'Mahj House Austin', 'austin-mahj-house-austin', 'American Mahjong studio in West Lake Hills serving Austin with beginner classes, open play and social nights.', (SELECT id FROM City WHERE name = 'Austin' AND state = 'TX'), '3316 Bee Caves Road Unit D, West Lake Hills, TX 78746', 'https://www.mahjhouseaustin.com/', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, 140, 'Open play, beginner series, guided play and membership; location is West Lake Hills.', 'https://www.mahjhouseaustin.com/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_austin-steiner-mahjong', 'Steiner Mahjong', 'austin-steiner-mahjong', (SELECT id FROM City WHERE name = 'Austin' AND state = 'TX'), 'https://www.steinermahjong.com/', NULL, 1, 1, 0, 1, 99, 'Private $99/session; group $249/session. Beginner-friendly American Mahjong.', 'https://www.steinermahjong.com/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_austin-austin-mahjong-social', 'Austin Mahjong Social', 'austin-austin-mahjong-social', (SELECT id FROM City WHERE name = 'Austin' AND state = 'TX'), 'https://austinmahjongsocial.net/', NULL, 1, 1, 0, 1, NULL, 'Classes, private lessons, social events and leagues.', 'https://austinmahjongsocial.net/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_austin-intro-to-mahjong-20261016', 'Intro to Mahjong', 'austin-intro-to-mahjong-20261016', '2026-10-16 00:00:00', '10:00', '12:00', 'Local & Wild, 11300 Jollyville', (SELECT id FROM City WHERE name = 'Austin' AND state = 'TX'), (SELECT id FROM Club WHERE name = 'itsamahjing' AND cityId = (SELECT id FROM City WHERE name = 'Austin' AND state = 'TX')), NULL, 'LESSON', 1, NULL, NULL, 'https://www.itsamahjing.com/events', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_austin-an-american-mahjong-social-tournament-20261027', 'An American Mahjong Social Tournament', 'austin-an-american-mahjong-social-tournament-20261027', '2026-10-27 00:00:00', '16:00', '19:00', 'The ABGB', (SELECT id FROM City WHERE name = 'Austin' AND state = 'TX'), (SELECT id FROM Club WHERE name = '3 Bee Mahj' AND cityId = (SELECT id FROM City WHERE name = 'Austin' AND state = 'TX')), NULL, 'TOURNAMENT', 0, NULL, NULL, 'https://theabgb.com/events', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
