INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_boston-mahjong-theory', 'Mahjong Theory', 'boston-mahjong-theory', (SELECT id FROM City WHERE name = 'Boston' AND state = 'MA'), 'https://www.mahjongtheory.com/', 'maria@mahjongtheory.com', 1, 1, 0, 1, NULL, 'American Mahjong instruction, open play and corporate events; lessons about two hours.', 'https://www.mahjongtheory.com/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_boston-south-shore-mahjong', 'South Shore Mahjong', 'boston-south-shore-mahjong', (SELECT id FROM City WHERE name = 'Boston' AND state = 'MA'), 'https://southshoremahjong.com/', 'hello@southshoremahjong.com; 617-378-5532', 1, 1, 0, 1, NULL, 'Classes, leagues, open play and events; studio is in Cohasset and serves Boston area.', 'https://southshoremahjong.com/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_boston-so-bam-fun-boston', 'So Bam Fun Boston', 'boston-so-bam-fun-boston', (SELECT id FROM City WHERE name = 'Boston' AND state = 'MA'), 'https://sobamfun.com/boston', 'hello@sobamfun.com', 1, 1, 0, 1, NULL, 'American Mahjong lessons, private/social events and corporate events across Boston.', 'https://sobamfun.com/boston', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_boston-go-team-pink-and-green-open-play-league-20260929', 'Go Team Pink and Green! Open Play @ League', 'boston-go-team-pink-and-green-open-play-league-20260929', '2026-09-29 00:00:00', '19:00', '22:00', 'Sol De Mexico, Milford, MA', (SELECT id FROM City WHERE name = 'Boston' AND state = 'MA'), (SELECT id FROM Club WHERE name = 'Bay State Bam' AND cityId = (SELECT id FROM City WHERE name = 'Boston' AND state = 'MA')), NULL, 'OPEN_PLAY', 0, NULL, NULL, 'https://www.baystatebam.com/upcoming-events', '2026-09-28', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_boston-pung-kong-pep-rally-open-play-fall-league-20261006', 'Pung, Kong, Pep Rally! Open Play @ Fall League', 'boston-pung-kong-pep-rally-open-play-fall-league-20261006', '2026-10-06 00:00:00', '19:00', '22:00', 'Sol De Mexico, Milford, MA', (SELECT id FROM City WHERE name = 'Boston' AND state = 'MA'), (SELECT id FROM Club WHERE name = 'Bay State Bam' AND cityId = (SELECT id FROM City WHERE name = 'Boston' AND state = 'MA')), NULL, 'OPEN_PLAY', 0, NULL, NULL, 'https://www.baystatebam.com/upcoming-events', '2026-09-28', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
