INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_miami-mahj-in-miami', 'Mahj in Miami', 'miami-mahj-in-miami', 'Miami American Mahjong community offering beginner classes, open-play socials, private lessons and events.', (SELECT id FROM City WHERE name = 'Miami' AND state = 'FL'), NULL, 'https://mahjinmiami.com/', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, 20, 'Mahj + Mingle open play: $20 / 2 hours.', 'https://mahjinmiami.com/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_miami-mahj-in-miami', 'Mahj in Miami', 'miami-mahj-in-miami', (SELECT id FROM City WHERE name = 'Miami' AND state = 'FL'), 'https://mahjinmiami.com/', 'abby@mahjinmiami.com', 1, 1, 0, 1, 215, 'Mahj 101 $215 for two 2.5-hour classes; Mahj 102 $75; private lessons by inquiry.', 'https://mahjinmiami.com/classes', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_miami-so-bam-fun-miami', 'So Bam Fun Miami', 'miami-so-bam-fun-miami', (SELECT id FROM City WHERE name = 'Miami' AND state = 'FL'), 'https://sobamfun.com/', 'hello@sobamfun.com', 1, 1, 0, 1, NULL, 'Beginner-friendly American Mahjong lessons and events across Miami.', 'https://sobamfun.com/', '2026-09-28', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_miami-mahj-101-with-mahj-in-miami-20261006', 'Mahj 101 with Mahj in Miami', 'miami-mahj-101-with-mahj-in-miami-20261006', '2026-10-06 00:00:00', '11:00', '13:30', 'Miami Beach Botanical Garden, 2000 Convention Center Dr', (SELECT id FROM City WHERE name = 'Miami' AND state = 'FL'), (SELECT id FROM Club WHERE slug = 'miami-mahj-in-miami'), NULL, 'LESSON', 1, 215, NULL, 'https://www.miamiandbeaches.com/event/mahj-101-with-mahj-in-miami/42791', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_miami-mahjong-game-101-20261015', 'Mahjong Game 101', 'miami-mahjong-game-101-20261015', '2026-10-15 00:00:00', '18:30', '20:30', 'Hilton Aventura Miami, 2885 NE 191st St', (SELECT id FROM City WHERE name = 'Miami' AND state = 'FL'), NULL, NULL, 'LESSON', 1, 65, NULL, 'https://happeningnext.com/event/mahjong-game-101-eid1ef0l5992uma', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
