INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_seattle-american-mahjong-at-the-j', 'American Mahjong at the J', 'seattle-american-mahjong-at-the-j', 'American Mahjong drop-in play and beginner classes at the Stroum Jewish Community Center of Greater Seattle.', (SELECT id FROM City WHERE name = 'Seattle' AND state = 'WA'), '3801 East Mercer Way, Mercer Island, WA 98040', 'https://sjcc.org/series/mahjong-at-the-j/', '206-232-7115', 'info@sjcc.org', NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Mondays 6:00-8:30pm drop-in play; daytime free play 1:00-3:00pm; beginner classes ($25-35) offered periodically; annual tournament.', 'https://sjcc.org/series/mahjong-at-the-j/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_seattle-pnw-mahj', 'PNW MAHJ', 'seattle-pnw-mahj', 'American Mahjong open play group meeting at Third Place Commons, welcoming players to connect, learn, and play.', (SELECT id FROM City WHERE name = 'Seattle' AND state = 'WA'), 'Third Place Commons, 17171 Bothell Way NE, Lake Forest Park, WA 98155', NULL, NULL, NULL, NULL, NULL, 1, 0, 1, 1, 0, 0, NULL, 'Wednesdays 5:00pm at Third Place Commons.', 'https://mahjmahj.co/events/seattle', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_seattle-mah-jongg-american-version-senior-center-of-west-seattle', 'Mah Jongg: American Version (Senior Center of West Seattle)', 'seattle-mah-jongg-american-version-senior-center-of-west-seattle', 'American Mahjong open play for beginners and all levels at the Senior Center of West Seattle (The Center for Active Living).', (SELECT id FROM City WHERE name = 'Seattle' AND state = 'WA'), '4217 SW Oregon St, Seattle, WA 98116', 'https://wscenter.org/', NULL, NULL, NULL, NULL, 1, 0, 1, 1, 0, 0, 2, 'Wednesdays 1:00-3:00pm; $1 members / $2 non-members.', 'https://westseattleblog.com/event/american-mah-jongg-in-west-seattle/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_seattle-hope-goldberg-eastside-mahjongg', 'Hope Goldberg (Eastside Mahjongg)', 'seattle-hope-goldberg-eastside-mahjongg', (SELECT id FROM City WHERE name = 'Seattle' AND state = 'WA'), 'https://eastsidemahjongg.wixsite.com/eastside-mahjongg-1', 'eastsidemahjongg@gmail.com; 404-320-2007', 1, 1, 0, 1, NULL, 'Teaches NMJL-rules American Mahjong; 20+ years experience; 3-week beginner lesson packages for private groups; serves Greater Seattle and Park City area.', 'https://eastsidemahjongg.wixsite.com/eastside-mahjongg-1', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_seattle-american-mahjong-open-play-at-third-place-commons-20261007', 'American Mahjong Open Play at Third Place Commons', 'seattle-american-mahjong-open-play-at-third-place-commons-20261007', '2026-10-07 00:00:00', '17:00', NULL, 'Third Place Commons, 17171 Bothell Way NE, Lake Forest Park', (SELECT id FROM City WHERE name = 'Seattle' AND state = 'WA'), (SELECT id FROM Club WHERE slug = 'seattle-pnw-mahj'), NULL, 'OPEN_PLAY', 1, NULL, NULL, 'https://mahjmahj.co/events/seattle', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
