INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_denver-rocky-mountain-mahjong', 'Rocky Mountain Mahjong', 'denver-rocky-mountain-mahjong', 'NMJL-rules American Mahjong group offering beginner lessons, mentoring, and weekly open play in Denver.', (SELECT id FROM City WHERE name = 'Denver' AND state = 'CO'), NULL, 'https://rockymountainmahjong.com/', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Weekly open play in Denver; private and monthly beginner group lessons; financial hardship accommodations available.', 'https://rockymountainmahjong.com/mahj-with-us', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_denver-jcc-denver-beginning-mahjong', 'JCC Denver (Beginning Mahjong)', 'denver-jcc-denver-beginning-mahjong', 'Multi-week beginner Mahjong course at the Jewish Community Center of Denver, covering tiles, passing, and how to read the card.', (SELECT id FROM City WHERE name = 'Denver' AND state = 'CO'), '350 S. Dahlia St., Denver, CO 80246', 'https://www.jccdenver.org/programs/games/beginning-mahjong/', '303.399.2660', NULL, NULL, NULL, 1, 1, 0, 1, 0, 0, NULL, 'Multi-week seasonal course; new sessions start roughly quarterly. Registration required.', 'https://www.jccdenver.org/programs/games/beginning-mahjong/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_denver-mahjong-social-club', 'Mahjong Social Club', 'denver-mahjong-social-club', 'Dedicated American Mahjong space in Denver offering drop-in open play, beginner classes, guided play, and private lessons.', (SELECT id FROM City WHERE name = 'Denver' AND state = 'CO'), '2000 S Osage St, Denver, CO 80223', 'https://www.mahjongsocialclub-denver.com/', '(216) 210-1295', 'mahjongsocialclub.den@gmail.com', NULL, NULL, 1, 1, 1, 1, 0, 0, 15, 'Drop-in play $15/2hr session; beginner classes $50; guided play $30; unlimited monthly $100.', 'https://www.mahjongsocialclub-denver.com/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_denver-mahjong-standard', 'Mahjong Standard', 'denver-mahjong-standard', 'American Mahjong open play series at rotating South Denver Metro bars and restaurants, plus in-home lessons; open play sessions are geared toward players who already know the basics.', (SELECT id FROM City WHERE name = 'Denver' AND state = 'CO'), NULL, 'https://mahjongstandard.com/', NULL, NULL, NULL, NULL, 0, 1, 1, 1, 0, 0, 35, 'Rotating weekly/biweekly open play sessions ($20-60/session) across South Denver Metro venues; in-home lessons for beginners available separately.', 'https://mahjongstandard.com/open-play', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_denver-kim-ruvolo-mile-high-mahjong', 'Kim Ruvolo (Mile High Mahjong)', 'denver-kim-ruvolo-mile-high-mahjong', (SELECT id FROM City WHERE name = 'Denver' AND state = 'CO'), 'https://www.milehighmahj.com/', 'hello@milehighmahj.com', 1, 1, 0, 1, 400, 'Private lessons designed for zero-experience beginners; $400 flat for 1-5 people ($80/person for 6-8); includes NMJL card. Guided play follow-up sessions also offered. Serves Denver metro incl. Arvada, Golden, Lakewood, Wheat Ridge; $100 travel fee beyond 20 miles from downtown Denver.', 'https://www.milehighmahj.com/learn-to-play-mahjong', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_denver-guess-company-christmas-mahjong-classic-20261024', 'Guess & Company Christmas Mahjong Classic', 'denver-guess-company-christmas-mahjong-classic-20261024', '2026-10-24 00:00:00', '10:30', '15:30', 'Guess & Company Warehouse, Denver', (SELECT id FROM City WHERE name = 'Denver' AND state = 'CO'), NULL, NULL, 'TOURNAMENT', 0, NULL, 'https://www.eventbrite.com/e/guess-company-christmas-mahjong-classic-tickets-1994585580163', 'https://www.eventbrite.com/e/guess-company-christmas-mahjong-classic-tickets-1994585580163', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_denver-open-play-at-postino-highlands-ranch-20260930', 'Open Play at Postino Highlands Ranch', 'denver-open-play-at-postino-highlands-ranch-20260930', '2026-09-30 00:00:00', '18:00', '20:00', 'Postino, Highlands Ranch', (SELECT id FROM City WHERE name = 'Denver' AND state = 'CO'), (SELECT id FROM Club WHERE slug = 'denver-mahjong-standard'), NULL, 'OPEN_PLAY', 0, 35, NULL, 'https://mahjongstandard.com/open-play', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
