INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_philadelphia-mahjong-at-old-york-road-temple-beth-am', 'Mahjong at Old York Road Temple-Beth Am', 'philadelphia-mahjong-at-old-york-road-temple-beth-am', 'Weekly American Mahjong class and open play nights at Old York Road Temple-Beth Am; class graduates receive a token for free open play.', (SELECT id FROM City WHERE name = 'Philadelphia' AND state = 'PA'), '971 Old York Rd, Abington, PA 19001', 'https://www.oyrtbetham.org/', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Classes and open play nights held Wednesdays.', 'https://www.jewishexponent.com/mahjong-brings-people-together-at-old-york-road-temple-beth-am/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_philadelphia-mahjwithlee', 'MahjWithLee', 'philadelphia-mahjwithlee', 'American Mahjong studio offering NMJL-rules Mahj 101/102 lessons and play-only open sessions for experienced players.', (SELECT id FROM City WHERE name = 'Philadelphia' AND state = 'PA'), '653 Skippack Pike Ste 100, Blue Bell, PA 19422', 'https://mahjwithlee.com/', NULL, 'mahjwithlee@gmail.com', NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Mahj 101 (basics, Charleston, full game play) and Mahj 102 (strategy/etiquette) lessons; separate play-only open sessions; doors open 15 min before start.', 'https://mahjwithlee.com/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_philadelphia-gems-at-the-j-kaiserman-jcc', 'Gems at the J (Kaiserman JCC)', 'philadelphia-gems-at-the-j-kaiserman-jcc', 'Weekly American Mahjong club at the Kaiserman JCC, facilitated by volunteers who teach rules to new players alongside experienced ones.', (SELECT id FROM City WHERE name = 'Philadelphia' AND state = 'PA'), '45 Haverford Rd, Wynnewood, PA 19096', 'https://www.phillyjcc.com/gems-mahjong-club-registration/', '(610) 896-7770', 'kaiserman@phillyjcc.com', NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Thursdays 1:00-3:00pm (except holidays) in the Kaiserman JCC back lobby.', 'https://www.phillyjcc.com/gems-mahjong-club-registration/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_philadelphia-julie-shuster-philly-mahj', 'Julie Shuster (Philly Mahj)', 'philadelphia-julie-shuster-philly-mahj', (SELECT id FROM City WHERE name = 'Philadelphia' AND state = 'PA'), 'https://phillymahj.com/', 'phillymahj@gmail.com', 1, 1, 0, 1, 90, 'Individual lessons $90/hr; group rates $35-45/person/hr depending on size; beginners'' workshop $70/person (2 hrs, incl. snacks/drinks); groups up to 24 people; corporate events offered.', 'https://phillymahj.com/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_philadelphia-leslie-mahj-and-mingle-with-leslie', 'Leslie (Mahj and Mingle with Leslie)', 'philadelphia-leslie-mahj-and-mingle-with-leslie', (SELECT id FROM City WHERE name = 'Philadelphia' AND state = 'PA'), 'https://www.mahjandminglewithleslie.com/', '302-858-1231', 1, 1, 0, 1, NULL, 'OMM Certified American Mahjong instructor; welcoming space for players of all skill levels.', 'https://meetups.americanmahjonggassociation.com/united-states/philadelphia/omm-certified-instructor/mahj-and-mingle-with-leslie', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
