INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_atlanta-le-mahj-club', 'Le Mahj Club', 'atlanta-le-mahj-club', 'American Mahjong club hosting 101/102 beginner lessons and casual open-play socials at venues around Alpharetta, Roswell, and Milton; instructors are Oh My Mahjong certified.', (SELECT id FROM City WHERE name = 'Atlanta' AND state = 'GA'), NULL, 'https://lemahjclub.com/', NULL, 'lemahjclub@gmail.com', NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Rotating events at partner venues around metro Atlanta (Alpharetta, Roswell, Milton); 101/102 lesson courses plus casual open-play socials.', 'https://lemahjclub.com/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_atlanta-mahj-studios', 'Mahj Studios', 'atlanta-mahj-studios', 'Membership American Mahjong club in Buckhead offering beginner lessons, guided play, and socials, plus automatic-table access.', (SELECT id FROM City WHERE name = 'Atlanta' AND state = 'GA'), '2300 Peachtree Road, Suite C101, Atlanta, GA 30309', 'https://www.mahjstudios.com/', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Membership-based; remaining tables released to non-members about a week in advance; beginner lessons and guided play offered.', 'https://www.mahjstudios.com/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_atlanta-katherine-mansfield-fortner-my-magnolia-mahjongg', 'Katherine Mansfield Fortner (My Magnolia Mahjongg)', 'atlanta-katherine-mansfield-fortner-my-magnolia-mahjongg', (SELECT id FROM City WHERE name = 'Atlanta' AND state = 'GA'), 'https://mymagnoliamahjongg.com/', 'mymagnoliamahjongg@gmail.com', 1, 1, 0, 1, 80, 'Mahjongg 101 $80/person, 102 $70/person, Guided Play $50/person (all with a $400 group minimum); also hosts parties, corporate events, and retreats.', 'https://mymagnoliamahjongg.com/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_atlanta-celesta-house-of-mahjong-atl', 'Celesta (House of Mahjong ATL)', 'atlanta-celesta-house-of-mahjong-atl', (SELECT id FROM City WHERE name = 'Atlanta' AND state = 'GA'), 'https://www.houseofmahjongatl.com/', NULL, 1, 1, 0, 1, 120, 'Introduction to Mahjong (private, $120/person, 3 hrs, min. 8 people); also Refinement (NMJL card/strategy, $65/person), Guided Play ($50/person), and Lil'' Mahj for kids/easier start. Travel fee outside zip 30307.', 'https://www.houseofmahjongatl.com/services', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_atlanta-luci-buckhead-mahjong-club', 'Luci (Buckhead Mahjong Club)', 'atlanta-luci-buckhead-mahjong-club', (SELECT id FROM City WHERE name = 'Atlanta' AND state = 'GA'), NULL, 'buckheadmahjongclub@gmail.com', 1, 1, 0, 1, NULL, 'NMJL-style American Mahjong instruction; over two decades of experience; also organizes tournaments, corporate events, and fundraisers across GA and the Palm Beach area.', 'https://themahjongline.com/pages/buckhead-mahjong-club', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
