INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_san-diego-beginners-american-mahjong-bam', 'Beginners American Mahjong (BAM!)', 'san-diego-beginners-american-mahjong-bam', 'American Mahjong beginner classes and guided play based in Scripps Ranch, with sessions offered throughout San Diego from Downtown to Carlsbad.', (SELECT id FROM City WHERE name = 'San Diego' AND state = 'CA'), NULL, 'https://www.beginnersmahjong.com/', NULL, 'bam@beginnersmahjong.com', NULL, NULL, 1, 1, 0, 1, 0, 0, NULL, '3-lesson beginner class series (afternoon 1-3:30pm or evening 6-8:30pm slots); separate Guided Play sessions for class graduates; custom classes available at your home/office/clubhouse.', 'https://www.beginnersmahjong.com/schedule', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_san-diego-coastal-mahjong-club-of-san-diego', 'Coastal Mahjong Club of San Diego', 'san-diego-coastal-mahjong-club-of-san-diego', 'Weekly American Mahjong (NMJL) open play group meeting at venues across San Diego''s North Coast — Del Mar, Carmel Valley, Encinitas, and La Jolla.', (SELECT id FROM City WHERE name = 'San Diego' AND state = 'CA'), NULL, NULL, NULL, 'ochobam.mahj@gmail.com', NULL, NULL, 1, 0, 1, 1, 0, 0, 12, 'Weekly sessions rotating across North Coast venues; drop-in $12/session or $32/month unlimited; bring current NMJL card or buy one on-site ($15); new players should message ahead for an intro session.', 'https://www.heylo.com/g/eb26b636-aa77-4608-97f3-a3c2dfe1f6df', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_san-diego-grace-decker-san-diego-american-mah-jongg-meetup', 'Grace Decker (San Diego American Mah Jongg Meetup)', 'san-diego-grace-decker-san-diego-american-mah-jongg-meetup', (SELECT id FROM City WHERE name = 'San Diego' AND state = 'CA'), NULL, 'graceldecker@gmail.com', 0, 1, 0, 1, 195, '3-session beginner course teaching NMJL rules and guidelines, $195 for all 3 sessions plus $15 for the current NMJL card.', 'https://www.meetup.com/san-diego-americanmah-jongg-meetup/', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_san-diego-carol-cohn', 'Carol Cohn', 'san-diego-carol-cohn', (SELECT id FROM City WHERE name = 'San Diego' AND state = 'CA'), NULL, 'ccohn1@gmail.com; 619.708.7760', 1, 1, 0, 1, NULL, 'American Mahjong for Beginners 6-week course, Thursdays 10:00am-12:30pm, in the San Diego/Mission Valley area.', 'https://sandiegomagazine.com/community-event/american-mahjong-for-beginners-6-week-course-3/', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_san-diego-sandra-novack', 'Sandra Novack', 'san-diego-sandra-novack', (SELECT id FROM City WHERE name = 'San Diego' AND state = 'CA'), NULL, 'sandra.novack31@gmail.com', 1, 1, 0, 1, NULL, 'Teaches American Mah Jongg (NMJL rules) in the San Diego area.', 'https://wherethewindsblow.com/teachers/', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
