INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_nashville-gordon-jewish-community-center-mah-jongg', 'Gordon Jewish Community Center Mah Jongg', 'nashville-gordon-jewish-community-center-mah-jongg', 'American Mah Jongg classes at Gordon JCC using official National Mah Jongg League rules', (SELECT id FROM City WHERE name = 'Nashville' AND state = 'TN'), '801 Percy Warner Blvd., Nashville, TN 37205', 'https://www.nashvillejcc.org/', '615-356-7170', 'info@nashvillejcc.org', NULL, NULL, 1, 1, 0, 1, 0, 0, NULL, 'Tuesdays 1–3 PM; Sep 8, 15, 22, 29 and Oct 13, 20, 27 and Nov 3; registration required; members $150, non-members $175 including current card', 'https://www.nashvillejcc.org/adults/classes-groups/', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_nashville-the-mahjong-club', 'The Mahjong Club', 'nashville-the-mahjong-club', 'Dedicated mahjong space in Brentwood with daily open play, classes, events and leagues', (SELECT id FROM City WHERE name = 'Nashville' AND state = 'TN'), '130 Wilson Pike Circle, Brentwood, TN 37027', 'https://www.mahjongclubtn.com/', '615-374-6652', NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Mon–Wed & Fri 10 AM–8 PM; Thu 2–8 PM; Sat 10 AM–4 PM; classes/events require signup; drop-in tables available to non-members', 'https://www.mahjongclubtn.com/', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_nashville-brentwood-mah-jongg-club', 'Brentwood Mah Jongg Club', 'nashville-brentwood-mah-jongg-club', 'Recurring American Mahjong open play at the John P. Holt Brentwood Library', (SELECT id FROM City WHERE name = 'Nashville' AND state = 'TN'), '8109 Concord Road, Brentwood, TN 37027', 'https://library.brentwoodtn.gov/', '615-371-0090', NULL, NULL, NULL, 1, 0, 1, 1, 0, 0, NULL, 'Mondays 12:30–3:30 PM; all players welcome; bring a set; no registration reported', 'https://linktr.ee/thenolomahjclub', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_nashville-williamson-county-enrichment-center-american-mahjong', 'Williamson County Enrichment Center American Mahjong', 'nashville-williamson-county-enrichment-center-american-mahjong', 'County senior-center American Mahjong open play for ages 55+', (SELECT id FROM City WHERE name = 'Nashville' AND state = 'TN'), '110 Everbright Ave., Franklin, TN 37064', 'https://www.wcparksandrec.com/', '615-786-0186', NULL, NULL, NULL, 1, 0, 1, 1, 0, 0, NULL, 'Wednesdays 9 AM–12 PM; 55+; walk-in; general admission or free with WCPR Pass', 'https://fliphtml5.com/WilliamsonCountyParks/Winter-2025-26-Newsletter---final-v2/', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_nashville-mahj-house-society-at-fork-of-the-south', 'Mahj House Society at Fork of the South', 'nashville-mahj-house-society-at-fork-of-the-south', 'American Mahjong social club with recurring open play and beginner/private lesson options in Franklin', (SELECT id FROM City WHERE name = 'Nashville' AND state = 'TN'), '230 Franklin Rd., Building 8, Franklin, TN 37064', 'https://www.forkofthesouthliving.com/mahjong-1', '615-497-2402', NULL, NULL, NULL, 1, 1, 1, 1, 0, 1, NULL, 'Mahjong Mondays every Monday 5–7 PM; complimentary open play with advance reservation; private beginner lessons available', 'https://www.forkofthesouthliving.com/mahjong-1', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_nashville-mahjong-night-at-the-regal-room', 'Mahjong Night at The Regal Room', 'nashville-mahjong-night-at-the-regal-room', 'Recurring Sunday open-play venue in Nolensville; local Nashville-area American Mahjong directory points to the venue', (SELECT id FROM City WHERE name = 'Nashville' AND state = 'TN'), '7180 Nolensville Rd Suite 1G, Nolensville, TN 37135', 'https://www.theregalroombyhs.com/', NULL, NULL, NULL, NULL, 1, 0, 1, 1, 0, 1, 0, 'Sundays 6–9 PM, excluding holidays; individual RSVP required; bring one set per four players', 'https://www.theregalroombyhs.com/event-details/mahjong-night-2026-08-30-18-00', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_nashville-so-bam-fun', 'So Bam Fun', 'nashville-so-bam-fun', (SELECT id FROM City WHERE name = 'Nashville' AND state = 'TN'), 'https://sobamfun.com/nashville/', 'https://sobamfun.com/nashville/', 1, 1, 0, 1, 300, 'American Mahjong / NMJL; private 2-hour group lessons brought to home, apartment or private venue; no experience needed; group lessons start at $300', 'https://sobamfun.com/nashville/', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_nashville-joy-marini', 'Joy Marini', 'nashville-joy-marini', (SELECT id FROM City WHERE name = 'Nashville' AND state = 'TN'), 'https://www.vanderbilt.edu/olli/', 'joymarini', 0, 1, 0, 1, 80, 'American Mahjong instructor; teaches OLLI beginner course and Mahjong 102; OLLI course materials/card included', 'https://cdn.vanderbilt.edu/vu-wpfsx/wp-content/uploads/sites/28/2026/02/Spring-2026-Catalog-1.pdf', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_nashville-laura-johnson-mama-mahjong', 'Laura Johnson / Mama Mahjong', 'nashville-laura-johnson-mama-mahjong', (SELECT id FROM City WHERE name = 'Nashville' AND state = 'TN'), 'https://www.mamamahjong.com/', 'info@mamamahjong.com', 1, 1, 0, 1, 75, 'American Mahjong classes and women-focused leagues; current site lists Mahjong 101 and says the community is rooted in American Mahjong; $75/person summer class pricing on the current class page', 'https://www.mamamahjong.com/mahjong-101', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_nashville-janelle-kraemer-mahjong-with-janelle', 'Janelle Kraemer / Mahjong with Janelle', 'nashville-janelle-kraemer-mahjong-with-janelle', (SELECT id FROM City WHERE name = 'Nashville' AND state = 'TN'), 'https://mahjongwithjanelle.com/', 'janelle@mahjongwithjanelle.com / 404-606-2601', 1, 1, 0, 1, NULL, 'Nashville instructor; beginner-friendly testimonials and lessons; American Mahjong confirmed by MahJongg Maven instructor directory', 'https://mahjonggmaven.com/teachers/', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_nashville-robin-learn-to-play-mahjongg', 'Robin / Learn to Play MahJongg', 'nashville-robin-learn-to-play-mahjongg', (SELECT id FROM City WHERE name = 'Nashville' AND state = 'TN'), 'https://www.learntoplaymahjongg.com/home-page-mahjongg', '908-334-6485 / Learntoplaymahjongg@gmail.com', 1, 1, 0, 1, NULL, 'Teaches American MahJongg in Nashville; offers one-on-one and group lessons; new Nashville Library beginner class scheduled to begin Nov 5, 2026', 'https://www.learntoplaymahjongg.com/home-page-mahjongg', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_nashville-liza-gaston-mahj-madness', 'Liza Gaston / Mahj Madness', 'nashville-liza-gaston-mahj-madness', (SELECT id FROM City WHERE name = 'Nashville' AND state = 'TN'), 'https://mahjong4friends.com/teachers/tn', '772-766-2238 / rexleyllc@icloud.com', 1, 1, 0, 1, NULL, 'Franklin-based instructor serving the Nashville area; teaches up to four people; Fork of the South lists private beginner lessons with Liza', 'https://mahjong4friends.com/teachers/tn', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_nashville-learn-mahjong-with-so-bam-fun-at-the-pharmacy-burger-20261001', 'Learn Mahjong with So Bam Fun at The Pharmacy Burger', 'nashville-learn-mahjong-with-so-bam-fun-at-the-pharmacy-burger-20261001', '2026-10-01 00:00:00', NULL, NULL, 'The Pharmacy Burger Parlor & Beer Garden', (SELECT id FROM City WHERE name = 'Nashville' AND state = 'TN'), NULL, (SELECT id FROM Instructor WHERE slug = 'nashville-so-bam-fun'), 'LESSON', 1, NULL, 'https://www.sobamfun.com/nashville/', 'https://nashvillelife.com/Performing-Arts/Nashville-Upcoming-Events/Type-Event', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
