INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_minneapolis-minneapolis-mah-jongg-club', 'Minneapolis Mah Jongg Club', 'minneapolis-minneapolis-mah-jongg-club', 'American Mah Jongg storefront club run by Abbe Blacker with open play, beginner series, leagues and mentored play.', (SELECT id FROM City WHERE name = 'Minneapolis' AND state = 'MN'), '3942 Market St, Edina, MN 55424', 'https://mplsmahjclub.com/', '952-254-7900', NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, 22, 'Open play on assorted dates/times; 4-part beginner series; by appointment/class registration at storefront', 'https://mplsmahjclub.com/', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_minneapolis-the-minneapolis-club-mahjong', 'The Minneapolis Club Mahjong', 'minneapolis-the-minneapolis-club-mahjong', 'Mahjong program at The Minneapolis Club with recurring Mahjong nights and lesson series; official 2026 card required.', (SELECT id FROM City WHERE name = 'Minneapolis' AND state = 'MN'), '729 2nd Ave S, Minneapolis, MN 55402', 'https://www.mplsclub.org/', '612-332-2292', NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, 75, 'Weekly Tuesday Mahjong night 6-8 PM for members/guests; lesson series offered in 2-session blocks', 'https://www.mplsclub.org/default.aspx?ID=203673&chgs=&p=.NETEventView&qfilter=&seriesDate=9%2F22%2F2026+6%3A00%3A00+PM&ssid=100095&title=&type=0', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_minneapolis-mn-mahjong-st-anthony-community-center', 'MN Mahjong - St. Anthony Community Center', 'minneapolis-mn-mahjong-st-anthony-community-center', 'American Style Mah Jongg classes and community events led by instructor/tournament director Tarri Levine.', (SELECT id FROM City WHERE name = 'Minneapolis' AND state = 'MN'), '3301 Silver Lake Rd NE, Minneapolis, MN', 'https://mnmahjong.com/', NULL, 'info@mnmahjong.com', NULL, NULL, 1, 1, 0, 1, 0, 0, 78, 'Beginner American Style Mah Jongg classes; Sep 28 and Nov 5, 2026 6-9 PM', 'https://mnmahjong.com/events/', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_minneapolis-abbe-blacker', 'Abbe Blacker', 'minneapolis-abbe-blacker', (SELECT id FROM City WHERE name = 'Minneapolis' AND state = 'MN'), 'https://mplsmahjclub.com/', '952-254-7900', 1, 1, 0, 1, 240, 'Runs Minneapolis Mah Jongg Club; 4-part beginner series and open play. Club storefront at 3942 Market St, Edina.', 'https://mplsmahjclub.com/', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_minneapolis-tarri-levine', 'Tarri Levine', 'minneapolis-tarri-levine', (SELECT id FROM City WHERE name = 'Minneapolis' AND state = 'MN'), 'https://mnmahjong.com/', 'info@mnmahjong.com', 1, 1, 0, 1, 78, 'Recognized instructor and tournament director; teaches American Style Mah Jongg in Minneapolis/New Brighton and elsewhere in Minnesota.', 'https://mnmahjong.com/events/', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_minneapolis-mahj-happy', 'Mahj Happy', 'minneapolis-mahj-happy', (SELECT id FROM City WHERE name = 'Minneapolis' AND state = 'MN'), 'https://playmahjhappy.com/', NULL, 1, 1, 0, 1, 60, 'American Mahjong lessons, private group events and open play across Minneapolis and the Twin Cities. Beginner lessons about two hours; $60/person.', 'https://playmahjhappy.com/lessons-events', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_minneapolis-jennifer-mahj-nest', 'Jennifer / Mahj Nest', 'minneapolis-jennifer-mahj-nest', (SELECT id FROM City WHERE name = 'Minneapolis' AND state = 'MN'), 'https://mahjnest.com/', 'mahjnest@gmail.com', 1, 1, 0, 1, 40, 'American Mahjong Mahj 101 and in-home private lessons across the southwest Twin Cities. In-home price is $40/person for a group of 4 or $30/person for a group of 8.', 'https://mahjnest.com/', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_minneapolis-paul-fisher-katie-o-kane-northstar-mahjong-society', 'Paul Fisher & Katie O''Kane / Northstar Mahjong Society', 'minneapolis-paul-fisher-katie-o-kane-northstar-mahjong-society', (SELECT id FROM City WHERE name = 'Minneapolis' AND state = 'MN'), 'https://www.northstarmahj.com/', '612-201-4315 / info@northstarmahj.com', 1, 1, 0, 1, NULL, 'American Mahjong teaching team offering public classes, guided open play and private events throughout the Twin Cities.', 'https://www.northstarmahj.com/about', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_minneapolis-lisa-marie-stienessen-let-s-learn-mahjong', 'Lisa-Marie Stienessen / Let''s Learn Mahjong!', 'minneapolis-lisa-marie-stienessen-let-s-learn-mahjong', (SELECT id FROM City WHERE name = 'Minneapolis' AND state = 'MN'), 'https://www.letslearnmahjong.com/', 'hello@letslearnmahjong.com / 763-245-7575', 1, 1, 0, 1, NULL, 'Twin Cities instructor offering public group lessons and private events. City of Fridley and local brewery pages identify upcoming American Mahjong beginner classes.', 'https://www.letslearnmahjong.com/', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_minneapolis-beginner-american-mah-jongg-20260930', 'Beginner American Mah Jongg', 'minneapolis-beginner-american-mah-jongg-20260930', '2026-09-30 00:00:00', '09:00', '12:00', 'New Brighton Community Center', (SELECT id FROM City WHERE name = 'Minneapolis' AND state = 'MN'), NULL, (SELECT id FROM Instructor WHERE slug = 'minneapolis-tarri-levine'), 'LESSON', 1, 80, NULL, 'https://mnmahjong.com/events/', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_minneapolis-let-s-learn-mahjong-adult-beginner-class-20261001', 'Let''s Learn Mahjong! Adult Beginner Class', 'minneapolis-let-s-learn-mahjong-adult-beginner-class-20261001', '2026-10-01 00:00:00', '18:00', '20:00', 'Commons Park Building, 555 61st St NE, Fridley, MN 55432', (SELECT id FROM City WHERE name = 'Minneapolis' AND state = 'MN'), NULL, (SELECT id FROM Instructor WHERE slug = 'minneapolis-lisa-marie-stienessen-let-s-learn-mahjong'), 'LESSON', 1, NULL, 'https://www.letslearnmahjong.com/', 'https://www.fridleymn.gov/Events-directory', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_minneapolis-guided-open-play-20261001', 'Guided Open Play', 'minneapolis-guided-open-play-20261001', '2026-10-01 00:00:00', NULL, NULL, 'Lifetime Flagship, Eden Prairie, MN', (SELECT id FROM City WHERE name = 'Minneapolis' AND state = 'MN'), NULL, (SELECT id FROM Instructor WHERE slug = 'minneapolis-paul-fisher-katie-o-kane-northstar-mahjong-society'), 'OPEN_PLAY', 1, NULL, 'https://www.northstarmahj.com/', 'https://www.northstarmahj.com/', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_minneapolis-learn-how-to-play-mahjong-20261005', 'Learn How To Play Mahjong!', 'minneapolis-learn-how-to-play-mahjong-20261005', '2026-10-05 00:00:00', NULL, NULL, 'Utepils Brewing, Minneapolis, MN', (SELECT id FROM City WHERE name = 'Minneapolis' AND state = 'MN'), NULL, (SELECT id FROM Instructor WHERE slug = 'minneapolis-paul-fisher-katie-o-kane-northstar-mahjong-society'), 'LESSON', 1, 60, 'https://www.northstarmahj.com/', 'https://www.northstarmahj.com/', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_minneapolis-let-s-learn-mahjong-beginner-class-20261006', 'Let''s Learn Mahjong! Beginner Class', 'minneapolis-let-s-learn-mahjong-beginner-class-20261006', '2026-10-06 00:00:00', '18:30', '20:30', 'Indeed Brewing / Ox Taproom, Minneapolis, MN', (SELECT id FROM City WHERE name = 'Minneapolis' AND state = 'MN'), NULL, (SELECT id FROM Instructor WHERE slug = 'minneapolis-lisa-marie-stienessen-let-s-learn-mahjong'), 'LESSON', 1, NULL, 'https://www.letslearnmahjong.com/', 'https://indeedbrewing.com/event/lets-learn-mahjong-beginner-class-2/', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_minneapolis-beginner-mahjong-lesson-at-picnic-20261025', 'Beginner Mahjong Lesson at Picnic', 'minneapolis-beginner-mahjong-lesson-at-picnic-20261025', '2026-10-25 00:00:00', '14:00', '16:00', 'Picnic, Minneapolis, MN', (SELECT id FROM City WHERE name = 'Minneapolis' AND state = 'MN'), NULL, (SELECT id FROM Instructor WHERE slug = 'minneapolis-mahj-happy'), 'LESSON', 1, 60, NULL, 'https://playmahjhappy.com/lessons-events', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_minneapolis-beginner-open-play-20261105', 'Beginner/Open Play', 'minneapolis-beginner-open-play-20261105', '2026-11-05 00:00:00', NULL, NULL, 'The Market at Malcolm Yards, Minneapolis, MN', (SELECT id FROM City WHERE name = 'Minneapolis' AND state = 'MN'), NULL, (SELECT id FROM Instructor WHERE slug = 'minneapolis-paul-fisher-katie-o-kane-northstar-mahjong-society'), 'OPEN_PLAY', 1, NULL, 'https://www.northstarmahj.com/', 'https://www.northstarmahj.com/', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_minneapolis-mahjong-social-tournament-20261114', 'Mahjong Social Tournament', 'minneapolis-mahjong-social-tournament-20261114', '2026-11-14 00:00:00', '10:00', '15:00', 'The Minneapolis Club, 729 2nd Ave S, Minneapolis, MN 55402', (SELECT id FROM City WHERE name = 'Minneapolis' AND state = 'MN'), (SELECT id FROM Club WHERE slug = 'minneapolis-the-minneapolis-club-mahjong'), NULL, 'TOURNAMENT', 0, 100, 'https://mahjplay.events/e/mpls-club-fall-2026', 'https://www.mplsclub.org/default.aspx?chgs=&mtab=true&noReset=yes&nomodresize=1&nonav=1&p=PrintCalendar&qfilter=&showfilter=&showfooter=false&ssid=100145&startdate=&subtitle=&title=&view=l5', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
