INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_portland-gracey-tile-club-pdx', 'Gracey Tile Club PDX', 'portland-gracey-tile-club-pdx', 'American Mahjong club in SE Portland offering beginner lessons, weekly open play and private events using official NMJL rules and card.', (SELECT id FROM City WHERE name = 'Portland' AND state = 'OR'), 'PureGreen Portland / Eastmoreland Golf Course Bar & Grill, Portland, OR', 'https://graceytileclubpdx.com/', NULL, 'graceytileclub.pdx@gmail.com', NULL, NULL, 1, 1, 1, 1, 0, 0, 25, 'Mahjong 101 Thursdays 6 PM; weekly Open Play Wednesdays 6 PM; Mahjong 101 $50/session; Open Play $25', 'https://graceytileclubpdx.com/', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_portland-pdx-mahjong-club', 'PDX Mahjong Club', 'portland-pdx-mahjong-club', 'Portland-area American Mahjong club offering NMJL-based Mahj 101, Mahj 102, guided open play and private sessions.', (SELECT id FROM City WHERE name = 'Portland' AND state = 'OR'), 'Portland metro; public classes primarily at The Grove Boutique and The Thirsty Caterpillar in Lake Oswego', 'https://www.pdxmahjongclub.com/', NULL, 'jackie@pdxmahjongclub.com', NULL, NULL, 1, 1, 1, 1, 0, 0, 55, 'Upcoming public sessions include Open Play Oct 4; Mahj 101 Oct 5/12, Oct 7; additional Mahj 101 Oct 10; Mahj 101/Mahj 102 and Open Play offered regularly', 'https://www.pdxmahjongclub.com/upcoming-events', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_portland-bird-bam-beth', 'Bird Bam Beth', 'portland-bird-bam-beth', 'Portland American Mahjong community led by Beth Pacyk, with beginner series, open play and private lessons; NMJL rules used for play.', (SELECT id FROM City WHERE name = 'Portland' AND state = 'OR'), 'Public events at Portland venues including Ora et Labora; private lessons at client location', 'https://birdbambeth.com/', '847-809-3801', 'beth@birdbambeth.com', NULL, NULL, 1, 1, 1, 1, 0, 0, 25, 'Upcoming Open Play Oct 10 at Ale & Cider House (West Linn), Oct 29 and Nov 19 at Ora et Labora (Portland); beginner series Oct 11 & 18 at Ora et Labora', 'https://birdbambeth.com/events', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_portland-mittleman-jewish-community-center-open-play-mah-jongg', 'Mittleman Jewish Community Center Open Play Mah Jongg', 'portland-mittleman-jewish-community-center-open-play-mah-jongg', 'JCC drop-in American Mah Jongg open play with recurring Wednesday and Sunday sessions plus beginner and intermediate class series.', (SELECT id FROM City WHERE name = 'Portland' AND state = 'OR'), '6651 SW Capitol Highway, Portland, OR 97219', 'https://www.oregonjcc.org/', '503-244-0111', 'mjcc@oregonjcc.org', NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Open Play Wednesdays 9:30-11:30 AM and Sundays 2-4 PM; fall beginner and intermediate American Mah Jongg classes listed', 'https://www.oregonjcc.org/arts-culture/upcoming-events', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_portland-eastside-jewish-commons-american-mahjong', 'Eastside Jewish Commons American Mahjong', 'portland-eastside-jewish-commons-american-mahjong', 'Three-part beginner American Mahjong series taught by Jennifer Yoken; registration includes a National American Mah Jongg League card and snacks.', (SELECT id FROM City WHERE name = 'Portland' AND state = 'OR'), '2420 NE Sandy Blvd, Portland, OR 97232', 'https://ejcpdx.org/', NULL, 'info@ejcpdx.org', NULL, NULL, 1, 1, 0, 1, 0, 0, 36, 'Beginner series Oct 8, 15 and 22, 2026, 1-3 PM; attendance at all three sessions required', 'https://ejcpdx.org/events/2026/10/8/beginner-american-mahjong-3bz4n-plz3p', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_portland-portland-parks-recreation-southwest-community-center-american-mah-jongg', 'Portland Parks & Recreation — Southwest Community Center American Mah Jongg', 'portland-portland-parks-recreation-southwest-community-center-american-mah-jongg', 'City of Portland Parks & Recreation American Mah Jongg beginner program at Southwest Community Center.', (SELECT id FROM City WHERE name = 'Portland' AND state = 'OR'), 'Southwest Community Center, Portland, OR', 'https://www.portland.gov/parks/activities/hobbies-and-interests', NULL, NULL, NULL, NULL, 1, 1, 0, 1, 0, 0, NULL, 'American Mah Jongg: Beginner; adult program at Southwest Community Center; current city page directs users to check availability', 'https://www.portland.gov/parks/activities/hobbies-and-interests', '2026-09-29', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_portland-karen-gracey', 'Karen Gracey', 'portland-karen-gracey', (SELECT id FROM City WHERE name = 'Portland' AND state = 'OR'), 'https://graceytileclubpdx.com/', 'graceytileclub.pdx@gmail.com', 1, 1, 0, 1, 50, 'Founder of Gracey Tile Club PDX. Teaches official NMJL rules/card. Mahjong 101 is $50/session; private events and group lessons start at $300/table of 4.', 'https://graceytileclubpdx.com/', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_portland-jackie-pdx-mahjong-club', 'Jackie / PDX Mahjong Club', 'portland-jackie-pdx-mahjong-club', (SELECT id FROM City WHERE name = 'Portland' AND state = 'OR'), 'https://www.pdxmahjongclub.com/', 'jackie@pdxmahjongclub.com', 1, 1, 0, 1, 55, 'Portland-area instructor. Teaches NMJL rules. Mahj 101 and 102 are $55/person; Open Play is $35/person. Private sessions available.', 'https://www.pdxmahjongclub.com/faq-2', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_portland-beth-pacyk-bird-bam-beth', 'Beth Pacyk / Bird Bam Beth', 'portland-beth-pacyk-bird-bam-beth', (SELECT id FROM City WHERE name = 'Portland' AND state = 'OR'), 'https://birdbambeth.com/', '847-809-3801 / beth@birdbambeth.com', 1, 1, 0, 1, 120, 'American Mahjong instructor and certified Oh My Mahjong Mahji Mentor. Beginner series is $120/person; private lessons $360 for up to 4 students.', 'https://birdbambeth.com/classes/mahjong-beginner-series', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_portland-lisa-perrin', 'Lisa Perrin', 'portland-lisa-perrin', (SELECT id FROM City WHERE name = 'Portland' AND state = 'OR'), 'https://www.mahjpdx.com/', '503-890-1550 / lisamperrinpdx@gmail.com', 1, 1, 0, 1, NULL, 'Portland-based instructor listed as teaching American Mahjong following NMJL rules; welcomes beginners.', 'https://mahjonggmaven.com/teachers/', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_portland-lynne-thompson-lucky-ducks-mahjong', 'Lynne Thompson / Lucky Ducks Mahjong', 'portland-lynne-thompson-lucky-ducks-mahjong', (SELECT id FROM City WHERE name = 'Portland' AND state = 'OR'), 'https://www.luckyducksmahjong.com/', '503-347-7125 / hello@luckyducksmahjong.com', 1, 1, 0, 1, NULL, 'Lake Oswego/Portland-area instructor. Directory listing explicitly says Lucky Ducks teaches American Mahjong to beginners and hosts private parties and events.', 'https://mahjong4friends.com/teachers/or', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_portland-jennifer-yoken', 'Jennifer Yoken', 'portland-jennifer-yoken', (SELECT id FROM City WHERE name = 'Portland' AND state = 'OR'), 'https://ejcpdx.org/', 'info@ejcpdx.org', 0, 1, 0, 1, 36, 'Teaches the three-part Beginner American Mahjong series at Eastside Jewish Commons. The $36 registration includes a National American Mah Jongg League card and snacks.', 'https://ejcpdx.org/events/2026/10/8/beginner-american-mahjong-3bz4n-plz3p', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_portland-american-mahjong-open-play-20260930', 'American Mahjong Open Play', 'portland-american-mahjong-open-play-20260930', '2026-09-30 00:00:00', '18:00', '20:00', 'Eastmoreland Golf Course Bar & Grill, 2425 SE Bybee Blvd, Portland, OR', (SELECT id FROM City WHERE name = 'Portland' AND state = 'OR'), (SELECT id FROM Club WHERE slug = 'portland-gracey-tile-club-pdx'), (SELECT id FROM Instructor WHERE slug = 'portland-karen-gracey'), 'OPEN_PLAY', 1, 25, 'https://graceytileclubpdx.as.me/openplay', 'https://graceytileclubpdx.com/', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_portland-open-play-20261004', 'Open Play', 'portland-open-play-20261004', '2026-10-04 00:00:00', '13:00', '16:00', 'The Grove Boutique, Lake Oswego, OR', (SELECT id FROM City WHERE name = 'Portland' AND state = 'OR'), (SELECT id FROM Club WHERE slug = 'portland-pdx-mahjong-club'), (SELECT id FROM Instructor WHERE slug = 'portland-jackie-pdx-mahjong-club'), 'OPEN_PLAY', 1, 35, 'https://www.pdxmahjongclub.com/upcoming-events', 'https://www.pdxmahjongclub.com/upcoming-events', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_portland-mahj-101-20261005', 'Mahj 101', 'portland-mahj-101-20261005', '2026-10-05 00:00:00', NULL, NULL, 'The Grove Boutique, Lake Oswego, OR', (SELECT id FROM City WHERE name = 'Portland' AND state = 'OR'), (SELECT id FROM Club WHERE slug = 'portland-pdx-mahjong-club'), (SELECT id FROM Instructor WHERE slug = 'portland-jackie-pdx-mahjong-club'), 'LESSON', 1, 55, 'https://www.pdxmahjongclub.com/upcoming-events', 'https://www.pdxmahjongclub.com/upcoming-events', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_portland-beginner-american-mahjong-session-1-20261008', 'Beginner American Mahjong — Session 1', 'portland-beginner-american-mahjong-session-1-20261008', '2026-10-08 00:00:00', '13:00', '15:00', 'Eastside Jewish Commons, 2420 NE Sandy Blvd, Portland, OR 97232', (SELECT id FROM City WHERE name = 'Portland' AND state = 'OR'), (SELECT id FROM Club WHERE slug = 'portland-eastside-jewish-commons-american-mahjong'), (SELECT id FROM Instructor WHERE slug = 'portland-jennifer-yoken'), 'LESSON', 1, 36, 'https://humanitix.com/event/beginner-american-mahjong-series', 'https://ejcpdx.org/events/2026/10/8/beginner-american-mahjong-3bz4n-plz3p', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_portland-mahjong-beginner-series-week-1-20261011', 'Mahjong Beginner Series — Week 1', 'portland-mahjong-beginner-series-week-1-20261011', '2026-10-11 00:00:00', '16:00', '18:00', 'Ora et Labora, 3928 N Williams Ave, Portland, OR 97227', (SELECT id FROM City WHERE name = 'Portland' AND state = 'OR'), (SELECT id FROM Club WHERE slug = 'portland-bird-bam-beth'), (SELECT id FROM Instructor WHERE slug = 'portland-beth-pacyk-bird-bam-beth'), 'LESSON', 1, 120, 'https://birdbambeth.com/classes/mahjong-beginner-series', 'https://birdbambeth.com/classes/mahjong-beginner-series', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_portland-american-mahjong-open-play-20261029', 'American Mahjong Open Play', 'portland-american-mahjong-open-play-20261029', '2026-10-29 00:00:00', '18:00', '20:00', 'Ora et Labora Wine Shop, 3928 N Williams Ave, Portland, OR 97227', (SELECT id FROM City WHERE name = 'Portland' AND state = 'OR'), (SELECT id FROM Club WHERE slug = 'portland-bird-bam-beth'), (SELECT id FROM Instructor WHERE slug = 'portland-beth-pacyk-bird-bam-beth'), 'OPEN_PLAY', 1, 25, 'https://birdbambeth.com/events', 'https://birdbambeth.com/events', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
