INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_washington-dc-drop-in-mahjongg', 'DC Drop-In Mahjongg', 'washington-dc-drop-in-mahjongg', 'Community playing American-style NMJL Mahjongg with free or low-cost instruction; recurring Tuesday sessions at Martin Luther King Jr. Memorial Library and Sunday sessions at the Capital Jewish Museum.', (SELECT id FROM City WHERE name = 'Washington' AND state = 'DC'), '901 G St NW, Washington, DC 20001', 'https://dcmahjongg.com/', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 1, 0, 'Tuesdays 6:00-8:00 PM at MLK Jr. Memorial Library; free lessons for new players require registration; open play is for all skill levels. Sunday American Mahjong sessions are also offered at Capital Jewish Museum when scheduled.', 'https://dcmahjongg.com/', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_washington-dc-mahj-collective', 'DC Mahj Collective', 'washington-dc-mahj-collective', 'Washington DC American Mahjong business offering recurring Hill Center open play, beginner lessons and guided play, plus private and corporate lessons.', (SELECT id FROM City WHERE name = 'Washington' AND state = 'DC'), '921 Pennsylvania Avenue SE, Washington, DC 20003', 'https://www.dcmahj.com/', NULL, 'dcmahjcollective@gmail.com', NULL, NULL, 1, 1, 1, 1, 0, 0, 20, 'American Mahjong at Hill Center every other Wednesday; Open Play $20, Beginner Lesson $75, Guided Play $50. Additional recurring series listed on events page.', 'https://www.dcmahj.com/events', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_washington-dc-mahj-collective', 'DC Mahj Collective', 'washington-dc-mahj-collective', (SELECT id FROM City WHERE name = 'Washington' AND state = 'DC'), 'https://www.dcmahj.com/', 'dcmahjcollective@gmail.com', 1, 1, 1, 1, 75, 'Mahj 101 covers American Mahjong from tiles through NMJL rules and hands. Private/group bookings available; Hill Center beginner lessons are $75.', 'https://www.dcmahj.com/book-a-lesson', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_washington-so-bam-fun', 'So Bam Fun', 'washington-so-bam-fun', (SELECT id FROM City WHERE name = 'Washington' AND state = 'DC'), 'https://sobamfun.com/washington-dc/', NULL, 1, 1, 0, 1, 300, 'Teaches American Mahjong and NMJL rules in Washington DC. Private group lessons start at $300 for 2 hours; no experience needed; instructor brings tiles and NMJL cards.', 'https://sobamfun.com/washington-dc/', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_washington-girls-who-mahjong', 'Girls Who Mahjong', 'washington-girls-who-mahjong', (SELECT id FROM City WHERE name = 'Washington' AND state = 'DC'), 'https://www.girlswhomahjong.com/events', 'GirlsWhoMahjong@gmail.com', 1, 1, 0, 1, 50, 'DC-based American Mahjong community led by Holly. Upcoming Mahjong 101 classes are beginner-friendly, no experience required; Relume class is $50.', 'https://www.girlswhomahjong.com/events', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_washington-jill-t-the-charleston-coach', 'Jill T. / The Charleston Coach', 'washington-jill-t-the-charleston-coach', (SELECT id FROM City WHERE name = 'Washington' AND state = 'DC'), 'https://www.thecharlestoncoach.com/', 'info@thecharlestoncoach.com / 417-268-5552', 1, 1, 0, 1, NULL, 'MahJongg Maven directory lists The Charleston Coach as providing beginner Mahjong instruction and social play throughout the DC, Maryland and Virginia area; American Mahjong specified.', 'https://mahjonggmaven.com/teachers/', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_washington-caryn-f', 'Caryn F.', 'washington-caryn-f', (SELECT id FROM City WHERE name = 'Washington' AND state = 'DC'), NULL, 'mymahjongg.cf@gmail.com', 1, 1, 0, 1, NULL, 'MahJongg Maven teacher directory lists Caryn F. in the Washington DC / Metro DC area as an American Mahjong teacher.', 'https://mahjonggmaven.com/teachers/', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_washington-dc-drop-in-mahjongg-tuesday-open-play-free-lessons-20260929', 'DC Drop-In Mahjongg — Tuesday Open Play & Free Lessons', 'washington-dc-drop-in-mahjongg-tuesday-open-play-free-lessons-20260929', '2026-09-29 00:00:00', '18:00', '20:00', 'Martin Luther King Jr. Memorial Library, 901 G St NW, Washington, DC 20001', (SELECT id FROM City WHERE name = 'Washington' AND state = 'DC'), (SELECT id FROM Club WHERE slug = 'washington-dc-drop-in-mahjongg'), NULL, 'OPEN_PLAY', 1, 0, 'https://luma.com/dcmahjongg', 'https://luma.com/n72f3s2j', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_washington-american-mahjong-with-dc-mahj-collective-20261007', 'American Mahjong with DC Mahj Collective', 'washington-american-mahjong-with-dc-mahj-collective-20261007', '2026-10-07 00:00:00', '18:00', '20:00', 'Hill Center DC, 921 Pennsylvania Avenue SE, Washington, DC 20003', (SELECT id FROM City WHERE name = 'Washington' AND state = 'DC'), (SELECT id FROM Club WHERE slug = 'washington-dc-mahj-collective'), (SELECT id FROM Instructor WHERE slug = 'washington-dc-mahj-collective'), 'OPEN_PLAY', 1, 20, 'https://www.hillcenterdc.org/event/american-mahjong-with-dc-mahj-collective/2026-10-07/', 'https://www.hillcenterdc.org/event/american-mahjong-with-dc-mahj-collective/2026-10-07/', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_washington-mahjong-101-shop-made-in-dc-georgetown-20261010', 'Mahjong 101 @ Shop Made in DC Georgetown', 'washington-mahjong-101-shop-made-in-dc-georgetown-20261010', '2026-10-10 00:00:00', '15:00', '17:00', 'Shop Made in DC Georgetown, 1304 Wisconsin Avenue NW, Washington, DC', (SELECT id FROM City WHERE name = 'Washington' AND state = 'DC'), NULL, (SELECT id FROM Instructor WHERE slug = 'washington-girls-who-mahjong'), 'LESSON', 1, 54, 'https://www.girlswhomahjong.com/events', 'https://www.girlswhomahjong.com/events', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_washington-mahjong-open-play-stellina-pizzeria-union-market-20261014', 'Mahjong Open Play @ Stellina Pizzeria Union Market', 'washington-mahjong-open-play-stellina-pizzeria-union-market-20261014', '2026-10-14 00:00:00', '18:30', '20:30', 'Stellina Pizzeria Union Market, Washington, DC', (SELECT id FROM City WHERE name = 'Washington' AND state = 'DC'), NULL, (SELECT id FROM Instructor WHERE slug = 'washington-girls-who-mahjong'), 'OPEN_PLAY', 0, NULL, 'https://www.girlswhomahjong.com/events', 'https://www.girlswhomahjong.com/events', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_washington-mahjong-101-class-w-girls-who-mahjong-20261023', 'Mahjong 101 class w/ Girls Who Mahjong', 'washington-mahjong-101-class-w-girls-who-mahjong-20261023', '2026-10-23 00:00:00', '18:00', '20:00', 'Relume, 760 C St SE, Washington, DC 20003', (SELECT id FROM City WHERE name = 'Washington' AND state = 'DC'), NULL, (SELECT id FROM Instructor WHERE slug = 'washington-girls-who-mahjong'), 'LESSON', 1, 50, 'https://relume.co/products/mahjong-101-class-w-girls-who-mahjong-10-23', 'https://relume.co/products/mahjong-101-class-w-girls-who-mahjong-10-23', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_washington-mahjong-night-20261030', 'Mahjong Night', 'washington-mahjong-night-20261030', '2026-10-30 00:00:00', '18:30', '20:30', 'Mount Vernon Place United Methodist Church, 900 Massachusetts Ave NW, Washington, DC 20001', (SELECT id FROM City WHERE name = 'Washington' AND state = 'DC'), NULL, NULL, 'SOCIAL', 1, NULL, NULL, 'https://mvpumc.org/events/mahjong-night', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_washington-mahjong-at-the-virginia-mae-center-20261104', 'Mahjong at the Virginia Mae Center', 'washington-mahjong-at-the-virginia-mae-center-20261104', '2026-11-04 00:00:00', '18:00', '21:00', 'Virginia Mae Center, Washington National Cathedral, 3101 Wisconsin Ave NW, Washington, DC 20016', (SELECT id FROM City WHERE name = 'Washington' AND state = 'DC'), NULL, (SELECT id FROM Instructor WHERE slug = 'washington-dc-mahj-collective'), 'OPEN_PLAY', 1, NULL, 'https://cathedral.org/calendar/mahjong-at-the-virginia-mae-center/', 'https://cathedral.org/calendar/mahjong-at-the-virginia-mae-center/', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
