INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_houston-houston-congregation-for-reform-judaism-mah-jongg', 'Houston Congregation for Reform Judaism Mah Jongg', 'houston-houston-congregation-for-reform-judaism-mah-jongg', 'Community-hosted American Mah Jongg program with recurring Learn and Play, intermediate play, and Thursday drop-in sessions.', (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX'), '801 Bering Dr., Houston, TX 77057', 'https://hcrj.org/', '713-782-4162', 'beth@HCRJ.org', NULL, NULL, 1, 1, 1, 1, 0, 1, 0, 'Learn and Play Mondays 6:00-8:30 PM; Wednesday intermediate play 10:00 AM-12:00 PM; Thursday drop-in 1:00-3:00 PM; free and open to community.', 'https://hcrj.org/venue/hcrj/', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_houston-houston-mahjong-club', 'Houston Mahjong Club', 'houston-houston-mahjong-club', 'Houston American Mahjong community offering NMJL-based league play and Mastering Mahjong classes; exact venue is shared with registered league players.', (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX'), 'Spring Branch area, Houston, TX', 'https://houstonmahjongclub.com/', NULL, NULL, NULL, NULL, 1, 1, 0, 1, 0, 0, 75, 'Monday American Mahjong league, 6:15-8:30 PM; current fall season Sept. 14-Oct. 5 is sold out; future seasons are offered.', 'https://houstonmahjongclub.com/league', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_houston-houston-heights-woman-s-club-mah-jongg', 'Houston Heights Woman''s Club Mah Jongg', 'houston-houston-heights-woman-s-club-mah-jongg', 'Members-only Mah Jongg activities including weekly sessions for new members and scheduled open-play days using the 2026 NMJL card.', (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX'), '1846 Harvard St., Houston, TX 77007', 'https://houstonheightswomansclub.com/', '281-948-1927 / 713-851-7940', 'susan.maybaum@gmail.com', NULL, NULL, 1, 0, 1, 1, 1, 0, NULL, 'Weekly Thursday Mah Jongg for new members; Oct. 28, 2026 1:00-3:00 PM Mah Jongg Open Play Day for experienced players.', 'https://houstonheightswomansclub.com/Calendar', '2026-09-29', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_houston-texas-mahjong-league-bellaire-westu', 'Texas Mahjong League - Bellaire/WestU', 'houston-texas-mahjong-league-bellaire-westu', 'Competitive social American Mahjong league serving Northwest and West Houston; NMJL rules required.', (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX'), '5305 Bissonnet St., Suite D, Bellaire, TX 77401', 'https://mchughtea.com/events-at-the-tea-room/mahjong-fall-league', '713-218-6300', 'info@mchughtea.com', NULL, NULL, 0, 0, 0, 1, 0, 0, NULL, 'Fall 2026 league began Sept. 22 and runs weekly for six weeks through Oct. 27; four scored games per session.', 'https://mchughtea.com/events-at-the-tea-room/mahjong-fall-league', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_houston-mahjaholic', 'Mahjaholic', 'houston-mahjaholic', (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX'), 'https://mahjaholic.com/', 'mahjaholichtx@gmail.com', 1, 1, 0, 1, NULL, 'Lacy Price provides private group American Mahjong lessons nationwide from Houston; explicitly teaches official NMJL rules.', 'https://mahjaholic.com/', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_houston-marchesa-mahjong', 'Marchesa Mahjong', 'houston-marchesa-mahjong', (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX'), 'https://www.marchesamahjong.com/', 'marchesamahjong@gmail.com / 713-724-9996', 1, 1, 0, 1, NULL, 'Arabella Hibbert-founded Houston Mahjong business offering lessons, parties, strategy and recurring public events. Specific upcoming public events are recorded separately in events.csv.', 'https://www.marchesamahjong.com/about', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_houston-the-mahjong-house-stacey-white', 'The Mahjong House / Stacey White', 'houston-the-mahjong-house-stacey-white', (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX'), 'https://themahjonghouse.com/pages/mahjong-classes', NULL, 1, 1, 0, 1, NULL, 'Houston-based lessons include Beginner Lessons, Refresh Lessons and Guided Play Lessons.', 'https://themahjonghouse.com/pages/mahjong-classes', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_houston-jillian-mahj-el-tov', 'Jillian / Mahj-el Tov!', 'houston-jillian-mahj-el-tov', (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX'), 'https://www.mahjeltovwithjillian.com/', NULL, 1, 1, 0, 1, NULL, 'American Mahjong instructor who explicitly teaches strictly by NMJL rules.', 'https://www.mahjeltovwithjillian.com/', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_houston-hcrj-learn-and-play-mah-jongg-20261005', 'HCRJ Learn and Play Mah Jongg', 'houston-hcrj-learn-and-play-mah-jongg-20261005', '2026-10-05 00:00:00', '18:00', '20:30', 'Houston Congregation for Reform Judaism, 801 Bering Dr., Houston, TX 77057', (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX'), (SELECT id FROM Club WHERE slug = 'houston-houston-congregation-for-reform-judaism-mah-jongg'), (SELECT id FROM Instructor WHERE name = 'Beth Nelson' AND cityId = (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX')), 'LESSON', 1, 0, 'https://hcrj.org/venue/hcrj/', 'https://hcrj.org/venue/hcrj/', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_houston-hcrj-thursday-drop-in-mah-jongg-20261001', 'HCRJ Thursday Drop-in Mah Jongg', 'houston-hcrj-thursday-drop-in-mah-jongg-20261001', '2026-10-01 00:00:00', '13:00', '15:00', 'Houston Congregation for Reform Judaism, 801 Bering Dr., Houston, TX 77057', (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX'), (SELECT id FROM Club WHERE slug = 'houston-houston-congregation-for-reform-judaism-mah-jongg'), (SELECT id FROM Instructor WHERE name = 'Beth Nelson' AND cityId = (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX')), 'OPEN_PLAY', 0, 0, 'https://hcrj.org/venue/hcrj/', 'https://hcrj.org/venue/hcrj/', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_houston-hcrj-mah-jongg-20261007', 'HCRJ Mah Jongg', 'houston-hcrj-mah-jongg-20261007', '2026-10-07 00:00:00', '10:00', '12:00', 'Houston Congregation for Reform Judaism, 801 Bering Dr., Houston, TX 77057', (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX'), (SELECT id FROM Club WHERE slug = 'houston-houston-congregation-for-reform-judaism-mah-jongg'), (SELECT id FROM Instructor WHERE name = 'Beth Nelson' AND cityId = (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX')), 'OPEN_PLAY', 0, 0, 'https://hcrj.org/venue/hcrj/', 'https://hcrj.org/venue/hcrj/', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_houston-mahjong-at-the-marigold-club-october-20261016', 'Mahjong at The Marigold Club - October', 'houston-mahjong-at-the-marigold-club-october-20261016', '2026-10-16 00:00:00', '11:00', NULL, 'The Marigold Club, Houston, TX', (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX'), NULL, (SELECT id FROM Instructor WHERE slug = 'houston-marchesa-mahjong'), 'OPEN_PLAY', 0, 95, 'https://www.opentable.com/r/the-marigold-club-houston', 'https://www.opentable.com/r/the-marigold-club-houston', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_houston-texas-mahjong-league-bellaire-westu-fall-league-20261006', 'Texas Mahjong League - Bellaire/WestU Fall League', 'houston-texas-mahjong-league-bellaire-westu-fall-league-20261006', '2026-10-06 00:00:00', '18:30', NULL, 'McHughTEA Room, 5305 Bissonnet St., Suite D, Bellaire, TX 77401', (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX'), (SELECT id FROM Club WHERE slug = 'houston-texas-mahjong-league-bellaire-westu'), NULL, 'TOURNAMENT', 0, NULL, 'https://mchughtea.com/events-at-the-tea-room/mahjong-fall-league', 'https://mchughtea.com/events-at-the-tea-room/mahjong-fall-league', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_houston-mahjong-madness-fall-classic-league-2026-20261027', 'Mahjong Madness Fall Classic League 2026', 'houston-mahjong-madness-fall-classic-league-2026-20261027', '2026-10-27 00:00:00', '18:30', '20:30', 'Blue Leaf Houston, Houston, TX', (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX'), NULL, (SELECT id FROM Instructor WHERE name = 'Bird Bam Bears' AND cityId = (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX')), 'TOURNAMENT', 0, 250, 'https://www.blueleafhouston.com/mahjong-madness-fall-classic-league-2026.html', 'https://www.blueleafhouston.com/mahjong-madness-fall-classic-league-2026.html', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_houston-mahjong-at-the-marigold-club-november-20261113', 'Mahjong at The Marigold Club - November', 'houston-mahjong-at-the-marigold-club-november-20261113', '2026-11-13 00:00:00', '11:00', NULL, 'The Marigold Club, Houston, TX', (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX'), NULL, (SELECT id FROM Instructor WHERE slug = 'houston-marchesa-mahjong'), 'OPEN_PLAY', 0, 95, 'https://www.opentable.com/r/the-marigold-club-houston', 'https://www.opentable.com/r/the-marigold-club-houston', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_houston-these-boots-are-made-for-mahjing-20261106', 'These Boots Are Made for Mahjing', 'houston-these-boots-are-made-for-mahjing-20261106', '2026-11-06 00:00:00', '18:00', NULL, 'Silver Street Studios at Sawyer Yards, Houston, TX', (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX'), NULL, (SELECT id FROM Instructor WHERE slug = 'houston-marchesa-mahjong'), 'SOCIAL', 0, NULL, 'https://www.marchesamahjong.com/thesebootsaremadeformahjing', 'https://www.marchesamahjong.com/thesebootsaremadeformahjing', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
