INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_charlotte-sparrow-mahjong-club', 'Sparrow Mahjong Club', 'charlotte-sparrow-mahjong-club', 'Charlotte-based American Mahjong club offering weekly open play, beginner and advanced lessons, special events and tournaments.', (SELECT id FROM City WHERE name = 'Charlotte' AND state = 'NC'), NULL, 'https://www.sparrowmahjongclub.com/', '305-546-3369', 'sparrowmahjongclub@gmail.com', NULL, NULL, 1, 1, 1, 1, 0, 0, 45, 'Weekly Open Play Monday, Tuesday and Wednesday evenings at venues in South Charlotte; membership is $45/month, with non-member event tickets also offered.', 'https://www.sparrowmahjongclub.com/club-membership', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_charlotte-charlotte-mahjong', 'Charlotte Mahjong', 'charlotte-charlotte-mahjong', 'Charlotte-area American Mahjong community offering lessons, monthly social/open-play events, private lessons and hosted events.', (SELECT id FROM City WHERE name = 'Charlotte' AND state = 'NC'), NULL, 'https://charlottemahjong.com/', NULL, 'Christina@charlottemahjong.com', NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Monthly social events plus scheduled MAHJ 101/Part II lessons; private lessons and events available by booking.', 'https://charlottemahjong.com/learn-mahjong', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_charlotte-queen-city-mahjong', 'Queen City Mahjong', 'charlotte-queen-city-mahjong', 'American Mahjong instruction and assisted open play serving Charlotte; founded by Jill Graham and additional instructors.', (SELECT id FROM City WHERE name = 'Charlotte' AND state = 'NC'), '1332 Maryland Avenue, Charlotte, NC 28209', 'https://www.queencitymahjong.com/', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Group lessons at the Junior League of Charlotte; assisted open play Wednesdays 6:00-8:00 PM at Gourmand Market at APEX across from SouthPark Mall; private socials also available.', 'https://www.queencitymahjong.com/learn', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_charlotte-crown-tile', 'Crown & Tile', 'charlotte-crown-tile', 'American Mahjong lessons, guided open play and private events based in Belmont and serving the greater Charlotte area.', (SELECT id FROM City WHERE name = 'Charlotte' AND state = 'NC'), '10 Catawba St, Belmont, NC 28012', 'https://crownandtile.com/', NULL, 'leesa@crownandtile.com', NULL, NULL, 1, 1, 1, 1, 0, 0, 15, 'Scheduled 2-hour lessons and open play at Jekyll and Hyde Taphouse Grill in Belmont; Oct. 13 lesson and November/December open-play dates are posted.', 'https://crownandtile.com/lessons', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_charlotte-sparrow-mahjong-club', 'Sparrow Mahjong Club', 'charlotte-sparrow-mahjong-club', (SELECT id FROM City WHERE name = 'Charlotte' AND state = 'NC'), 'https://www.sparrowmahjongclub.com/', 'sparrowmahjongclub@gmail.com / 305-546-3369', 1, 1, 0, 1, 50, 'American Mahjong 101 and 102 are $50 each; four-week Learning Series $100; private lessons available at varying price.', 'https://www.sparrowmahjongclub.com/courses', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_charlotte-queen-city-mahjong', 'Queen City Mahjong', 'charlotte-queen-city-mahjong', (SELECT id FROM City WHERE name = 'Charlotte' AND state = 'NC'), 'https://www.queencitymahjong.com/', 'Contact form', 1, 1, 0, 1, 95, 'American Mahjong instruction based on official National Mah Jongg League rules. Boot camps, assisted open play, refresh/strategy classes and private socials. Private social lessons are $115/person for 4-6 people or $95/person for 7+.', 'https://www.queencitymahjong.com/learn', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_charlotte-charlotte-mahjong', 'Charlotte Mahjong', 'charlotte-charlotte-mahjong', (SELECT id FROM City WHERE name = 'Charlotte' AND state = 'NC'), 'https://charlottemahjong.com/', 'Christina@CharlotteMahjong.com', 1, 1, 0, 1, NULL, 'Teaches American Mahjong; beginner MAHJ 101 classes, Part II strategy lessons, private in-home lessons and hosted events. Upcoming October 2026 lessons are posted.', 'https://charlottemahjong.com/learn-mahjong', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_charlotte-mahj-in-the-city', 'Mahj In The City', 'charlotte-mahj-in-the-city', (SELECT id FROM City WHERE name = 'Charlotte' AND state = 'NC'), 'https://www.mahjinthecity.com/', 'mahjinthecity@gmail.com', 1, 1, 0, 1, 65, 'Group and private lessons, events and fundraisers. October 13-27 beginner series at The Grove is $65 per lesson or $185 for all three.', 'https://www.mahjinthecity.com/contact', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_charlotte-mrs-merriman-mahjong', 'Mrs. Merriman Mahjong', 'charlotte-mrs-merriman-mahjong', (SELECT id FROM City WHERE name = 'Charlotte' AND state = 'NC'), 'https://mrsmerrimanmahjong.com/', 'mrs.merriman.mahjong@gmail.com', 1, 1, 0, 1, NULL, 'American Mahjong lessons, assisted play and hosted gatherings across Charlotte; booking calendar and contact available. Site states National Mah Jongg League standard rules.', 'https://mrsmerrimanmahjong.com/', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_charlotte-open-play-the-club-house-mondays-20261005', 'Open Play @ The Club House, Mondays', 'charlotte-open-play-the-club-house-mondays-20261005', '2026-10-05 00:00:00', '19:00', '21:00', 'The Club House, Charlotte, NC 28277', (SELECT id FROM City WHERE name = 'Charlotte' AND state = 'NC'), (SELECT id FROM Club WHERE slug = 'charlotte-sparrow-mahjong-club'), NULL, 'OPEN_PLAY', 1, NULL, 'https://www.tickettailor.com/events/sparrowopen', 'https://www.tickettailor.com/events/sparrowopen', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_charlotte-mahjong-101-lesson-rally-pickleball-20261005', 'Mahjong 101 Lesson @ Rally Pickleball', 'charlotte-mahjong-101-lesson-rally-pickleball-20261005', '2026-10-05 00:00:00', '18:00', '20:30', 'Rally Pickleball, Charlotte, NC 28217', (SELECT id FROM City WHERE name = 'Charlotte' AND state = 'NC'), (SELECT id FROM Club WHERE slug = 'charlotte-sparrow-mahjong-club'), NULL, 'LESSON', 1, NULL, 'https://www.tickettailor.com/events/sparrowopen', 'https://www.tickettailor.com/events/sparrowopen', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_charlotte-open-play-open-tap-tuesdays-20261006', 'Open Play @ Open Tap, Tuesdays', 'charlotte-open-play-open-tap-tuesdays-20261006', '2026-10-06 00:00:00', '19:00', '21:00', 'Open Tap, 5010 Carmel Center Dr, Charlotte, NC 28226', (SELECT id FROM City WHERE name = 'Charlotte' AND state = 'NC'), (SELECT id FROM Club WHERE slug = 'charlotte-sparrow-mahjong-club'), NULL, 'OPEN_PLAY', 0, NULL, 'https://www.tickettailor.com/events/sparrowopen', 'https://www.tickettailor.com/events/sparrowopen', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_charlotte-let-s-mahj-for-young-life-capernaum-20261006', 'Let''s Mahj for Young Life Capernaum', 'charlotte-let-s-mahj-for-young-life-capernaum-20261006', '2026-10-06 00:00:00', '18:30', '21:00', 'Sardis Swim & Racquet Club, 7400 Thermal Rd, Charlotte, NC 28211', (SELECT id FROM City WHERE name = 'Charlotte' AND state = 'NC'), NULL, (SELECT id FROM Instructor WHERE slug = 'charlotte-mahj-in-the-city'), 'SOCIAL', 1, NULL, 'https://www.mahjinthecity.com/local-events', 'https://www.mahjinthecity.com/local-events', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_charlotte-get-mahj-n-beginner-series-the-grove-20261013', 'Get Mahj''N — Beginner Series @ The Grove', 'charlotte-get-mahj-n-beginner-series-the-grove-20261013', '2026-10-13 00:00:00', '18:30', '20:00', 'The Grove, 1043 Providence Rd, Charlotte, NC 28207', (SELECT id FROM City WHERE name = 'Charlotte' AND state = 'NC'), NULL, (SELECT id FROM Instructor WHERE slug = 'charlotte-mahj-in-the-city'), 'LESSON', 1, 65, 'https://www.mahjinthecity.com/event-details-registration/get-mahjn-beginner-series-the-grove-6', 'https://www.mahjinthecity.com/event-details-registration/get-mahjn-beginner-series-the-grove-6', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_charlotte-american-mahjong-open-play-toastique-20261005', 'American Mahjong Open Play @ Toastique', 'charlotte-american-mahjong-open-play-toastique-20261005', '2026-10-05 00:00:00', '09:30', '11:00', 'Toastique, 1120 S Tryon St, Charlotte, NC', (SELECT id FROM City WHERE name = 'Charlotte' AND state = 'NC'), (SELECT id FROM Club WHERE slug = 'charlotte-sparrow-mahjong-club'), NULL, 'OPEN_PLAY', 1, NULL, NULL, 'https://sparrow-mahjong-club.bamgoodtime.com/events/787670ce-7030-441a-a3e9-b5451043055b', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_charlotte-mahjong-101-lesson-rally-pickleball-20261019', 'Mahjong 101 Lesson @ Rally Pickleball', 'charlotte-mahjong-101-lesson-rally-pickleball-20261019', '2026-10-19 00:00:00', '18:00', '20:30', 'Rally Pickleball, Charlotte, NC 28217', (SELECT id FROM City WHERE name = 'Charlotte' AND state = 'NC'), (SELECT id FROM Club WHERE slug = 'charlotte-sparrow-mahjong-club'), NULL, 'LESSON', 1, NULL, 'https://www.tickettailor.com/events/sparrowopen', 'https://www.tickettailor.com/events/sparrowopen', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_charlotte-get-mahj-n-beginner-series-the-grove-20261020', 'Get Mahj''N — Beginner Series @ The Grove', 'charlotte-get-mahj-n-beginner-series-the-grove-20261020', '2026-10-20 00:00:00', '18:30', '20:00', 'The Grove, 1043 Providence Rd, Charlotte, NC 28207', (SELECT id FROM City WHERE name = 'Charlotte' AND state = 'NC'), NULL, (SELECT id FROM Instructor WHERE slug = 'charlotte-mahj-in-the-city'), 'LESSON', 1, 65, 'https://www.mahjinthecity.com/event-details-registration/get-mahjn-beginner-series-the-grove-6', 'https://www.mahjinthecity.com/event-details-registration/get-mahjn-beginner-series-the-grove-6', '2026-09-29', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
