INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_tampa-shanna-bryan-glazer-jcc-mah-jongg-open-play', 'Shanna & Bryan Glazer JCC Mah Jongg Open Play', 'tampa-shanna-bryan-glazer-jcc-mah-jongg-open-play', 'American Mah Jongg open play; novices and experienced players welcome. Related beginner course explicitly teaches American Mah Jongg with the National Mah Jongg League card.', (SELECT id FROM City WHERE name = 'Tampa' AND state = 'FL'), '522 N. Howard Ave, Tampa, FL 33606', 'https://www.jewishtampa.com/activeadults', '813-291-2253', 'pnina.levermore@jewishtampa.com', NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Tuesdays 11:30 AM–2 PM and Wednesdays 1:30–3:30 PM; free with JCC membership; no registration required.', 'https://www.jewishtampa.com/activeadults', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_tampa-life-enrichment-center-open-play-mah-jongg', 'Life Enrichment Center - Open Play Mah Jongg', 'tampa-life-enrichment-center-open-play-mah-jongg', 'Recurring in-person American Mah Jongg open play with instructor Alice Webb; beginners can be taught and returning players refreshed.', (SELECT id FROM City WHERE name = 'Tampa' AND state = 'FL'), '9704 North Boulevard, Tampa, FL', 'https://lectampa.org/', '813-932-0241', 'info@lectampa.org', NULL, NULL, 1, 1, 1, 1, 0, 0, 8, 'Wednesdays 1:00–3:30 PM through Dec. 31, 2026; $8 member / $10 non-member.', 'https://www.meetup.com/lectampa/events/cbkhvtyjcmbnc/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_tampa-south-tampa-mahjong-parlor', 'South Tampa Mahjong Parlor', 'tampa-south-tampa-mahjong-parlor', 'Dedicated Mahjong venue with Open Play, weekly league, beginner/intermediate instruction, private parties and day passes.', (SELECT id FROM City WHERE name = 'Tampa' AND state = 'FL'), '3318 W Bay To Bay Blvd, Tampa, FL 33629', 'https://www.southtampamahjongparlor.com/', '813-302-0566', 'hello@southtampamahjongparlor.com', NULL, NULL, 1, 1, 1, 1, 0, 0, 40, 'Weekly tournament-style league Mondays 6–9 PM through Nov. 2, 2026; Open Play via membership or $40 day pass.', 'https://www.southtampamahjongparlor.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_tampa-the-lucky-tile-mah-jongg', 'The Lucky Tile Mah Jongg', 'tampa-the-lucky-tile-mah-jongg', (SELECT id FROM City WHERE name = 'Tampa' AND state = 'FL'), 'https://www.theluckytilemahjongg.com/', '813-394-5226 / theluckytilemahjongg@gmail.com', 1, 1, 0, 1, NULL, 'Aimee Wagner teaches American Mah Jongg under NMJL rules and official annual card; beginner group classes and private lessons.', 'https://www.theluckytilemahjongg.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_tampa-dragons-on-the-green', 'Dragons on the Green', 'tampa-dragons-on-the-green', (SELECT id FROM City WHERE name = 'Tampa' AND state = 'FL'), 'https://www.dragonsonthegreen.org/', 'Contact through website', 1, 1, 0, 1, 100, 'Tampa Bay organization offering classes and private lessons; classes follow official NMJL rules. Glazer JCC beginner series is four sessions.', 'https://www.dragonsonthegreen.org/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_tampa-tampa-mahjong-club', 'Tampa Mahjong Club', 'tampa-tampa-mahjong-club', (SELECT id FROM City WHERE name = 'Tampa' AND state = 'FL'), 'https://bookeo.com/tampamahjongclub', '813-679-0109 / tbmahjmom@gmail.com', 1, 1, 0, 1, NULL, 'Shannon Norden offers lessons, guided play, open play and leagues. Oct. 6 event uses American Mahjong and asks players to bring the NMJL card.', 'https://mahjong4friends.com/teachers/fl', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_tampa-alice-webb', 'Alice Webb', 'tampa-alice-webb', (SELECT id FROM City WHERE name = 'Tampa' AND state = 'FL'), 'https://lectampa.org/', 'info@lectampa.org / 813-932-0241', 0, 1, 0, 1, 8, 'Instructor for recurring American Mah Jongg open play at Life Enrichment Center; current listing says she teaches beginners and refreshes returning players.', 'https://www.meetup.com/lectampa/events/cbkhvtyjcmbnc/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_tampa-holly-lewis', 'Holly Lewis', 'tampa-holly-lewis', (SELECT id FROM City WHERE name = 'Tampa' AND state = 'FL'), 'https://linktr.ee/tampabaymahj', 'Event sign-up via linked Calendly', 1, 1, 0, 1, NULL, 'Tampa Bay American Mahjong instructor; current Tampa listings describe NMJL classes and beginner/intermediate lessons.', 'https://linktr.ee/tampabaymahj', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_tampa-mahj-y-margs-at-sal-y-mar-20261006', 'Mahj Y Margs at Sal Y Mar', 'tampa-mahj-y-margs-at-sal-y-mar-20261006', '2026-10-06 00:00:00', '18:00', '20:00', 'Sal Y Mar Rooftop Bar, 3650 Midtown Dr, Tampa, FL 33607', (SELECT id FROM City WHERE name = 'Tampa' AND state = 'FL'), NULL, (SELECT id FROM Instructor WHERE slug = 'tampa-tampa-mahjong-club'), 'OPEN_PLAY', 1, 20, 'https://bookeo.com/tampamahjongclub', 'https://midtowntampa.com/event/mahj-y-margs-at-sal-y-mar-%F0%9F%80%84%F0%9F%8D%B9/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_tampa-south-tampa-mahjong-parlor-2-hour-open-play-pass-20261006', 'South Tampa Mahjong Parlor 2-Hour Open Play Pass', 'tampa-south-tampa-mahjong-parlor-2-hour-open-play-pass-20261006', '2026-10-06 00:00:00', '10:00', NULL, 'South Tampa Mahjong Parlor, 3318 W Bay To Bay Blvd, Tampa, FL 33629', (SELECT id FROM City WHERE name = 'Tampa' AND state = 'FL'), (SELECT id FROM Club WHERE slug = 'tampa-south-tampa-mahjong-parlor'), NULL, 'OPEN_PLAY', 1, 40, 'https://www.southtampamahjongparlor.com/event-details/2-hour-pass-2026-10-06-10-00', 'https://www.southtampamahjongparlor.com/event-details/2-hour-pass-2026-10-06-10-00', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_tampa-south-tampa-mahjong-parlor-2-hour-open-play-pass-20261014', 'South Tampa Mahjong Parlor 2-Hour Open Play Pass', 'tampa-south-tampa-mahjong-parlor-2-hour-open-play-pass-20261014', '2026-10-14 00:00:00', '10:00', NULL, 'South Tampa Mahjong Parlor, 3318 W Bay To Bay Blvd, Tampa, FL 33629', (SELECT id FROM City WHERE name = 'Tampa' AND state = 'FL'), (SELECT id FROM Club WHERE slug = 'tampa-south-tampa-mahjong-parlor'), NULL, 'OPEN_PLAY', 1, 40, 'https://www.southtampamahjongparlor.com/event-details/2-hour-pass-2026-10-14-10-00', 'https://www.southtampamahjongparlor.com/event-details/2-hour-pass-2026-10-14-10-00', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_tampa-mah-jongg-beginner-class-evening-series-20261001', 'Mah Jongg Beginner Class — Evening Series', 'tampa-mah-jongg-beginner-class-evening-series-20261001', '2026-10-01 00:00:00', '18:30', '20:30', 'Shanna & Bryan Glazer JCC, 522 N. Howard Ave, Tampa, FL 33606', (SELECT id FROM City WHERE name = 'Tampa' AND state = 'FL'), (SELECT id FROM Club WHERE slug = 'tampa-shanna-bryan-glazer-jcc-mah-jongg-open-play'), (SELECT id FROM Instructor WHERE slug = 'tampa-dragons-on-the-green'), 'LESSON', 1, 100, 'https://www.jewishtampa.com/activeadults', 'https://www.jewishtampa.com/activeadults', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_tampa-mah-jongg-beginner-class-evening-series-20261008', 'Mah Jongg Beginner Class — Evening Series', 'tampa-mah-jongg-beginner-class-evening-series-20261008', '2026-10-08 00:00:00', '18:30', '20:30', 'Shanna & Bryan Glazer JCC, 522 N. Howard Ave, Tampa, FL 33606', (SELECT id FROM City WHERE name = 'Tampa' AND state = 'FL'), (SELECT id FROM Club WHERE slug = 'tampa-shanna-bryan-glazer-jcc-mah-jongg-open-play'), (SELECT id FROM Instructor WHERE slug = 'tampa-dragons-on-the-green'), 'LESSON', 1, 100, 'https://www.jewishtampa.com/activeadults', 'https://www.jewishtampa.com/activeadults', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_tampa-mah-jongg-beginner-class-evening-series-20261015', 'Mah Jongg Beginner Class — Evening Series', 'tampa-mah-jongg-beginner-class-evening-series-20261015', '2026-10-15 00:00:00', '18:30', '20:30', 'Shanna & Bryan Glazer JCC, 522 N. Howard Ave, Tampa, FL 33606', (SELECT id FROM City WHERE name = 'Tampa' AND state = 'FL'), (SELECT id FROM Club WHERE slug = 'tampa-shanna-bryan-glazer-jcc-mah-jongg-open-play'), (SELECT id FROM Instructor WHERE slug = 'tampa-dragons-on-the-green'), 'LESSON', 1, 100, 'https://www.jewishtampa.com/activeadults', 'https://www.jewishtampa.com/activeadults', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_tampa-mah-jongg-beginner-class-evening-series-20261022', 'Mah Jongg Beginner Class — Evening Series', 'tampa-mah-jongg-beginner-class-evening-series-20261022', '2026-10-22 00:00:00', '18:30', '20:30', 'Shanna & Bryan Glazer JCC, 522 N. Howard Ave, Tampa, FL 33606', (SELECT id FROM City WHERE name = 'Tampa' AND state = 'FL'), (SELECT id FROM Club WHERE slug = 'tampa-shanna-bryan-glazer-jcc-mah-jongg-open-play'), (SELECT id FROM Instructor WHERE slug = 'tampa-dragons-on-the-green'), 'LESSON', 1, 100, 'https://www.jewishtampa.com/activeadults', 'https://www.jewishtampa.com/activeadults', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
