-- "Getting Started" intro paragraphs for every published city
-- (docs/CITY_PAGE_POLICY.md §2). Each is written only from that city's
-- verified listings — no counts or dates, which would go stale as
-- listings change.

UPDATE "City" SET "intro" = 'Atlanta''s listings lean toward lessons and social play. Le Mahj Club runs 101 and 102 beginner lessons and casual open-play socials around Alpharetta, Roswell and Milton, while Mahj Studios in Buckhead is a membership club with beginner lessons, guided play and socials. Several independent instructors also teach American Mahjong across the metro. If you''re new, a beginner lesson is the clearest first step.' WHERE "slug" = 'atlanta';

UPDATE "City" SET "intro" = 'Austin mixes leagues, a studio and pop-up lessons. Austin Mahjong Social offers classes, private lessons and seasonal leagues. Mahj House Austin is a studio in West Lake Hills with a beginner series, open play and social nights. itsamahjing hosts lessons and themed pop-up events around town. Beginner-friendly options are marked on each listing, so you can start with a class and move into league or open play once you know the game.' WHERE "slug" = 'austin';

UPDATE "City" SET "intro" = 'Boston''s listings center on instruction and hosted events. Bay State Bam teaches and is home to the Troop Mahjong Boston/Worcester chapter, which hosts leagues, socials and open play. Mahjong Theory, South Shore Mahjong (with a studio in Cohasset) and So Bam Fun Boston also offer lessons. We''re still building out Boston, so contacting a teacher directly is often the surest way in to a first game.' WHERE "slug" = 'boston';

UPDATE "City" SET "intro" = 'Charlotte''s American Mahjong meets in restaurants, taprooms and community venues. Sparrow Mahjong Club holds open play on Monday to Wednesday evenings in South Charlotte, with an optional monthly membership. Queen City Mahjong offers assisted open play on Wednesdays, and Charlotte Mahjong runs monthly socials and beginner lessons. Crown & Tile in Belmont adds lessons and guided open play. Beginner lessons are listed by several of these groups, so you can pick the location and schedule that suit you.' WHERE "slug" = 'charlotte';

UPDATE "City" SET "intro" = 'Chicago''s American Mahjong here runs through two community groups. The Mahjong Society offers 101 and 102 lessons, guided play, open play, leagues and events at rotating venues. Mahj & Mingle Social Club offers 101 lessons, guided play, open play and leagues. Both start newcomers with an introductory class and offer guided play as a next step, so you can learn the basics before joining open play.' WHERE "slug" = 'chicago';

UPDATE "City" SET "intro" = 'Dallas has independent clubs and a Jewish Community Center program. Dallas Mahj Club offers private and group lessons and social play. Modern Day Mahj runs beginner courses, open play and leagues. J Mahj at the Aaron Family Jewish Community Center of Dallas hosts scheduled play, theme nights, lessons and leagues. All three list lessons for newcomers, so you can take a class first and join open play afterward.' WHERE "slug" = 'dallas';

UPDATE "City" SET "intro" = 'Denver has dedicated spaces and pop-up play. Mahjong Social Club is a Denver space with drop-in play and beginner classes. JCC Denver runs a seasonal multi-week Beginning Mahjong course, and Rocky Mountain Mahjong offers lessons plus weekly open play. Mahjong Standard hosts rotating open play at South Denver venues, but those sessions are aimed at players who already know the basics, so take a class first if you''re new.' WHERE "slug" = 'denver';

UPDATE "City" SET "intro" = 'Houston mixes a free community program with leagues. Houston Congregation for Reform Judaism hosts free Learn and Play sessions on Mondays plus weekday drop-in play. Houston Mahjong Club runs an NMJL league and Mastering Mahjong classes, and the Texas Mahjong League in Bellaire is a competitive league where players are expected to know NMJL rules. Several teachers offer lessons, so you can learn first and join a league later.' WHERE "slug" = 'houston';

UPDATE "City" SET "intro" = 'In Los Angeles, our listings center on two groups that combine teaching with events. Mahjong Smiles offers hosted classes, private experiences and guided play. LA LA Mahjong offers beginner classes, events and league play under NMJL rules. Both also list instructors for private or group lessons, and both offer guided play, which makes a good step after your first class.' WHERE "slug" = 'los-angeles';

UPDATE "City" SET "intro" = 'Miami''s listings currently center on one community. Mahj in Miami offers beginner classes, open-play socials, private lessons and events. Its Mahj 101 is a two-session class of about two and a half hours each, with a Mahj 102 follow-up for the next step. Because it is a single community for now, start with the beginner class if you''re new. We''re still adding to Miami, so check back as more clubs and teachers are confirmed.' WHERE "slug" = 'miami';

UPDATE "City" SET "intro" = 'Minneapolis has lots of beginner classes in everyday places. Lessons are listed at breweries, community centers and a park building around the Twin Cities, alongside a storefront club in Edina with a four-part beginner series and open play. The Minneapolis Club hosts a weekly Tuesday Mahjong night and lesson series, and MN Mahjong holds classes at the St. Anthony Community Center. Several instructors teach American Mahjong across the metro.' WHERE "slug" = 'minneapolis';

UPDATE "City" SET "intro" = 'Nashville''s American Mahjong is spread across public and community spaces. Listings include a library group in Brentwood, a senior-center program in Franklin for ages 55 and up, classes at the Gordon Jewish Community Center, and open play at Fork of the South in Franklin and The Regal Room in Nolensville. The Mahjong Club in Brentwood is a dedicated space with regular open play and classes, and several instructors offer lessons.' WHERE "slug" = 'nashville';

UPDATE "City" SET "intro" = 'Our New York listings are in Manhattan. Sparrow''s Nest Studio offers beginner lessons and open play, and Congregation Habonim on the Upper West Side offers beginner classes and regular open play. UES Mahjong and So Bam Fun New York provide private and group lessons. We''re still adding to New York, so more options will appear over time; for now, a beginner class at either venue is the simplest way in.' WHERE "slug" = 'new-york';

UPDATE "City" SET "intro" = 'Our Philadelphia listings are in the surrounding suburbs and community centers. Old York Road Temple-Beth Am in Abington runs Wednesday classes and open play nights. Gems at the J meets Thursday afternoons at the Kaiserman JCC in Wynnewood. MahjWithLee has a studio in Blue Bell with Mahj 101 and 102 lessons. Independent teachers also offer private and group lessons, so there are several ways to learn before your first game.' WHERE "slug" = 'philadelphia';

UPDATE "City" SET "intro" = 'Phoenix''s listings lean toward teachers rather than fixed clubs. Mahj Mind, Maj by Daron, Mod Mahj (in Arcadia and Central Phoenix) and So Bam Fun Phoenix offer courses ranging from beginner to advanced, plus supervised play. The one group listed, Mahjong for People who Work, is a Meetup group with recurring games where American Mahjong may be played when enough players attend, so confirm before you go.' WHERE "slug" = 'phoenix';

UPDATE "City" SET "intro" = 'Portland has several groups that pair beginner classes with regular open play. Gracey Tile Club PDX runs Mahjong 101 and weekly open play. PDX Mahjong Club and Bird Bam Beth hold public classes and open play at local venues around the metro. The Mittleman Jewish Community Center offers drop-in open play on Wednesdays and Sundays, and Eastside Jewish Commons runs a three-part beginner series.' WHERE "slug" = 'portland';

UPDATE "City" SET "intro" = 'San Diego''s listings split between classes and weekly play. Beginners American Mahjong (BAM!) runs three-lesson beginner series and follow-up guided play, mainly in Scripps Ranch. Coastal Mahjong Club meets weekly at venues along the North Coast, including Del Mar, Carmel Valley, Encinitas and La Jolla, and asks brand-new players to message ahead for an intro session. Independent teachers also offer courses.' WHERE "slug" = 'san-diego';

UPDATE "City" SET "intro" = 'Our San Francisco listings are still small. The Jewish Community Center of San Francisco hosts American Mah Jongg social play and beginner classes. Mahjong with Kim (who also teaches online) and So Bam Fun San Francisco offer private lessons and events. Because the options are limited, starting with a beginner class at the JCC or booking a private lesson is the simplest way in. We''re still adding to this page, so check back for more.' WHERE "slug" = 'san-francisco';

UPDATE "City" SET "intro" = 'Scottsdale''s listings center on two groups. Phoenix Mahjong Club, despite its name, is a storefront club in Old Town Scottsdale with open play, socials, lessons and leagues. Scottsdale Mahjong Society offers open play, beginner and intermediate lessons and seasonal leagues. Both list beginner lessons, so either is a reasonable place to start, and both pair lessons with open play, so you can move from a first class to regular play without switching groups.' WHERE "slug" = 'scottsdale';

UPDATE "City" SET "intro" = 'Seattle''s listings are mostly community-based. The Stroum Jewish Community Center on Mercer Island runs Monday evening drop-in play, daytime free play and periodic beginner classes. The Senior Center of West Seattle hosts a Wednesday afternoon session for $1 to $2, and PNW MAHJ meets Wednesday evenings at Third Place Commons in Lake Forest Park. Hope Goldberg teaches NMJL-rules lessons for private groups.' WHERE "slug" = 'seattle';

UPDATE "City" SET "intro" = 'Tampa''s listings include a JCC program, a dedicated parlor and instructor-led open play. The Shanna & Bryan Glazer JCC hosts open play on Tuesdays and Wednesdays (free with JCC membership), Life Enrichment Center holds instructor-led open play on Wednesday afternoons, and South Tampa Mahjong Parlor offers open play, a weekly league and instruction. Several teachers offer beginner classes and private lessons.' WHERE "slug" = 'tampa';

UPDATE "City" SET "intro" = 'Washington, DC has a free option: DC Drop-In Mahjongg meets Tuesday evenings at the MLK Jr. Memorial Library, with free lessons for new players (registration required). DC Mahj Collective runs open play, beginner lessons and guided play at Hill Center. Events also appear at shops, a church and the Washington National Cathedral, and several teachers offer private and group lessons.' WHERE "slug" = 'washington-dc';
