INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_boston-jcc-greater-boston-drop-in-mah-jongg', 'JCC Greater Boston Drop-in Mah Jongg', 'boston-jcc-greater-boston-drop-in-mah-jongg', 'Weekly ongoing American Mah Jongg drop-in at the Leventhal-Sidman JCC. Open to all skill levels who know the basics; NMJL rules and current NMJL card required.', (SELECT id FROM City WHERE name = 'Boston' AND state = 'MA'), '333 Nahanton Street, Newton, MA 02459', 'https://www.bostonjcc.org/program/adult-classes/', NULL, 'adultprog@jccgb.org', NULL, NULL, 0, 0, 1, 1, 0, 0, 5, 'Tuesdays 12:30–2:30 PM and Thursdays 10:00 AM–12:00 PM, Wexler Family Lounge. No pre-registration; free for members and $5 for non-members.', 'https://www.bostonjcc.org/program/adult-classes/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_boston-dianne-m', 'Dianne M.', 'boston-dianne-m', (SELECT id FROM City WHERE name = 'Boston' AND state = 'MA'), NULL, 'rikkileigh@aol.com', 1, 1, 0, 1, NULL, 'Teacher directory lists Dianne M. in Boston/Brookline as teaching American Mah Jongg. Contact is provided for arranging lessons.', 'https://wherethewindsblow.com/teachers/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_boston-mah-jongg-a-thon-fall-2026-20261101', 'Mah Jongg-a-thon – Fall 2026', 'boston-mah-jongg-a-thon-fall-2026-20261101', '2026-11-01 00:00:00', '13:00', '16:30', 'Leventhal-Sidman JCC, 333 Nahanton Street, Newton, MA 02459', (SELECT id FROM City WHERE name = 'Boston' AND state = 'MA'), (SELECT id FROM Club WHERE slug = 'boston-jcc-greater-boston-drop-in-mah-jongg'), NULL, 'SOCIAL', 0, 5, 'https://www.bostonjcc.org/calendar/mah-jongg-a-thon-fall-2026/', 'https://www.bostonjcc.org/calendar/mah-jongg-a-thon-fall-2026/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
