INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_san-francisco-toby-salk', 'Toby Salk', 'san-francisco-toby-salk', (SELECT id FROM City WHERE name = 'San Francisco' AND state = 'CA'), 'https://tobysmj.com/', 'tobysmj@gmail.com / 510-334-4516', 1, 1, 0, 1, NULL, 'Bay Area instructor. Teaches American Mah Jongg according to National Mah Jongg League Guidelines; beginner classes, strategy workshops and Mah Jongg brunches. Travels to Bay Area locations and private homes.', 'https://tobysmj.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_san-francisco-mahj-with-molly', 'Mahj with Molly', 'san-francisco-mahj-with-molly', (SELECT id FROM City WHERE name = 'San Francisco' AND state = 'CA'), 'https://www.mahjongmolly.com/', 'info@mahjongmolly.com', 1, 1, 0, 1, NULL, 'Bay Area instructor based in Berkeley and serving the Bay Area. Offers American Mahjong lessons and small/large group lessons; American version uses the National Mahjong League card.', 'https://www.mahjongmolly.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_san-francisco-mahjong-social-play-20261022', 'Mahjong – Social Play', 'san-francisco-mahjong-social-play-20261022', '2026-10-22 00:00:00', '18:30', '21:30', 'JCCSF', (SELECT id FROM City WHERE name = 'San Francisco' AND state = 'CA'), (SELECT id FROM Club WHERE name = 'JCCSF Mahjong – Social Play' AND cityId = (SELECT id FROM City WHERE name = 'San Francisco' AND state = 'CA')), (SELECT id FROM Instructor WHERE name = 'Mahj Social Club SF' AND cityId = (SELECT id FROM City WHERE name = 'San Francisco' AND state = 'CA')), 'OPEN_PLAY', 1, 36, 'https://www.jccsf.org/event/mahjong-social-play/2026-10-22/', 'https://www.jccsf.org/event/mahjong-social-play/2026-10-22/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
