INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_miami-michael-ann-russell-jcc-mah-jongg', 'Michael-Ann Russell JCC Mah Jongg', 'miami-michael-ann-russell-jcc-mah-jongg', 'Adult Services Mah Jongg program at the Michael-Ann Russell Jewish Community Center in North Miami Beach. Dated Wednesday Mah Jongg and Thursday learner-only series are on the official 2026 calendar.', (SELECT id FROM City WHERE name = 'Miami' AND state = 'FL'), '18900 NE 25th Avenue, North Miami Beach, FL 33180', 'https://marjcc.org/series/adult-services-mah-jongg/', '305-932-4200', NULL, NULL, NULL, 1, 0, 1, 1, 0, 0, NULL, 'Wednesdays 10:00 AM–12:00 PM; learner-only Thursdays 10:00 AM–12:00 PM. September–October 2026 dates are posted. Guest/member fee not stated.', 'https://marjcc.org/series/adult-services-mah-jongg/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_miami-wendy-rudman', 'Wendy Rudman', 'miami-wendy-rudman', (SELECT id FROM City WHERE name = 'Miami' AND state = 'FL'), NULL, 'wrudman07@aol.com / 305-298-5422', 1, 1, 0, 1, NULL, 'Longtime Miami-area American/NMJL teacher. Teaches in Miami, Kendall, Coral Gables, South Miami, Miami Beach and Aventura; offers private and group classes in homes and at JCCs, senior living centers, country clubs and condos.', 'https://sloperama.com/majexchange/links.html', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_miami-adult-services-mah-jongg-20261007', 'Adult Services: Mah Jongg', 'miami-adult-services-mah-jongg-20261007', '2026-10-07 00:00:00', '10:00', '12:00', 'Michael-Ann Russell Jewish Community Center, 18900 NE 25th Avenue, North Miami Beach, FL 33180', (SELECT id FROM City WHERE name = 'Miami' AND state = 'FL'), (SELECT id FROM Club WHERE slug = 'miami-michael-ann-russell-jcc-mah-jongg'), NULL, 'OPEN_PLAY', 1, NULL, 'https://marjcc.org/series/adult-services-mah-jongg/', 'https://marjcc.org/series/adult-services-mah-jongg/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
