INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_scottsdale-north-scottsdale-mahjong-players', 'North Scottsdale Mahjong Players', 'scottsdale-north-scottsdale-mahjong-players', 'Recurring American Mahjong group at Holland Community Center. Plays NMJL rules with designated house rules; open weekly Monday session and public contact information.', (SELECT id FROM City WHERE name = 'Scottsdale' AND state = 'AZ'), '34250 N. 60th Street, Scottsdale, AZ 85266', 'https://hollandcenter.org/', '602-214-8207', 'susan@susandryer.com', NULL, NULL, 1, 0, 1, 1, 0, 0, 5, 'Mondays 2:15–3:30 PM at Holland Community Center; $5 supports the Holland Center.', 'https://modernmahjong.com/pages/arizona', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_scottsdale-sonoran-mahjong-co', 'Sonoran Mahjong Co.', 'scottsdale-sonoran-mahjong-co', (SELECT id FROM City WHERE name = 'Scottsdale' AND state = 'AZ'), 'https://www.sonoranmahjongco.com/', 'info@sonoranmahjongco.com', 1, 1, 0, 1, 75, 'Scottsdale-area American Mahjong business. Event pages show NMJL-card play, beginner bootcamp lessons and social play; current site provides a working booking/contact path.', 'https://www.sonoranmahjongco.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_scottsdale-beginner-guided-open-play-american-mah-jongg-20261005', 'Beginner Guided Open Play: American Mah Jongg', 'scottsdale-beginner-guided-open-play-american-mah-jongg-20261005', '2026-10-05 00:00:00', '09:30', '12:00', 'The Holland Center, 34250 N. 60th Street, Scottsdale, AZ 85266', (SELECT id FROM City WHERE name = 'Scottsdale' AND state = 'AZ'), NULL, (SELECT id FROM Instructor WHERE name = 'Katie Petrine' AND cityId = (SELECT id FROM City WHERE name = 'Scottsdale' AND state = 'AZ')), 'OPEN_PLAY', 1, 25, 'https://hollandcenter.org/event/beginner-guided-open-play-american-mah-jongg-10/', 'https://hollandcenter.org/event/beginner-guided-open-play-american-mah-jongg-10/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
