INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_raleigh-the-kitchen-table', 'The Kitchen Table', 'raleigh-the-kitchen-table', 'Recurring American Mahjong open play and beginner classes at The Kitchen Table. Current fall schedule includes multiple October and November open-play dates, and players use the current NMJL card.', (SELECT id FROM City WHERE name = 'Raleigh' AND state = 'NC'), '5629 Creedmoor Rd, Raleigh, NC 27612', 'https://www.kitchentableraleigh.com/', '919-787-1855', NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, 20, 'Open play generally Mondays 6:00-8:30 PM; additional lunch and beginner-class sessions are scheduled.', 'https://www.kitchentableraleigh.com/event-details/mahjong-open-play-on-the-patio-2026-11-30-18-00', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_raleigh-beth-meyer-synagogue-mah-jongg-meet-up', 'Beth Meyer Synagogue Mah Jongg Meet-Up', 'raleigh-beth-meyer-synagogue-mah-jongg-meet-up', 'Weekly Sunday drop-in Mah Jongg in the synagogue library; beginners are welcome and the organizer asks players to bring an American Mah Jongg set and National Mah Jongg League card.', (SELECT id FROM City WHERE name = 'Raleigh' AND state = 'NC'), '504 Newton Road, Raleigh, NC 27615', 'https://www.bethmeyer.org/event/mah-jongg-meet-up.html', '919-848-1420', 'office@bethmeyer.org', NULL, NULL, 1, 0, 1, 1, 0, 0, NULL, 'Sundays 10:00 AM-12:00 PM while religious school is in session; upcoming dates include October 11, 18, 25 and November 1, 8, 15, 22, 2026.', 'https://www.bethmeyer.org/event/mah-jongg-meet-up.html', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_raleigh-mahj-with-r-m', 'Mahj With R+M', 'raleigh-mahj-with-r-m', 'Raleigh Mahjong community with recurring Monday open play at BottleRev3. Current listings show multiple October 2026 sessions and require players to bring NMJL cards.', (SELECT id FROM City WHERE name = 'Raleigh' AND state = 'NC'), '7713 Lead Mine Rd #47, Raleigh, NC 27615', 'https://mahj-with-read.bamgoodtime.com/', NULL, NULL, NULL, NULL, 0, 1, 1, 1, 0, 0, 15, 'Mahj Mondays at BottleRev3, Mondays 6:30-8:30 PM; October 5, 12, 19 and 26, 2026 are listed as open.', 'https://mahj-with-read.bamgoodtime.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_raleigh-wake-up-n-mahj-social-club', 'Wake-Up N'' Mahj Social Club', 'raleigh-wake-up-n-mahj-social-club', 'American Mahjong social club serving Wake County with many day and evening drop-in games and Mahjong 101 prerequisites.', (SELECT id FROM City WHERE name = 'Raleigh' AND state = 'NC'), 'Raleigh / Wake County, NC', 'https://wakeupandmahj.com/', NULL, '954-658-2129', NULL, NULL, 0, 1, 1, 1, 0, 0, 25, 'Many day and evening games per week across Wake County, but the main site does not expose enough exact current session details for a public ACTIVE listing.', 'https://wakeupandmahj.com/', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_raleigh-mandi-mcmillan-mahj-with-mcmillan', 'Mandi McMillan / Mahj with McMillan', 'raleigh-mandi-mcmillan-mahj-with-mcmillan', (SELECT id FROM City WHERE name = 'Raleigh' AND state = 'NC'), 'https://mahjwithmcmillan.com/', '984-386-0335 / hello@mahjwithmcmillan.com', 1, 1, 0, 1, NULL, 'Official site identifies American Mahjong and offers beginner classes, guided play, strategy and league play in the Triangle.', 'https://mahjwithmcmillan.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_raleigh-carol-m', 'Carol M.', 'raleigh-carol-m', (SELECT id FROM City WHERE name = 'Raleigh' AND state = 'NC'), NULL, '919-732-2913 / gourdlover318@gmail.com', 1, 1, 0, 1, NULL, 'MahJongg Maven teacher directory lists Carol M. in Raleigh as an American Mahjong teacher; she teaches at the Senior Center and is open to private lessons.', 'https://mahjonggmaven.com/teachers/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_raleigh-michelle-nice-the-mahj-lady', 'Michelle Nice / The Mahj Lady', 'raleigh-michelle-nice-the-mahj-lady', (SELECT id FROM City WHERE name = 'Raleigh' AND state = 'NC'), NULL, '954-658-2129 / themahjlady@gmail.com', 1, 1, 0, 1, NULL, 'MahJongg Maven teacher directory lists Michelle Nice/The Mahj Lady for Raleigh and surrounding NC cities; she teaches all-level American Mahjong, including beginner to advanced, refresher classes, groups and individuals.', 'https://mahjonggmaven.com/teachers/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_raleigh-gathermahj', 'GatherMahj', 'raleigh-gathermahj', (SELECT id FROM City WHERE name = 'Raleigh' AND state = 'NC'), 'https://www.gathermahj.com/', NULL, 1, 1, 0, 1, NULL, 'Official site offers American Mahjong lessons, private parties and hosted events throughout Raleigh and the Triangle; beginner lessons are available by arrangement.', 'https://www.gathermahj.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_raleigh-open-play-mahjong-at-the-kitchen-table-20261005', 'Open Play Mahjong at The Kitchen Table', 'raleigh-open-play-mahjong-at-the-kitchen-table-20261005', '2026-10-05 00:00:00', '18:00', '20:30', 'The Kitchen Table, 5629 Creedmoor Rd, Raleigh, NC 27612', (SELECT id FROM City WHERE name = 'Raleigh' AND state = 'NC'), (SELECT id FROM Club WHERE slug = 'raleigh-the-kitchen-table'), NULL, 'OPEN_PLAY', 0, 20, 'https://www.kitchentableraleigh.com/event-details/mahjong-open-play-on-the-patio-2026-11-30-18-00', 'https://www.kitchentableraleigh.com/event-details/mahjong-open-play-on-the-patio-2026-11-30-18-00', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_raleigh-mahj-mondays-at-bottlerev3-20261005', 'Mahj Mondays - at BottleRev3', 'raleigh-mahj-mondays-at-bottlerev3-20261005', '2026-10-05 00:00:00', '18:30', '20:30', 'BottleRev3, 7713 Lead Mine Rd #47, Raleigh, NC 27615', (SELECT id FROM City WHERE name = 'Raleigh' AND state = 'NC'), (SELECT id FROM Club WHERE slug = 'raleigh-mahj-with-r-m'), NULL, 'OPEN_PLAY', 0, 15, 'https://mahj-with-read.bamgoodtime.com/', 'https://mahj-with-read.bamgoodtime.com/events', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_raleigh-mah-jongg-meet-up-20261011', 'Mah Jongg Meet-Up', 'raleigh-mah-jongg-meet-up-20261011', '2026-10-11 00:00:00', '10:00', '12:00', 'Beth Meyer Synagogue Library, 504 Newton Road, Raleigh, NC 27615', (SELECT id FROM City WHERE name = 'Raleigh' AND state = 'NC'), (SELECT id FROM Club WHERE slug = 'raleigh-beth-meyer-synagogue-mah-jongg-meet-up'), NULL, 'OPEN_PLAY', 1, NULL, 'https://www.bethmeyer.org/event/mah-jongg-meet-up.html', 'https://www.bethmeyer.org/event/mah-jongg-meet-up.html', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_raleigh-mahj-mondays-at-bottlerev3-20261012', 'Mahj Mondays - at BottleRev3', 'raleigh-mahj-mondays-at-bottlerev3-20261012', '2026-10-12 00:00:00', '18:30', '20:30', 'BottleRev3, 7713 Lead Mine Rd #47, Raleigh, NC 27615', (SELECT id FROM City WHERE name = 'Raleigh' AND state = 'NC'), (SELECT id FROM Club WHERE slug = 'raleigh-mahj-with-r-m'), NULL, 'OPEN_PLAY', 0, 15, 'https://mahj-with-read.bamgoodtime.com/', 'https://mahj-with-read.bamgoodtime.com/events', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_raleigh-open-play-mahjong-at-the-kitchen-table-20261019', 'Open Play Mahjong at The Kitchen Table', 'raleigh-open-play-mahjong-at-the-kitchen-table-20261019', '2026-10-19 00:00:00', '18:00', '20:30', 'The Kitchen Table, 5629 Creedmoor Rd, Raleigh, NC 27612', (SELECT id FROM City WHERE name = 'Raleigh' AND state = 'NC'), (SELECT id FROM Club WHERE slug = 'raleigh-the-kitchen-table'), NULL, 'OPEN_PLAY', 0, 20, 'https://www.kitchentableraleigh.com/event-details/mahjong-open-play-on-the-patio-2026-11-30-18-00', 'https://www.kitchentableraleigh.com/event-details/mahjong-open-play-on-the-patio-2026-11-30-18-00', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
