INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_baltimore-the-tiles-social-club', 'The Tiles Social Club', 'baltimore-the-tiles-social-club', 'Baltimore American Mahjong community hosting recurring open play, lessons and leagues at multiple public venues.', (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD'), 'Baltimore, MD', 'https://tilessocialclub.bamgoodtime.com/', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Current calendar includes October open play and lesson sessions at Cool Beans, Copper Shark, Chesapeake Wine Co, Vessel and other venues.', 'https://tilessocialclub.bamgoodtime.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_baltimore-severna-park-community-center-mahj-in-the-park', 'Severna Park Community Center - Mahj in the Park', 'baltimore-severna-park-community-center-mahj-in-the-park', 'American Mahjong program with beginner lessons and guided open play; sessions explicitly use the NMJL card/rules.', (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD'), '623 Baltimore Annapolis Blvd, Severna Park, MD 21146', 'https://www.spcommunitycenter.org/mahjong/', '410-647-5843', NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, 40, 'MAHJ 101 Oct 7, 14 and 28, 2026; Open Play Mahjoween Oct 29, 2026.', 'https://www.spcommunitycenter.org/mahjong/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_baltimore-howard-county-library-miller-branch-mah-jongg-meet-up', 'Howard County Library - Miller Branch Mah Jongg Meet Up', 'baltimore-howard-county-library-miller-branch-mah-jongg-meet-up', 'Recurring American Mah Jongg meetup for all levels at Miller Branch in Ellicott City.', (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD'), '9421 Frederick Rd, Ellicott City, MD 21042', 'https://www.hclibrary.org/', NULL, NULL, NULL, NULL, 1, 0, 1, 1, 0, 1, NULL, '2nd and 4th Tuesdays monthly, 6:30-8:00 PM; American Mah Jongg, all levels.', 'https://www.bambuddies.org/mahjong-near-me/baltimore-md', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_baltimore-iris-pressman-hi-mahj', 'Iris Pressman / Hi Mahj', 'baltimore-iris-pressman-hi-mahj', (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD'), 'https://himahj.com/', '410-274-2437 / iris4mj@gmail.com', 1, 1, 0, 1, NULL, 'American Mah Jongg instructor teaching in Baltimore May-October; follows National Mah Jongg League rules and teaches beginners and strategy.', 'https://mahjong4friends.com/teachers/md', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_baltimore-heather-s', 'Heather S.', 'baltimore-heather-s', (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD'), NULL, 'hbhimmel@hotmail.com', 1, 1, 0, 1, NULL, 'MahJongg Maven lists Heather S. in Baltimore as an American Mahjong teacher for beginners.', 'https://mahjonggmaven.com/teachers/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_baltimore-mahj-101-20261007', 'MAHJ 101', 'baltimore-mahj-101-20261007', '2026-10-07 00:00:00', '10:00', '12:30', 'Severna Park Community Center, 623 Baltimore Annapolis Blvd, Severna Park, MD 21146', (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD'), (SELECT id FROM Club WHERE slug = 'baltimore-severna-park-community-center-mahj-in-the-park'), NULL, 'LESSON', 1, 40, 'https://www.spcommunitycenter.org/mahjong/', 'https://www.spcommunitycenter.org/mahjong/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_baltimore-open-play-mahjoween-20261029', 'Open Play Mahjoween', 'baltimore-open-play-mahjoween-20261029', '2026-10-29 00:00:00', '10:00', '12:00', 'Severna Park Community Center, 623 Baltimore Annapolis Blvd, Severna Park, MD 21146', (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD'), (SELECT id FROM Club WHERE slug = 'baltimore-severna-park-community-center-mahj-in-the-park'), NULL, 'OPEN_PLAY', 0, 20, 'https://www.spcommunitycenter.org/mahjong/', 'https://www.spcommunitycenter.org/mahjong/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_baltimore-sunday-mahjong-open-play-at-cool-beans-20261004', 'Sunday Mahjong Open Play at Cool Beans', 'baltimore-sunday-mahjong-open-play-at-cool-beans-20261004', '2026-10-04 00:00:00', '11:00', NULL, 'Cool Beans Coffee, Baltimore, MD', (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD'), (SELECT id FROM Club WHERE slug = 'baltimore-the-tiles-social-club'), NULL, 'OPEN_PLAY', 0, 10, 'https://tilessocialclub.bamgoodtime.com/', 'https://tilessocialclub.bamgoodtime.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
