INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_columbus-jewish-community-center-of-greater-columbus-mahjong', 'Jewish Community Center of Greater Columbus Mahjong', 'columbus-jewish-community-center-of-greater-columbus-mahjong', 'American Mahjong program with monthly open play and a six-week beginner series.', (SELECT id FROM City WHERE name = 'Columbus' AND state = 'OH'), '1125 College Ave, Columbus, OH 43209', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Monthly open play, plus beginner series.', 'https://www.bambuddies.org/mahjong-near-me/columbus-oh', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_columbus-clintonville-woman-s-club-mah-jongg', 'Clintonville Woman''s Club Mah Jongg', 'columbus-clintonville-woman-s-club-mah-jongg', 'Recurring mahjong play group with weekly/monthly sessions and periodic tournaments.', (SELECT id FROM City WHERE name = 'Columbus' AND state = 'OH'), '3951 N High St, Columbus, OH 43214', NULL, NULL, NULL, NULL, NULL, 0, 0, 1, 1, 0, 0, NULL, 'Weekly/monthly play and periodic tournaments.', 'https://www.bambuddies.org/mahjong-near-me/columbus-oh', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_columbus-columbus-mah-jongg-mavens', 'Columbus Mah Jongg Mavens', 'columbus-columbus-mah-jongg-mavens', 'Recurring American Mahjong group explicitly described as using NMJL rules and the current-year card.', (SELECT id FROM City WHERE name = 'Columbus' AND state = 'OH'), 'Columbus, OH', NULL, NULL, NULL, NULL, NULL, 0, 0, 1, 1, 0, 0, NULL, 'Recurring schedule arranged through the group.', 'https://www.bambuddies.org/mahjong-near-me/columbus-oh', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_columbus-the-poppy-pair', 'The Poppy Pair', 'columbus-the-poppy-pair', 'American Mah Jongg classes, guided play, private groups and social gatherings throughout Columbus and Central Ohio.', (SELECT id FROM City WHERE name = 'Columbus' AND state = 'OH'), 'Grove City Brewing Co., 3946 Broadway, Grove City, OH 43123', 'https://www.thepoppypair.com/', NULL, NULL, NULL, NULL, 1, 1, 0, 1, 0, 0, NULL, 'Current 2026 classes include Grove City, Marion and Shawnee Hills dates.', 'https://www.thepoppypair.com/classes', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_columbus-let-s-get-mahj-d', 'Let''s Get Mahj''d', 'columbus-let-s-get-mahj-d', 'Columbus-area American Mahjong teaching and social-play group with recurring Mahjong 101/102 classes and open play.', (SELECT id FROM City WHERE name = 'Columbus' AND state = 'OH'), 'Worthington Hills Country Club, 920 Clubview Blvd S, Columbus, OH 43235', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, 65.87, 'Current event Oct 18, 2026; additional classes and open play are scheduled through the fall.', 'https://www.eventbrite.com/e/lets-get-mahjd-mahjong-mimosas-tickets-1993541371908', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_columbus-the-poppy-pair', 'The Poppy Pair', 'columbus-the-poppy-pair', (SELECT id FROM City WHERE name = 'Columbus' AND state = 'OH'), 'https://www.thepoppypair.com/', NULL, 1, 1, 0, 1, NULL, 'American Mah Jongg teaching team serving Columbus and Central Ohio with beginner classes, guided play, private groups and social events; current classes use the NMJL card.', 'https://www.thepoppypair.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_columbus-alice-s', 'Alice S.', 'columbus-alice-s', (SELECT id FROM City WHERE name = 'Columbus' AND state = 'OH'), NULL, 'alice.sadaka@gmail.com', 1, 1, 0, 1, NULL, 'MahJongg Maven lists Alice S. in Columbus as an American Mahjong teacher.', 'https://mahjonggmaven.com/teachers/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_columbus-mahj-102-grove-city-20261014', 'Mahj 102 - Grove City', 'columbus-mahj-102-grove-city-20261014', '2026-10-14 00:00:00', '19:00', '21:00', 'Grove City Brewing Co., 3946 Broadway, Grove City, OH 43123', (SELECT id FROM City WHERE name = 'Columbus' AND state = 'OH'), (SELECT id FROM Club WHERE slug = 'columbus-the-poppy-pair'), NULL, 'LESSON', 1, 35, 'https://www.thepoppypair.com/classes', 'https://www.thepoppypair.com/classes', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_columbus-mahjong-mimosas-20261018', 'Mahjong & Mimosas', 'columbus-mahjong-mimosas-20261018', '2026-10-18 00:00:00', '11:00', '13:00', 'Worthington Hills Country Club, 920 Clubview Blvd S, Columbus, OH 43235', (SELECT id FROM City WHERE name = 'Columbus' AND state = 'OH'), (SELECT id FROM Club WHERE slug = 'columbus-let-s-get-mahj-d'), NULL, 'OPEN_PLAY', 0, 65.87, 'https://www.eventbrite.com/e/lets-get-mahjd-mahjong-mimosas-tickets-1993541371908', 'https://www.eventbrite.com/e/lets-get-mahjd-mahjong-mimosas-tickets-1993541371908', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
