INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_detroit-mahjong-social-club-michigan', 'Mahjong Social Club Michigan', 'detroit-mahjong-social-club-michigan', 'Metro Detroit American Mahjong community offering beginner lessons, guided play, open play and special events.', (SELECT id FROM City WHERE name = 'Detroit' AND state = 'MI'), 'Shelby Township, MI', 'https://mahjongsocialclubmi.com/', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'October 3, 4 and 11, 2026 Mahjong 101 classes at the home studio; additional events listed.', 'https://mahjongsocialclubmi.com/events-classes/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_detroit-birmingham-berkley-first-umc-mah-jongg-open-play', 'Birmingham & Berkley First UMC Mah Jongg Open Play', 'detroit-birmingham-berkley-first-umc-mah-jongg-open-play', 'American Mah Jongg open play at First United Methodist Church in Birmingham.', (SELECT id FROM City WHERE name = 'Detroit' AND state = 'MI'), '1589 W Maple Rd, Birmingham, MI 48009', NULL, NULL, NULL, NULL, NULL, 0, 0, 1, 1, 0, 0, NULL, 'Mondays 6:00-8:00 PM and Saturdays 9:00 AM-12:00 PM, September-November.', 'https://www.bambuddies.org/mahjong-near-me/detroit-mi', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_detroit-westland-public-library-american-mah-jongg-open-play', 'Westland Public Library American Mah Jongg Open Play', 'detroit-westland-public-library-american-mah-jongg-open-play', 'Library-hosted American Mah Jongg open play using the National Mah Jongg League card.', (SELECT id FROM City WHERE name = 'Detroit' AND state = 'MI'), '6123 Central City Pkwy, Westland, MI 48185', 'https://westlandlibrary.org/', NULL, NULL, NULL, NULL, 0, 0, 1, 1, 0, 1, NULL, 'Upcoming open play: October 17, 2026, 10:00 AM-12:00 PM.', 'https://westland.librarycalendar.com/events/list?page=2', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_detroit-katie-wallace-motor-city-mahjong', 'Katie Wallace / Motor City Mahjong', 'detroit-katie-wallace-motor-city-mahjong', (SELECT id FROM City WHERE name = 'Detroit' AND state = 'MI'), 'https://motorcitymahjong.com/', 'katie@motorcitymahjong.com', 1, 1, 0, 1, NULL, 'MahJongg Maven lists Katie Wallace in Detroit as an American Mahjong teacher teaching according to NMJL throughout Southeast Michigan.', 'https://mahjonggmaven.com/teachers/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_detroit-mah-jongg-mommas-jamie-auster', 'Mah Jongg Mommas / Jamie Auster', 'detroit-mah-jongg-mommas-jamie-auster', (SELECT id FROM City WHERE name = 'Detroit' AND state = 'MI'), 'https://www.mahjonggmommas.com/', '925-984-8496 / mahjonggmommas@gmail.com', 1, 1, 1, 1, NULL, 'American Mah Jongg instructor based in the Detroit metro; teaches NMJL rules and offers in-person/online instruction. Current October 2026 classes are published.', 'https://mahjong4friends.com/teachers/mi', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_detroit-mahjong-101-20261003', 'Mahjong 101', 'detroit-mahjong-101-20261003', '2026-10-03 00:00:00', '17:00', NULL, 'Home studio, Shelby Township, MI', (SELECT id FROM City WHERE name = 'Detroit' AND state = 'MI'), (SELECT id FROM Club WHERE slug = 'detroit-mahjong-social-club-michigan'), NULL, 'LESSON', 1, NULL, 'https://mahjongsocialclubmi.com/events-classes/', 'https://mahjongsocialclubmi.com/events-classes/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_detroit-american-mah-jongg-open-play-20261017', 'American Mah Jongg Open Play', 'detroit-american-mah-jongg-open-play-20261017', '2026-10-17 00:00:00', '10:00', '12:00', 'Westland Public Library, 6123 Central City Pkwy, Westland, MI 48185', (SELECT id FROM City WHERE name = 'Detroit' AND state = 'MI'), (SELECT id FROM Club WHERE slug = 'detroit-westland-public-library-american-mah-jongg-open-play'), NULL, 'OPEN_PLAY', 0, NULL, 'https://westland.librarycalendar.com/events/list?page=2', 'https://westland.librarycalendar.com/events/list?page=2', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
