INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_kansas-city-kansas-city-mahjong-club', 'Kansas City Mahjong Club', 'kansas-city-kansas-city-mahjong-club', 'American Mahjong club offering public group lessons, guided open play and open play; current fall programming includes a scheduled October 27 guided-play event.', (SELECT id FROM City WHERE name = 'Kansas City' AND state = 'MO'), 'Prairie Village, KS (Big Grove Brewery; Kansas City metro)', NULL, '816-665-9938', 'katie@kcmahjongclub.com', NULL, NULL, 0, 1, 1, 1, 0, 0, NULL, 'Oct 27, 2026 guided play 5:30-8:00 PM; additional public lessons/open play scheduled through the club.', 'https://www.kansascitymahjong.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_kansas-city-park-hill-district-office-mahjong', 'Park Hill District Office Mahjong', 'kansas-city-park-hill-district-office-mahjong', 'American Mahjong beginner course using the National Mah Jongg League card; two-session class with guided gameplay.', (SELECT id FROM City WHERE name = 'Kansas City' AND state = 'MO'), '7703 NW Barry Road, Kansas City, MO 64153', NULL, NULL, NULL, NULL, NULL, 1, 1, 0, 0, 0, 0, 140, 'October 13 and 20, 2026; beginner class.', 'https://www.active.com/kansas-city-mo/performing-arts/camp/mahjong-for-beginners-2026', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_kansas-city-lauren-sinovic-kansas-city-mahjong', 'Lauren Sinovic / Kansas City Mahjong', 'kansas-city-lauren-sinovic-kansas-city-mahjong', (SELECT id FROM City WHERE name = 'Kansas City' AND state = 'MO'), 'https://www.kansascitymahjong.com/', '469-471-3676 / kansascitymahjong@gmail.com', 1, 1, 0, 1, NULL, 'MahJongg Maven lists Lauren Sinovic as an American Mahjong teacher offering lessons, parties, events and social play in the Kansas City area.', 'https://mahjonggmaven.com/teachers/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_kansas-city-emily-levine-kc-mahjong-mama', 'Emily Levine / KC Mahjong Mama', 'kansas-city-emily-levine-kc-mahjong-mama', (SELECT id FROM City WHERE name = 'Kansas City' AND state = 'MO'), NULL, '913-375-2958 / kcmahjongmama@gmail.com', 1, 1, 0, 1, NULL, 'MahJongg Maven lists Emily Levine as an American Mahjong teacher based in the Kansas City metro, offering lessons, open play and leagues.', 'https://mahjonggmaven.com/teachers/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_kansas-city-val-h', 'Val H.', 'kansas-city-val-h', (SELECT id FROM City WHERE name = 'Kansas City' AND state = 'MO'), NULL, 'mahjongkcmo@gmail.com', 1, 1, 1, 1, NULL, 'MahJongg Maven lists Val H. as an American Mahjong teacher in the KCMO metro, offering in-person and virtual lessons; also plays Siamese and Chinese variants, so confirm desired format when booking.', 'https://mahjonggmaven.com/teachers/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_kansas-city-mahjong-for-beginners-20261013', 'Mahjong for Beginners', 'kansas-city-mahjong-for-beginners-20261013', '2026-10-13 00:00:00', NULL, NULL, 'Park Hill District Office, 7703 NW Barry Road, Kansas City, MO 64153', (SELECT id FROM City WHERE name = 'Kansas City' AND state = 'MO'), (SELECT id FROM Club WHERE slug = 'kansas-city-park-hill-district-office-mahjong'), NULL, 'LESSON', 1, 140, 'https://www.active.com/kansas-city-mo/performing-arts/camp/mahjong-for-beginners-2026', 'https://www.active.com/kansas-city-mo/performing-arts/camp/mahjong-for-beginners-2026', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_kansas-city-kansas-city-mahjong-guided-play-20261027', 'Kansas City Mahjong Guided Play', 'kansas-city-kansas-city-mahjong-guided-play-20261027', '2026-10-27 00:00:00', '17:30', '20:00', 'Big Grove Brewery, Prairie Village, KS', (SELECT id FROM City WHERE name = 'Kansas City' AND state = 'MO'), (SELECT id FROM Club WHERE slug = 'kansas-city-kansas-city-mahjong-club'), (SELECT id FROM Instructor WHERE name = 'Lauren Sinovic' AND cityId = (SELECT id FROM City WHERE name = 'Kansas City' AND state = 'MO')), 'OPEN_PLAY', 0, NULL, 'https://www.kansascitymahjong.com/', 'https://www.kansascitymahjong.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
