INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_pittsburgh-lauri-ann-west-community-center-beginner-mah-jongg', 'Lauri Ann West Community Center - Beginner Mah Jongg', 'pittsburgh-lauri-ann-west-community-center-beginner-mah-jongg', 'Beginner American Mah Jongg class series in the Fox Chapel/O''Hara Township area.', (SELECT id FROM City WHERE name = 'Pittsburgh' AND state = 'PA'), '1220 Powers Run Rd, O''Hara Township, PA', NULL, NULL, NULL, NULL, NULL, 1, 1, 0, 0, 0, 0, NULL, 'Registration-based beginner class series.', 'https://www.bambuddies.org/mahjong-near-me/pittsburgh-pa', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_pittsburgh-cooper-siegel-community-library-open-mah-jong-play', 'Cooper-Siegel Community Library - Open Mah Jong Play', 'pittsburgh-cooper-siegel-community-library-open-mah-jong-play', 'Weekly American Mah Jongg open play in the Fox Chapel area.', (SELECT id FROM City WHERE name = 'Pittsburgh' AND state = 'PA'), '403 Fox Chapel Rd, Fox Chapel area, PA', NULL, NULL, NULL, NULL, NULL, 0, 0, 1, 1, 0, 0, NULL, 'Fridays afternoon; drop-in with registration.', 'https://www.bambuddies.org/mahjong-near-me/pittsburgh-pa', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_pittsburgh-pittsburgh-mahjong-club-at-rodef-shalom', 'Pittsburgh Mahjong Club at Rodef Shalom', 'pittsburgh-pittsburgh-mahjong-club-at-rodef-shalom', 'Monthly American Mahjong open play and group lessons at Rodef Shalom in Shadyside.', (SELECT id FROM City WHERE name = 'Pittsburgh' AND state = 'PA'), '4905 Fifth Ave, Pittsburgh, PA 15213', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Monthly meetups with open play and group lessons.', 'https://www.bambuddies.org/mahjong-near-me/pittsburgh-pa', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_pittsburgh-pgh-mahjong-club-at-the-picket-fence', 'PGH Mahjong Club at The Picket Fence', 'pittsburgh-pgh-mahjong-club-at-the-picket-fence', 'Beginner-level American Mah Jongg sessions hosted by PGH Mahjong Club at The Picket Fence in Sewickley.', (SELECT id FROM City WHERE name = 'Pittsburgh' AND state = 'PA'), 'The Picket Fence, Sewickley, PA', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Beginner-level sessions listed for the Pittsburgh metro.', 'https://orderofthetile.com/find-mahjong/pennsylvania/', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_pittsburgh-liz-watkins', 'Liz Watkins', 'pittsburgh-liz-watkins', (SELECT id FROM City WHERE name = 'Pittsburgh' AND state = 'PA'), NULL, NULL, 1, 1, 0, 1, NULL, 'BamBuddies lists Liz Watkins as an American Mahjong instructor in Pittsburgh/Western PA offering lessons, open play sessions and tournaments by arrangement.', 'https://www.bambuddies.org/mahjong-near-me/pittsburgh-pa', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_pittsburgh-three-rivers-mahjong', 'Three Rivers Mahjong', 'pittsburgh-three-rivers-mahjong', (SELECT id FROM City WHERE name = 'Pittsburgh' AND state = 'PA'), NULL, NULL, 0, 1, 0, 1, NULL, 'BamBuddies lists Three Rivers Mahjong with scheduled Mahjong 101/102 classes in the Pittsburgh-area Wexford and Cranberry locations.', 'https://www.bambuddies.org/mahjong-near-me/pittsburgh-pa', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
