INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_cincinnati-mayerson-jcc-mah-jongg-drop-in', 'Mayerson JCC Mah-Jongg Drop-In', 'cincinnati-mayerson-jcc-mah-jongg-drop-in', 'Recurring American Mah Jongg drop-in at the Mayerson JCC.', (SELECT id FROM City WHERE name = 'Cincinnati' AND state = 'OH'), '8485 Ridge Rd, Cincinnati, OH 45236', NULL, NULL, NULL, NULL, NULL, 0, 0, 1, 1, 0, 0, NULL, 'Tuesdays 1:00-4:00 PM, drop-in.', 'https://www.bambuddies.org/mahjong-near-me/cincinnati-oh', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_cincinnati-mariemont-branch-library-open-play-mahjong', 'Mariemont Branch Library - Open Play Mahjong', 'cincinnati-mariemont-branch-library-open-play-mahjong', 'Recurring American Mahjong open play with beginner instruction.', (SELECT id FROM City WHERE name = 'Cincinnati' AND state = 'OH'), '3810 Pocahontas Ave, Cincinnati, OH 45227', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 1, NULL, 'Select Tuesdays 6:00-8:00 PM; beginner instruction 5:30-6:00 PM.', 'https://www.bambuddies.org/mahjong-near-me/cincinnati-oh', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_cincinnati-mrs-mahj', 'Mrs Mahj', 'cincinnati-mrs-mahj', (SELECT id FROM City WHERE name = 'Cincinnati' AND state = 'OH'), NULL, NULL, 1, 1, 0, 1, NULL, 'American Mahjong group and private lessons by appointment.', 'https://www.bambuddies.org/mahjong-near-me/cincinnati-oh', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_cincinnati-mahj-with-meg', 'Mahj with Meg', 'cincinnati-mahj-with-meg', (SELECT id FROM City WHERE name = 'Cincinnati' AND state = 'OH'), 'https://www.mahjwithmeg.com/', NULL, 1, 1, 0, 1, 75, 'American Mahjong instruction; current materials explicitly teach the NMJL card and full-game basics.', 'https://www.mahjwithmeg.com/event/mahj-basics-f3s63', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_cincinnati-american-mahjong-open-play-20261015', 'American Mahjong - Open Play', 'cincinnati-american-mahjong-open-play-20261015', '2026-10-15 00:00:00', '17:30', '20:30', 'Green Township Branch Library, Cincinnati, OH', (SELECT id FROM City WHERE name = 'Cincinnati' AND state = 'OH'), NULL, NULL, 'OPEN_PLAY', 1, NULL, 'https://cincinnatilibrary.bibliocommons.com/v2/events?series=6a401f30c7d3cd58006342c1', 'https://cincinnatilibrary.bibliocommons.com/v2/events?series=6a401f30c7d3cd58006342c1', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_cincinnati-mix-mingle-mahjong-20261007', 'Mix, Mingle & Mahjong', 'cincinnati-mix-mingle-mahjong-20261007', '2026-10-07 00:00:00', '17:30', '20:00', 'The Roosevelt Room-Rookwood, 3825 Edwards Rd Suite 107, Cincinnati, OH 45209', (SELECT id FROM City WHERE name = 'Cincinnati' AND state = 'OH'), NULL, NULL, 'OPEN_PLAY', 1, 15, 'https://www.visitcincy.com/event/mix-mingle-%26-mahjong/20364/', 'https://www.visitcincy.com/event/mix-mingle-%26-mahjong/20364/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
