INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_cleveland-cleveland-mahjong-collective', 'Cleveland Mahjong Collective', 'cleveland-cleveland-mahjong-collective', 'Recurring American Mahjong open play, guided play, lessons and leagues.', (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH'), 'Cleveland, OH', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Recurring open play, lessons and leagues.', 'https://www.bambuddies.org/mahjong-near-me/cleveland-oh', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_cleveland-southwest-cleveland-mahjong', 'Southwest Cleveland Mahjong', 'cleveland-southwest-cleveland-mahjong', 'American Mahjong group running recurring Mahjong 101/102 and open play in the Cleveland metro.', (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH'), 'Market 42, 2099 Pearl Rd, Brunswick, OH 44212', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, 12.51, 'Recurring Tuesday sessions around 6:00 PM; current fall 2026 season uses the 2026 NMJL card.', 'https://mahjmuddle.com/swclemahjong', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_cleveland-amy-myers-mahj', 'Amy Myers Mahj', 'cleveland-amy-myers-mahj', (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH'), NULL, NULL, 1, 1, 0, 1, NULL, 'American Mahjong teacher offering beginner/intermediate classes, guided play, strategy sessions, group lessons and league play in the Cleveland area.', 'https://www.bambuddies.org/mahjong-near-me/cleveland-oh', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_cleveland-mahjong-101-or-open-play-at-market-42-20261006', 'Mahjong 101 or Open Play at Market 42', 'cleveland-mahjong-101-or-open-play-at-market-42-20261006', '2026-10-06 00:00:00', '18:00', '20:30', 'Market 42, 2099 Pearl Road, Brunswick, OH 44212', (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH'), (SELECT id FROM Club WHERE slug = 'cleveland-southwest-cleveland-mahjong'), NULL, 'OPEN_PLAY', 1, 12.51, 'https://www.eventbrite.com/e/mahjong-101-or-open-play-at-market-42-tickets-1997269209972', 'https://www.eventbrite.com/e/mahjong-101-or-open-play-at-market-42-tickets-1997269209972', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_cleveland-mahjong-open-play-20261007', 'Mahjong Open Play', 'cleveland-mahjong-open-play-20261007', '2026-10-07 00:00:00', '17:30', '19:30', 'Kelly''s Cafe, 1661 Pearl Road, Brunswick, OH 44212', (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH'), (SELECT id FROM Club WHERE slug = 'cleveland-southwest-cleveland-mahjong'), NULL, 'OPEN_PLAY', 0, NULL, 'https://www.eventbrite.com/e/mahjong-open-play-tickets-2001707424792', 'https://www.eventbrite.com/e/mahjong-open-play-tickets-2001707424792', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_cleveland-mahjong-101-open-play-glass-of-wine-20261013', 'Mahjong 101 & Open Play + Glass of Wine', 'cleveland-mahjong-101-open-play-glass-of-wine-20261013', '2026-10-13 00:00:00', '18:00', '20:30', 'Flight Cleveland, 5712 Detroit Avenue, Cleveland, OH 44102', (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH'), NULL, NULL, 'LESSON', 1, 65, 'https://stayhappening.com/e/mahjong-101-andamp-open-play-glass-of-wine-mahjong-irl-at-flight-cleveland-E118SB5EETNCY', 'https://stayhappening.com/e/mahjong-101-andamp-open-play-glass-of-wine-mahjong-irl-at-flight-cleveland-E118SB5EETNCY', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
