INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_indianapolis-fishers-mah-jongg-center', 'Fishers Mah Jongg Center', 'indianapolis-fishers-mah-jongg-center', 'Dedicated central Indiana Mah Jongg center observing National Mah Jongg League rules; members and non-members welcome.', (SELECT id FROM City WHERE name = 'Indianapolis' AND state = 'IN'), '9006 Technology Ln, Fishers, IN 46038', 'https://fishersmahjongg.com/', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, 15, 'Open play sessions; non-members $15/session; beginner lessons $40/session.', 'https://fishersmahjongg.com/join-us/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_indianapolis-317-mahj-collective', '317 Mahj Collective', 'indianapolis-317-mahj-collective', 'Indianapolis-area American Mahjong group hosting lessons, community events and Mahjong Mondays.', (SELECT id FROM City WHERE name = 'Indianapolis' AND state = 'IN'), 'Indianapolis, IN', 'https://linktr.ee/317mahj', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Mahjong 101, brunches, drop-in passes and recurring community events.', 'https://linktr.ee/317mahj', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_indianapolis-jaime-keith-meet-at-mahj', 'Jaime Keith / Meet at Mahj', 'indianapolis-jaime-keith-meet-at-mahj', (SELECT id FROM City WHERE name = 'Indianapolis' AND state = 'IN'), 'https://meetatmahj.com/', '317-763-0239 / support@meetatmahj.com', 1, 1, 0, 1, NULL, 'Certified instructor; American Mahjong lessons, parties and events, with studio in nearby Zionsville.', 'https://meetatmahj.com/about', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_indianapolis-american-mahjong-open-play-20261006', 'American Mahjong - Open Play', 'indianapolis-american-mahjong-open-play-20261006', '2026-10-06 00:00:00', '17:30', '19:30', 'Indianapolis Central Library, 40 E Saint Clair St, Indianapolis, IN 46204', (SELECT id FROM City WHERE name = 'Indianapolis' AND state = 'IN'), NULL, NULL, 'OPEN_PLAY', 0, NULL, 'https://indianapolis.libnet.info/event/17448434', 'https://indianapolis.libnet.info/event/17448434', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_indianapolis-american-mahjong-instruction-20261015', 'American Mahjong – Instruction', 'indianapolis-american-mahjong-instruction-20261015', '2026-10-15 00:00:00', '14:00', '16:00', 'Indianapolis Central Library, 40 E Saint Clair St, Indianapolis, IN 46204', (SELECT id FROM City WHERE name = 'Indianapolis' AND state = 'IN'), NULL, NULL, 'LESSON', 1, NULL, 'https://indianapolis.libnet.info/event/17427789', 'https://indianapolis.libnet.info/event/17427789', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_indianapolis-american-mahjong-open-play-20261020', 'American Mahjong – Open Play', 'indianapolis-american-mahjong-open-play-20261020', '2026-10-20 00:00:00', '17:30', '19:30', 'Indianapolis Central Library, 40 E Saint Clair St, Indianapolis, IN 46204', (SELECT id FROM City WHERE name = 'Indianapolis' AND state = 'IN'), NULL, NULL, 'OPEN_PLAY', 0, NULL, 'https://indianapolis.libnet.info/event/17448476', 'https://indianapolis.libnet.info/event/17448476', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
