INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_milwaukee-harry-rose-samson-family-jcc-mah-jongg', 'Harry & Rose Samson Family JCC — Mah Jongg', 'milwaukee-harry-rose-samson-family-jcc-mah-jongg', 'Weekly American Mahjong at the Harry & Rose Samson Family JCC.', (SELECT id FROM City WHERE name = 'Milwaukee' AND state = 'WI'), 'Whitefish Bay, WI', NULL, NULL, NULL, NULL, NULL, 0, 0, 1, 1, 0, 0, NULL, 'Mondays 12:00-3:00 PM.', 'https://www.bambuddies.org/mahjong-near-me/milwaukee-wi', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_milwaukee-american-mah-jongg-at-whole-foods-market', 'American Mah Jongg at Whole Foods Market', 'milwaukee-american-mah-jongg-at-whole-foods-market', 'Recurring American Mahjong play at the Prospect Avenue Whole Foods location.', (SELECT id FROM City WHERE name = 'Milwaukee' AND state = 'WI'), 'Whole Foods Market, Prospect Ave, Milwaukee, WI', NULL, NULL, NULL, NULL, NULL, 0, 0, 1, 1, 0, 0, NULL, 'Fridays 1:00-4:00 PM.', 'https://www.bambuddies.org/mahjong-near-me/milwaukee-wi', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_milwaukee-the-sassy-sparrow-mahjong', 'The Sassy Sparrow Mahjong', 'milwaukee-the-sassy-sparrow-mahjong', 'American Mahjong lessons, open play and league activity in the Milwaukee metro.', (SELECT id FROM City WHERE name = 'Milwaukee' AND state = 'WI'), 'Waterford, WI', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Lessons, open play and league; events posted on site calendar.', 'https://www.bambuddies.org/mahjong-near-me/milwaukee-wi', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_milwaukee-julie-littman-mke-mahjong', 'Julie Littman / MKE Mahjong', 'milwaukee-julie-littman-mke-mahjong', (SELECT id FROM City WHERE name = 'Milwaukee' AND state = 'WI'), 'https://www.mkemahjong.com/wisconsin', '414-755-9845 / julie@mkemahjong.com', 1, 1, 0, 1, 50, 'Certified American Mah Jongg instructor; explicitly teaches National Mah Jongg League rules and the annual card.', 'https://www.mkemahjong.com/wisconsin', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_milwaukee-candace-burrows', 'Candace Burrows', 'milwaukee-candace-burrows', (SELECT id FROM City WHERE name = 'Milwaukee' AND state = 'WI'), NULL, NULL, 1, 1, 0, 1, NULL, 'American Mah Jongg teacher serving the Milwaukee metro; lessons by arrangement.', 'https://www.bambuddies.org/mahjong-near-me/milwaukee-wi', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
