INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_st-louis-clover-club', 'Clover Club', 'st-louis-clover-club', 'Dedicated St. Louis American Mah Jongg teaching, guided-play and open-play business.', (SELECT id FROM City WHERE name = 'St. Louis' AND state = 'MO'), '10000 Watson Road, North Bldg, Suite L-2, Crestwood, MO 63126', 'https://www.cloverclubstl.com/', NULL, 'support@cloverclubstl.com', NULL, NULL, 1, 1, 1, 1, 0, 0, 25, 'Guided Tables are $25 for 2 hours; current sessions use the NMJL card.', 'https://www.cloverclubstl.com/guided-play', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_st-louis-magpie-mahjong', 'Magpie Mahjong', 'st-louis-magpie-mahjong', 'St. Louis American Mahjong community offering lessons and signature open-play events.', (SELECT id FROM City WHERE name = 'St. Louis' AND state = 'MO'), 'St. Louis, MO', 'https://www.magpiemahjong.com/', NULL, 'magpiemahjong@gmail.com', NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Lessons and open-play events; current 2026 community events.', 'https://www.bamgoodtime.com/clubs', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_st-louis-ali-salter-magpie-mahjong', 'Ali Salter / Magpie Mahjong', 'st-louis-ali-salter-magpie-mahjong', (SELECT id FROM City WHERE name = 'St. Louis' AND state = 'MO'), 'https://www.magpiemahjong.com/', 'magpiemahjong@gmail.com', 1, 1, 0, 1, NULL, 'St. Louis American Mahjong instructor and founder of Magpie Mahjong; current event listings identify Ali as instructor and guide.', 'https://www.mahjonggmaven.com/teachers/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_st-louis-free-mahjong-open-play-at-cork-rind-20261003', 'Free Mahjong Open Play at Cork & Rind', 'st-louis-free-mahjong-open-play-at-cork-rind-20261003', '2026-10-03 00:00:00', '14:00', '16:00', 'Cork & Rind, 555 First Capitol Drive, Saint Charles, MO 63301', (SELECT id FROM City WHERE name = 'St. Louis' AND state = 'MO'), NULL, NULL, 'OPEN_PLAY', 0, 0, 'https://www.eventbrite.com/e/free-mahjong-open-play-at-cork-rind-tickets-2001083254883', 'https://www.eventbrite.com/e/free-mahjong-open-play-at-cork-rind-tickets-2001083254883', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_st-louis-a-charming-mahjong-league-thursday-nights-20261001', 'A Charming Mahjong League: Thursday Nights', 'st-louis-a-charming-mahjong-league-thursday-nights-20261001', '2026-10-01 00:00:00', '19:00', '21:00', 'Paisley Boutique, 36 W Lockwood Ave, Webster Groves, MO 63119', (SELECT id FROM City WHERE name = 'St. Louis' AND state = 'MO'), NULL, NULL, 'TOURNAMENT', 0, 220, 'https://www.eventbrite.com/e/a-charming-mahjong-league-thursday-nights-tickets-2000233901444', 'https://www.eventbrite.com/e/a-charming-mahjong-league-thursday-nights-tickets-2000233901444', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_st-louis-mahj-social-open-play-20261006', 'Mahj Social Open Play', 'st-louis-mahj-social-open-play-20261006', '2026-10-06 00:00:00', '16:00', '18:00', '36 W Lockwood Ave, Webster Groves, MO 63119', (SELECT id FROM City WHERE name = 'St. Louis' AND state = 'MO'), NULL, NULL, 'OPEN_PLAY', 0, 10.38, 'https://www.unation.com/city/mo/st-louis/festus/', 'https://www.unation.com/city/mo/st-louis/festus/', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
