INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_pittsburgh-hillel-juc-of-pittsburgh-mahjong-club', 'Hillel JUC of Pittsburgh - Mahjong Club', 'pittsburgh-hillel-juc-of-pittsburgh-mahjong-club', 'Monthly American Mahjong club in Oakland.', (SELECT id FROM City WHERE name = 'Pittsburgh' AND state = 'PA'), 'Oakland, Pittsburgh, PA', NULL, NULL, NULL, NULL, NULL, 0, 1, 1, 1, 0, 0, NULL, 'Monthly.', 'https://www.bambuddies.org/mahjong-near-me/pittsburgh-pa', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_pittsburgh-temple-sinai-mahjong-club', 'Temple Sinai Mahjong Club', 'pittsburgh-temple-sinai-mahjong-club', 'American Mahjong lessons plus recurring weekly sessions.', (SELECT id FROM City WHERE name = 'Pittsburgh' AND state = 'PA'), 'Squirrel Hill, Pittsburgh, PA', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Lessons plus recurring weekly sessions.', 'https://www.bambuddies.org/mahjong-near-me/pittsburgh-pa', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_pittsburgh-jane-s', 'Jane S.', 'pittsburgh-jane-s', (SELECT id FROM City WHERE name = 'Pittsburgh' AND state = 'PA'), NULL, '412-805-7374', 1, 1, 0, 1, NULL, 'MahJongg Maven teacher directory lists Jane S. in Cranberry Township/Pittsburgh as an American Mahjong teacher.', 'https://mahjonggmaven.com/teachers/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_pittsburgh-american-mahjong-at-northern-tier-regional-library-20261007', 'American Mahjong at Northern Tier Regional Library', 'pittsburgh-american-mahjong-at-northern-tier-regional-library-20261007', '2026-10-07 00:00:00', '13:00', '15:00', 'Northern Tier Regional Library, Pittsburgh, PA', (SELECT id FROM City WHERE name = 'Pittsburgh' AND state = 'PA'), NULL, NULL, 'OPEN_PLAY', 0, NULL, 'https://northerntier.librarycalendar.com/events/week', 'https://northerntier.librarycalendar.com/events/week', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_pittsburgh-open-play-at-cornerstone-restaurant-20261003', 'Open Play at Cornerstone Restaurant', 'pittsburgh-open-play-at-cornerstone-restaurant-20261003', '2026-10-03 00:00:00', NULL, NULL, 'Cornerstone Restaurant and Bar, Pittsburgh, PA', (SELECT id FROM City WHERE name = 'Pittsburgh' AND state = 'PA'), NULL, NULL, 'OPEN_PLAY', 0, NULL, 'https://www.yinzmahj.com/', 'https://www.yinzmahj.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
