INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_louisville-keneseth-israel-mahjong-club', 'Keneseth Israel Mahjong Club', 'louisville-keneseth-israel-mahjong-club', 'Community Mahjong club meeting Thursdays at Keneseth Israel; current calendar confirms recurring sessions, but the current event page does not explicitly identify the variant.', (SELECT id FROM City WHERE name = 'Louisville' AND state = 'KY'), '2531 Taylorsville Road, Louisville, KY', 'https://jewishlouisville.org/community-calendar/', NULL, NULL, NULL, NULL, 1, 0, 1, 1, 0, 1, NULL, 'Thursdays at 1:30 PM', 'https://jewishlouisville.org/community-calendar/', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_louisville-trager-family-jcc-mahjong', 'Trager Family JCC Mahjong', 'louisville-trager-family-jcc-mahjong', 'Mahjong programming at the Trager Family JCC is documented, including NMJL use in a 2026 event, but no current dated public session was found.', (SELECT id FROM City WHERE name = 'Louisville' AND state = 'KY'), '3600 Dutchmans Lane, Louisville, KY 40205', 'https://jewishlouisville.org/', '502-459-0660', NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, NULL, 'https://jfcslouisville.org/event/mahjong-for-a-mission/', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_louisville-sissy-w', 'Sissy W.', 'louisville-sissy-w', (SELECT id FROM City WHERE name = 'Louisville' AND state = 'KY'), NULL, 'mbwatson17@icloud.com', 0, 0, 0, 1, NULL, 'American Mah Jongg for beginners; directory listing says American.', 'https://mahjonggmaven.com/teachers/', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_louisville-mahjong-club-20261001', 'Mahjong Club', 'louisville-mahjong-club-20261001', '2026-10-01 00:00:00', '13:30', '15:00', 'Keneseth Israel Congregation, 2531 Taylorsville Road, Louisville, KY', (SELECT id FROM City WHERE name = 'Louisville' AND state = 'KY'), (SELECT id FROM Club WHERE slug = 'louisville-keneseth-israel-mahjong-club'), NULL, 'OPEN_PLAY', 1, NULL, NULL, 'https://jewishlouisville.org/community-calendar/', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_louisville-mahjong-club-20261008', 'Mahjong Club', 'louisville-mahjong-club-20261008', '2026-10-08 00:00:00', '13:30', '15:00', 'Keneseth Israel Congregation, 2531 Taylorsville Road, Louisville, KY', (SELECT id FROM City WHERE name = 'Louisville' AND state = 'KY'), (SELECT id FROM Club WHERE slug = 'louisville-keneseth-israel-mahjong-club'), NULL, 'OPEN_PLAY', 1, NULL, NULL, 'https://jewishlouisville.org/community-calendar/', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_louisville-mahjong-club-20261015', 'Mahjong Club', 'louisville-mahjong-club-20261015', '2026-10-15 00:00:00', '13:30', '15:00', 'Keneseth Israel Congregation, 2531 Taylorsville Road, Louisville, KY', (SELECT id FROM City WHERE name = 'Louisville' AND state = 'KY'), (SELECT id FROM Club WHERE slug = 'louisville-keneseth-israel-mahjong-club'), NULL, 'OPEN_PLAY', 1, NULL, NULL, 'https://jewishlouisville.org/community-calendar/', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_louisville-mahjong-club-20261022', 'Mahjong Club', 'louisville-mahjong-club-20261022', '2026-10-22 00:00:00', '13:30', '15:00', 'Keneseth Israel Congregation, 2531 Taylorsville Road, Louisville, KY', (SELECT id FROM City WHERE name = 'Louisville' AND state = 'KY'), (SELECT id FROM Club WHERE slug = 'louisville-keneseth-israel-mahjong-club'), NULL, 'OPEN_PLAY', 1, NULL, NULL, 'https://jewishlouisville.org/community-calendar/', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_louisville-mahjong-club-20261029', 'Mahjong Club', 'louisville-mahjong-club-20261029', '2026-10-29 00:00:00', '13:30', '15:00', 'Keneseth Israel Congregation, 2531 Taylorsville Road, Louisville, KY', (SELECT id FROM City WHERE name = 'Louisville' AND state = 'KY'), (SELECT id FROM Club WHERE slug = 'louisville-keneseth-israel-mahjong-club'), NULL, 'OPEN_PLAY', 1, NULL, NULL, 'https://jewishlouisville.org/community-calendar/', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_louisville-mahjong-club-20261105', 'Mahjong Club', 'louisville-mahjong-club-20261105', '2026-11-05 00:00:00', '13:30', '15:00', 'Keneseth Israel Congregation, 2531 Taylorsville Road, Louisville, KY', (SELECT id FROM City WHERE name = 'Louisville' AND state = 'KY'), (SELECT id FROM Club WHERE slug = 'louisville-keneseth-israel-mahjong-club'), NULL, 'OPEN_PLAY', 1, NULL, NULL, 'https://jewishlouisville.org/community-calendar/', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_louisville-mahjong-club-20261112', 'Mahjong Club', 'louisville-mahjong-club-20261112', '2026-11-12 00:00:00', '13:30', '15:00', 'Keneseth Israel Congregation, 2531 Taylorsville Road, Louisville, KY', (SELECT id FROM City WHERE name = 'Louisville' AND state = 'KY'), (SELECT id FROM Club WHERE slug = 'louisville-keneseth-israel-mahjong-club'), NULL, 'OPEN_PLAY', 1, NULL, NULL, 'https://jewishlouisville.org/community-calendar/', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_louisville-mahjong-club-20261119', 'Mahjong Club', 'louisville-mahjong-club-20261119', '2026-11-19 00:00:00', '13:30', '15:00', 'Keneseth Israel Congregation, 2531 Taylorsville Road, Louisville, KY', (SELECT id FROM City WHERE name = 'Louisville' AND state = 'KY'), (SELECT id FROM Club WHERE slug = 'louisville-keneseth-israel-mahjong-club'), NULL, 'OPEN_PLAY', 1, NULL, NULL, 'https://jewishlouisville.org/community-calendar/', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
