INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_oklahoma-city-mahj-bougie', 'Mahj & Bougie', 'oklahoma-city-mahj-bougie', 'American Mahjong organizer offering lessons, open play and league events in Oklahoma City.', (SELECT id FROM City WHERE name = 'Oklahoma City' AND state = 'OK'), 'Oklahoma City, OK', 'https://mahj-bougie.bamgoodtime.com/', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, NULL, 'https://mahj-bougie.bamgoodtime.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_oklahoma-city-ok-let-s-mahjong', 'OK LET''S MAHJONG', 'oklahoma-city-ok-let-s-mahjong', 'Oklahoma City Mahjong organizer with dated social league and tournament events.', (SELECT id FROM City WHERE name = 'Oklahoma City' AND state = 'OK'), 'Oklahoma City, OK', 'https://www.okletsmahjong.com/events', NULL, NULL, NULL, NULL, 0, 0, 1, 1, 0, 0, NULL, NULL, 'https://www.okletsmahjong.com/events', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_oklahoma-city-mahj-bougie-event-20261004', 'Mahj & Bougie Event', 'oklahoma-city-mahj-bougie-event-20261004', '2026-10-04 00:00:00', '13:00', '16:00', 'Maxwell''s on The Lake, 4491 S Lake Hefner Dr, Oklahoma City, OK 73116', (SELECT id FROM City WHERE name = 'Oklahoma City' AND state = 'OK'), (SELECT id FROM Club WHERE slug = 'oklahoma-city-mahj-bougie'), NULL, 'SOCIAL', 0, 35, 'https://mahj-bougie.bamgoodtime.com/', 'https://mahj-bougie.bamgoodtime.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_oklahoma-city-mahj-bougie-event-20261005', 'Mahj & Bougie Event', 'oklahoma-city-mahj-bougie-event-20261005', '2026-10-05 00:00:00', '18:30', '20:30', 'Bar Serra, 424 NW 10th St Ste 103, Oklahoma City, OK 73103', (SELECT id FROM City WHERE name = 'Oklahoma City' AND state = 'OK'), (SELECT id FROM Club WHERE slug = 'oklahoma-city-mahj-bougie'), NULL, 'LESSON', 1, 50, 'https://mahj-bougie.bamgoodtime.com/', 'https://mahj-bougie.bamgoodtime.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_oklahoma-city-mahj-bougie-event-20261011', 'Mahj & Bougie Event', 'oklahoma-city-mahj-bougie-event-20261011', '2026-10-11 00:00:00', '13:00', '16:00', 'Maxwell''s on The Lake, 4491 S Lake Hefner Dr, Oklahoma City, OK 73116', (SELECT id FROM City WHERE name = 'Oklahoma City' AND state = 'OK'), (SELECT id FROM Club WHERE slug = 'oklahoma-city-mahj-bougie'), NULL, 'SOCIAL', 0, 35, 'https://mahj-bougie.bamgoodtime.com/', 'https://mahj-bougie.bamgoodtime.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_oklahoma-city-mahj-bougie-event-20261019', 'Mahj & Bougie Event', 'oklahoma-city-mahj-bougie-event-20261019', '2026-10-19 00:00:00', '18:30', '20:30', 'Bar Serra, 424 NW 10th St Ste 103, Oklahoma City, OK 73103', (SELECT id FROM City WHERE name = 'Oklahoma City' AND state = 'OK'), (SELECT id FROM Club WHERE slug = 'oklahoma-city-mahj-bougie'), NULL, 'LESSON', 1, 50, 'https://mahj-bougie.bamgoodtime.com/', 'https://mahj-bougie.bamgoodtime.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_oklahoma-city-mahj-bougie-event-20261101', 'Mahj & Bougie Event', 'oklahoma-city-mahj-bougie-event-20261101', '2026-11-01 00:00:00', '13:00', '16:00', 'Maxwell''s on The Lake, 4491 S Lake Hefner Dr, Oklahoma City, OK 73116', (SELECT id FROM City WHERE name = 'Oklahoma City' AND state = 'OK'), (SELECT id FROM Club WHERE slug = 'oklahoma-city-mahj-bougie'), NULL, 'SOCIAL', 0, 35, 'https://mahj-bougie.bamgoodtime.com/', 'https://mahj-bougie.bamgoodtime.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_oklahoma-city-mahj-bougie-event-20261115', 'Mahj & Bougie Event', 'oklahoma-city-mahj-bougie-event-20261115', '2026-11-15 00:00:00', '13:00', '16:00', 'Maxwell''s on The Lake, 4491 S Lake Hefner Dr, Oklahoma City, OK 73116', (SELECT id FROM City WHERE name = 'Oklahoma City' AND state = 'OK'), (SELECT id FROM Club WHERE slug = 'oklahoma-city-mahj-bougie'), NULL, 'SOCIAL', 0, 35, 'https://mahj-bougie.bamgoodtime.com/', 'https://mahj-bougie.bamgoodtime.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_oklahoma-city-okc-two-player-showdown-with-my-wife-plays-mahjong-20261012', 'OKC: Two-Player Showdown with My Wife Plays Mahjong', 'oklahoma-city-okc-two-player-showdown-with-my-wife-plays-mahjong-20261012', '2026-10-12 00:00:00', '18:30', '20:30', 'Cosabella Kitchen, 6516 N Olie Ave, Oklahoma City, OK', (SELECT id FROM City WHERE name = 'Oklahoma City' AND state = 'OK'), (SELECT id FROM Club WHERE slug = 'oklahoma-city-ok-let-s-mahjong'), NULL, 'TOURNAMENT', 0, 100, 'https://www.okletsmahjong.com/events', 'https://www.okletsmahjong.com/events', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_oklahoma-city-okc-fall-social-league-20261021', 'OKC: Fall Social League', 'oklahoma-city-okc-fall-social-league-20261021', '2026-10-21 00:00:00', '18:00', '20:00', 'Cloud Puncher Rooftop Bar & Restaurant at Lively Hotel, Oklahoma City, OK', (SELECT id FROM City WHERE name = 'Oklahoma City' AND state = 'OK'), (SELECT id FROM Club WHERE slug = 'oklahoma-city-ok-let-s-mahjong'), NULL, 'SOCIAL', 0, 30, 'https://www.okletsmahjong.com/events', 'https://www.okletsmahjong.com/events', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
