INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_salt-lake-city-ij-jeanne-wagner-jewish-community-center-mahjong', 'IJ & Jeanné Wagner Jewish Community Center Mahjong', 'salt-lake-city-ij-jeanne-wagner-jewish-community-center-mahjong', 'American Mahjong program at the JCC; official page explicitly says American Mahjong and National Mahjong League card.', (SELECT id FROM City WHERE name = 'Salt Lake City' AND state = 'UT'), '2 North Medical Dr, Salt Lake City, UT 84113', 'https://www.slcjcc.org/', '801-581-0098', 'community@slcjcc.org', NULL, NULL, 1, 1, 0, 1, 0, 0, NULL, 'Session 1 Mondays 2:00-3:15 PM Oct 5-Nov 9; Session 2 Tuesdays 5:15-6:30 PM Oct 6-Nov 10; $60 members / $90 public', 'https://www.slcjcc.org/events/2026/10/05/special-events/learn-to-play-mahjong/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_salt-lake-city-learn-to-play-mahjong-session-1-20261005', 'Learn to Play Mahjong — Session 1', 'salt-lake-city-learn-to-play-mahjong-session-1-20261005', '2026-10-05 00:00:00', '14:00', '15:15', 'IJ & Jeanné Wagner Jewish Community Center, 2 North Medical Dr, Salt Lake City, UT 84113', (SELECT id FROM City WHERE name = 'Salt Lake City' AND state = 'UT'), (SELECT id FROM Club WHERE slug = 'salt-lake-city-ij-jeanne-wagner-jewish-community-center-mahjong'), NULL, 'LESSON', 1, NULL, 'https://www.slcjcc.org/events/2026/10/05/special-events/learn-to-play-mahjong/', 'https://www.slcjcc.org/events/2026/10/05/special-events/learn-to-play-mahjong/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_salt-lake-city-learn-to-play-mahjong-session-1-20261012', 'Learn to Play Mahjong — Session 1', 'salt-lake-city-learn-to-play-mahjong-session-1-20261012', '2026-10-12 00:00:00', '14:00', '15:15', 'IJ & Jeanné Wagner Jewish Community Center, 2 North Medical Dr, Salt Lake City, UT 84113', (SELECT id FROM City WHERE name = 'Salt Lake City' AND state = 'UT'), (SELECT id FROM Club WHERE slug = 'salt-lake-city-ij-jeanne-wagner-jewish-community-center-mahjong'), NULL, 'LESSON', 1, NULL, 'https://www.slcjcc.org/events/2026/10/05/special-events/learn-to-play-mahjong/', 'https://www.slcjcc.org/events/2026/10/05/special-events/learn-to-play-mahjong/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_salt-lake-city-learn-to-play-mahjong-session-1-20261019', 'Learn to Play Mahjong — Session 1', 'salt-lake-city-learn-to-play-mahjong-session-1-20261019', '2026-10-19 00:00:00', '14:00', '15:15', 'IJ & Jeanné Wagner Jewish Community Center, 2 North Medical Dr, Salt Lake City, UT 84113', (SELECT id FROM City WHERE name = 'Salt Lake City' AND state = 'UT'), (SELECT id FROM Club WHERE slug = 'salt-lake-city-ij-jeanne-wagner-jewish-community-center-mahjong'), NULL, 'LESSON', 1, NULL, 'https://www.slcjcc.org/events/2026/10/05/special-events/learn-to-play-mahjong/', 'https://www.slcjcc.org/events/2026/10/05/special-events/learn-to-play-mahjong/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_salt-lake-city-learn-to-play-mahjong-session-1-20261026', 'Learn to Play Mahjong — Session 1', 'salt-lake-city-learn-to-play-mahjong-session-1-20261026', '2026-10-26 00:00:00', '14:00', '15:15', 'IJ & Jeanné Wagner Jewish Community Center, 2 North Medical Dr, Salt Lake City, UT 84113', (SELECT id FROM City WHERE name = 'Salt Lake City' AND state = 'UT'), (SELECT id FROM Club WHERE slug = 'salt-lake-city-ij-jeanne-wagner-jewish-community-center-mahjong'), NULL, 'LESSON', 1, NULL, 'https://www.slcjcc.org/events/2026/10/05/special-events/learn-to-play-mahjong/', 'https://www.slcjcc.org/events/2026/10/05/special-events/learn-to-play-mahjong/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_salt-lake-city-learn-to-play-mahjong-session-1-20261102', 'Learn to Play Mahjong — Session 1', 'salt-lake-city-learn-to-play-mahjong-session-1-20261102', '2026-11-02 00:00:00', '14:00', '15:15', 'IJ & Jeanné Wagner Jewish Community Center, 2 North Medical Dr, Salt Lake City, UT 84113', (SELECT id FROM City WHERE name = 'Salt Lake City' AND state = 'UT'), (SELECT id FROM Club WHERE slug = 'salt-lake-city-ij-jeanne-wagner-jewish-community-center-mahjong'), NULL, 'LESSON', 1, NULL, 'https://www.slcjcc.org/events/2026/10/05/special-events/learn-to-play-mahjong/', 'https://www.slcjcc.org/events/2026/10/05/special-events/learn-to-play-mahjong/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_salt-lake-city-learn-to-play-mahjong-session-1-20261109', 'Learn to Play Mahjong — Session 1', 'salt-lake-city-learn-to-play-mahjong-session-1-20261109', '2026-11-09 00:00:00', '14:00', '15:15', 'IJ & Jeanné Wagner Jewish Community Center, 2 North Medical Dr, Salt Lake City, UT 84113', (SELECT id FROM City WHERE name = 'Salt Lake City' AND state = 'UT'), (SELECT id FROM Club WHERE slug = 'salt-lake-city-ij-jeanne-wagner-jewish-community-center-mahjong'), NULL, 'LESSON', 1, NULL, 'https://www.slcjcc.org/events/2026/10/05/special-events/learn-to-play-mahjong/', 'https://www.slcjcc.org/events/2026/10/05/special-events/learn-to-play-mahjong/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_salt-lake-city-learn-to-play-mahjong-session-2-20261006', 'Learn to Play Mahjong — Session 2', 'salt-lake-city-learn-to-play-mahjong-session-2-20261006', '2026-10-06 00:00:00', '17:15', '18:30', 'IJ & Jeanné Wagner Jewish Community Center, 2 North Medical Dr, Salt Lake City, UT 84113', (SELECT id FROM City WHERE name = 'Salt Lake City' AND state = 'UT'), (SELECT id FROM Club WHERE slug = 'salt-lake-city-ij-jeanne-wagner-jewish-community-center-mahjong'), NULL, 'LESSON', 1, NULL, 'https://www.slcjcc.org/events/2026/10/05/special-events/learn-to-play-mahjong/', 'https://www.slcjcc.org/events/2026/10/05/special-events/learn-to-play-mahjong/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_salt-lake-city-learn-to-play-mahjong-session-2-20261013', 'Learn to Play Mahjong — Session 2', 'salt-lake-city-learn-to-play-mahjong-session-2-20261013', '2026-10-13 00:00:00', '17:15', '18:30', 'IJ & Jeanné Wagner Jewish Community Center, 2 North Medical Dr, Salt Lake City, UT 84113', (SELECT id FROM City WHERE name = 'Salt Lake City' AND state = 'UT'), (SELECT id FROM Club WHERE slug = 'salt-lake-city-ij-jeanne-wagner-jewish-community-center-mahjong'), NULL, 'LESSON', 1, NULL, 'https://www.slcjcc.org/events/2026/10/05/special-events/learn-to-play-mahjong/', 'https://www.slcjcc.org/events/2026/10/05/special-events/learn-to-play-mahjong/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
