INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_las-vegas-las-vegas-mahjong', 'Las Vegas Mahjong', 'las-vegas-las-vegas-mahjong', 'American Mahjong studio offering lessons and social open play; official site explicitly references the National Mah Jongg League card.', (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV'), '8687 W. Sahara Ave., Suite 200, Las Vegas, NV 89117', 'https://www.lasvegasmahj.com/', NULL, 'hello@lasvegasmahj.com', NULL, NULL, 1, 1, 1, 1, 0, 0, 60, 'Multiple weekly sessions Price: $60/person group lesson; open play price varies', 'https://www.lasvegasmahj.com/schedule', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_las-vegas-social-open-play-20261001', 'Social Open Play', 'las-vegas-social-open-play-20261001', '2026-10-01 00:00:00', '18:00', '20:00', 'Las Vegas Mahjong at Lucky Hare, 8687 W. Sahara Ave., Suite 200, Las Vegas, NV 89117', (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV'), (SELECT id FROM Club WHERE slug = 'las-vegas-las-vegas-mahjong'), NULL, 'OPEN_PLAY', 0, NULL, 'https://www.lasvegasmahj.com/schedule', 'https://www.lasvegasmahj.com/schedule', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_las-vegas-mahj-103-with-shauna-20261001', 'Mahj 103 with Shauna', 'las-vegas-mahj-103-with-shauna-20261001', '2026-10-01 00:00:00', '18:30', '21:00', 'Las Vegas Mahjong at Lucky Hare, 8687 W. Sahara Ave., Suite 200, Las Vegas, NV 89117', (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV'), (SELECT id FROM Club WHERE slug = 'las-vegas-las-vegas-mahjong'), NULL, 'LESSON', 0, NULL, 'https://www.lasvegasmahj.com/schedule', 'https://www.lasvegasmahj.com/schedule', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_las-vegas-social-open-play-20261002', 'Social Open Play', 'las-vegas-social-open-play-20261002', '2026-10-02 00:00:00', '09:30', '11:30', 'Las Vegas Mahjong at Lucky Hare, 8687 W. Sahara Ave., Suite 200, Las Vegas, NV 89117', (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV'), (SELECT id FROM Club WHERE slug = 'las-vegas-las-vegas-mahjong'), NULL, 'OPEN_PLAY', 0, NULL, 'https://www.lasvegasmahj.com/schedule', 'https://www.lasvegasmahj.com/schedule', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_las-vegas-mahj-101-with-shauna-20261002', 'Mahj 101 with Shauna', 'las-vegas-mahj-101-with-shauna-20261002', '2026-10-02 00:00:00', '10:00', '12:30', 'Las Vegas Mahjong at Lucky Hare, 8687 W. Sahara Ave., Suite 200, Las Vegas, NV 89117', (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV'), (SELECT id FROM Club WHERE slug = 'las-vegas-las-vegas-mahjong'), NULL, 'LESSON', 1, NULL, 'https://www.lasvegasmahj.com/schedule', 'https://www.lasvegasmahj.com/schedule', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_las-vegas-social-open-play-20261006', 'Social Open Play', 'las-vegas-social-open-play-20261006', '2026-10-06 00:00:00', '17:30', '19:30', 'Las Vegas Mahjong at Lucky Hare, 8687 W. Sahara Ave., Suite 200, Las Vegas, NV 89117', (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV'), (SELECT id FROM Club WHERE slug = 'las-vegas-las-vegas-mahjong'), NULL, 'OPEN_PLAY', 0, NULL, 'https://www.lasvegasmahj.com/schedule', 'https://www.lasvegasmahj.com/schedule', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_las-vegas-mahj-102-with-shauna-20261006', 'Mahj 102 with Shauna', 'las-vegas-mahj-102-with-shauna-20261006', '2026-10-06 00:00:00', '18:00', '20:30', 'Las Vegas Mahjong at Lucky Hare, 8687 W. Sahara Ave., Suite 200, Las Vegas, NV 89117', (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV'), (SELECT id FROM Club WHERE slug = 'las-vegas-las-vegas-mahjong'), NULL, 'LESSON', 0, NULL, 'https://www.lasvegasmahj.com/schedule', 'https://www.lasvegasmahj.com/schedule', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_las-vegas-social-open-play-20261007', 'Social Open Play', 'las-vegas-social-open-play-20261007', '2026-10-07 00:00:00', '09:00', '11:00', 'Las Vegas Mahjong at Lucky Hare, 8687 W. Sahara Ave., Suite 200, Las Vegas, NV 89117', (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV'), (SELECT id FROM Club WHERE slug = 'las-vegas-las-vegas-mahjong'), NULL, 'OPEN_PLAY', 0, NULL, 'https://www.lasvegasmahj.com/schedule', 'https://www.lasvegasmahj.com/schedule', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_las-vegas-mahj-101-with-shauna-20261007', 'Mahj 101 with Shauna', 'las-vegas-mahj-101-with-shauna-20261007', '2026-10-07 00:00:00', '09:30', '12:00', 'Las Vegas Mahjong at Lucky Hare, 8687 W. Sahara Ave., Suite 200, Las Vegas, NV 89117', (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV'), (SELECT id FROM Club WHERE slug = 'las-vegas-las-vegas-mahjong'), NULL, 'LESSON', 1, NULL, 'https://www.lasvegasmahj.com/schedule', 'https://www.lasvegasmahj.com/schedule', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
