INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_sacramento-sierra-2-center-learnery', 'Sierra 2 Center Learnery', 'sacramento-sierra-2-center-learnery', 'Community learning venue with dated American Mah Jongg classes taught by Sheri Graciano.', (SELECT id FROM City WHERE name = 'Sacramento' AND state = 'CA'), '2791 24th Street, Sacramento, CA 95818', 'https://sierra2.org/', '916-452-3005', 'info@sierra2.org', NULL, NULL, 1, 1, 0, 1, 0, 0, 20, 'Dated classes listed on Learnery calendar Price: $20-$30', 'https://sierra2.org/events/category/the-learnery/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_sacramento-sheri-graciano', 'Sheri Graciano', 'sacramento-sheri-graciano', (SELECT id FROM City WHERE name = 'Sacramento' AND state = 'CA'), 'https://sierra2.org/', 'info@sierra2.org / 916-452-3005 via Sierra 2 Center', 0, 1, 0, 1, 20, 'Teaches dated American Mah Jongg classes at Sierra 2 Center; January 2027 2.0 class explicitly covers NMJL rules. Price: $20-$30', 'https://sierra2.org/events/category/the-learnery/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_sacramento-introduction-to-american-mah-jongg-20261109', 'Introduction to American Mah Jongg', 'sacramento-introduction-to-american-mah-jongg-20261109', '2026-11-09 00:00:00', '13:00', '16:00', 'Sierra 2 Center Learnery Room 7, 2791 24th Street, Sacramento, CA 95818', (SELECT id FROM City WHERE name = 'Sacramento' AND state = 'CA'), (SELECT id FROM Club WHERE slug = 'sacramento-sierra-2-center-learnery'), (SELECT id FROM Instructor WHERE slug = 'sacramento-sheri-graciano'), 'LESSON', 1, 20, 'https://sierra2.org/events/category/the-learnery/', 'https://sierra2.org/events/category/the-learnery/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_sacramento-introduction-to-american-mah-jongg-20261118', 'Introduction to American Mah Jongg', 'sacramento-introduction-to-american-mah-jongg-20261118', '2026-11-18 00:00:00', '17:00', '20:00', 'Sierra 2 Center Learnery Room 7, 2791 24th Street, Sacramento, CA 95818', (SELECT id FROM City WHERE name = 'Sacramento' AND state = 'CA'), (SELECT id FROM Club WHERE slug = 'sacramento-sierra-2-center-learnery'), (SELECT id FROM Instructor WHERE slug = 'sacramento-sheri-graciano'), 'LESSON', 1, 20, 'https://sierra2.org/events/category/the-learnery/', 'https://sierra2.org/events/category/the-learnery/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_sacramento-introduction-to-american-mah-jongg-20261119', 'Introduction to American Mah Jongg', 'sacramento-introduction-to-american-mah-jongg-20261119', '2026-11-19 00:00:00', '17:00', '20:00', 'Sierra 2 Center Learnery Room 7, 2791 24th Street, Sacramento, CA 95818', (SELECT id FROM City WHERE name = 'Sacramento' AND state = 'CA'), (SELECT id FROM Club WHERE slug = 'sacramento-sierra-2-center-learnery'), (SELECT id FROM Instructor WHERE slug = 'sacramento-sheri-graciano'), 'LESSON', 1, 20, 'https://sierra2.org/events/category/the-learnery/', 'https://sierra2.org/events/category/the-learnery/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_sacramento-american-mah-jongg-2-0-20270105', 'American Mah Jongg 2.0', 'sacramento-american-mah-jongg-2-0-20270105', '2027-01-05 00:00:00', '17:00', '20:00', 'Sierra 2 Center Learnery Room 7, 2791 24th Street, Sacramento, CA 95818', (SELECT id FROM City WHERE name = 'Sacramento' AND state = 'CA'), (SELECT id FROM Club WHERE slug = 'sacramento-sierra-2-center-learnery'), (SELECT id FROM Instructor WHERE slug = 'sacramento-sheri-graciano'), 'LESSON', 0, 30, 'https://sierra2.org/events/category/the-learnery/', 'https://sierra2.org/events/category/the-learnery/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_sacramento-introduction-to-american-mah-jongg-20270111', 'Introduction to American Mah Jongg', 'sacramento-introduction-to-american-mah-jongg-20270111', '2027-01-11 00:00:00', '13:00', '16:00', 'Sierra 2 Center Learnery Room 7, 2791 24th Street, Sacramento, CA 95818', (SELECT id FROM City WHERE name = 'Sacramento' AND state = 'CA'), (SELECT id FROM Club WHERE slug = 'sacramento-sierra-2-center-learnery'), (SELECT id FROM Instructor WHERE slug = 'sacramento-sheri-graciano'), 'LESSON', 1, 30, 'https://sierra2.org/events/category/the-learnery/', 'https://sierra2.org/events/category/the-learnery/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_sacramento-american-mah-jongg-2-0-20270120', 'American Mah Jongg 2.0', 'sacramento-american-mah-jongg-2-0-20270120', '2027-01-20 00:00:00', '17:00', '20:00', 'Sierra 2 Center Learnery Room 7, 2791 24th Street, Sacramento, CA 95818', (SELECT id FROM City WHERE name = 'Sacramento' AND state = 'CA'), (SELECT id FROM Club WHERE slug = 'sacramento-sierra-2-center-learnery'), (SELECT id FROM Instructor WHERE slug = 'sacramento-sheri-graciano'), 'LESSON', 0, 30, 'https://sierra2.org/events/category/the-learnery/', 'https://sierra2.org/events/category/the-learnery/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_sacramento-introduction-to-american-mah-jongg-20270125', 'Introduction to American Mah Jongg', 'sacramento-introduction-to-american-mah-jongg-20270125', '2027-01-25 00:00:00', '13:00', '16:00', 'Sierra 2 Center Learnery Room 7, 2791 24th Street, Sacramento, CA 95818', (SELECT id FROM City WHERE name = 'Sacramento' AND state = 'CA'), (SELECT id FROM Club WHERE slug = 'sacramento-sierra-2-center-learnery'), (SELECT id FROM Instructor WHERE slug = 'sacramento-sheri-graciano'), 'LESSON', 1, 30, 'https://sierra2.org/events/category/the-learnery/', 'https://sierra2.org/events/category/the-learnery/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
