INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_san-antonio-encino-library-american-mahjong-open-play', 'Encino Library American Mahjong Open Play', 'san-antonio-encino-library-american-mahjong-open-play', 'San Antonio Public Library recurring American Mahjong open play at Encino Library.', (SELECT id FROM City WHERE name = 'San Antonio' AND state = 'TX'), 'Encino Library, San Antonio, TX', 'https://library.sanantonio.gov/', '210-207-9300', 'ann.laird@sanantonio.gov', NULL, NULL, 1, 0, 1, 1, 0, 1, NULL, 'Recurring Tuesday afternoons; current calendar shows 12:30/1:00-3:00 PM sessions', 'https://www.trumba.com/events-calendar/tx/san-antonio/mysapl/events/san-antonio-public-library', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_san-antonio-troop-mahjong', 'Troop Mahjong', 'san-antonio-troop-mahjong', 'San Antonio-based American Mahjong social club with leagues and events.', (SELECT id FROM City WHERE name = 'San Antonio' AND state = 'TX'), 'San Antonio, TX', 'https://stylinbrunette.com/blogs/news/upcoming-events-troop-mahjong-in-san-antonio-tx-boerne-tx-new-braunfels-tx', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 1, 0, NULL, NULL, 'https://stylinbrunette.com/blogs/news/upcoming-events-troop-mahjong-in-san-antonio-tx-boerne-tx-new-braunfels-tx', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_san-antonio-san-antonio-fall-league-20261006', 'San Antonio Fall League', 'san-antonio-san-antonio-fall-league-20261006', '2026-10-06 00:00:00', '18:30', '21:00', 'San Antonio, TX', (SELECT id FROM City WHERE name = 'San Antonio' AND state = 'TX'), (SELECT id FROM Club WHERE slug = 'san-antonio-troop-mahjong'), NULL, 'SOCIAL', 0, NULL, 'https://stylinbrunette.com/blogs/news/upcoming-events-troop-mahjong-in-san-antonio-tx-boerne-tx-new-braunfels-tx', 'https://stylinbrunette.com/blogs/news/upcoming-events-troop-mahjong-in-san-antonio-tx-boerne-tx-new-braunfels-tx', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_san-antonio-san-antonio-fall-league-20261020', 'San Antonio Fall League', 'san-antonio-san-antonio-fall-league-20261020', '2026-10-20 00:00:00', '18:30', '21:00', 'San Antonio, TX', (SELECT id FROM City WHERE name = 'San Antonio' AND state = 'TX'), (SELECT id FROM Club WHERE slug = 'san-antonio-troop-mahjong'), NULL, 'SOCIAL', 0, NULL, 'https://stylinbrunette.com/blogs/news/upcoming-events-troop-mahjong-in-san-antonio-tx-boerne-tx-new-braunfels-tx', 'https://stylinbrunette.com/blogs/news/upcoming-events-troop-mahjong-in-san-antonio-tx-boerne-tx-new-braunfels-tx', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_san-antonio-san-antonio-fall-league-20261027', 'San Antonio Fall League', 'san-antonio-san-antonio-fall-league-20261027', '2026-10-27 00:00:00', '18:30', '21:00', 'San Antonio, TX', (SELECT id FROM City WHERE name = 'San Antonio' AND state = 'TX'), (SELECT id FROM Club WHERE slug = 'san-antonio-troop-mahjong'), NULL, 'SOCIAL', 0, NULL, 'https://stylinbrunette.com/blogs/news/upcoming-events-troop-mahjong-in-san-antonio-tx-boerne-tx-new-braunfels-tx', 'https://stylinbrunette.com/blogs/news/upcoming-events-troop-mahjong-in-san-antonio-tx-boerne-tx-new-braunfels-tx', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_san-antonio-halloween-open-play-at-the-st-anthony-20261029', 'Halloween Open Play at the St. Anthony', 'san-antonio-halloween-open-play-at-the-st-anthony-20261029', '2026-10-29 00:00:00', NULL, NULL, 'San Antonio, TX', (SELECT id FROM City WHERE name = 'San Antonio' AND state = 'TX'), (SELECT id FROM Club WHERE slug = 'san-antonio-troop-mahjong'), NULL, 'SOCIAL', 1, NULL, 'https://stylinbrunette.com/blogs/news/upcoming-events-troop-mahjong-in-san-antonio-tx-boerne-tx-new-braunfels-tx', 'https://stylinbrunette.com/blogs/news/upcoming-events-troop-mahjong-in-san-antonio-tx-boerne-tx-new-braunfels-tx', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_san-antonio-san-antonio-fall-league-20261103', 'San Antonio Fall League', 'san-antonio-san-antonio-fall-league-20261103', '2026-11-03 00:00:00', '18:30', '21:00', 'San Antonio, TX', (SELECT id FROM City WHERE name = 'San Antonio' AND state = 'TX'), (SELECT id FROM Club WHERE slug = 'san-antonio-troop-mahjong'), NULL, 'SOCIAL', 0, NULL, 'https://stylinbrunette.com/blogs/news/upcoming-events-troop-mahjong-in-san-antonio-tx-boerne-tx-new-braunfels-tx', 'https://stylinbrunette.com/blogs/news/upcoming-events-troop-mahjong-in-san-antonio-tx-boerne-tx-new-braunfels-tx', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_san-antonio-open-play-at-the-st-anthony-20261112', 'Open Play at the St. Anthony', 'san-antonio-open-play-at-the-st-anthony-20261112', '2026-11-12 00:00:00', NULL, NULL, 'San Antonio, TX', (SELECT id FROM City WHERE name = 'San Antonio' AND state = 'TX'), (SELECT id FROM Club WHERE slug = 'san-antonio-troop-mahjong'), NULL, 'SOCIAL', 1, NULL, 'https://stylinbrunette.com/blogs/news/upcoming-events-troop-mahjong-in-san-antonio-tx-boerne-tx-new-braunfels-tx', 'https://stylinbrunette.com/blogs/news/upcoming-events-troop-mahjong-in-san-antonio-tx-boerne-tx-new-braunfels-tx', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
