INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_oklahoma-city-ok-let-s-mahjong', 'OK LET''S MAHJONG', 'oklahoma-city-ok-let-s-mahjong', 'Oklahoma City-based organizer offering lessons, open group classes and social events; official site explicitly describes its offering as American Mahjong.', (SELECT id FROM City WHERE name = 'Oklahoma City' AND state = 'OK'), 'Oklahoma City, OK', 'https://www.okletsmahjong.com/oklahoma-city', NULL, NULL, NULL, NULL, 0, 0, 1, 1, 0, 0, NULL, NULL, 'https://www.okletsmahjong.com/about-mahjong', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_oklahoma-city-okc-two-player-showdown-with-my-wife-plays-mahjong-20261012', 'OKC: Two-Player Showdown with My Wife Plays Mahjong', 'oklahoma-city-okc-two-player-showdown-with-my-wife-plays-mahjong-20261012', '2026-10-12 00:00:00', '18:30', '20:30', 'Cosabella Kitchen, 6516 N Olie Ave, Oklahoma City, OK', (SELECT id FROM City WHERE name = 'Oklahoma City' AND state = 'OK'), (SELECT id FROM Club WHERE slug = 'oklahoma-city-ok-let-s-mahjong'), NULL, 'TOURNAMENT', 0, 100, 'https://www.okletsmahjong.com/events', 'https://www.okletsmahjong.com/events', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_oklahoma-city-okc-fall-social-league-20261021', 'OKC: Fall Social League', 'oklahoma-city-okc-fall-social-league-20261021', '2026-10-21 00:00:00', '18:00', '20:00', 'Cloud Puncher Rooftop Bar & Restaurant at Lively Hotel, Oklahoma City, OK', (SELECT id FROM City WHERE name = 'Oklahoma City' AND state = 'OK'), (SELECT id FROM Club WHERE slug = 'oklahoma-city-ok-let-s-mahjong'), NULL, 'SOCIAL', 0, 30, 'https://www.okletsmahjong.com/events', 'https://www.okletsmahjong.com/events', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
