INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_memphis-emmanuel-mahjong', 'Emmanuel Mahjong', 'memphis-emmanuel-mahjong', 'Weekly National Mah Jongg League play at Emmanuel United Methodist Church; beginners welcome and church membership is not required.', (SELECT id FROM City WHERE name = 'Memphis' AND state = 'TN'), '2404 Kirby Road, Memphis, TN 38119', 'https://www.emmanuelmemphis.org/ministries/wellness-and-recreation/emmanuel-mahjong/', NULL, 'info@emmanuelmemphis.org', NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Mondays 2:00 PM; Thursdays 6:00 PM', 'https://www.emmanuelmemphis.org/ministries/wellness-and-recreation/emmanuel-mahjong/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_memphis-vicki-campbell-mahj-memphis', 'Vicki Campbell / MahJ Memphis', 'memphis-vicki-campbell-mahj-memphis', (SELECT id FROM City WHERE name = 'Memphis' AND state = 'TN'), 'https://mahjmemphis.com/', NULL, 1, 1, 1, 1, NULL, 'Beginner-friendly American NMJL lessons, workshops and events.', 'https://mahjmemphis.com/about-me', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_memphis-pat-ford-mahj-squad-901', 'Pat Ford / MahJ Squad 901', 'memphis-pat-ford-mahj-squad-901', (SELECT id FROM City WHERE name = 'Memphis' AND state = 'TN'), NULL, '9012921627', 1, 1, 0, 1, NULL, 'American Mah Jongg instruction following NMJL rules; instructor listing identifies Memphis/Mid-South coverage.', 'https://mahjonggmaven.com/teachers/', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_memphis-emmanuel-mahjong-weekly-play-20261001', 'Emmanuel Mahjong Weekly Play', 'memphis-emmanuel-mahjong-weekly-play-20261001', '2026-10-01 00:00:00', '18:00', NULL, 'Emmanuel United Methodist Church', (SELECT id FROM City WHERE name = 'Memphis' AND state = 'TN'), (SELECT id FROM Club WHERE slug = 'memphis-emmanuel-mahjong'), NULL, 'OPEN_PLAY', 1, 0, 'https://www.emmanuelmemphis.org/ministries/wellness-and-recreation/emmanuel-mahjong/', 'https://www.emmanuelmemphis.org/ministries/wellness-and-recreation/emmanuel-mahjong/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
