INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_new-orleans-fleur-de-mahj', 'Fleur de Mahj', 'new-orleans-fleur-de-mahj', 'New Orleans metro American Mah Jongg parlor teaching official NMJL rules, with beginner classes, guided play, strategy classes and events.', (SELECT id FROM City WHERE name = 'New Orleans' AND state = 'LA'), '110 Veterans Blvd, Suite 121, Metairie, LA 70005', 'https://fleurdemahj.com/', '504-401-5890', NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Live event schedule; booking required', 'https://fleurdemahj.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_new-orleans-fleur-de-mahj-sheila', 'Fleur de Mahj / Sheila', 'new-orleans-fleur-de-mahj-sheila', (SELECT id FROM City WHERE name = 'New Orleans' AND state = 'LA'), 'https://fleurdemahj.com/', '504-401-5890', 1, 1, 0, 1, NULL, 'American Mah Jongg instruction using official NMJL rules.', 'https://fleurdemahj.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_new-orleans-experienced-players-tournament-20261003', 'Experienced Players'' Tournament', 'new-orleans-experienced-players-tournament-20261003', '2026-10-03 00:00:00', '09:30', '16:00', 'Fleur de Mahj, 110 Veterans Blvd, Suite 121, Metairie, LA 70005', (SELECT id FROM City WHERE name = 'New Orleans' AND state = 'LA'), (SELECT id FROM Club WHERE slug = 'new-orleans-fleur-de-mahj'), NULL, 'TOURNAMENT', 0, 125, 'https://fleurdemahj.com/products/experienced-players-tournament-1', 'https://fleurdemahj.com/products/experienced-players-tournament-1', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_new-orleans-beginners-intermediate-tournament-20261004', 'Beginners''/Intermediate Tournament', 'new-orleans-beginners-intermediate-tournament-20261004', '2026-10-04 00:00:00', '09:30', '16:00', 'Fleur de Mahj, 110 Veterans Blvd, Suite 121, Metairie, LA 70005', (SELECT id FROM City WHERE name = 'New Orleans' AND state = 'LA'), (SELECT id FROM Club WHERE slug = 'new-orleans-fleur-de-mahj'), NULL, 'TOURNAMENT', 1, 125, 'https://fleurdemahj.com/products/beginners-intermediate-tournament-sunday-october-4', 'https://fleurdemahj.com/products/beginners-intermediate-tournament-sunday-october-4', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_new-orleans-mahjong-monday-at-urban-south-brewery-20261005', 'Mahjong Monday at Urban South Brewery', 'new-orleans-mahjong-monday-at-urban-south-brewery-20261005', '2026-10-05 00:00:00', '18:00', NULL, 'Urban South Brewery', (SELECT id FROM City WHERE name = 'New Orleans' AND state = 'LA'), NULL, NULL, 'OPEN_PLAY', 0, NULL, NULL, 'https://neworleansmom.com/things-to-do-in-new-orleans-with-kids/', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
