INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_birmingham-o-neal-library-mah-jongg-meetup', 'O''Neal Library Mah Jongg Meetup', 'birmingham-o-neal-library-mah-jongg-meetup', 'O''Neal Library''s recurring meetup plays American-style Mah Jongg using the National Mah Jongg League card; beginners have a first-Monday lesson.', (SELECT id FROM City WHERE name = 'Birmingham' AND state = 'AL'), '50 Oak Street, Mountain Brook, AL 35213', 'https://oneallibrary.org/', '205-879-0459', 'kmoellering@oneallibrary.org', NULL, NULL, 1, 1, 1, 1, 0, 1, NULL, 'Generally Mondays 10:00 AM-Noon; beginner lesson first Monday', 'https://oneallibrary.org/event/16690967', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_birmingham-katie-moellering', 'Katie Moellering', 'birmingham-katie-moellering', (SELECT id FROM City WHERE name = 'Birmingham' AND state = 'AL'), NULL, 'kmoellering@oneallibrary.org', 0, 1, 0, 1, NULL, 'Official O''Neal Library page identifies Katie Moellering as the contact for first-Monday beginner lessons.', 'https://oneallibrary.org/event/16690967', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_birmingham-o-neal-library-mah-jongg-meetup-20261228', 'O''Neal Library Mah Jongg Meetup', 'birmingham-o-neal-library-mah-jongg-meetup-20261228', '2026-12-28 00:00:00', '10:00', '12:00', 'Mountain Brook Baptist Church, 3631 Montevallo Road, Mountain Brook, AL 35213', (SELECT id FROM City WHERE name = 'Birmingham' AND state = 'AL'), (SELECT id FROM Club WHERE slug = 'birmingham-o-neal-library-mah-jongg-meetup'), NULL, 'OPEN_PLAY', 1, 0, 'https://oneallibrary.org/event/16690967', 'https://oneallibrary.org/event/16690967', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
