INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_richmond-mahjongrva', 'MahjongRVA', 'richmond-mahjongrva', 'American Mahjong instruction, open play and events in the Richmond area.', (SELECT id FROM City WHERE name = 'Richmond' AND state = 'VA'), 'Richmond, VA', 'https://www.mahjongrva.com/', NULL, 'letsplay@mahjongrva.com', NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'See current class/event calendar', 'https://www.mahjongrva.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_richmond-mahjongrva-emilie-rabke', 'MahjongRVA / Emilie Rabke', 'richmond-mahjongrva-emilie-rabke', (SELECT id FROM City WHERE name = 'Richmond' AND state = 'VA'), 'https://www.mahjongrva.com/', 'letsplay@mahjongrva.com', 1, 1, 0, 1, NULL, 'American Mahjong instruction and beginner classes.', 'https://www.mahjongrva.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_richmond-the-lucky-sparrow-emily-cox', 'The Lucky Sparrow / Emily Cox', 'richmond-the-lucky-sparrow-emily-cox', (SELECT id FROM City WHERE name = 'Richmond' AND state = 'VA'), 'https://www.theluckysparrow.com/', 'emily@theluckysparrow.com', 1, 1, 0, 1, NULL, 'NMJL-based private events, group lessons and coaching.', 'https://www.theluckysparrow.com/events', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_richmond-american-mahjong-basic-class-20261001', 'American Mahjong Basic Class', 'richmond-american-mahjong-basic-class-20261001', '2026-10-01 00:00:00', '18:00', '20:30', 'The Heist, Bowling Green', (SELECT id FROM City WHERE name = 'Richmond' AND state = 'VA'), (SELECT id FROM Club WHERE slug = 'richmond-mahjongrva'), (SELECT id FROM Instructor WHERE slug = 'richmond-mahjongrva-emilie-rabke'), 'LESSON', 1, NULL, 'https://www.mahjongrva.com/', 'https://www.mahjongrva.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_richmond-american-mahjong-basic-class-20261015', 'American Mahjong Basic Class', 'richmond-american-mahjong-basic-class-20261015', '2026-10-15 00:00:00', '18:00', '20:30', NULL, (SELECT id FROM City WHERE name = 'Richmond' AND state = 'VA'), (SELECT id FROM Club WHERE slug = 'richmond-mahjongrva'), (SELECT id FROM Instructor WHERE slug = 'richmond-mahjongrva-emilie-rabke'), 'LESSON', 1, NULL, 'https://www.mahjongrva.com/', 'https://www.mahjongrva.com/', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_richmond-mahj-o-ween-mania-event-20261030', 'MAHJ-O-WEEN Mania Event', 'richmond-mahj-o-ween-mania-event-20261030', '2026-10-30 00:00:00', '12:00', '15:30', NULL, (SELECT id FROM City WHERE name = 'Richmond' AND state = 'VA'), (SELECT id FROM Club WHERE slug = 'richmond-mahjongrva'), (SELECT id FROM Instructor WHERE slug = 'richmond-mahjongrva-emilie-rabke'), 'TOURNAMENT', 1, NULL, 'https://www.mahjongrva.com/', 'https://www.mahjongrva.com/', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_richmond-mahjingo-waygone-20261007', 'Mahjingo™ @ WayGone!', 'richmond-mahjingo-waygone-20261007', '2026-10-07 00:00:00', NULL, NULL, 'WayGone Brewery', (SELECT id FROM City WHERE name = 'Richmond' AND state = 'VA'), NULL, (SELECT id FROM Instructor WHERE slug = 'richmond-the-lucky-sparrow-emily-cox'), 'SOCIAL', 0, NULL, 'https://www.theluckysparrow.com/events', 'https://www.theluckysparrow.com/events', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_richmond-open-play-bar-west-20261011', 'Open Play @ Bar West!', 'richmond-open-play-bar-west-20261011', '2026-10-11 00:00:00', NULL, NULL, 'Bar West', (SELECT id FROM City WHERE name = 'Richmond' AND state = 'VA'), NULL, (SELECT id FROM Instructor WHERE slug = 'richmond-the-lucky-sparrow-emily-cox'), 'OPEN_PLAY', 0, 25, 'https://www.theluckysparrow.com/events', 'https://www.theluckysparrow.com/events', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_richmond-haunted-mahjong-20261025', 'Haunted Mahjong', 'richmond-haunted-mahjong-20261025', '2026-10-25 00:00:00', NULL, NULL, 'The Poe Museum', (SELECT id FROM City WHERE name = 'Richmond' AND state = 'VA'), NULL, (SELECT id FROM Instructor WHERE slug = 'richmond-the-lucky-sparrow-emily-cox'), 'SOCIAL', 1, 75, 'https://www.theluckysparrow.com/events', 'https://www.theluckysparrow.com/events', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
