INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_jacksonville-mahjong-social-club-jax', 'Mahjong Social Club Jax', 'jacksonville-mahjong-social-club-jax', 'American Mahjong social/open play organizer; official event page requires the 2026 NMJL card.', (SELECT id FROM City WHERE name = 'Jacksonville' AND state = 'FL'), 'Jacksonville, FL', 'https://www.mahjongsocialclubjax.com/', NULL, NULL, NULL, NULL, 0, 1, 1, 1, 0, 0, NULL, 'See official event calendar', 'https://www.mahjongsocialclubjax.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_jacksonville-del-webb-etown-mah-jongg-interest-group', 'Del Webb eTown Mah Jongg Interest Group', 'jacksonville-del-webb-etown-mah-jongg-interest-group', 'Official HOA page identifies American-style Mah Jongg and NMJL rules, but access appears tied to the Del Webb eTown community; retain for review rather than public ACTIVE.', (SELECT id FROM City WHERE name = 'Jacksonville' AND state = 'FL'), '11251 Town View Dr, Jacksonville, FL 32256', 'https://www.delwebbetownhoa.com/', NULL, NULL, NULL, NULL, 1, 0, 1, 1, 0, 0, NULL, 'Mondays 7:00-10:00 PM; Wednesdays 1:00-4:00 PM', 'https://www.delwebbetownhoa.com/venue/the-gallery/', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_jacksonville-bams-boos-and-brews-grazing-parlor-20261028', 'Bams, Boos and Brews! @ Grazing Parlor', 'jacksonville-bams-boos-and-brews-grazing-parlor-20261028', '2026-10-28 00:00:00', '18:00', '21:00', 'Grazing Parlor, 1108 3rd St S, Jacksonville Beach, FL 32250', (SELECT id FROM City WHERE name = 'Jacksonville' AND state = 'FL'), (SELECT id FROM Club WHERE slug = 'jacksonville-mahjong-social-club-jax'), NULL, 'OPEN_PLAY', 0, 58.3, 'https://www.mahjongsocialclubjax.com/mahjongevents/p/bams-boos-brews', 'https://www.mahjongsocialclubjax.com/mahjongevents/p/bams-boos-brews', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
