INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_tucson-tucson-j-mah-jongg', 'Tucson J Mah Jongg', 'tucson-tucson-j-mah-jongg', 'Tucson J offers American Mah Jongg open play and multi-session classes using official NMJL rules.', (SELECT id FROM City WHERE name = 'Tucson' AND state = 'AZ'), '3800 E River Rd, Tucson, AZ 85718', 'https://tucsonjcc.org/programs-events/clubs-groups-games/', '520-299-3000', NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Tuesday open play 10:00 AM-Noon; classes scheduled seasonally', 'https://tucsonjcc.org/programs-events/clubs-groups-games/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_tucson-tucson-chinese-cultural-center-learn-mahjong', 'Tucson Chinese Cultural Center Learn Mahjong', 'tucson-tucson-chinese-cultural-center-learn-mahjong', 'Official calendar lists recurring Learn Mahjong sessions, but the current page does not specify American/NMJL, so it is retained for review only.', (SELECT id FROM City WHERE name = 'Tucson' AND state = 'AZ'), 'Tucson, AZ', 'https://www.tucsonchinese.org/', NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL, 'Sundays 12:00 PM-2:00 PM on listed dates', 'https://www.tucsonchinese.org/calendar', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_tucson-cynthia-a', 'Cynthia A.', 'tucson-cynthia-a', (SELECT id FROM City WHERE name = 'Tucson' AND state = 'AZ'), NULL, 'cnaz22057@comcast.net', 1, 1, 0, 1, NULL, 'Teacher listing identifies Cynthia A. as teaching American Mah Jongg in Tucson; no independent current website found.', 'https://wherethewindsblow.com/teachers/', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_tucson-intro-to-mahj-starting-oct-5-20261005', 'Intro to Mahj – starting Oct 5', 'tucson-intro-to-mahj-starting-oct-5-20261005', '2026-10-05 00:00:00', '09:00', '11:00', 'Tucson J', (SELECT id FROM City WHERE name = 'Tucson' AND state = 'AZ'), (SELECT id FROM Club WHERE slug = 'tucson-tucson-j-mah-jongg'), NULL, 'LESSON', 1, NULL, 'https://tucsonjcc.org/programs-events/clubs-groups-games/', 'https://tucsonjcc.org/programs-events/clubs-groups-games/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_tucson-intro-to-mahj-starting-oct-19-20261019', 'Intro to Mahj – starting Oct 19', 'tucson-intro-to-mahj-starting-oct-19-20261019', '2026-10-19 00:00:00', '09:00', '11:00', 'Tucson J', (SELECT id FROM City WHERE name = 'Tucson' AND state = 'AZ'), (SELECT id FROM Club WHERE slug = 'tucson-tucson-j-mah-jongg'), NULL, 'LESSON', 1, NULL, 'https://tucsonjcc.org/programs-events/clubs-groups-games/', 'https://tucsonjcc.org/programs-events/clubs-groups-games/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_tucson-next-level-mahj-starts-nov-2-20261102', 'Next Level Mahj – starts Nov 2', 'tucson-next-level-mahj-starts-nov-2-20261102', '2026-11-02 00:00:00', '09:00', '11:00', 'Tucson J', (SELECT id FROM City WHERE name = 'Tucson' AND state = 'AZ'), (SELECT id FROM Club WHERE slug = 'tucson-tucson-j-mah-jongg'), NULL, 'LESSON', 1, NULL, 'https://tucsonjcc.org/programs-events/clubs-groups-games/', 'https://tucsonjcc.org/programs-events/clubs-groups-games/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_tucson-tucson-j-tuesday-open-play-20261006', 'Tucson J Tuesday Open Play', 'tucson-tucson-j-tuesday-open-play-20261006', '2026-10-06 00:00:00', '10:00', '12:00', 'Tucson J', (SELECT id FROM City WHERE name = 'Tucson' AND state = 'AZ'), (SELECT id FROM Club WHERE slug = 'tucson-tucson-j-mah-jongg'), NULL, 'OPEN_PLAY', 1, 0, 'https://tucsonjcc.org/programs-events/clubs-groups-games/', 'https://tucsonjcc.org/programs-events/clubs-groups-games/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
