INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_louisville-douglass-community-center-american-mah-jongg', 'Douglass Community Center American Mah Jongg', 'louisville-douglass-community-center-american-mah-jongg', 'Louisville Parks and Recreation lists American Mah Jongg at Douglass Community Center.', (SELECT id FROM City WHERE name = 'Louisville' AND state = 'KY'), '2305 Douglass Boulevard, Louisville, KY 40205', 'https://louisvilleky.gov/government/parks/douglass-community-center', '502-456-8120', NULL, NULL, NULL, 1, 1, 1, 1, 0, 1, NULL, 'Tuesdays 12:30 PM-2:00 PM; October lessons Mondays 11:30 AM-2:30 PM', 'https://kylouisvilleweb.myvscloud.com/webtrac/web/search.html', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_louisville-sissy-w', 'Sissy W.', 'louisville-sissy-w', (SELECT id FROM City WHERE name = 'Louisville' AND state = 'KY'), NULL, 'mbwatson17@icloud.com', 1, 1, 0, 1, NULL, 'American Mah Jongg for beginners; strategy and etiquette sessions', 'https://mahjonggmaven.com/teachers/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_louisville-american-mah-jongg-lessons-oct-20261001', 'American Mah Jongg Lessons Oct', 'louisville-american-mah-jongg-lessons-oct-20261001', '2026-10-01 00:00:00', '11:30', '14:30', 'Douglass Community Center', (SELECT id FROM City WHERE name = 'Louisville' AND state = 'KY'), NULL, NULL, 'LESSON', 1, 0, 'https://kylouisvilleweb.myvscloud.com/webtrac/web/search.html', 'https://kylouisvilleweb.myvscloud.com/webtrac/web/search.html', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
