INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_san-antonio-the-polished-tile', 'The Polished Tile', 'san-antonio-the-polished-tile', 'Mahjong social house and parlor with lessons, guided play, leagues and open play; official site describes American Mahjong and NMJL-card curriculum.', (SELECT id FROM City WHERE name = 'San Antonio' AND state = 'TX'), '511 W French Place, San Antonio, TX 78212', 'https://play.thepolishedtile.com/', NULL, 'hello@thepolishedtile.com', NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Tuesday-Friday daytime open play; lessons and guided play on calendar', 'https://play.thepolishedtile.com/?type=open_play', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_san-antonio-mahjong-101-am-20261001', 'Mahjong 101 AM', 'san-antonio-mahjong-101-am-20261001', '2026-10-01 00:00:00', '10:30', NULL, '511 W French Place, San Antonio, TX 78212', (SELECT id FROM City WHERE name = 'San Antonio' AND state = 'TX'), (SELECT id FROM Club WHERE slug = 'san-antonio-the-polished-tile'), NULL, 'LESSON', 1, NULL, 'https://play.thepolishedtile.com/', 'https://play.thepolishedtile.com/?type=lesson', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_san-antonio-mahjong-101-pm-20261001', 'Mahjong 101 PM', 'san-antonio-mahjong-101-pm-20261001', '2026-10-01 00:00:00', '18:00', NULL, '511 W French Place, San Antonio, TX 78212', (SELECT id FROM City WHERE name = 'San Antonio' AND state = 'TX'), (SELECT id FROM Club WHERE slug = 'san-antonio-the-polished-tile'), NULL, 'LESSON', 1, NULL, 'https://play.thepolishedtile.com/', 'https://play.thepolishedtile.com/?type=lesson', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_san-antonio-mahjong-103-pm-20261002', 'Mahjong 103 PM', 'san-antonio-mahjong-103-pm-20261002', '2026-10-02 00:00:00', '18:00', NULL, '511 W French Place, San Antonio, TX 78212', (SELECT id FROM City WHERE name = 'San Antonio' AND state = 'TX'), (SELECT id FROM Club WHERE slug = 'san-antonio-the-polished-tile'), NULL, 'LESSON', 1, NULL, 'https://play.thepolishedtile.com/', 'https://play.thepolishedtile.com/?type=lesson', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_san-antonio-mahjong-102-am-20261003', 'Mahjong 102 AM', 'san-antonio-mahjong-102-am-20261003', '2026-10-03 00:00:00', '10:00', NULL, '511 W French Place, San Antonio, TX 78212', (SELECT id FROM City WHERE name = 'San Antonio' AND state = 'TX'), (SELECT id FROM Club WHERE slug = 'san-antonio-the-polished-tile'), NULL, 'LESSON', 1, NULL, 'https://play.thepolishedtile.com/', 'https://play.thepolishedtile.com/?type=lesson', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
