INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_omaha-club-mahj', 'Club Mahj', 'omaha-club-mahj', 'American Mahjong club offering private/group lessons, supervised play and open play.', (SELECT id FROM City WHERE name = 'Omaha' AND state = 'NE'), '15671 California St, Omaha, NE 68118', 'https://www.clubmahj.org/', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Current official calendar includes upcoming themed open-play events', 'https://www.clubmahj.org/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_omaha-one-bam', 'One Bam', 'omaha-one-bam', 'American Mahjong lessons and open play across Omaha Metro.', (SELECT id FROM City WHERE name = 'Omaha' AND state = 'NE'), 'Omaha, NE', 'https://www.onebammahj.com/', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Beginner classes and recurring open play', 'https://www.onebammahj.com/classes', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_omaha-mahjong-with-mary-mary-mcbride', 'Mahjong with Mary / Mary McBride', 'omaha-mahjong-with-mary-mary-mcbride', (SELECT id FROM City WHERE name = 'Omaha' AND state = 'NE'), 'https://www.mahjongwithmary.com/', NULL, 1, 1, 0, 1, NULL, 'American Mahjong instructor offering lessons, leagues and events at a central Omaha studio.', 'https://www.mahjongwithmary.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_omaha-beginner-mahjong-class-20261008', 'Beginner Mahjong Class', 'omaha-beginner-mahjong-class-20261008', '2026-10-08 00:00:00', '18:00', '21:00', 'Champions Run, 13800 Eagle Run Dr, Omaha, NE 68164', (SELECT id FROM City WHERE name = 'Omaha' AND state = 'NE'), (SELECT id FROM Club WHERE slug = 'omaha-one-bam'), NULL, 'LESSON', 1, 25, 'https://www.onebammahj.com/event-details-1/beginner-mahjong-class', 'https://www.onebammahj.com/event-details-1/beginner-mahjong-class', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_omaha-open-play-vino-mas-legacy-20261006', 'Open Play | Vino Mas Legacy', 'omaha-open-play-vino-mas-legacy-20261006', '2026-10-06 00:00:00', '17:30', '19:30', 'Vino Mas Legacy, 2835 S 170th Plaza #206, Omaha, NE 68130', (SELECT id FROM City WHERE name = 'Omaha' AND state = 'NE'), (SELECT id FROM Club WHERE slug = 'omaha-one-bam'), NULL, 'OPEN_PLAY', 0, 10, 'https://www.onebammahj.com/event-details-1/open-play-vino-mas-legacy-2026-10-06-17-30', 'https://www.onebammahj.com/event-details-1/open-play-vino-mas-legacy-2026-10-06-17-30', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_omaha-open-play-vino-mas-legacy-20261020', 'Open Play | Vino Mas Legacy', 'omaha-open-play-vino-mas-legacy-20261020', '2026-10-20 00:00:00', '17:30', '19:30', 'Vino Mas Legacy, 2835 S 170th Plaza #206, Omaha, NE 68130', (SELECT id FROM City WHERE name = 'Omaha' AND state = 'NE'), (SELECT id FROM Club WHERE slug = 'omaha-one-bam'), NULL, 'OPEN_PLAY', 0, 10, 'https://www.onebammahj.com/event-details-1/open-play-vino-mas-legacy-2026-10-06-17-30', 'https://www.onebammahj.com/event-details-1/open-play-vino-mas-legacy-2026-10-06-17-30', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
