INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_albuquerque-san-pedro-library-let-s-mahj-get-along', 'San Pedro Library Let''s Mahj-Get-Along', 'albuquerque-san-pedro-library-let-s-mahj-get-along', 'Albuquerque Public Library hosts an adults-only Mahjong club, but the current official source does not explicitly identify American/NMJL.', (SELECT id FROM City WHERE name = 'Albuquerque' AND state = 'NM'), '5600 Trumbull Ave SE, Albuquerque, NM 87108', 'https://abqlibrary.org/', NULL, NULL, NULL, NULL, 0, 0, 1, 1, 0, 0, NULL, 'Current recurring club; variant requires confirmation', 'https://abqlibrary.org/', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_albuquerque-cyndi-heller', 'Cyndi Heller', 'albuquerque-cyndi-heller', (SELECT id FROM City WHERE name = 'Albuquerque' AND state = 'NM'), NULL, '505-440-0044', 1, 1, 0, 1, NULL, 'Directory identifies American Mah Jongg instruction in Albuquerque; no current independent official page found.', 'https://orderofthetile.com/find-mahjong/new-mexico/', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_albuquerque-michelle-weinstein-abq-mahjong', 'Michelle Weinstein / ABQ Mahjong', 'albuquerque-michelle-weinstein-abq-mahjong', (SELECT id FROM City WHERE name = 'Albuquerque' AND state = 'NM'), NULL, NULL, 1, 1, 0, 1, NULL, 'Directory identifies American Mahjong lessons in Albuquerque; no current independent official page found.', 'https://orderofthetile.com/find-mahjong/new-mexico/', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
