INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_buffalo-jcc-buffalo-open-play-mah-jongg', 'JCC Buffalo Open Play Mah Jongg', 'buffalo-jcc-buffalo-open-play-mah-jongg', 'JCC Buffalo''s Fall 2026 adult program explicitly describes American Mahjong open play.', (SELECT id FROM City WHERE name = 'Buffalo' AND state = 'NY'), '2640 North Forest Rd, Getzville, NY 14068', 'https://www.jccbuffalo.org/index.php?category=Buffalo+Adult+Engagement&src=programs&srctype=lister&submenu=programs', NULL, NULL, NULL, NULL, 0, 0, 1, 1, 0, 0, 36, 'Tuesdays 11:30 AM-2:00 PM, Sep 1-Dec 8', 'https://www.jccbuffalo.org/index.php?category=Buffalo+Adult+Engagement&src=programs&srctype=lister&submenu=programs', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_buffalo-jcc-buffalo-learn-to-play-mah-jongg', 'JCC Buffalo Learn to Play Mah Jongg', 'buffalo-jcc-buffalo-learn-to-play-mah-jongg', 'JCC Buffalo''s Fall 2026 course provides the official Mahjong card and requires no experience.', (SELECT id FROM City WHERE name = 'Buffalo' AND state = 'NY'), '2640 North Forest Rd, Getzville, NY 14068', 'https://www.jccbuffalo.org/index.php?category=Buffalo+Adult+Engagement&src=programs&srctype=lister&submenu=programs', NULL, NULL, NULL, NULL, 1, 1, 0, 0, 0, 0, 75, 'Wednesdays 11:30 AM-1:30 PM, Oct 7-Nov 25', 'https://www.jccbuffalo.org/index.php?category=Buffalo+Adult+Engagement&src=programs&srctype=lister&submenu=programs', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_buffalo-macia-sheibley', 'Macia Sheibley', 'buffalo-macia-sheibley', (SELECT id FROM City WHERE name = 'Buffalo' AND state = 'NY'), 'https://www.jccbuffalo.org/', NULL, 0, 1, 0, 1, NULL, 'Seasoned instructor leading the JCC Buffalo Learn to Play Mah Jongg course.', 'https://www.jccbuffalo.org/index.php?category=Buffalo+Adult+Engagement&src=programs&srctype=lister&submenu=programs', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_buffalo-learn-to-play-mah-jongg-20261007', 'Learn to Play Mah Jongg', 'buffalo-learn-to-play-mah-jongg-20261007', '2026-10-07 00:00:00', '11:30', '13:30', 'JCC Buffalo, 2640 North Forest Rd, Getzville, NY 14068', (SELECT id FROM City WHERE name = 'Buffalo' AND state = 'NY'), (SELECT id FROM Club WHERE slug = 'buffalo-jcc-buffalo-learn-to-play-mah-jongg'), (SELECT id FROM Instructor WHERE slug = 'buffalo-macia-sheibley'), 'LESSON', 1, NULL, 'https://www.jccbuffalo.org/index.php?category=Buffalo+Adult+Engagement&src=programs&srctype=lister&submenu=programs', 'https://www.jccbuffalo.org/index.php?category=Buffalo+Adult+Engagement&src=programs&srctype=lister&submenu=programs', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_buffalo-learn-to-play-mah-jongg-20261014', 'Learn to Play Mah Jongg', 'buffalo-learn-to-play-mah-jongg-20261014', '2026-10-14 00:00:00', '11:30', '13:30', 'JCC Buffalo, 2640 North Forest Rd, Getzville, NY 14068', (SELECT id FROM City WHERE name = 'Buffalo' AND state = 'NY'), (SELECT id FROM Club WHERE slug = 'buffalo-jcc-buffalo-learn-to-play-mah-jongg'), (SELECT id FROM Instructor WHERE slug = 'buffalo-macia-sheibley'), 'LESSON', 1, NULL, 'https://www.jccbuffalo.org/index.php?category=Buffalo+Adult+Engagement&src=programs&srctype=lister&submenu=programs', 'https://www.jccbuffalo.org/index.php?category=Buffalo+Adult+Engagement&src=programs&srctype=lister&submenu=programs', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_buffalo-learn-to-play-mah-jongg-20261021', 'Learn to Play Mah Jongg', 'buffalo-learn-to-play-mah-jongg-20261021', '2026-10-21 00:00:00', '11:30', '13:30', 'JCC Buffalo, 2640 North Forest Rd, Getzville, NY 14068', (SELECT id FROM City WHERE name = 'Buffalo' AND state = 'NY'), (SELECT id FROM Club WHERE slug = 'buffalo-jcc-buffalo-learn-to-play-mah-jongg'), (SELECT id FROM Instructor WHERE slug = 'buffalo-macia-sheibley'), 'LESSON', 1, NULL, 'https://www.jccbuffalo.org/index.php?category=Buffalo+Adult+Engagement&src=programs&srctype=lister&submenu=programs', 'https://www.jccbuffalo.org/index.php?category=Buffalo+Adult+Engagement&src=programs&srctype=lister&submenu=programs', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_buffalo-learn-to-play-mah-jongg-20261028', 'Learn to Play Mah Jongg', 'buffalo-learn-to-play-mah-jongg-20261028', '2026-10-28 00:00:00', '11:30', '13:30', 'JCC Buffalo, 2640 North Forest Rd, Getzville, NY 14068', (SELECT id FROM City WHERE name = 'Buffalo' AND state = 'NY'), (SELECT id FROM Club WHERE slug = 'buffalo-jcc-buffalo-learn-to-play-mah-jongg'), (SELECT id FROM Instructor WHERE slug = 'buffalo-macia-sheibley'), 'LESSON', 1, NULL, 'https://www.jccbuffalo.org/index.php?category=Buffalo+Adult+Engagement&src=programs&srctype=lister&submenu=programs', 'https://www.jccbuffalo.org/index.php?category=Buffalo+Adult+Engagement&src=programs&srctype=lister&submenu=programs', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_buffalo-learn-to-play-mah-jongg-20261104', 'Learn to Play Mah Jongg', 'buffalo-learn-to-play-mah-jongg-20261104', '2026-11-04 00:00:00', '11:30', '13:30', 'JCC Buffalo, 2640 North Forest Rd, Getzville, NY 14068', (SELECT id FROM City WHERE name = 'Buffalo' AND state = 'NY'), (SELECT id FROM Club WHERE slug = 'buffalo-jcc-buffalo-learn-to-play-mah-jongg'), (SELECT id FROM Instructor WHERE slug = 'buffalo-macia-sheibley'), 'LESSON', 1, NULL, 'https://www.jccbuffalo.org/index.php?category=Buffalo+Adult+Engagement&src=programs&srctype=lister&submenu=programs', 'https://www.jccbuffalo.org/index.php?category=Buffalo+Adult+Engagement&src=programs&srctype=lister&submenu=programs', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_buffalo-learn-to-play-mah-jongg-20261111', 'Learn to Play Mah Jongg', 'buffalo-learn-to-play-mah-jongg-20261111', '2026-11-11 00:00:00', '11:30', '13:30', 'JCC Buffalo, 2640 North Forest Rd, Getzville, NY 14068', (SELECT id FROM City WHERE name = 'Buffalo' AND state = 'NY'), (SELECT id FROM Club WHERE slug = 'buffalo-jcc-buffalo-learn-to-play-mah-jongg'), (SELECT id FROM Instructor WHERE slug = 'buffalo-macia-sheibley'), 'LESSON', 1, NULL, 'https://www.jccbuffalo.org/index.php?category=Buffalo+Adult+Engagement&src=programs&srctype=lister&submenu=programs', 'https://www.jccbuffalo.org/index.php?category=Buffalo+Adult+Engagement&src=programs&srctype=lister&submenu=programs', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_buffalo-learn-to-play-mah-jongg-20261118', 'Learn to Play Mah Jongg', 'buffalo-learn-to-play-mah-jongg-20261118', '2026-11-18 00:00:00', '11:30', '13:30', 'JCC Buffalo, 2640 North Forest Rd, Getzville, NY 14068', (SELECT id FROM City WHERE name = 'Buffalo' AND state = 'NY'), (SELECT id FROM Club WHERE slug = 'buffalo-jcc-buffalo-learn-to-play-mah-jongg'), (SELECT id FROM Instructor WHERE slug = 'buffalo-macia-sheibley'), 'LESSON', 1, NULL, 'https://www.jccbuffalo.org/index.php?category=Buffalo+Adult+Engagement&src=programs&srctype=lister&submenu=programs', 'https://www.jccbuffalo.org/index.php?category=Buffalo+Adult+Engagement&src=programs&srctype=lister&submenu=programs', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_buffalo-learn-to-play-mah-jongg-20261125', 'Learn to Play Mah Jongg', 'buffalo-learn-to-play-mah-jongg-20261125', '2026-11-25 00:00:00', '11:30', '13:30', 'JCC Buffalo, 2640 North Forest Rd, Getzville, NY 14068', (SELECT id FROM City WHERE name = 'Buffalo' AND state = 'NY'), (SELECT id FROM Club WHERE slug = 'buffalo-jcc-buffalo-learn-to-play-mah-jongg'), (SELECT id FROM Instructor WHERE slug = 'buffalo-macia-sheibley'), 'LESSON', 1, NULL, 'https://www.jccbuffalo.org/index.php?category=Buffalo+Adult+Engagement&src=programs&srctype=lister&submenu=programs', 'https://www.jccbuffalo.org/index.php?category=Buffalo+Adult+Engagement&src=programs&srctype=lister&submenu=programs', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
