INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_fort-lauderdale-modern-mahjong-fort-lauderdale', 'Modern Mahjong - Fort Lauderdale', 'fort-lauderdale-modern-mahjong-fort-lauderdale', 'Modern Mahjong lists American Mahjong play locations in Fort Lauderdale, including Beach Community Center, downtown Saturdays and a VFW Wednesday session.', (SELECT id FROM City WHERE name = 'Fort Lauderdale' AND state = 'FL'), '3351 NE 33rd Avenue, Fort Lauderdale, FL 33308', 'https://modernmahjong.com/pages/florida', '954-828-4610', NULL, NULL, NULL, 0, 0, 1, 1, 0, 0, NULL, 'Beach Community Center; downtown Saturdays noon-3; VFW Wednesdays 12:30-4:30', 'https://modernmahjong.com/pages/florida', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_fort-lauderdale-your-mahjong-mama', 'Your Mahjong Mama', 'fort-lauderdale-your-mahjong-mama', (SELECT id FROM City WHERE name = 'Fort Lauderdale' AND state = 'FL'), 'https://linktr.ee/your.mahjong.mama', NULL, 1, 1, 0, 1, NULL, 'Certified American Mahjong instructor in Fort Lauderdale; current profile lists private lessons/events and dated guided/open play.', 'https://linktr.ee/your.mahjong.mama', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_fort-lauderdale-mahjong-at-the-fort-20260930', 'Mahjong at The Fort', 'fort-lauderdale-mahjong-at-the-fort-20260930', '2026-09-30 00:00:00', '12:00', '14:00', 'The FORT Pickleball, 891 SW 34th St, Fort Lauderdale, FL 33315', (SELECT id FROM City WHERE name = 'Fort Lauderdale' AND state = 'FL'), NULL, (SELECT id FROM Instructor WHERE slug = 'fort-lauderdale-your-mahjong-mama'), 'OPEN_PLAY', 0, 25, NULL, 'https://patch.com/florida/hollywood-fl/calendar/event/20260928/374b6f3d-5931-4c2b-aac3-1a9f999031e7/mahjong-at-the-fort', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
