INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_memphis-pat-ford-mahj-squad-901', 'Pat Ford / MahJ Squad 901', 'memphis-pat-ford-mahj-squad-901', (SELECT id FROM City WHERE name = 'Memphis' AND state = 'TN'), 'https://mahjsquad901.com/', '901-292-1627', 1, 1, 0, 1, NULL, 'Following NMJL rules; beginner/intermediate classes, open play and mini-tournaments.', 'https://mahjong4friends.com/teachers/tn', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_memphis-ice-cream-social-mah-jongg-at-lakeview-20261023', 'Ice Cream Social & Mah Jongg at Lakeview', 'memphis-ice-cream-social-mah-jongg-at-lakeview-20261023', '2026-10-23 00:00:00', '13:00', '16:00', 'Lakeview Germantown, 7900 Wolf River Boulevard, Germantown, TN 38138', (SELECT id FROM City WHERE name = 'Memphis' AND state = 'TN'), NULL, (SELECT id FROM Instructor WHERE slug = 'memphis-pat-ford-mahj-squad-901'), 'SOCIAL', 1, 0, 'https://www.simpletix.com/e/ice-cream-social-mah-jongg-at-lakeview-tickets-282233', 'https://www.simpletix.com/e/ice-cream-social-mah-jongg-at-lakeview-tickets-282233', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_memphis-2026-mahj-bam-jam-4th-quarter-tournament-20261024', '2026 MahJ Bam Jam 4th Quarter Tournament', 'memphis-2026-mahj-bam-jam-4th-quarter-tournament-20261024', '2026-10-24 00:00:00', NULL, NULL, 'Immaculate Conception Catholic Church, 1669 Central Avenue, Memphis, TN 38104', (SELECT id FROM City WHERE name = 'Memphis' AND state = 'TN'), NULL, (SELECT id FROM Instructor WHERE name = 'Vicki Campbell / MahJ Memphis' AND cityId = (SELECT id FROM City WHERE name = 'Memphis' AND state = 'TN')), 'TOURNAMENT', 1, NULL, 'https://mahjmemphis.com/mahj-bam-jam-series', 'https://mahjmemphis.com/mahj-bam-jam-series', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
