INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_birmingham-levite-jcc-mahjong', 'Levite JCC Mahjong', 'birmingham-levite-jcc-mahjong', 'Levite JCC hosts free public Mahjong open play and a three-part beginner Mahjong 101 series.', (SELECT id FROM City WHERE name = 'Birmingham' AND state = 'AL'), '3960 Montclair Rd, Birmingham, AL 35213', 'https://bhamjcc.org/programs/', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 1, NULL, 'Open play Thursdays 11:30 AM-2:30 PM; Mahjong 101 begins Oct 6', 'https://bhamjcc.org/programs/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_birmingham-mahjong-101-part-1-20261006', 'Mahjong 101 - Part 1', 'birmingham-mahjong-101-part-1-20261006', '2026-10-06 00:00:00', '17:00', '19:00', 'Levite Jewish Community Center, 3960 Montclair Rd, Birmingham, AL 35213', (SELECT id FROM City WHERE name = 'Birmingham' AND state = 'AL'), (SELECT id FROM Club WHERE slug = 'birmingham-levite-jcc-mahjong'), NULL, 'LESSON', 1, 100, 'https://bhamjcc.org/programs/', 'https://www.bjf.org/community-events/tag/91988', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_birmingham-mahjong-101-part-2-20261013', 'Mahjong 101 - Part 2', 'birmingham-mahjong-101-part-2-20261013', '2026-10-13 00:00:00', '17:00', '19:00', 'Levite Jewish Community Center, 3960 Montclair Rd, Birmingham, AL 35213', (SELECT id FROM City WHERE name = 'Birmingham' AND state = 'AL'), (SELECT id FROM Club WHERE slug = 'birmingham-levite-jcc-mahjong'), NULL, 'LESSON', 1, 100, 'https://bhamjcc.org/programs/', 'https://www.bjf.org/community-events/tag/91988', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_birmingham-mahjong-open-play-20261001', 'Mahjong Open Play', 'birmingham-mahjong-open-play-20261001', '2026-10-01 00:00:00', '11:30', '14:30', 'Levite Jewish Community Center, 3960 Montclair Rd, Birmingham, AL 35213', (SELECT id FROM City WHERE name = 'Birmingham' AND state = 'AL'), (SELECT id FROM Club WHERE slug = 'birmingham-levite-jcc-mahjong'), NULL, 'OPEN_PLAY', 0, 0, 'https://bhamjcc.org/events/month/2026-09/', 'https://bhamjcc.org/events/month/2026-09/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
