INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_new-orleans-new-orleans-jcc-mah-jongg', 'New Orleans JCC Mah Jongg', 'new-orleans-new-orleans-jcc-mah-jongg', 'New Orleans JCC runs multi-session beginner Mah Jongg classes using National Mah Jongg League rules.', (SELECT id FROM City WHERE name = 'New Orleans' AND state = 'LA'), '5342 St Charles Ave, New Orleans, LA 70115', 'https://www.nojcc.org/adultclasses', '504-897-0143', NULL, NULL, NULL, 1, 1, 0, 0, 0, 0, 100, 'Current series include Oct 6-14 Metairie and Oct 26-Nov 5 Uptown', 'https://www.nojcc.org/adultclasses', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_new-orleans-learn-to-play-mah-jongg-metairie-20261006', 'Learn to Play Mah Jongg - Metairie', 'new-orleans-learn-to-play-mah-jongg-metairie-20261006', '2026-10-06 00:00:00', '17:30', '20:30', 'New Orleans JCC Metairie', (SELECT id FROM City WHERE name = 'New Orleans' AND state = 'LA'), (SELECT id FROM Club WHERE slug = 'new-orleans-new-orleans-jcc-mah-jongg'), NULL, 'LESSON', 1, 125, 'https://www.nojcc.org/adultclasses', 'https://www.nojcc.org/adultclasses', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_new-orleans-learn-to-play-mah-jongg-uptown-20261026', 'Learn to Play Mah Jongg - Uptown', 'new-orleans-learn-to-play-mah-jongg-uptown-20261026', '2026-10-26 00:00:00', '17:30', '20:30', 'New Orleans JCC Uptown', (SELECT id FROM City WHERE name = 'New Orleans' AND state = 'LA'), (SELECT id FROM Club WHERE slug = 'new-orleans-new-orleans-jcc-mah-jongg'), NULL, 'LESSON', 1, 125, 'https://www.nojcc.org/adultclasses', 'https://www.nojcc.org/adultclasses', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
