INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_jacksonville-tiles-for-tatas-20261003', 'Tiles for TaTas', 'jacksonville-tiles-for-tatas-20261003', '2026-10-03 00:00:00', NULL, NULL, 'Havana Jax Cafe, 2578 Atlantic Blvd, Jacksonville, FL 32207', (SELECT id FROM City WHERE name = 'Jacksonville' AND state = 'FL'), (SELECT id FROM Club WHERE name = 'Mahjong Social Club Jax' AND cityId = (SELECT id FROM City WHERE name = 'Jacksonville' AND state = 'FL')), NULL, 'TOURNAMENT', 1, 150, 'https://www.mahjongsocialclubjax.com/mahjongevents', 'https://www.mahjongsocialclubjax.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_jacksonville-mahjong-101-grazing-parlor-20261006', 'Mahjong 101 @ Grazing Parlor', 'jacksonville-mahjong-101-grazing-parlor-20261006', '2026-10-06 00:00:00', NULL, NULL, 'Grazing Parlor', (SELECT id FROM City WHERE name = 'Jacksonville' AND state = 'FL'), (SELECT id FROM Club WHERE name = 'Mahjong Social Club Jax' AND cityId = (SELECT id FROM City WHERE name = 'Jacksonville' AND state = 'FL')), NULL, 'LESSON', 1, NULL, 'https://www.mahjongsocialclubjax.com/mahjongevents', 'https://www.mahjongsocialclubjax.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_jacksonville-mahjong-101-grazing-parlor-20261014', 'Mahjong 101 @ Grazing Parlor', 'jacksonville-mahjong-101-grazing-parlor-20261014', '2026-10-14 00:00:00', NULL, NULL, 'Grazing Parlor', (SELECT id FROM City WHERE name = 'Jacksonville' AND state = 'FL'), (SELECT id FROM Club WHERE name = 'Mahjong Social Club Jax' AND cityId = (SELECT id FROM City WHERE name = 'Jacksonville' AND state = 'FL')), NULL, 'LESSON', 1, NULL, 'https://www.mahjongsocialclubjax.com/mahjongevents', 'https://www.mahjongsocialclubjax.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_jacksonville-bams-boos-and-brews-grazing-parlor-20261028', 'Bams, Boos and Brews! @ Grazing Parlor', 'jacksonville-bams-boos-and-brews-grazing-parlor-20261028', '2026-10-28 00:00:00', NULL, NULL, 'Grazing Parlor, 1108 3rd St S, Jacksonville Beach, FL 32250', (SELECT id FROM City WHERE name = 'Jacksonville' AND state = 'FL'), (SELECT id FROM Club WHERE name = 'Mahjong Social Club Jax' AND cityId = (SELECT id FROM City WHERE name = 'Jacksonville' AND state = 'FL')), NULL, 'OPEN_PLAY', 1, 58.3, 'https://www.mahjongsocialclubjax.com/mahjongevents', 'https://www.mahjongsocialclubjax.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
