-- ACTIVE counts: Omaha 6, Buffalo 11, Memphis 6, Birmingham 6, New Orleans 7,
-- Jacksonville 5 — at or above the docs/CITY_PAGE_POLICY.md §11 minimum (>=5).
-- Boise (1), Fort Lauderdale (1), Louisville (3), Albuquerque (0) and
-- Charleston (0) stay unpublished.
UPDATE "City" SET "published" = 1 WHERE "slug" IN ('omaha', 'buffalo', 'memphis', 'birmingham', 'new-orleans', 'jacksonville');
UPDATE "City" SET "intro" = 'Omaha has two clubs and a private teacher. One Bam offers beginner classes and open play at restaurants and venues around the metro, Club Mahj offers lessons, supervised play and themed open-play events, and Mahjong with Mary teaches at a central Omaha studio. If you are new, a beginner class is the natural first step, and open play is a relaxed way to practice. Locations vary by event, so check the address first.' WHERE "slug" = 'omaha';
UPDATE "City" SET "intro" = 'Buffalo''s American Mahjong is centered on the JCC in Getzville. A weekly Learn to Play Mah Jongg course, led by Macia Sheibley, runs through the fall and provides the official card, and a Tuesday open play is available for players who know the game. The course is a good fit if you have no experience. Check the JCC program page for the next session dates and how to register.' WHERE "slug" = 'buffalo';
UPDATE "City" SET "intro" = 'Memphis players have a church-hosted weekly game, teachers and tournaments. Emmanuel United Methodist Church hosts weekly National Mah Jongg League play, with beginners welcome and no church membership required. Vicki Campbell of MahJ Memphis and Pat Ford of MahJ Squad 901 teach American Mah Jongg, and they also run tournaments and social events around the city. If you are new, a beginner class or the Emmanuel game is a friendly place to start.' WHERE "slug" = 'memphis';
UPDATE "City" SET "intro" = 'Birmingham''s listings center on two community sites. The Levite Jewish Community Center offers free open play and a multi-part Mahjong 101 series, and O''Neal Library in Mountain Brook hosts a recurring meetup that uses the National Mah Jongg League card, with a beginner lesson on the first Monday. Both are a good fit for newcomers. Check the event pages for the current location and dates before you go.' WHERE "slug" = 'birmingham';
UPDATE "City" SET "intro" = 'New Orleans has a parlor and a JCC program. Fleur de Mahj, in Metairie, offers beginner and strategy classes, guided play and tournaments using official National Mah Jongg League rules, and the New Orleans JCC runs multi-session beginner classes at its Metairie and Uptown locations. If you are new, a JCC class or a Fleur de Mahj beginners event is a good first step. Booking is usually required, so check the schedule first.' WHERE "slug" = 'new-orleans';
UPDATE "City" SET "intro" = 'Jacksonville''s listings come from Mahjong Social Club Jax, an organizer that runs Mahjong 101 classes, open play and larger events around the city and beaches, including a benefit tournament. Events are held at cafes and restaurants, and the official site notes the current National Mah Jongg League card is needed. If you are new, start with a Mahjong 101 class. Check the event page for time, location and price before you go.' WHERE "slug" = 'jacksonville';
