INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_charleston-holy-mahj-the-card-room', 'Holy Mahj - The Card Room', 'charleston-holy-mahj-the-card-room', 'Charleston-based American Mahjong organization with a dedicated Card Room and public beginner series, open play and league programming.', (SELECT id FROM City WHERE name = 'Charleston' AND state = 'SC'), '78 Line Street, Charleston, SC 29403', 'https://www.holymahj.com/', NULL, 'hello@holymahj.com', NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Public beginner series and other events; see official event page.', 'https://www.holymahj.com/pages/play-in-charleston', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_charleston-cara-stein', 'Cara Stein', 'charleston-cara-stein', (SELECT id FROM City WHERE name = 'Charleston' AND state = 'SC'), 'https://www.holymahj.com/', 'hello@holymahj.com', 1, 1, 0, 1, NULL, 'Charleston teacher for Holy Mahj; leads the Under 30 Club and kids classes.', 'https://www.holymahj.com/pages/meet-the-team', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_charleston-debbie-engel', 'Debbie Engel', 'charleston-debbie-engel', (SELECT id FROM City WHERE name = 'Charleston' AND state = 'SC'), 'https://www.holymahj.com/', 'hello@holymahj.com', 1, 1, 0, 1, NULL, 'Charleston teacher for Holy Mahj; teaches/plays with the local community.', 'https://www.holymahj.com/pages/meet-the-team', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_charleston-ashley-o-brien', 'Ashley O''Brien', 'charleston-ashley-o-brien', (SELECT id FROM City WHERE name = 'Charleston' AND state = 'SC'), 'https://www.holymahj.com/', 'hello@holymahj.com', 1, 1, 0, 1, NULL, 'Charleston teacher for Holy Mahj.', 'https://www.holymahj.com/pages/meet-the-team', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
