INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_fort-lauderdale-guided-play-at-shooters-waterfront-20261005', 'Guided Play at Shooters Waterfront', 'fort-lauderdale-guided-play-at-shooters-waterfront-20261005', '2026-10-05 00:00:00', NULL, NULL, 'Shooters Waterfront', (SELECT id FROM City WHERE name = 'Fort Lauderdale' AND state = 'FL'), NULL, (SELECT id FROM Instructor WHERE name = 'Your Mahjong Mama' AND cityId = (SELECT id FROM City WHERE name = 'Fort Lauderdale' AND state = 'FL')), 'LESSON', 0, NULL, 'https://linktr.ee/your.mahjong.mama', 'https://linktr.ee/your.mahjong.mama', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_fort-lauderdale-open-play-at-shooters-waterfront-20261005', 'Open Play at Shooters Waterfront', 'fort-lauderdale-open-play-at-shooters-waterfront-20261005', '2026-10-05 00:00:00', NULL, NULL, 'Shooters Waterfront', (SELECT id FROM City WHERE name = 'Fort Lauderdale' AND state = 'FL'), NULL, (SELECT id FROM Instructor WHERE name = 'Your Mahjong Mama' AND cityId = (SELECT id FROM City WHERE name = 'Fort Lauderdale' AND state = 'FL')), 'SOCIAL', 0, NULL, 'https://linktr.ee/your.mahjong.mama', 'https://linktr.ee/your.mahjong.mama', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_fort-lauderdale-guided-play-at-shooters-waterfront-20261019', 'Guided Play at Shooters Waterfront', 'fort-lauderdale-guided-play-at-shooters-waterfront-20261019', '2026-10-19 00:00:00', NULL, NULL, 'Shooters Waterfront', (SELECT id FROM City WHERE name = 'Fort Lauderdale' AND state = 'FL'), NULL, (SELECT id FROM Instructor WHERE name = 'Your Mahjong Mama' AND cityId = (SELECT id FROM City WHERE name = 'Fort Lauderdale' AND state = 'FL')), 'LESSON', 0, NULL, 'https://linktr.ee/your.mahjong.mama', 'https://linktr.ee/your.mahjong.mama', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_fort-lauderdale-open-play-at-shooters-waterfront-20261019', 'Open Play at Shooters Waterfront', 'fort-lauderdale-open-play-at-shooters-waterfront-20261019', '2026-10-19 00:00:00', NULL, NULL, 'Shooters Waterfront', (SELECT id FROM City WHERE name = 'Fort Lauderdale' AND state = 'FL'), NULL, (SELECT id FROM Instructor WHERE name = 'Your Mahjong Mama' AND cityId = (SELECT id FROM City WHERE name = 'Fort Lauderdale' AND state = 'FL')), 'SOCIAL', 0, NULL, 'https://linktr.ee/your.mahjong.mama', 'https://linktr.ee/your.mahjong.mama', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
