INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_durham-monthly-mahjong-dssolvr-open-play-20261022', 'Monthly Mahjong @ DSSOLVR - Open Play', 'durham-monthly-mahjong-dssolvr-open-play-20261022', '2026-10-22 00:00:00', '18:30', '20:30', 'DSSOLVR Durham', (SELECT id FROM City WHERE name = 'Durham' AND state = 'NC'), NULL, NULL, 'OPEN_PLAY', 0, 0, 'https://downtowndurham.com/event/monthly-mahjong-dssolvr-free-play-every-4th-thursday/2026-10-22/', 'https://dssolvr.com/event-detail/monthly-mahjong-free-play-every-4th-thursday-durham/2026-09-24/', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_durham-learn-to-play-mahjong-20261007', 'Learn to Play Mahjong', 'durham-learn-to-play-mahjong-20261007', '2026-10-07 00:00:00', '12:00', '15:00', 'North Regional Library', (SELECT id FROM City WHERE name = 'Durham' AND state = 'NC'), NULL, NULL, 'LESSON', 1, NULL, 'https://durhamcountylibrary.org/', 'https://durhamcountylibrary.org/person/bob/', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_durham-learn-to-play-mahjong-20261014', 'Learn to Play Mahjong', 'durham-learn-to-play-mahjong-20261014', '2026-10-14 00:00:00', '12:00', '15:00', 'North Regional Library', (SELECT id FROM City WHERE name = 'Durham' AND state = 'NC'), NULL, NULL, 'LESSON', 1, NULL, 'https://durhamcountylibrary.org/', 'https://durhamcountylibrary.org/person/bob/', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
