INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_providence-mahjong-20261007', 'MahJong', 'providence-mahjong-20261007', '2026-10-07 00:00:00', '13:00', '15:00', 'Rochambeau Library – Community Room', (SELECT id FROM City WHERE name = 'Providence' AND state = 'RI'), NULL, NULL, 'OPEN_PLAY', 1, NULL, 'https://clpvd.org/event/mahjong-2-2/2026-10-07/', 'https://clpvd.org/event/mahjong-2-2/2026-10-07/', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_providence-mahjong-20261014', 'MahJong', 'providence-mahjong-20261014', '2026-10-14 00:00:00', '13:00', '15:00', 'Rochambeau Library – Community Room', (SELECT id FROM City WHERE name = 'Providence' AND state = 'RI'), NULL, NULL, 'OPEN_PLAY', 1, NULL, 'https://clpvd.org/event/mahjong-2-2/2026-10-14/', 'https://clpvd.org/event/mahjong-2-2/2026-10-14/', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_providence-mahjong-20261021', 'MahJong', 'providence-mahjong-20261021', '2026-10-21 00:00:00', '13:00', '15:00', 'Rochambeau Library – Community Room', (SELECT id FROM City WHERE name = 'Providence' AND state = 'RI'), NULL, NULL, 'OPEN_PLAY', 1, NULL, 'https://clpvd.org/event/mahjong-2-2/2026-10-21/', 'https://clpvd.org/event/mahjong-2-2/2026-10-21/', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_providence-mahjong-20261028', 'MahJong', 'providence-mahjong-20261028', '2026-10-28 00:00:00', '13:00', '15:00', 'Rochambeau Library – Community Room', (SELECT id FROM City WHERE name = 'Providence' AND state = 'RI'), NULL, NULL, 'OPEN_PLAY', 1, NULL, 'https://clpvd.org/event/mahjong-2-2/2026-10-28/', 'https://clpvd.org/event/mahjong-2-2/2026-10-28/', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
