INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_boise-mahjong-at-the-local', 'Mahjong at the Local', 'boise-mahjong-at-the-local', (SELECT id FROM City WHERE name = 'Boise' AND state = 'ID'), 'https://www.eventbrite.com/o/121388652873', NULL, 0, 1, 0, 1, NULL, 'Organizer for Downtown Boise classes. Event pages explicitly say the classes teach American Mahjong using the official rules and playing card of the National Mah Jongg League.', 'https://www.eventbrite.com/o/121388652873', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_boise-curious-about-mahjong-learn-to-play-in-a-2-part-beginner-series-20261019', 'Curious About Mahjong? Learn to Play in a 2-Part Beginner Series', 'boise-curious-about-mahjong-learn-to-play-in-a-2-part-beginner-series-20261019', '2026-10-19 00:00:00', '13:00', '15:00', 'LOCAL Boise, 250 East Myrtle Street, Boise, ID 83702', (SELECT id FROM City WHERE name = 'Boise' AND state = 'ID'), NULL, (SELECT id FROM Instructor WHERE slug = 'boise-mahjong-at-the-local'), 'LESSON', 1, 50, 'https://www.eventbrite.com/e/curious-about-mahjong-learn-to-play-in-a-2-part-beginner-series-101926-tickets-2000962549851', 'https://www.eventbrite.com/e/curious-about-mahjong-learn-to-play-in-a-2-part-beginner-series-101926-tickets-2000962549851', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_boise-curious-about-mahjong-learn-to-play-in-a-2-part-beginner-series-20261026', 'Curious About Mahjong? Learn to Play in a 2-Part Beginner Series', 'boise-curious-about-mahjong-learn-to-play-in-a-2-part-beginner-series-20261026', '2026-10-26 00:00:00', '13:00', '15:00', 'LOCAL Boise, 250 East Myrtle Street, Boise, ID 83702', (SELECT id FROM City WHERE name = 'Boise' AND state = 'ID'), NULL, (SELECT id FROM Instructor WHERE slug = 'boise-mahjong-at-the-local'), 'LESSON', 1, 50, 'https://www.eventbrite.com/e/curious-about-mahjong-learn-to-play-in-a-2-part-beginner-series-101926-tickets-2000962549851', 'https://www.eventbrite.com/e/curious-about-mahjong-learn-to-play-in-a-2-part-beginner-series-101926-tickets-2000962549851', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
