INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_hartford-river-bend-bookshop', 'River Bend Bookshop', 'hartford-river-bend-bookshop', 'West Hartford venue hosting American Mah Jongg courses and open studio; its event pages require an NMJL card.', (SELECT id FROM City WHERE name = 'Hartford' AND state = 'CT'), '224 Park Road, West Hartford, CT 06119', 'https://riverbendbookshop.com/', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Recurring Mah Jongg Open Studio and American Mah Jongg 101/102 courses', 'https://riverbendbookshop.com/events/2026/10', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_hartford-linda-houde', 'Linda Houde', 'hartford-linda-houde', (SELECT id FROM City WHERE name = 'Hartford' AND state = 'CT'), 'https://riverbendbookshop.com/', NULL, 0, 1, 0, 1, NULL, 'River Bend Bookshop identifies Linda Houde as its local instructor for the 101 Beginner and 102 Intermediate American Mah Jongg courses.', 'https://riverbendbookshop.com/events/2026/10', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_hartford-learn-to-play-american-mah-jongg-102-intermediate-course-20261005', 'Learn to Play American Mah Jongg: 102 Intermediate Course', 'hartford-learn-to-play-american-mah-jongg-102-intermediate-course-20261005', '2026-10-05 00:00:00', '18:00', '20:30', 'River Bend - West Hartford', (SELECT id FROM City WHERE name = 'Hartford' AND state = 'CT'), (SELECT id FROM Club WHERE slug = 'hartford-river-bend-bookshop'), (SELECT id FROM Instructor WHERE slug = 'hartford-linda-houde'), 'LESSON', 1, NULL, 'https://riverbendbookshop.com/events/2026/10', 'https://riverbendbookshop.com/events/2026/10', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_hartford-mah-jongg-open-studio-20261012', 'Mah Jongg Open Studio', 'hartford-mah-jongg-open-studio-20261012', '2026-10-12 00:00:00', '18:00', '20:00', 'River Bend - West Hartford', (SELECT id FROM City WHERE name = 'Hartford' AND state = 'CT'), (SELECT id FROM Club WHERE slug = 'hartford-river-bend-bookshop'), NULL, 'OPEN_PLAY', 0, NULL, 'https://riverbendbookshop.com/events/2026/10', 'https://riverbendbookshop.com/events/2026/10', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_hartford-learn-to-play-american-mah-jongg-101-beginner-course-20261019', 'Learn to Play American Mah Jongg: 101 Beginner Course', 'hartford-learn-to-play-american-mah-jongg-101-beginner-course-20261019', '2026-10-19 00:00:00', '18:00', '20:30', 'River Bend - West Hartford', (SELECT id FROM City WHERE name = 'Hartford' AND state = 'CT'), (SELECT id FROM Club WHERE slug = 'hartford-river-bend-bookshop'), (SELECT id FROM Instructor WHERE slug = 'hartford-linda-houde'), 'LESSON', 1, NULL, 'https://riverbendbookshop.com/events/2026/10', 'https://riverbendbookshop.com/events/2026/10', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_hartford-mah-jongg-open-studio-20261026', 'Mah Jongg Open Studio', 'hartford-mah-jongg-open-studio-20261026', '2026-10-26 00:00:00', '18:00', '20:00', 'River Bend - West Hartford', (SELECT id FROM City WHERE name = 'Hartford' AND state = 'CT'), (SELECT id FROM Club WHERE slug = 'hartford-river-bend-bookshop'), NULL, 'OPEN_PLAY', 0, NULL, 'https://riverbendbookshop.com/events/2026/10', 'https://riverbendbookshop.com/events/2026/10', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_hartford-learn-to-play-american-mah-jongg-102-intermediate-course-20261102', 'Learn to Play American Mah Jongg: 102 Intermediate Course', 'hartford-learn-to-play-american-mah-jongg-102-intermediate-course-20261102', '2026-11-02 00:00:00', '18:00', '20:30', 'River Bend - West Hartford', (SELECT id FROM City WHERE name = 'Hartford' AND state = 'CT'), (SELECT id FROM Club WHERE slug = 'hartford-river-bend-bookshop'), (SELECT id FROM Instructor WHERE slug = 'hartford-linda-houde'), 'LESSON', 1, NULL, 'https://riverbendbookshop.com/upcoming-events', 'https://riverbendbookshop.com/upcoming-events', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
