INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_columbia-twyla-stowe', 'Twyla Stowe', 'columbia-twyla-stowe', (SELECT id FROM City WHERE name = 'Columbia' AND state = 'SC'), 'https://cms.sc.edu/about/offices_and_divisions/continuing_education/personal_interest/personal_enrichment_and_lifestyle/mah_jong/', NULL, 1, 1, 0, 1, 115, 'University of South Carolina says Twyla is based in Columbia, offers beginner-to-advanced instruction, and teaches American mahjong.', 'https://cms.sc.edu/about/offices_and_divisions/continuing_education/personal_interest/personal_enrichment_and_lifestyle/mah_jong/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_columbia-mah-jongg-morning-session-20261014', 'Mah Jongg - Morning Session', 'columbia-mah-jongg-morning-session-20261014', '2026-10-14 00:00:00', '10:00', '11:30', 'University of South Carolina', (SELECT id FROM City WHERE name = 'Columbia' AND state = 'SC'), NULL, (SELECT id FROM Instructor WHERE slug = 'columbia-twyla-stowe'), 'LESSON', 1, 115, 'https://cms.sc.edu/about/offices_and_divisions/continuing_education/personal_interest/personal_enrichment_and_lifestyle/mah_jong/', 'https://cms.sc.edu/about/offices_and_divisions/continuing_education/personal_interest/personal_enrichment_and_lifestyle/mah_jong/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_columbia-mah-jongg-afternoon-session-20261014', 'Mah Jongg - Afternoon Session', 'columbia-mah-jongg-afternoon-session-20261014', '2026-10-14 00:00:00', '13:00', '14:30', 'University of South Carolina', (SELECT id FROM City WHERE name = 'Columbia' AND state = 'SC'), NULL, (SELECT id FROM Instructor WHERE slug = 'columbia-twyla-stowe'), 'LESSON', 1, 115, 'https://cms.sc.edu/about/offices_and_divisions/continuing_education/personal_interest/personal_enrichment_and_lifestyle/mah_jong/', 'https://cms.sc.edu/about/offices_and_divisions/continuing_education/personal_interest/personal_enrichment_and_lifestyle/mah_jong/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_columbia-mahjong-guided-play-with-alice-20261001', 'Mahjong Guided Play with Alice!', 'columbia-mahjong-guided-play-with-alice-20261001', '2026-10-01 00:00:00', '18:00', '20:30', 'Piecewise Coffee Co.', (SELECT id FROM City WHERE name = 'Columbia' AND state = 'SC'), NULL, NULL, 'OPEN_PLAY', 0, NULL, 'https://piecewisecoffee.com/events/mahjongjuly16-as5rl-ranbp', 'https://piecewisecoffee.com/events/mahjongjuly16-as5rl-ranbp', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
