INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_des-moines-mahjong-open-play-w-dsm-pop-up-social-club-20261006', 'Mahjong open play w/ DSM Pop-up Social Club', 'des-moines-mahjong-open-play-w-dsm-pop-up-social-club-20261006', '2026-10-06 00:00:00', '09:30', '11:30', 'Barista''s Bouquet - Urbandale', (SELECT id FROM City WHERE name = 'Des Moines' AND state = 'IA'), NULL, NULL, 'OPEN_PLAY', 0, NULL, NULL, 'https://baristasbouquet.com/events.html', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_des-moines-mahjong-open-play-w-dsm-pop-up-social-club-20261028', 'Mahjong open play w/ DSM Pop-up Social Club', 'des-moines-mahjong-open-play-w-dsm-pop-up-social-club-20261028', '2026-10-28 00:00:00', '09:30', '11:30', 'Barista''s Bouquet - Urbandale', (SELECT id FROM City WHERE name = 'Des Moines' AND state = 'IA'), NULL, NULL, 'OPEN_PLAY', 0, NULL, NULL, 'https://baristasbouquet.com/events.html', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_des-moines-mahjong-monday-open-play-20261012', 'Mahjong Monday: Open Play', 'des-moines-mahjong-monday-open-play-20261012', '2026-10-12 00:00:00', '17:00', NULL, 'WineStyles Wine Bar - The District', (SELECT id FROM City WHERE name = 'Des Moines' AND state = 'IA'), NULL, NULL, 'OPEN_PLAY', 0, NULL, NULL, 'https://winestyles.com/ankeny/', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_des-moines-mahjong-monday-101-beginners-class-20261026', 'Mahjong Monday 101: Beginners Class', 'des-moines-mahjong-monday-101-beginners-class-20261026', '2026-10-26 00:00:00', '17:30', NULL, 'WineStyles Wine Bar - The District', (SELECT id FROM City WHERE name = 'Des Moines' AND state = 'IA'), NULL, NULL, 'LESSON', 1, NULL, NULL, 'https://winestyles.com/ankeny/', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
