INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_durham-dssolvr-durham', 'DSSOLVR Durham', 'durham-dssolvr-durham', 'Durham taproom hosting Mahjong with Get Your Mahjong NC. Its official event page says beginners learn the essentials of American Mahjong.', (SELECT id FROM City WHERE name = 'Durham' AND state = 'NC'), '630 Rigsbee Ave, Durham, NC 27701', 'https://dssolvr.com/', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, '2nd Thursday beginner/intermediate lessons and 4th Thursday experienced open play', 'https://dssolvr.com/events/month/2026-10/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_durham-durham-county-library-north-regional-library', 'Durham County Library - North Regional Library', 'durham-durham-county-library-north-regional-library', 'North Regional Library hosts Learn to Play Mahjong; the official librarian event listing explicitly says it is American Mahjong and welcomes beginners.', (SELECT id FROM City WHERE name = 'Durham' AND state = 'NC'), '221 Milton Rd, Durham, NC 27705', 'https://durhamcountylibrary.org/', NULL, NULL, NULL, NULL, 1, 1, 0, 0, 0, 1, NULL, 'Weekly Wednesday 12:00 PM-3:00 PM Learn to Play Mahjong', 'https://durhamcountylibrary.org/person/bob/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_durham-monthly-mahjong-beginner-lessons-guided-play-20261008', 'Monthly Mahjong - Beginner Lessons & Guided Play', 'durham-monthly-mahjong-beginner-lessons-guided-play-20261008', '2026-10-08 00:00:00', '18:30', '21:30', 'DSSOLVR Durham', (SELECT id FROM City WHERE name = 'Durham' AND state = 'NC'), (SELECT id FROM Club WHERE slug = 'durham-dssolvr-durham'), NULL, 'LESSON', 1, NULL, NULL, 'https://dssolvr.com/events/month/2026-10/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_durham-learn-to-play-mahjong-20261007', 'Learn to Play Mahjong', 'durham-learn-to-play-mahjong-20261007', '2026-10-07 00:00:00', '12:00', '15:00', 'North Regional Library', (SELECT id FROM City WHERE name = 'Durham' AND state = 'NC'), (SELECT id FROM Club WHERE slug = 'durham-durham-county-library-north-regional-library'), NULL, 'LESSON', 1, NULL, NULL, 'https://durhamcountylibrary.org/person/bob/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_durham-learn-to-play-mahjong-20261014', 'Learn to Play Mahjong', 'durham-learn-to-play-mahjong-20261014', '2026-10-14 00:00:00', '12:00', '15:00', 'North Regional Library', (SELECT id FROM City WHERE name = 'Durham' AND state = 'NC'), (SELECT id FROM Club WHERE slug = 'durham-durham-county-library-north-regional-library'), NULL, 'LESSON', 1, NULL, NULL, 'https://durhamcountylibrary.org/person/bob/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_durham-monthly-mahjong-free-play-20261022', 'Monthly Mahjong - Free Play', 'durham-monthly-mahjong-free-play-20261022', '2026-10-22 00:00:00', '18:30', '21:30', 'DSSOLVR Durham', (SELECT id FROM City WHERE name = 'Durham' AND state = 'NC'), (SELECT id FROM Club WHERE slug = 'durham-dssolvr-durham'), NULL, 'OPEN_PLAY', 0, NULL, NULL, 'https://dssolvr.com/events/month/2026-10/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_durham-monthly-mahjong-free-play-20261126', 'Monthly Mahjong - Free Play', 'durham-monthly-mahjong-free-play-20261126', '2026-11-26 00:00:00', '18:30', '21:30', 'DSSOLVR Durham', (SELECT id FROM City WHERE name = 'Durham' AND state = 'NC'), (SELECT id FROM Club WHERE slug = 'durham-dssolvr-durham'), NULL, 'OPEN_PLAY', 0, NULL, NULL, 'https://dssolvr.com/event-detail/monthly-mahjong-free-play-every-4th-thursday-durham/2026-11-26/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_durham-monthly-mahjong-dssolvr-beginner-lessons-guided-play-20261112', 'Monthly Mahjong @ DSSOLVR - Beginner Lessons & Guided Play', 'durham-monthly-mahjong-dssolvr-beginner-lessons-guided-play-20261112', '2026-11-12 00:00:00', '18:30', '21:30', 'DSSOLVR Durham, 630 Rigsbee Avenue, Durham, NC 27701', (SELECT id FROM City WHERE name = 'Durham' AND state = 'NC'), (SELECT id FROM Club WHERE slug = 'durham-dssolvr-durham'), NULL, 'LESSON', 1, 40, 'https://docs.google.com/forms/d/e/1FAIpQLSc-noSGg1JfOubEVtBTTRS7VCgABQf9U-5YasQR2wMyR-xK5A/viewform?usp=header', 'https://dssolvr.com/event-detail/monthly-mahjong-beginner-lessons-guided-play-every-2nd-thursday-durham/2026-11-12/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
