INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_little-rock-little-rock-mahjong', 'Little Rock Mahjong', 'little-rock-little-rock-mahjong', 'Official site calls this Little Rock''s Home for American Mahjong and says it teaches American Mahjong using NMJL rules.', (SELECT id FROM City WHERE name = 'Little Rock' AND state = 'AR'), 'Little Rock, AR', 'https://www.littlerockmahjong.com/', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Public classes, private lessons and ongoing leagues; contact for current schedule.', 'https://www.littlerockmahjong.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_little-rock-kimberly-anderson', 'Kimberly Anderson', 'little-rock-kimberly-anderson', (SELECT id FROM City WHERE name = 'Little Rock' AND state = 'AR'), 'https://www.littlerockmahjong.com/', 'kimberly@littlerockmahjong.com', 1, 1, 0, 1, NULL, 'Founder/instructor. Official site says she teaches American Mahjong and that the program uses NMJL rules.', 'https://www.littlerockmahjong.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_little-rock-mahjong-mondays-with-jllr-20261013', 'Mahjong Mondays with JLLR', 'little-rock-mahjong-mondays-with-jllr-20261013', '2026-10-13 00:00:00', '18:00', '20:00', 'Junior League of Little Rock', (SELECT id FROM City WHERE name = 'Little Rock' AND state = 'AR'), NULL, NULL, 'OPEN_PLAY', 1, 20, 'https://members.jllr.org/', 'https://members.jllr.org/?fundraiser_id=52&nd=ticket_list&wpframe=1', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_little-rock-mahjong-mondays-with-jllr-20261110', 'Mahjong Mondays with JLLR', 'little-rock-mahjong-mondays-with-jllr-20261110', '2026-11-10 00:00:00', '18:00', '20:00', 'Junior League of Little Rock', (SELECT id FROM City WHERE name = 'Little Rock' AND state = 'AR'), NULL, NULL, 'OPEN_PLAY', 1, 20, 'https://members.jllr.org/', 'https://members.jllr.org/?fundraiser_id=52&nd=ticket_list&wpframe=1', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
