INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_fort-worth-the-mahj-clubhouse', 'The Mahj Clubhouse', 'fort-worth-the-mahj-clubhouse', 'Official site describes the business as a Fort Worth social club for American Mahjong and lists its fixed Fort Worth address.', (SELECT id FROM City WHERE name = 'Fort Worth' AND state = 'TX'), '5220 Pershing Avenue, Bldg B, Fort Worth, TX 76107', 'https://www.themahjclubhouse.com/', NULL, 'themahjclubhouse@gmail.com', NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Open play, leagues, learning series and tournaments.', 'https://www.themahjclubhouse.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_fort-worth-october-mahjong-madness-monday-6-weeks-20261012', 'October Mahjong Madness Monday - 6 Weeks', 'fort-worth-october-mahjong-madness-monday-6-weeks-20261012', '2026-10-12 00:00:00', '10:00', '12:00', 'The Mahj Clubhouse', (SELECT id FROM City WHERE name = 'Fort Worth' AND state = 'TX'), (SELECT id FROM Club WHERE slug = 'fort-worth-the-mahj-clubhouse'), NULL, 'OPEN_PLAY', 0, 140, 'https://www.themahjclubhouse.com/', 'https://www.themahjclubhouse.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_fort-worth-october-see-you-next-tuesday-mahj-nights-6-weeks-20261013', 'October See You Next Tuesday Mahj Nights - 6 Weeks', 'fort-worth-october-see-you-next-tuesday-mahj-nights-6-weeks-20261013', '2026-10-13 00:00:00', '18:00', '20:00', 'The Mahj Clubhouse', (SELECT id FROM City WHERE name = 'Fort Worth' AND state = 'TX'), (SELECT id FROM Club WHERE slug = 'fort-worth-the-mahj-clubhouse'), NULL, 'SOCIAL', 0, 140, 'https://www.themahjclubhouse.com/', 'https://www.themahjclubhouse.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_fort-worth-tournament-play-with-prizes-6-weeks-20261015', 'Tournament Play with Prizes! - 6 Weeks', 'fort-worth-tournament-play-with-prizes-6-weeks-20261015', '2026-10-15 00:00:00', '12:30', '14:30', 'The Mahj Clubhouse', (SELECT id FROM City WHERE name = 'Fort Worth' AND state = 'TX'), (SELECT id FROM Club WHERE slug = 'fort-worth-the-mahj-clubhouse'), NULL, 'TOURNAMENT', 0, 180, 'https://www.themahjclubhouse.com/', 'https://www.themahjclubhouse.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_fort-worth-open-play-at-the-sidesaddle-saloon-20261005', 'OPEN PLAY at The Sidesaddle Saloon', 'fort-worth-open-play-at-the-sidesaddle-saloon-20261005', '2026-10-05 00:00:00', NULL, NULL, 'The Sidesaddle Saloon', (SELECT id FROM City WHERE name = 'Fort Worth' AND state = 'TX'), (SELECT id FROM Club WHERE slug = 'fort-worth-the-mahj-clubhouse'), NULL, 'OPEN_PLAY', 0, 30, 'https://www.themahjclubhouse.com/', 'https://www.themahjclubhouse.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
