INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_des-moines-newcomers-compass-club-of-greater-des-moines', 'Newcomers Compass Club of Greater Des Moines', 'des-moines-newcomers-compass-club-of-greater-des-moines', 'Club''s official Cards and Games page explicitly says its American Mahjong group meets twice weekly. Membership club; confirm whether the group is open to non-members before publishing.', (SELECT id FROM City WHERE name = 'Des Moines' AND state = 'IA'), 'Des Moines, IA', 'https://newcomersdesmoines.wildapricot.org/Activities-Cards-and-Games', NULL, NULL, NULL, NULL, 0, 0, 1, 1, 0, 0, NULL, 'American Mahjong meets every Monday and Thursday at Valley Community Center.', 'https://newcomersdesmoines.wildapricot.org/Activities-Cards-and-Games', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_des-moines-juliann-cline-mahjong-mama-dsm', 'Juliann Cline / Mahjong Mama DSM', 'des-moines-juliann-cline-mahjong-mama-dsm', (SELECT id FROM City WHERE name = 'Des Moines' AND state = 'IA'), 'https://www.mahjongmamadsm.com/', NULL, 1, 1, 0, 1, NULL, 'Official site identifies Juliann as an American Mahjong teacher and offers private events, intro classes and practice play.', 'https://www.mahjongmamadsm.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_des-moines-cocktails-and-cardboard-and-mahj-20261008', 'Cocktails and Cardboard and Mahj!', 'des-moines-cocktails-and-cardboard-and-mahj-20261008', '2026-10-08 00:00:00', '18:00', '21:00', 'The New Northwestern Cocktail & Wine Bar', (SELECT id FROM City WHERE name = 'Des Moines' AND state = 'IA'), NULL, NULL, 'OPEN_PLAY', 0, NULL, 'https://eventvesta.com/events/163881/t/tickets', 'https://www.dsmpartnership.com/downtowndsmusa/experiencing-downtown/festivals-and-markets/events/event-list/cocktails-and-cardboard-and-mahj?event=91b4d198-1c42-497a-b161-17b80908b901', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_des-moines-cocktails-and-cardboard-and-mahj-20261022', 'Cocktails and Cardboard and Mahj!', 'des-moines-cocktails-and-cardboard-and-mahj-20261022', '2026-10-22 00:00:00', '18:00', '21:00', 'The New Northwestern Cocktail & Wine Bar', (SELECT id FROM City WHERE name = 'Des Moines' AND state = 'IA'), NULL, NULL, 'OPEN_PLAY', 0, NULL, 'https://eventvesta.com/events/163881/t/tickets', 'https://www.dsmpartnership.com/downtowndsmusa/experiencing-downtown/festivals-and-markets/events/event-list/cocktails-and-cardboard-and-mahj?event=91b4d198-1c42-497a-b161-17b80908b901', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_des-moines-cocktails-and-cardboard-and-mahj-20261112', 'Cocktails and Cardboard and Mahj!', 'des-moines-cocktails-and-cardboard-and-mahj-20261112', '2026-11-12 00:00:00', '18:00', '21:00', 'The New Northwestern Cocktail & Wine Bar', (SELECT id FROM City WHERE name = 'Des Moines' AND state = 'IA'), NULL, NULL, 'OPEN_PLAY', 0, NULL, 'https://eventvesta.com/events/163881/t/tickets', 'https://www.dsmpartnership.com/downtowndsmusa/experiencing-downtown/festivals-and-markets/events/event-list/cocktails-and-cardboard-and-mahj?event=91b4d198-1c42-497a-b161-17b80908b901', '2026-09-30', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
