INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_fresno-charleston-society', 'Charleston Society', 'fresno-charleston-society', 'Group page describes Charleston Society as a Fresno/Clovis Mahjong community and explicitly describes Mahjong 101 as an introduction to American Mahjong; upcoming fall 2026 sessions are listed.', (SELECT id FROM City WHERE name = 'Fresno' AND state = 'CA'), 'Fresno, CA', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Upcoming American Mahjong 101 and Guided Play sessions listed for October 2026.', 'https://charleston-society.bamgoodtime.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_fresno-american-mahjong-101-20261005', 'American Mahjong 101', 'fresno-american-mahjong-101-20261005', '2026-10-05 00:00:00', '18:00', NULL, 'Areni Wine Room - Kingsburg', (SELECT id FROM City WHERE name = 'Fresno' AND state = 'CA'), (SELECT id FROM Club WHERE slug = 'fresno-charleston-society'), NULL, 'LESSON', 1, 70, 'https://charleston-society.bamgoodtime.com/', 'https://charleston-society.bamgoodtime.com/?type=lesson', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_fresno-american-mahjong-101-20261009', 'American Mahjong 101', 'fresno-american-mahjong-101-20261009', '2026-10-09 00:00:00', '17:30', NULL, 'Three Oaks Vineyard and Winery', (SELECT id FROM City WHERE name = 'Fresno' AND state = 'CA'), (SELECT id FROM Club WHERE slug = 'fresno-charleston-society'), NULL, 'LESSON', 1, 80, 'https://charleston-society.bamgoodtime.com/', 'https://charleston-society.bamgoodtime.com/?type=lesson', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_fresno-guided-play-20261012', 'Guided Play', 'fresno-guided-play-20261012', '2026-10-12 00:00:00', '18:00', NULL, 'Out of the Barrel - Fig Garden', (SELECT id FROM City WHERE name = 'Fresno' AND state = 'CA'), (SELECT id FROM Club WHERE slug = 'fresno-charleston-society'), NULL, 'OPEN_PLAY', 1, 40, 'https://charleston-society.bamgoodtime.com/', 'https://charleston-society.bamgoodtime.com/?type=lesson', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_fresno-guided-play-20261021', 'Guided Play', 'fresno-guided-play-20261021', '2026-10-21 00:00:00', '18:00', NULL, 'Areni Wine Room - Kingsburg', (SELECT id FROM City WHERE name = 'Fresno' AND state = 'CA'), (SELECT id FROM Club WHERE slug = 'fresno-charleston-society'), NULL, 'OPEN_PLAY', 1, 40, 'https://charleston-society.bamgoodtime.com/', 'https://charleston-society.bamgoodtime.com/?type=lesson', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_fresno-american-mahjong-101-20261026', 'American Mahjong 101', 'fresno-american-mahjong-101-20261026', '2026-10-26 00:00:00', '18:00', NULL, 'Out of the Barrel - Fig Garden', (SELECT id FROM City WHERE name = 'Fresno' AND state = 'CA'), (SELECT id FROM Club WHERE slug = 'fresno-charleston-society'), NULL, 'LESSON', 1, 70, 'https://charleston-society.bamgoodtime.com/', 'https://charleston-society.bamgoodtime.com/?type=lesson', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
