INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_orlando-orlando-mah-jongg-club', 'Orlando Mah Jongg Club', 'orlando-orlando-mah-jongg-club', 'Official site describes a welcoming American Mahjong club across the Orlando area and publishes weekly games; NMJL cards are used at listed tables.', (SELECT id FROM City WHERE name = 'Orlando' AND state = 'FL'), 'Orlando, FL', 'https://mahjongflorida.com/', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Weekly games across Orlando-area venues; RSVP required.', 'https://mahjongflorida.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_orlando-mahj-away', 'Mahj & Away', 'orlando-mahj-away', 'Official site describes hosted American Mahjong events, beginner lessons and open play and explicitly identifies the game as the National Mah Jongg League version.', (SELECT id FROM City WHERE name = 'Orlando' AND state = 'FL'), 'Orlando, FL', 'https://www.mahjandaway.com/', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Public hosted events and beginner/open-play sessions in Central Florida.', 'https://www.mahjandaway.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_orlando-mahjong-night-at-mahjong-102-20261015', 'Mahjong Night at Mahjong 102', 'orlando-mahjong-night-at-mahjong-102-20261015', '2026-10-15 00:00:00', '17:30', '20:30', 'Mahjong 102, 815 N Magnolia Ave, Orlando, FL', (SELECT id FROM City WHERE name = 'Orlando' AND state = 'FL'), (SELECT id FROM Club WHERE slug = 'orlando-mahj-away'), NULL, 'SOCIAL', 1, 75, 'https://www.mahjandaway.com/events/mahjong-night-mahjong-102-winter-park', 'https://www.mahjandaway.com/events/mahjong-night-mahjong-102-winter-park', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_orlando-mahjong-night-at-ocean-prime-20261020', 'Mahjong Night at Ocean Prime', 'orlando-mahjong-night-at-ocean-prime-20261020', '2026-10-20 00:00:00', '17:30', '21:00', 'Ocean Prime, Dr Phillips, Orlando, FL', (SELECT id FROM City WHERE name = 'Orlando' AND state = 'FL'), (SELECT id FROM Club WHERE slug = 'orlando-mahj-away'), NULL, 'SOCIAL', 1, 45, 'https://www.mahjandaway.com/', 'https://www.mahjandaway.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_orlando-american-mahjong-at-beardall-senior-center-20261006', 'American Mahjong at Beardall Senior Center', 'orlando-american-mahjong-at-beardall-senior-center-20261006', '2026-10-06 00:00:00', '10:30', '16:00', 'Beardall Senior Center, 800 S Delaney Ave, Orlando, FL 32801', (SELECT id FROM City WHERE name = 'Orlando' AND state = 'FL'), NULL, NULL, 'OPEN_PLAY', 1, NULL, 'https://www.orlando.gov/Events/American-Mahjong?lang_update=639176266242806566', 'https://www.orlando.gov/Events/American-Mahjong?lang_update=639176266242806566', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_orlando-american-mahjong-at-beardall-senior-center-20261013', 'American Mahjong at Beardall Senior Center', 'orlando-american-mahjong-at-beardall-senior-center-20261013', '2026-10-13 00:00:00', '10:30', '16:00', 'Beardall Senior Center, 800 S Delaney Ave, Orlando, FL 32801', (SELECT id FROM City WHERE name = 'Orlando' AND state = 'FL'), NULL, NULL, 'OPEN_PLAY', 1, NULL, 'https://www.orlando.gov/Events/American-Mahjong?lang_update=639176266242806566', 'https://www.orlando.gov/Events/American-Mahjong?lang_update=639176266242806566', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_orlando-american-mahjong-at-beardall-senior-center-20261020', 'American Mahjong at Beardall Senior Center', 'orlando-american-mahjong-at-beardall-senior-center-20261020', '2026-10-20 00:00:00', '10:30', '16:00', 'Beardall Senior Center, 800 S Delaney Ave, Orlando, FL 32801', (SELECT id FROM City WHERE name = 'Orlando' AND state = 'FL'), NULL, NULL, 'OPEN_PLAY', 1, NULL, 'https://www.orlando.gov/Events/American-Mahjong?lang_update=639176266242806566', 'https://www.orlando.gov/Events/American-Mahjong?lang_update=639176266242806566', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_orlando-play-an-american-mahjong-game-open-play-at-swirlery-wine-bar-20261007', 'Play an American Mahjong Game (Open Play) at Swirlery Wine Bar', 'orlando-play-an-american-mahjong-game-open-play-at-swirlery-wine-bar-20261007', '2026-10-07 00:00:00', '18:00', '21:00', 'Swirlery, 1508 East Michigan Street, Orlando, FL 32806', (SELECT id FROM City WHERE name = 'Orlando' AND state = 'FL'), NULL, NULL, 'OPEN_PLAY', 0, NULL, 'https://www.eventbrite.com/e/play-an-american-mahjong-game-open-play-at-swirlery-wine-bar-tickets-2001656716121', 'https://www.eventbrite.com/e/play-an-american-mahjong-game-open-play-at-swirlery-wine-bar-tickets-2001656716121', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_orlando-introduction-to-american-mahjong-at-boston-coffee-20261005', 'Introduction to American Mahjong at Boston Coffee', 'orlando-introduction-to-american-mahjong-at-boston-coffee-20261005', '2026-10-05 00:00:00', '11:00', '14:00', 'Boston Coffee House, 851 S State Road 434 #1190, Altamonte Springs, FL 32714', (SELECT id FROM City WHERE name = 'Orlando' AND state = 'FL'), NULL, NULL, 'LESSON', 1, NULL, 'https://www.eventbrite.com/e/introduction-to-american-mahjong-tickets-2001648379185', 'https://www.eventbrite.com/e/introduction-to-american-mahjong-tickets-2001648379185', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
