INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_west-palm-beach-boca-raton-history-museum-mahjong', 'Boca Raton History Museum Mahjong', 'west-palm-beach-boca-raton-history-museum-mahjong', 'The Boca Raton Historical Society & Museum publishes fall 2026 Mahjong 101 and Open Play sessions and explicitly states that the instruction is American Mahjong.', (SELECT id FROM City WHERE name = 'West Palm Beach' AND state = 'FL'), '71 N. Federal Hwy, Boca Raton, FL 33432', 'https://bocahistory.org/mahjong-at-the-museum/', NULL, 'events@bocahistory.org', NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Fall 2026 recurring Mahjong 101, Open Play, Morning Mahjong 101 and Mahjong 102 sessions.', 'https://bocahistory.org/mahjong-at-the-museum/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_west-palm-beach-museum-mahj-morning-20261005', 'Museum Mahj Morning', 'west-palm-beach-museum-mahj-morning-20261005', '2026-10-05 00:00:00', '09:00', '11:30', 'The Schmidt Boca Raton History Museum, 71 N Federal Hwy, Boca Raton, FL 33432', (SELECT id FROM City WHERE name = 'West Palm Beach' AND state = 'FL'), (SELECT id FROM Club WHERE slug = 'west-palm-beach-boca-raton-history-museum-mahjong'), NULL, 'LESSON', 1, NULL, 'https://bocahistory.org/mahjong-at-the-museum/', 'https://bocahistory.org/mahjong-at-the-museum/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_west-palm-beach-mahjong-101-open-play-20261020', 'Mahjong 101 & Open Play', 'west-palm-beach-mahjong-101-open-play-20261020', '2026-10-20 00:00:00', '18:00', '20:30', 'The Schmidt Boca Raton History Museum, 71 N Federal Hwy, Boca Raton, FL 33432', (SELECT id FROM City WHERE name = 'West Palm Beach' AND state = 'FL'), (SELECT id FROM Club WHERE slug = 'west-palm-beach-boca-raton-history-museum-mahjong'), NULL, 'LESSON', 1, NULL, 'https://bocahistory.org/mahjong-at-the-museum/', 'https://bocahistory.org/mahjong-at-the-museum/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_west-palm-beach-mahjong-102-20261027', 'Mahjong 102', 'west-palm-beach-mahjong-102-20261027', '2026-10-27 00:00:00', '18:00', '20:30', 'The Schmidt Boca Raton History Museum, 71 N Federal Hwy, Boca Raton, FL 33432', (SELECT id FROM City WHERE name = 'West Palm Beach' AND state = 'FL'), (SELECT id FROM Club WHERE slug = 'west-palm-beach-boca-raton-history-museum-mahjong'), NULL, 'LESSON', 0, NULL, 'https://bocahistory.org/mahjong-at-the-museum/', 'https://bocahistory.org/mahjong-at-the-museum/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_west-palm-beach-museum-mahj-morning-20261109', 'Museum Mahj Morning', 'west-palm-beach-museum-mahj-morning-20261109', '2026-11-09 00:00:00', '09:00', '11:30', 'The Schmidt Boca Raton History Museum, 71 N Federal Hwy, Boca Raton, FL 33432', (SELECT id FROM City WHERE name = 'West Palm Beach' AND state = 'FL'), (SELECT id FROM Club WHERE slug = 'west-palm-beach-boca-raton-history-museum-mahjong'), NULL, 'LESSON', 1, NULL, 'https://bocahistory.org/mahjong-at-the-museum/', 'https://bocahistory.org/mahjong-at-the-museum/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_west-palm-beach-mahjong-101-open-play-20261201', 'Mahjong 101 & Open Play', 'west-palm-beach-mahjong-101-open-play-20261201', '2026-12-01 00:00:00', '18:00', '20:30', 'The Schmidt Boca Raton History Museum, 71 N Federal Hwy, Boca Raton, FL 33432', (SELECT id FROM City WHERE name = 'West Palm Beach' AND state = 'FL'), (SELECT id FROM Club WHERE slug = 'west-palm-beach-boca-raton-history-museum-mahjong'), NULL, 'LESSON', 1, NULL, 'https://bocahistory.org/mahjong-at-the-museum/', 'https://bocahistory.org/mahjong-at-the-museum/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_west-palm-beach-museum-mahj-morning-20261207', 'Museum Mahj Morning', 'west-palm-beach-museum-mahj-morning-20261207', '2026-12-07 00:00:00', '09:00', '11:30', 'The Schmidt Boca Raton History Museum, 71 N Federal Hwy, Boca Raton, FL 33432', (SELECT id FROM City WHERE name = 'West Palm Beach' AND state = 'FL'), (SELECT id FROM Club WHERE slug = 'west-palm-beach-boca-raton-history-museum-mahjong'), NULL, 'LESSON', 1, NULL, 'https://bocahistory.org/mahjong-at-the-museum/', 'https://bocahistory.org/mahjong-at-the-museum/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_west-palm-beach-museum-mahj-night-20261215', 'Museum Mahj Night', 'west-palm-beach-museum-mahj-night-20261215', '2026-12-15 00:00:00', '18:00', '20:30', 'The Schmidt Boca Raton History Museum, 71 N Federal Hwy, Boca Raton, FL 33432', (SELECT id FROM City WHERE name = 'West Palm Beach' AND state = 'FL'), (SELECT id FROM Club WHERE slug = 'west-palm-beach-boca-raton-history-museum-mahjong'), NULL, 'OPEN_PLAY', 0, NULL, 'https://bocahistory.org/mahjong-at-the-museum/', 'https://bocahistory.org/mahjong-at-the-museum/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
