INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_newark-casa-essex-mahjong', 'CASA Essex Mahjong', 'newark-casa-essex-mahjong', 'CASA Essex publishes a four-date fall series of guided open-play American Mahjong using NMJL rules; newcomers and experienced players are welcome.', (SELECT id FROM City WHERE name = 'Newark' AND state = 'NJ'), '350 University Avenue, Newark, NJ 07102', 'https://www.casaessex.org/mahjong', '(862) 754-4600', 'INFO@CASAESSEX.ORG', NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Fall series: Sep 10, Oct 8, Nov 12, Dec 3, 2026.', 'https://www.casaessex.org/mahjong', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_newark-keep-mahjing-on', 'Keep Mahjing On', 'newark-keep-mahjing-on', 'Keep Mahjing On is an American Mahjong lessons/open-play/community organizer serving New Jersey; its official site identifies American Mahjong and NMJL-based instruction.', (SELECT id FROM City WHERE name = 'Newark' AND state = 'NJ'), 'Newark, NJ', 'https://www.keepmahjingon.com/', NULL, 'hello@keepmahjingon.com', NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Public lessons, guided open play and community events throughout New Jersey.', 'https://www.keepmahjingon.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_newark-shanna-gottlieb', 'Shanna Gottlieb', 'newark-shanna-gottlieb', (SELECT id FROM City WHERE name = 'Newark' AND state = 'NJ'), 'https://www.keepmahjingon.com/', 'hello@keepmahjingon.com', 1, 1, 0, 1, NULL, 'Owner/instructor of Keep Mahjing On. Official site identifies her as teaching American Mahjong and lists public lessons, open play and community events using the NMJL card.', 'https://www.keepmahjingon.com/', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_newark-spooky-tiles-wicked-wins-20261008', 'Spooky Tiles & Wicked Wins', 'newark-spooky-tiles-wicked-wins-20261008', '2026-10-08 00:00:00', NULL, NULL, 'CASA Essex, 350 University Avenue, Newark, NJ 07102', (SELECT id FROM City WHERE name = 'Newark' AND state = 'NJ'), (SELECT id FROM Club WHERE slug = 'newark-casa-essex-mahjong'), NULL, 'SOCIAL', 1, NULL, 'https://www.casaessex.org/mahjong', 'https://www.casaessex.org/mahjong', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_newark-grateful-for-the-game-20261112', 'Grateful for the Game', 'newark-grateful-for-the-game-20261112', '2026-11-12 00:00:00', NULL, NULL, 'CASA Essex, 350 University Avenue, Newark, NJ 07102', (SELECT id FROM City WHERE name = 'Newark' AND state = 'NJ'), (SELECT id FROM Club WHERE slug = 'newark-casa-essex-mahjong'), NULL, 'SOCIAL', 1, NULL, 'https://www.casaessex.org/mahjong', 'https://www.casaessex.org/mahjong', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_newark-winter-wonderland-20261203', 'Winter Wonderland', 'newark-winter-wonderland-20261203', '2026-12-03 00:00:00', NULL, NULL, 'CASA Essex, 350 University Avenue, Newark, NJ 07102', (SELECT id FROM City WHERE name = 'Newark' AND state = 'NJ'), (SELECT id FROM Club WHERE slug = 'newark-casa-essex-mahjong'), NULL, 'SOCIAL', 1, NULL, 'https://www.casaessex.org/mahjong', 'https://www.casaessex.org/mahjong', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_newark-guided-open-play-at-java-in-montclair-20260930', 'Guided Open Play at Java in Montclair', 'newark-guided-open-play-at-java-in-montclair-20260930', '2026-09-30 00:00:00', '18:30', '20:30', 'Kung Fu Tea, 375 Bloomfield Avenue, Montclair, NJ 07043', (SELECT id FROM City WHERE name = 'Newark' AND state = 'NJ'), (SELECT id FROM Club WHERE slug = 'newark-keep-mahjing-on'), (SELECT id FROM Instructor WHERE slug = 'newark-shanna-gottlieb'), 'OPEN_PLAY', 1, NULL, 'https://www.eventbrite.com/e/guided-open-play-at-kung-fu-tea-in-montclair-tickets-2001077122541', 'https://www.keepmahjingon.com/events-admin/american-mahjong-for-beginners-series-pkt9s', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_newark-foundations-of-american-mahjong-20261015', 'Foundations of American Mahjong', 'newark-foundations-of-american-mahjong-20261015', '2026-10-15 00:00:00', '18:00', '20:30', 'The Bar Method Marlboro, Marlboro, NJ', (SELECT id FROM City WHERE name = 'Newark' AND state = 'NJ'), (SELECT id FROM Club WHERE slug = 'newark-keep-mahjing-on'), (SELECT id FROM Instructor WHERE slug = 'newark-shanna-gottlieb'), 'LESSON', 1, NULL, 'https://www.keepmahjingon.com/events', 'https://www.keepmahjingon.com/events', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_newark-mahjong-at-mojo-hoboken-20261022', 'Mahjong at Mojo Hoboken', 'newark-mahjong-at-mojo-hoboken-20261022', '2026-10-22 00:00:00', '18:30', '20:30', 'MOJO Coffee Company, Hoboken, NJ', (SELECT id FROM City WHERE name = 'Newark' AND state = 'NJ'), (SELECT id FROM Club WHERE slug = 'newark-keep-mahjing-on'), (SELECT id FROM Instructor WHERE slug = 'newark-shanna-gottlieb'), 'LESSON', 1, NULL, 'https://www.keepmahjingon.com/events', 'https://www.keepmahjingon.com/events', '2026-09-30', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
