-- City intro rewrite: varied structures (newcomer first, lead with the place,
-- learn then play), no generic closers (a sitewide line on the city page covers
-- "check the event page"), National Mah Jongg League (NMJL) spelled out on first
-- use, "American Mahjong" for the game. Facts are unchanged from earlier intros.

UPDATE "City" SET "intro" = 'In Atlanta, the same groups that teach beginners also host social play. Le Mahj Club teaches 101 and 102 beginner lessons and hosts casual open-play socials around Alpharetta, Roswell and Milton. In Buckhead, Mahj Studios is a membership club where you can take beginner lessons, try guided play and come back for socials. Several independent instructors also teach American Mahjong across the metro.' WHERE "slug" = 'atlanta';

UPDATE "City" SET "intro" = 'Want to learn first or jump into a league? Austin has both. Austin Mahjong Social offers classes, private lessons and seasonal leagues. Mahj House Austin is a studio in West Lake Hills with a beginner series, open play and social nights, and itsamahjing hosts lessons and themed pop-up events around town. Beginner-friendly options are marked on each listing.' WHERE "slug" = 'austin';

UPDATE "City" SET "intro" = 'Baltimore play is spread across the wider metro, so plan your travel. The Tiles Social Club hosts open play and lessons at cafes and other public venues. Severna Park Community Center runs a beginner MAHJ 101 course and guided open play, and Howard County Library holds a meet-up for all levels. Iris Pressman and other local teachers offer private and group lessons.' WHERE "slug" = 'baltimore';

UPDATE "City" SET "intro" = 'At the Levite Jewish Community Center in Birmingham, open play is free, and a multi-part Mahjong 101 series teaches the basics. In Mountain Brook, O''Neal Library hosts a recurring meetup that plays from the National Mah Jongg League (NMJL) card, with a beginner lesson on the first Monday. Both are set up for newcomers.' WHERE "slug" = 'birmingham';

UPDATE "City" SET "intro" = 'If you''re just starting out in Boise, look for the two-part introductory series from Mahjong at the Local. It meets at LOCAL Boise downtown and teaches from the National Mah Jongg League (NMJL) card. If you''d rather learn privately, OK LET''S MAHJONG offers private lessons, and it hosts community events too. Dates and sign-up details are on each event page.' WHERE "slug" = 'boise';

UPDATE "City" SET "intro" = 'Boston has teachers first and drop-in play second. Bay State Bam teaches and is home to the Troop Mahjong Boston/Worcester chapter, which hosts leagues, socials and open play. Mahjong Theory, South Shore Mahjong and So Bam Fun Boston also offer lessons. Once you know the basics, the Newton JCC runs a weekly drop-in for players who already know the game.' WHERE "slug" = 'boston';

UPDATE "City" SET "intro" = 'The JCC in Getzville is home base for American Mahjong around Buffalo. Through the fall, Macia Sheibley leads a weekly Learn to Play Mah Jongg course there, and the official card is included. If you''ve never played, the course is a natural place to start. Once you know the game, you can join the JCC''s Tuesday open play. Upcoming dates and sign-up details are on the JCC''s program page.' WHERE "slug" = 'buffalo';

UPDATE "City" SET "intro" = 'Charleston centers on Holy Mahj, which runs a dedicated card room on Line Street with a public beginner series, open play and leagues. Its teachers include Cara Stein, who leads an under-30 club and kids classes, along with Debbie Engel and Ashley O''Brien. Newcomers can start with the beginner series and then join open play. A Ladies Mahjong Night at the Tidewater Club is another way to play.' WHERE "slug" = 'charleston';

UPDATE "City" SET "intro" = 'Charlotte players meet in restaurants, taprooms and community venues. Sparrow Mahjong Club holds open play on Monday to Wednesday evenings in South Charlotte, with an optional monthly membership. Queen City Mahjong offers assisted open play on Wednesdays, and Charlotte Mahjong runs monthly socials and beginner lessons. In Belmont, Crown & Tile adds lessons and guided open play.' WHERE "slug" = 'charlotte';

UPDATE "City" SET "intro" = 'Chicago has two community groups that both start newcomers with an introductory class. The Mahjong Society offers 101 and 102 lessons, guided play, open play, leagues and events at rotating venues. Mahj & Mingle Social Club offers 101 lessons, guided play, open play and leagues. Guided play makes a gentle step between your first lesson and open play.' WHERE "slug" = 'chicago';

UPDATE "City" SET "intro" = 'In Cleveland, some sessions are beginner classes and others assume you know the rules, so read each event description before signing up. Southwest Cleveland Mahjong runs Mahjong 101 and open play in Brunswick. Mahjong IRL holds sessions at Flight Cleveland that pair play with a glass of wine. Bring a current National Mah Jongg League (NMJL) card, and check the venue address, since play is spread across the metro.' WHERE "slug" = 'cleveland';

UPDATE "City" SET "intro" = 'Teaching groups lead American Mahjong in Columbus. The Poppy Pair runs classes and guided play around Central Ohio, and Let''s Get Mahj''d offers Mahjong 101 and 102 classes with open play and social events. Alice S. is another local teacher. Sessions move between venues such as breweries and country clubs, so confirm whether a class or open play fits before you sign up.' WHERE "slug" = 'columbus';

UPDATE "City" SET "intro" = 'You can take a class first and join open play afterward at all three Dallas options. Dallas Mahj Club offers private and group lessons and social play. Modern Day Mahj runs beginner courses, open play and leagues. J Mahj at the Aaron Family Jewish Community Center of Dallas hosts scheduled play, theme nights, lessons and leagues.' WHERE "slug" = 'dallas';

UPDATE "City" SET "intro" = 'Denver mixes dedicated spaces with pop-up play. Mahjong Social Club has drop-in play and beginner classes, JCC Denver runs a seasonal multi-week Beginning Mahjong course, and Rocky Mountain Mahjong offers lessons plus weekly open play. Mahjong Standard hosts rotating open play at South Denver venues, but those sessions are aimed at players who know the basics, so take a class first if you''re new.' WHERE "slug" = 'denver';

UPDATE "City" SET "intro" = 'Metro Detroit has lessons and several open-play options, spread across the suburbs. Mahjong Social Club Michigan offers Mahjong 101 classes and guided play, and Westland Public Library hosts open play. Katie Wallace and Mah Jongg Mommas teach across Southeast Michigan, and Mah Jongg Mommas also offers online lessons.' WHERE "slug" = 'detroit';

UPDATE "City" SET "intro" = 'Durham gives beginners two regular places to start. North Regional Library runs a Learn to Play Mahjong session on Wednesday afternoons that welcomes newcomers and covers American Mahjong. DSSOLVR, a taproom, hosts monthly beginner lessons and guided play on the second Thursday. On the fourth Thursday, it hosts a free open play for experienced players.' WHERE "slug" = 'durham';

UPDATE "City" SET "intro" = 'Fort Lauderdale centers on Your Mahjong Mama, an instructor who describes herself as a certified American Mahjong teacher. She offers private lessons and events, including guided play and open play at Shooters Waterfront. Guided play lets you learn at the table with an instructor''s help, and open play is a relaxed way to practice afterward. Event times are posted on her profile page.' WHERE "slug" = 'fort-lauderdale';

UPDATE "City" SET "intro" = 'The Mahj Clubhouse is the center of American Mahjong in Fort Worth. It is a social club with a fixed address on Pershing Avenue and runs six-week open-play and social series, tournament play with prizes, and pop-up open play at a local saloon. Series are priced for the full run, so check what is included before you sign up. Newcomers can ask the club about its learning series.' WHERE "slug" = 'fort-worth';

UPDATE "City" SET "intro" = 'In the Fresno and Clovis area, American Mahjong comes from Charleston Society, a community group that holds American Mahjong 101 classes and guided play at wine rooms and wineries around the valley, including Kingsburg. The 101 class introduces the American game, and guided play is a good next step. Events carry a ticket price and venues change.' WHERE "slug" = 'fresno';

UPDATE "City" SET "intro" = 'Beginners in the Hartford area can learn the game at a local bookshop. River Bend Bookshop in West Hartford hosts Linda Houde''s American Mah Jongg 101 course, and you can join the shop''s regular open studio night when you''re ready to practice. A 102 intermediate course is there when you want to go further. Bring a current National Mah Jongg League (NMJL) card, since the bookshop''s event pages ask for one. Those pages also list the next course dates.' WHERE "slug" = 'hartford';

UPDATE "City" SET "intro" = 'In Houston, a free community program sits alongside competitive leagues. Houston Congregation for Reform Judaism hosts free Learn and Play sessions on Mondays plus weekday drop-in play. Houston Mahjong Club runs a National Mah Jongg League (NMJL) league and Mastering Mahjong classes. The Texas Mahjong League in Bellaire is competitive, and players are expected to know NMJL rules. Several teachers offer lessons if you want to learn first.' WHERE "slug" = 'houston';

UPDATE "City" SET "intro" = 'Central Indiana players have a dedicated center and public-library options. Fishers Mah Jongg Center offers open play and beginner lessons, and Indianapolis Central Library hosts open play and instruction sessions. Jaime Keith teaches lessons and hosts events from a studio in nearby Zionsville. Fishers and Zionsville are a short drive from downtown Indianapolis.' WHERE "slug" = 'indianapolis';

UPDATE "City" SET "intro" = 'Mahjong Social Club Jax runs American Mahjong around Jacksonville and the beaches, with Mahjong 101 classes, open play and larger events, including a benefit tournament. Events are held at cafes and restaurants, and the official site says to bring the current National Mah Jongg League (NMJL) card. Newcomers can begin with a Mahjong 101 class. Time, location and price are listed on each event page.' WHERE "slug" = 'jacksonville';

UPDATE "City" SET "intro" = 'Kansas City has a club, a beginner course and several teachers, and venues are spread across the metro. Kansas City Mahjong Club offers public lessons and guided open play at local venues. The Park Hill District Office runs a two-session beginner course using the National Mah Jongg League (NMJL) card. Lauren Sinovic, Emily Levine and Val H. also teach, some online. One teacher also plays other styles, so confirm you are booking American Mahjong.' WHERE "slug" = 'kansas-city';

UPDATE "City" SET "intro" = 'Las Vegas has a dedicated American Mahjong studio on West Sahara Avenue. Las Vegas Mahjong teaches a lesson series, Mahj 101, 102 and 103, and hosts weekday social open play. Start with Mahj 101, work up through the series and then join open play.' WHERE "slug" = 'las-vegas';

UPDATE "City" SET "intro" = 'Two Los Angeles groups combine teaching with events. Mahjong Smiles offers hosted classes, private experiences and guided play. LA LA Mahjong offers beginner classes, events and league play under National Mah Jongg League (NMJL) rules. Both also list instructors for private or group lessons, and both offer guided play, which fits well after your first class.' WHERE "slug" = 'los-angeles';

UPDATE "City" SET "intro" = 'Memphis has a church-hosted weekly game, teachers and tournaments. Emmanuel United Methodist Church hosts weekly National Mah Jongg League (NMJL) play, with beginners welcome and no church membership required. Vicki Campbell of MahJ Memphis and Pat Ford of MahJ Squad 901 teach American Mah Jongg. They also run tournaments and social events around the city.' WHERE "slug" = 'memphis';

UPDATE "City" SET "intro" = 'In Miami, most newcomers begin with Mahj in Miami, which offers beginner classes, open-play socials and private lessons. A two-session Mahj 101 is the usual first step. The Michael-Ann Russell JCC in North Miami Beach runs a weekly Mah Jongg program with a learner-only session, and Wendy Rudman teaches private and group classes around the area.' WHERE "slug" = 'miami';

UPDATE "City" SET "intro" = 'Minneapolis offers beginner classes in everyday places, from breweries and community centers to a park building around the Twin Cities. A storefront club in Edina has a four-part beginner series and open play. The Minneapolis Club hosts a weekly Tuesday Mahjong night and lesson series, and MN Mahjong holds classes at the St. Anthony Community Center. Several instructors teach American Mahjong across the metro.' WHERE "slug" = 'minneapolis';

UPDATE "City" SET "intro" = 'Nashville play is spread across public and community spaces. Groups meet at a library in Brentwood, a senior center in Franklin for ages 55 and up, and the Gordon Jewish Community Center, which holds classes. Open play happens at Fork of the South in Franklin and The Regal Room in Nolensville. The Mahjong Club in Brentwood is a dedicated space with regular open play and classes, and several instructors offer lessons.' WHERE "slug" = 'nashville';

UPDATE "City" SET "intro" = 'New Orleans has a parlor and a JCC program. Fleur de Mahj, in Metairie, offers beginner and strategy classes, guided play and tournaments under official National Mah Jongg League (NMJL) rules. The New Orleans JCC runs multi-session beginner classes at its Metairie and Uptown locations. Booking is usually required.' WHERE "slug" = 'new-orleans';

UPDATE "City" SET "intro" = 'New York listings are in Manhattan so far. Sparrow''s Nest Studio offers beginner lessons and open play, and Congregation Habonim on the Upper West Side offers beginner classes and regular open play. UES Mahjong and So Bam Fun New York provide private and group lessons. More options will be added over time.' WHERE "slug" = 'new-york';

UPDATE "City" SET "intro" = 'New Jersey listings come from a community center and a teaching organizer. CASA Essex in Newark hosts a guided open-play series under National Mah Jongg League (NMJL) rules, welcoming newcomers and experienced players. Keep Mahjing On, run by Shanna Gottlieb, offers lessons and guided open play at cafes and studios across the state, including Montclair and Hoboken.' WHERE "slug" = 'newark';

UPDATE "City" SET "intro" = 'Oklahoma City American Mahjong comes with food and drinks. Mahj & Bougie runs social play and beginner lessons at venues around the city, including a lakeside restaurant and a downtown bar. OK LET''S MAHJONG hosts lessons, a social league and special events at local restaurants and bars. Events often carry a ticket price. The lesson nights are the place for newcomers to start.' WHERE "slug" = 'oklahoma-city';

UPDATE "City" SET "intro" = 'Omaha has two clubs and a private teacher. One Bam offers beginner classes and open play at restaurants and venues around the metro, and Club Mahj offers lessons, supervised play and themed open-play events. Mahjong with Mary teaches at a central Omaha studio. Locations vary by event, so check the address.' WHERE "slug" = 'omaha';

UPDATE "City" SET "intro" = 'Orlando games are spread across the metro, and some require an RSVP. Orlando Mah Jongg Club hosts weekly games at venues around the area, and Mahj & Away runs hosted evenings and beginner lessons. The City of Orlando offers a Tuesday American Mahjong session at Beardall Senior Center. Local cafes and wine bars also host open play and introductory classes.' WHERE "slug" = 'orlando';

UPDATE "City" SET "intro" = 'Philadelphia listings are in the surrounding suburbs and community centers. Old York Road Temple-Beth Am in Abington runs Wednesday classes and open play nights, and Gems at the J meets Thursday afternoons at the Kaiserman JCC in Wynnewood. MahjWithLee has a studio in Blue Bell with Mahj 101 and 102 lessons. Independent teachers also offer private and group lessons.' WHERE "slug" = 'philadelphia';

UPDATE "City" SET "intro" = 'Phoenix has more teachers than fixed clubs. Mahj Mind, Maj by Daron, Mod Mahj (in Arcadia and Central Phoenix) and So Bam Fun Phoenix offer courses from beginner to advanced, plus supervised play. Mahjong for People who Work holds recurring Meetup games, but its games are not always American Mahjong, so confirm the style before you go.' WHERE "slug" = 'phoenix';

UPDATE "City" SET "intro" = 'Several Portland groups pair beginner classes with regular open play. Gracey Tile Club PDX runs Mahjong 101 and weekly open play, and PDX Mahjong Club and Bird Bam Beth hold public classes and open play at local venues around the metro. The Mittleman Jewish Community Center offers drop-in open play on Wednesdays and Sundays, and Eastside Jewish Commons runs a three-part beginner series.' WHERE "slug" = 'portland';

UPDATE "City" SET "intro" = 'Raleigh play happens in cafes, bars and a synagogue library. The Kitchen Table hosts open play and beginner classes, Mahj With R+M holds Monday sessions at BottleRev3, and Beth Meyer Synagogue runs a Sunday drop-in in its library where beginners are welcome. Mahj with McMillan, GatherMahj and other local teachers offer lessons for newcomers. Most groups ask you to bring a current National Mah Jongg League (NMJL) card.' WHERE "slug" = 'raleigh';

UPDATE "City" SET "intro" = 'Two organizers cover Richmond. MahjongRVA teaches American Mahjong with beginner classes and events, and newcomers can start with its basic class. The Lucky Sparrow hosts socials and open play based on National Mah Jongg League (NMJL) rules at local venues such as a brewery, a bar and the Poe Museum. Events move between venues and often carry a ticket price.' WHERE "slug" = 'richmond';

UPDATE "City" SET "intro" = 'In Sacramento, American Mah Jongg classes are taught by Sheri Graciano at the Learnery at Sierra 2 Center. The Introduction class is for beginners, and a second-level 2.0 class covers National Mah Jongg League (NMJL) rules in more depth. Classes run in the evening and on weekday afternoons, and prices are on the Learnery calendar. New sessions are added through the year.' WHERE "slug" = 'sacramento';

UPDATE "City" SET "intro" = 'The Jewish Community Center is the place to learn American Mahjong in Salt Lake City. Its Learn to Play Mahjong course teaches with the National Mah Jongg League (NMJL) card over six weeks, with a daytime session and an evening session. Pricing differs for members and the public. To ask about what comes after the course, contact the JCC.' WHERE "slug" = 'salt-lake-city';

UPDATE "City" SET "intro" = 'San Antonio has a dedicated parlor and a free library game. The Polished Tile offers Mahjong 101, 102 and 103 lessons, guided play and open play, using the National Mah Jongg League (NMJL) card. Encino Library hosts a free open play on Tuesday afternoons. A good path is Mahjong 101 at the parlor, then open play at the library.' WHERE "slug" = 'san-antonio';

UPDATE "City" SET "intro" = 'San Diego splits between classes and weekly play. Beginners American Mahjong (BAM!) runs three-lesson beginner series and follow-up guided play, mainly in Scripps Ranch. Coastal Mahjong Club meets weekly at venues along the North Coast, including Del Mar, Carmel Valley, Encinitas and La Jolla, and asks brand-new players to message ahead for an intro session. Independent teachers also offer courses.' WHERE "slug" = 'san-diego';

UPDATE "City" SET "intro" = 'San Francisco listings are still small. The Jewish Community Center of San Francisco hosts American Mahjong social play and beginner classes. Toby Salk and Mahj with Molly teach around the Bay Area, and Mahjong with Kim (who also teaches online) and So Bam Fun San Francisco offer private lessons and events.' WHERE "slug" = 'san-francisco';

UPDATE "City" SET "intro" = 'Scottsdale covers clubs, teachers and events. Phoenix Mahjong Club, despite its name, is a storefront club in Old Town Scottsdale with open play, socials, lessons and leagues. Scottsdale Mahjong Society offers open play and lessons, and North Scottsdale Mahjong Players meets at the Holland Center. Sonoran Mahjong Co. runs beginner guided open play, which suits first-timers.' WHERE "slug" = 'scottsdale';

UPDATE "City" SET "intro" = 'Seattle play is mostly community-based. The Stroum Jewish Community Center on Mercer Island runs Monday evening drop-in play, daytime free play and periodic beginner classes. The Senior Center of West Seattle hosts a Wednesday afternoon session for $1 to $2, and PNW MAHJ meets Wednesday evenings at Third Place Commons in Lake Forest Park. Hope Goldberg teaches lessons based on National Mah Jongg League (NMJL) rules for private groups.' WHERE "slug" = 'seattle';

UPDATE "City" SET "intro" = 'St. Louis has both a dedicated club and community-run events. Clover Club in Crestwood offers guided tables and open play, and Magpie Mahjong runs lessons and open-play events led by Ali Salter. Other events are held at shops and restaurants around the metro, including Saint Charles and Webster Groves. Guided play is a gentle way in if you''re new.' WHERE "slug" = 'st-louis';

UPDATE "City" SET "intro" = 'Tampa has a JCC program, a dedicated parlor and instructor-led open play. The Shanna & Bryan Glazer JCC hosts open play on Tuesdays and Wednesdays, free with JCC membership. Life Enrichment Center holds instructor-led open play on Wednesday afternoons, and South Tampa Mahjong Parlor offers open play, a weekly league and instruction. Several teachers offer beginner classes and private lessons.' WHERE "slug" = 'tampa';

UPDATE "City" SET "intro" = 'American Mahjong in Tucson centers on Tucson J, the Jewish community center. It offers a free Tuesday open play and multi-session classes under official National Mah Jongg League (NMJL) rules. The Intro to Mahj class starts new groups through the fall, and a Next Level class follows for returning players. Newcomers can take the intro class and then join Tuesday open play.' WHERE "slug" = 'tucson';

UPDATE "City" SET "intro" = 'Washington, DC has a free option. DC Drop-In Mahjongg meets Tuesday evenings at the MLK Jr. Memorial Library, with free lessons for new players (registration required). DC Mahj Collective runs open play, beginner lessons and guided play at Hill Center. Events also appear at shops, a church and the Washington National Cathedral, and several teachers offer private and group lessons.' WHERE "slug" = 'washington-dc';

UPDATE "City" SET "intro" = 'In Palm Beach County, the Boca Raton History Museum runs American Mahjong classes and open play through the fall. Morning sessions and a Mahjong 101 evening class suit beginners, and a Mahjong 102 class follows for players who know the basics. Registration details are on the museum''s page.' WHERE "slug" = 'west-palm-beach';
