INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_columbia-usc-continuing-education-mah-jongg', 'USC Continuing Education Mah Jongg', 'columbia-usc-continuing-education-mah-jongg', 'University of South Carolina four-session course taught by Twyla Stowe. Page states the course uses "National Mah Jongg League (NMJL) rules" and teaches reading the NMJL card.', (SELECT id FROM City WHERE name = 'Columbia' AND state = 'SC'), 'University of South Carolina, Columbia, SC', 'https://sc.edu/about/offices_and_divisions/continuing_education/personal_interest/personal_enrichment_and_lifestyle/mah_jong/', NULL, NULL, NULL, NULL, 1, 1, 0, 0, 0, 0, NULL, 'Oct 14-22 2026; morning 10:00-11:30 AM or afternoon 1:00-2:30 PM; 4 sessions; the page lists $115 per session (4 sessions total), unclear if that is the course total', 'https://sc.edu/about/offices_and_divisions/continuing_education/personal_interest/personal_enrichment_and_lifestyle/mah_jong/', '2026-10-05', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_columbia-soda-city-mahj', 'Soda City Mahj', 'columbia-soda-city-mahj', 'Founded by Mary Ellen Barnwell. A Columbia Museum of Art event page (May 2026) describes American Mahjong (NMJL) lessons and open play on Boyd Plaza. The club''s own page does not say American and lists no current dates.', (SELECT id FROM City WHERE name = 'Columbia' AND state = 'SC'), 'Columbia, SC', 'https://sodacitymaj.bamgoodtime.com', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'No dates currently scheduled; request lessons via website', 'https://www.columbiamuseum.org/events/mahjong-boyd-plaza-0', '2026-10-05', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_columbia-mahjong-with-alice', 'Mahjong with Alice', 'columbia-mahjong-with-alice', 'Intro classes and open play at venues such as Hotel Trundle and Pitas (Bam Good Time). American/NMJL not stated on the organizer page; directory lists it as American.', (SELECT id FROM City WHERE name = 'Columbia' AND state = 'SC'), 'Columbia, SC (venues vary)', 'https://mahjongwithalice.bamgoodtime.com', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, 35, 'Intro to Mahjong 35; open play 10-20', 'https://mahjongwithalice.bamgoodtime.com', '2026-10-05', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_columbia-open-play-at-hotel-trundle-20261008', 'Open Play at Hotel Trundle', 'columbia-open-play-at-hotel-trundle-20261008', '2026-10-08 00:00:00', '18:30', NULL, 'Hotel Trundle', (SELECT id FROM City WHERE name = 'Columbia' AND state = 'SC'), (SELECT id FROM Club WHERE slug = 'columbia-mahjong-with-alice'), NULL, 'OPEN_PLAY', 0, 20, 'https://mahjongwithalice.bamgoodtime.com', 'https://mahjongwithalice.bamgoodtime.com', '2026-10-05', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_columbia-intro-to-mahjong-20261012', 'Intro to Mahjong', 'columbia-intro-to-mahjong-20261012', '2026-10-12 00:00:00', '13:30', NULL, NULL, (SELECT id FROM City WHERE name = 'Columbia' AND state = 'SC'), (SELECT id FROM Club WHERE slug = 'columbia-mahjong-with-alice'), NULL, 'LESSON', 1, 35, 'https://mahjongwithalice.bamgoodtime.com', 'https://mahjongwithalice.bamgoodtime.com', '2026-10-05', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_columbia-intro-to-mahjong-20261016', 'Intro to Mahjong', 'columbia-intro-to-mahjong-20261016', '2026-10-16 00:00:00', '18:30', NULL, NULL, (SELECT id FROM City WHERE name = 'Columbia' AND state = 'SC'), (SELECT id FROM Club WHERE slug = 'columbia-mahjong-with-alice'), NULL, 'LESSON', 1, 35, 'https://mahjongwithalice.bamgoodtime.com', 'https://mahjongwithalice.bamgoodtime.com', '2026-10-05', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_columbia-open-play-at-pitas-20261104', 'Open Play at Pitas', 'columbia-open-play-at-pitas-20261104', '2026-11-04 00:00:00', '18:00', NULL, 'Pitas', (SELECT id FROM City WHERE name = 'Columbia' AND state = 'SC'), (SELECT id FROM Club WHERE slug = 'columbia-mahjong-with-alice'), NULL, 'OPEN_PLAY', 0, 10, 'https://mahjongwithalice.bamgoodtime.com', 'https://mahjongwithalice.bamgoodtime.com', '2026-10-05', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
