INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_cincinnati-cincy-mahjong-club', 'Cincy Mahjong Club', 'cincinnati-cincy-mahjong-club', 'Cincinnati club offering lessons for all skill levels, leagues and open play at various venues. The club''s own page does not say American/NMJL (only third-party listings do), so kept for review.', (SELECT id FROM City WHERE name = 'Cincinnati' AND state = 'OH'), 'Cincinnati, OH', 'https://mahjcincy.com/', '(513) 258-7090', 'cincymahjongclub@gmail.com', NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Fall 2026 leagues: Tuesday 5:30-8 PM at Fueled Collective (Rookwood Commons) Sept 1-Nov 3; Wednesday 5:30-8 PM at Four Bridges Country Club Sept 23-Nov 18. League fees $250 / $200; membership $150 per fall season or $500 per year.', 'https://mahjcincy.com/', '2026-10-05', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_cincinnati-mrs-mahj', 'Mrs Mahj', 'cincinnati-mrs-mahj', (SELECT id FROM City WHERE name = 'Cincinnati' AND state = 'OH'), 'https://www.themrsmahj.com/', 'Book online via website', 1, 1, 0, 1, NULL, 'Instructor''s own page: "I teach American Mahjong by National Mah Jongg League rules in Cincinnati and Northern Kentucky." Private groups and individuals; pricing not listed on page.', 'https://www.themrsmahj.com/', '2026-10-05', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_cincinnati-cincy-mahjong-club-tuesday-league-20261006', 'Cincy Mahjong Club Tuesday League', 'cincinnati-cincy-mahjong-club-tuesday-league-20261006', '2026-10-06 00:00:00', '17:30', '20:00', 'Fueled Collective, Rookwood Commons, Cincinnati, OH', (SELECT id FROM City WHERE name = 'Cincinnati' AND state = 'OH'), (SELECT id FROM Club WHERE slug = 'cincinnati-cincy-mahjong-club'), NULL, 'OTHER', 0, NULL, 'https://mahjcincy.com/', 'https://mahjcincy.com/', '2026-10-05', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_cincinnati-cincy-mahjong-club-wednesday-league-20261007', 'Cincy Mahjong Club Wednesday League', 'cincinnati-cincy-mahjong-club-wednesday-league-20261007', '2026-10-07 00:00:00', '17:30', '20:00', 'Four Bridges Country Club, Cincinnati, OH', (SELECT id FROM City WHERE name = 'Cincinnati' AND state = 'OH'), (SELECT id FROM Club WHERE slug = 'cincinnati-cincy-mahjong-club'), NULL, 'OTHER', 0, NULL, 'https://mahjcincy.com/', 'https://mahjcincy.com/', '2026-10-05', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_cincinnati-mahjong-continuation-class-at-slatt-s-bar-grill-20261006', 'Mahjong Continuation Class at Slatt''s Bar & Grill', 'cincinnati-mahjong-continuation-class-at-slatt-s-bar-grill-20261006', '2026-10-06 00:00:00', '17:00', NULL, 'Slatts Pub & Grill, 4858 Cooper Road, Cincinnati, OH 45242', (SELECT id FROM City WHERE name = 'Cincinnati' AND state = 'OH'), NULL, NULL, 'LESSON', 0, NULL, 'https://www.eventbrite.com/e/mahjong-continuation-class-at-slatts-bar-grill-tickets-1998837801672', 'https://www.eventbrite.com/e/mahjong-continuation-class-at-slatts-bar-grill-tickets-1998837801672', '2026-10-05', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
