INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_cleveland-mahjong-101-open-play-at-wild-iris-home-20261008', 'Mahjong 101 + Open Play at Wild Iris Home', 'cleveland-mahjong-101-open-play-at-wild-iris-home-20261008', '2026-10-08 00:00:00', '18:00', '20:30', 'Wild Iris Home, 36840 Detroit Road, Avon, OH 44011', (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH'), NULL, NULL, 'LESSON', 1, NULL, 'https://www.eventbrite.com/e/mahjong-101-open-play-at-wild-iris-home-tickets-1997973113366', 'https://www.eventbrite.com/e/mahjong-101-open-play-at-wild-iris-home-tickets-1997973113366', '2026-10-05', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_fort-worth-november-mahjong-learning-series-20261104', 'November Mahjong Learning Series', 'fort-worth-november-mahjong-learning-series-20261104', '2026-11-04 00:00:00', '18:00', '20:00', 'The Mahj Clubhouse, 5220 Pershing Ave, Bldg B, Fort Worth, TX 76107', (SELECT id FROM City WHERE name = 'Fort Worth' AND state = 'TX'), (SELECT id FROM Club WHERE name = 'The Mahj Clubhouse' AND cityId = (SELECT id FROM City WHERE name = 'Fort Worth' AND state = 'TX')), NULL, 'LESSON', 1, NULL, 'https://www.themahjclubhouse.com/service-page/november-mahjong-learning-series', 'https://www.themahjclubhouse.com/', '2026-10-05', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_fort-worth-january-2027-mahjong-learning-series-20270106', 'January 2027 Mahjong Learning Series', 'fort-worth-january-2027-mahjong-learning-series-20270106', '2027-01-06 00:00:00', '18:00', '20:00', 'The Mahj Clubhouse, 5220 Pershing Ave, Bldg B, Fort Worth, TX 76107', (SELECT id FROM City WHERE name = 'Fort Worth' AND state = 'TX'), (SELECT id FROM Club WHERE name = 'The Mahj Clubhouse' AND cityId = (SELECT id FROM City WHERE name = 'Fort Worth' AND state = 'TX')), NULL, 'LESSON', 1, NULL, 'https://www.themahjclubhouse.com/service-page/january-2027-mahjong-learning-series', 'https://www.themahjclubhouse.com/', '2026-10-05', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_las-vegas-social-open-play-20261009', 'Social Open Play', 'las-vegas-social-open-play-20261009', '2026-10-09 00:00:00', '09:30', NULL, 'Las Vegas Mahjong studio inside Lucky Hare, 8687 W. Sahara Ave., Suite 200, Las Vegas, NV', (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV'), (SELECT id FROM Club WHERE name = 'Las Vegas Mahjong' AND cityId = (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV')), NULL, 'OPEN_PLAY', 0, NULL, 'https://bookwhen.com/lasvegasmahjong', 'https://bookwhen.com/lasvegasmahjong', '2026-10-05', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_las-vegas-mahj-102-with-shauna-20261009', 'Mahj 102 with Shauna', 'las-vegas-mahj-102-with-shauna-20261009', '2026-10-09 00:00:00', '10:00', NULL, 'Las Vegas Mahjong studio inside Lucky Hare, 8687 W. Sahara Ave., Suite 200, Las Vegas, NV', (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV'), (SELECT id FROM Club WHERE name = 'Las Vegas Mahjong' AND cityId = (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV')), NULL, 'LESSON', 0, NULL, 'https://bookwhen.com/lasvegasmahjong', 'https://bookwhen.com/lasvegasmahjong', '2026-10-05', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_las-vegas-mahj-101-with-nicole-20261012', 'Mahj 101 with Nicole', 'las-vegas-mahj-101-with-nicole-20261012', '2026-10-12 00:00:00', '12:00', NULL, 'Las Vegas Mahjong studio inside Lucky Hare, 8687 W. Sahara Ave., Suite 200, Las Vegas, NV', (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV'), (SELECT id FROM Club WHERE name = 'Las Vegas Mahjong' AND cityId = (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV')), NULL, 'LESSON', 1, NULL, 'https://bookwhen.com/lasvegasmahjong', 'https://bookwhen.com/lasvegasmahjong', '2026-10-05', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_las-vegas-social-open-play-20261013', 'Social Open Play', 'las-vegas-social-open-play-20261013', '2026-10-13 00:00:00', '17:30', NULL, 'Las Vegas Mahjong studio inside Lucky Hare, 8687 W. Sahara Ave., Suite 200, Las Vegas, NV', (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV'), (SELECT id FROM Club WHERE name = 'Las Vegas Mahjong' AND cityId = (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV')), NULL, 'OPEN_PLAY', 0, NULL, 'https://bookwhen.com/lasvegasmahjong', 'https://bookwhen.com/lasvegasmahjong', '2026-10-05', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_las-vegas-mahj-103-with-shauna-20261013', 'Mahj 103 with Shauna', 'las-vegas-mahj-103-with-shauna-20261013', '2026-10-13 00:00:00', '18:00', NULL, 'Las Vegas Mahjong studio inside Lucky Hare, 8687 W. Sahara Ave., Suite 200, Las Vegas, NV', (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV'), (SELECT id FROM Club WHERE name = 'Las Vegas Mahjong' AND cityId = (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV')), NULL, 'LESSON', 0, NULL, 'https://bookwhen.com/lasvegasmahjong', 'https://bookwhen.com/lasvegasmahjong', '2026-10-05', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_las-vegas-social-open-play-20261014', 'Social Open Play', 'las-vegas-social-open-play-20261014', '2026-10-14 00:00:00', '09:00', NULL, 'Las Vegas Mahjong studio inside Lucky Hare, 8687 W. Sahara Ave., Suite 200, Las Vegas, NV', (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV'), (SELECT id FROM Club WHERE name = 'Las Vegas Mahjong' AND cityId = (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV')), NULL, 'OPEN_PLAY', 0, NULL, 'https://bookwhen.com/lasvegasmahjong', 'https://bookwhen.com/lasvegasmahjong', '2026-10-05', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_las-vegas-mahj-102-with-shauna-20261014', 'Mahj 102 with Shauna', 'las-vegas-mahj-102-with-shauna-20261014', '2026-10-14 00:00:00', '09:30', NULL, 'Las Vegas Mahjong studio inside Lucky Hare, 8687 W. Sahara Ave., Suite 200, Las Vegas, NV', (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV'), (SELECT id FROM Club WHERE name = 'Las Vegas Mahjong' AND cityId = (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV')), NULL, 'LESSON', 0, NULL, 'https://bookwhen.com/lasvegasmahjong', 'https://bookwhen.com/lasvegasmahjong', '2026-10-05', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_las-vegas-social-open-play-20261015', 'Social Open Play', 'las-vegas-social-open-play-20261015', '2026-10-15 00:00:00', '18:30', NULL, 'Las Vegas Mahjong studio inside Lucky Hare, 8687 W. Sahara Ave., Suite 200, Las Vegas, NV', (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV'), (SELECT id FROM Club WHERE name = 'Las Vegas Mahjong' AND cityId = (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV')), NULL, 'OPEN_PLAY', 0, NULL, 'https://bookwhen.com/lasvegasmahjong', 'https://bookwhen.com/lasvegasmahjong', '2026-10-05', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_las-vegas-mahj-102-with-nicole-20261019', 'Mahj 102 with Nicole', 'las-vegas-mahj-102-with-nicole-20261019', '2026-10-19 00:00:00', '12:00', NULL, 'Las Vegas Mahjong studio inside Lucky Hare, 8687 W. Sahara Ave., Suite 200, Las Vegas, NV', (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV'), (SELECT id FROM Club WHERE name = 'Las Vegas Mahjong' AND cityId = (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV')), NULL, 'LESSON', 0, NULL, 'https://bookwhen.com/lasvegasmahjong', 'https://bookwhen.com/lasvegasmahjong', '2026-10-05', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_las-vegas-social-open-play-20261021', 'Social Open Play', 'las-vegas-social-open-play-20261021', '2026-10-21 00:00:00', '09:00', NULL, 'Las Vegas Mahjong studio inside Lucky Hare, 8687 W. Sahara Ave., Suite 200, Las Vegas, NV', (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV'), (SELECT id FROM Club WHERE name = 'Las Vegas Mahjong' AND cityId = (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV')), NULL, 'OPEN_PLAY', 0, NULL, 'https://bookwhen.com/lasvegasmahjong', 'https://bookwhen.com/lasvegasmahjong', '2026-10-05', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_las-vegas-mahj-103-with-shauna-20261021', 'Mahj 103 with Shauna', 'las-vegas-mahj-103-with-shauna-20261021', '2026-10-21 00:00:00', '09:30', NULL, 'Las Vegas Mahjong studio inside Lucky Hare, 8687 W. Sahara Ave., Suite 200, Las Vegas, NV', (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV'), (SELECT id FROM Club WHERE name = 'Las Vegas Mahjong' AND cityId = (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV')), NULL, 'LESSON', 0, NULL, 'https://bookwhen.com/lasvegasmahjong', 'https://bookwhen.com/lasvegasmahjong', '2026-10-05', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_las-vegas-social-open-play-20261023', 'Social Open Play', 'las-vegas-social-open-play-20261023', '2026-10-23 00:00:00', '09:30', NULL, 'Las Vegas Mahjong studio inside Lucky Hare, 8687 W. Sahara Ave., Suite 200, Las Vegas, NV', (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV'), (SELECT id FROM Club WHERE name = 'Las Vegas Mahjong' AND cityId = (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV')), NULL, 'OPEN_PLAY', 0, NULL, 'https://bookwhen.com/lasvegasmahjong', 'https://bookwhen.com/lasvegasmahjong', '2026-10-05', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_las-vegas-mahj-103-with-shauna-20261023', 'Mahj 103 with Shauna', 'las-vegas-mahj-103-with-shauna-20261023', '2026-10-23 00:00:00', '10:00', NULL, 'Las Vegas Mahjong studio inside Lucky Hare, 8687 W. Sahara Ave., Suite 200, Las Vegas, NV', (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV'), (SELECT id FROM Club WHERE name = 'Las Vegas Mahjong' AND cityId = (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV')), NULL, 'LESSON', 0, NULL, 'https://bookwhen.com/lasvegasmahjong', 'https://bookwhen.com/lasvegasmahjong', '2026-10-05', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_las-vegas-mahj-103-with-nicole-20261026', 'Mahj 103 with Nicole', 'las-vegas-mahj-103-with-nicole-20261026', '2026-10-26 00:00:00', '12:00', NULL, 'Las Vegas Mahjong studio inside Lucky Hare, 8687 W. Sahara Ave., Suite 200, Las Vegas, NV', (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV'), (SELECT id FROM Club WHERE name = 'Las Vegas Mahjong' AND cityId = (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV')), NULL, 'LESSON', 0, NULL, 'https://bookwhen.com/lasvegasmahjong', 'https://bookwhen.com/lasvegasmahjong', '2026-10-05', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_las-vegas-social-open-play-20261029', 'Social Open Play', 'las-vegas-social-open-play-20261029', '2026-10-29 00:00:00', '10:00', NULL, 'Las Vegas Mahjong studio inside Lucky Hare, 8687 W. Sahara Ave., Suite 200, Las Vegas, NV', (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV'), (SELECT id FROM Club WHERE name = 'Las Vegas Mahjong' AND cityId = (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV')), NULL, 'OPEN_PLAY', 0, NULL, 'https://bookwhen.com/lasvegasmahjong', 'https://bookwhen.com/lasvegasmahjong', '2026-10-05', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_las-vegas-halloween-open-play-fun-with-your-boo-or-bestie-20261030', 'Halloween Open Play Fun With Your Boo (or Bestie)!', 'las-vegas-halloween-open-play-fun-with-your-boo-or-bestie-20261030', '2026-10-30 00:00:00', '18:00', NULL, 'Las Vegas Mahjong studio inside Lucky Hare, 8687 W. Sahara Ave., Suite 200, Las Vegas, NV', (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV'), (SELECT id FROM Club WHERE name = 'Las Vegas Mahjong' AND cityId = (SELECT id FROM City WHERE name = 'Las Vegas' AND state = 'NV')), NULL, 'SOCIAL', 0, NULL, 'https://bookwhen.com/lasvegasmahjong', 'https://bookwhen.com/lasvegasmahjong', '2026-10-05', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
