INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_cleveland-cle-urban-winery-open-play-20261006', 'CLE Urban Winery Open Play', 'cleveland-cle-urban-winery-open-play-20261006', '2026-10-06 00:00:00', '18:00', '20:00', 'CLE Urban Winery, 2180 Lee Road, Cleveland Heights, OH', (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH'), NULL, NULL, 'OPEN_PLAY', 0, NULL, 'https://www.eventbrite.com/e/cle-urban-winery-open-play-winery-tickets-2002521011251', 'https://www.eventbrite.com/e/cle-urban-winery-open-play-winery-tickets-2002521011251', '2026-10-05', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_jacksonville-mahjong-101-trattoria-di-bernardone-20261007', 'Mahjong 101 @ Trattoria Di Bernardone', 'jacksonville-mahjong-101-trattoria-di-bernardone-20261007', '2026-10-07 00:00:00', NULL, NULL, 'Trattoria Di Bernardone, Jacksonville, FL', (SELECT id FROM City WHERE name = 'Jacksonville' AND state = 'FL'), (SELECT id FROM Club WHERE name = 'Mahjong Social Club Jax' AND cityId = (SELECT id FROM City WHERE name = 'Jacksonville' AND state = 'FL')), NULL, 'LESSON', 1, NULL, 'https://www.mahjongsocialclubjax.com/', 'https://www.mahjongsocialclubjax.com/', '2026-10-05', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_jacksonville-mahjong-101-trattoria-di-bernardone-20261021', 'Mahjong 101 @ Trattoria Di Bernardone', 'jacksonville-mahjong-101-trattoria-di-bernardone-20261021', '2026-10-21 00:00:00', NULL, NULL, 'Trattoria Di Bernardone, Jacksonville, FL', (SELECT id FROM City WHERE name = 'Jacksonville' AND state = 'FL'), (SELECT id FROM Club WHERE name = 'Mahjong Social Club Jax' AND cityId = (SELECT id FROM City WHERE name = 'Jacksonville' AND state = 'FL')), NULL, 'LESSON', 1, NULL, 'https://www.mahjongsocialclubjax.com/', 'https://www.mahjongsocialclubjax.com/', '2026-10-05', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_jacksonville-mahjong-102-trattoria-di-bernardone-20261014', 'Mahjong 102 @ Trattoria Di Bernardone', 'jacksonville-mahjong-102-trattoria-di-bernardone-20261014', '2026-10-14 00:00:00', NULL, NULL, 'Trattoria Di Bernardone, Jacksonville, FL', (SELECT id FROM City WHERE name = 'Jacksonville' AND state = 'FL'), (SELECT id FROM Club WHERE name = 'Mahjong Social Club Jax' AND cityId = (SELECT id FROM City WHERE name = 'Jacksonville' AND state = 'FL')), NULL, 'LESSON', 0, NULL, 'https://www.mahjongsocialclubjax.com/', 'https://www.mahjongsocialclubjax.com/', '2026-10-05', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_jacksonville-open-play-trattoria-di-bernardone-20261015', 'Open Play @ Trattoria Di Bernardone', 'jacksonville-open-play-trattoria-di-bernardone-20261015', '2026-10-15 00:00:00', NULL, NULL, 'Trattoria Di Bernardone, Jacksonville, FL', (SELECT id FROM City WHERE name = 'Jacksonville' AND state = 'FL'), (SELECT id FROM Club WHERE name = 'Mahjong Social Club Jax' AND cityId = (SELECT id FROM City WHERE name = 'Jacksonville' AND state = 'FL')), NULL, 'OPEN_PLAY', 0, NULL, 'https://www.mahjongsocialclubjax.com/', 'https://www.mahjongsocialclubjax.com/', '2026-10-05', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_jacksonville-open-play-trattoria-di-bernardone-20261104', 'Open Play @ Trattoria Di Bernardone', 'jacksonville-open-play-trattoria-di-bernardone-20261104', '2026-11-04 00:00:00', NULL, NULL, 'Trattoria Di Bernardone, Jacksonville, FL', (SELECT id FROM City WHERE name = 'Jacksonville' AND state = 'FL'), (SELECT id FROM Club WHERE name = 'Mahjong Social Club Jax' AND cityId = (SELECT id FROM City WHERE name = 'Jacksonville' AND state = 'FL')), NULL, 'OPEN_PLAY', 0, NULL, 'https://www.mahjongsocialclubjax.com/', 'https://www.mahjongsocialclubjax.com/', '2026-10-05', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_tucson-next-level-mahj-starts-dec-7-20261207', 'Next Level Mahj – starts Dec 7', 'tucson-next-level-mahj-starts-dec-7-20261207', '2026-12-07 00:00:00', '09:00', '11:00', 'Tucson J, 3800 E. River Road, Tucson, AZ', (SELECT id FROM City WHERE name = 'Tucson' AND state = 'AZ'), (SELECT id FROM Club WHERE name = 'Tucson J Mah Jongg' AND cityId = (SELECT id FROM City WHERE name = 'Tucson' AND state = 'AZ')), NULL, 'LESSON', 0, NULL, 'https://operations.daxko.com/Online/5078/ProgramsV2/OfferingDetails.mvc?program_id=TMP48362&offering_id=SES1522953&location_id=B330', 'https://tucsonjcc.org/programs-events/clubs-groups-games/', '2026-10-05', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
