INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_fort-lauderdale-mahjong-with-besties-bams-20261006', 'Mahjong with Besties & Bams', 'fort-lauderdale-mahjong-with-besties-bams-20261006', '2026-10-06 00:00:00', '19:00', '22:00', 'Sunness Supper Club, 2465 E Sunrise Blvd, Fort Lauderdale, FL', (SELECT id FROM City WHERE name = 'Fort Lauderdale' AND state = 'FL'), NULL, NULL, 'SOCIAL', 1, NULL, 'https://www.sunnesssupperclub.com/events', 'https://www.sunnesssupperclub.com/events', '2026-10-05', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_fort-lauderdale-mahjong-with-besties-bams-20261020', 'Mahjong with Besties & Bams', 'fort-lauderdale-mahjong-with-besties-bams-20261020', '2026-10-20 00:00:00', '19:00', '22:00', 'Sunness Supper Club, 2465 E Sunrise Blvd, Fort Lauderdale, FL', (SELECT id FROM City WHERE name = 'Fort Lauderdale' AND state = 'FL'), NULL, NULL, 'SOCIAL', 1, NULL, 'https://www.sunnesssupperclub.com/events', 'https://www.sunnesssupperclub.com/events', '2026-10-05', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_fort-lauderdale-mahjong-mingle-20261015', 'Mahjong & Mingle', 'fort-lauderdale-mahjong-mingle-20261015', '2026-10-15 00:00:00', '18:00', '20:30', 'The Ritz-Carlton Fort Lauderdale, 1 N Fort Lauderdale Beach Blvd, Fort Lauderdale, FL', (SELECT id FROM City WHERE name = 'Fort Lauderdale' AND state = 'FL'), NULL, NULL, 'LESSON', 1, NULL, 'https://event.marriott.com/fllrz-the-ritz-carlton-fort-lauderdale/events/fort-lauderdale/mahjong-mingle-12532704', 'https://event.marriott.com/fllrz-the-ritz-carlton-fort-lauderdale/events/fort-lauderdale/mahjong-mingle-12532704', '2026-10-05', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_jacksonville-open-play-gaa-cafe-20261009', 'Open Play @ Gaa Cafe', 'jacksonville-open-play-gaa-cafe-20261009', '2026-10-09 00:00:00', '18:00', '20:30', 'Gaa Cafe, 9865 Baymeadows Rd #10, Jacksonville, FL 32256', (SELECT id FROM City WHERE name = 'Jacksonville' AND state = 'FL'), (SELECT id FROM Club WHERE name = 'Mahjong Social Club Jax' AND cityId = (SELECT id FROM City WHERE name = 'Jacksonville' AND state = 'FL')), NULL, 'OPEN_PLAY', 0, 23.3, 'https://www.mahjongsocialclubjax.com/mahjongevents', 'https://www.mahjongsocialclubjax.com/mahjongevents', '2026-10-05', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_jacksonville-open-play-gaa-cafe-20261120', 'Open Play @ Gaa Cafe', 'jacksonville-open-play-gaa-cafe-20261120', '2026-11-20 00:00:00', '18:00', '20:30', 'Gaa Cafe, 9865 Baymeadows Rd #10, Jacksonville, FL 32256', (SELECT id FROM City WHERE name = 'Jacksonville' AND state = 'FL'), (SELECT id FROM Club WHERE name = 'Mahjong Social Club Jax' AND cityId = (SELECT id FROM City WHERE name = 'Jacksonville' AND state = 'FL')), NULL, 'OPEN_PLAY', 0, 23.3, 'https://www.mahjongsocialclubjax.com/mahjongevents', 'https://www.mahjongsocialclubjax.com/mahjongevents', '2026-10-05', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
