INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_naples-mahjong-cafe', 'Mahjong Cafe', 'naples-mahjong-cafe', 'Pop-up American Mahjong events at Golden Grove Kitchen (also Marco Island Brewery on Mondays). Own site: ''learn the fundamentals of American Mahjong in a relaxed, step-by-step class''; NMJL not named explicitly. Advance tickets required.', (SELECT id FROM City WHERE name = 'Naples' AND state = 'FL'), 'Golden Grove Kitchen, 12035 Collier Blvd, Naples, FL 34116', 'https://www.mahjongcafe.com/', '(239) 206-0010', NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Tuesdays 9AM-12PM beginner instruction + breakfast; 1PM-4PM lunch & social play; evening play 6-9PM starting October (Mondays/Tuesdays); tickets via Ticket Tailor', 'https://www.mahjongcafe.com/mahjong-naples-fl', '2026-10-07', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_naples-naples-ladies-mah-jongg-american-version', 'Naples Ladies Mah Jongg (American Version)', 'naples-naples-ladies-mah-jongg-american-version', 'Meetup group; own page says it is for players who ''d like to learn how to play American Mah Jongg or who are already versed in the game''. Beginner to advanced. $1 per person fee plus quarters. Hosted by a group member; exact location is given to registered players; in-season group.', (SELECT id FROM City WHERE name = 'Naples' AND state = 'FL'), 'Naples, FL', 'https://www.meetup.com/naples-mahjong-meetup-group/', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Tuesday and Thursday evenings (in season); reserve spot via Meetup', 'https://www.meetup.com/naples-mahjong-meetup-group/', '2026-10-07', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_naples-naples-mahjong', 'Naples Mahjong', 'naples-naples-mahjong', 'Three local moms offering mahjong lessons for all levels and open play at local businesses; Eventbrite ticketing. Organizer''s own page does not state American/NMJL (directory and Eventbrite listing snippets say American Mahjong) - needs confirmation.', (SELECT id FROM City WHERE name = 'Naples' AND state = 'FL'), 'Naples, FL', 'https://www.naplesmahjong.com/', NULL, 'naplesmahjong@gmail.com', NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Events at various Naples venues; lessons up to $60 per Gulfshore Life', 'https://www.naplesmahjong.com/', '2026-10-07', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_naples-swfl-mahjong', 'SWFL Mahjong', 'naples-swfl-mahjong', 'Directory listings (BamBuddies; Gulfshore Life) say private and group lessons strictly by NMJL rules; games at Cheddar''s Scratch Kitchen Naples. Own site swflmahjong.com now redirects to a page that returned 404 - not verified by organizer.', (SELECT id FROM City WHERE name = 'Naples' AND state = 'FL'), 'Cheddar''s Scratch Kitchen, 10940 Tamiami Trail N, Naples, FL', 'https://www.swflmahjong.com/', NULL, 'swflmahjong@gmail.com', NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Group workshops about 2 hours; games at Naples venues - schedule unconfirmed', 'https://bamgoodtime.com/mahjong-clubs/naples-fl', '2026-10-07', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_naples-east-naples-community-park-mah-jongg', 'East Naples Community Park Mah Jongg', 'naples-east-naples-community-park-mah-jongg', 'ENCP Mah Jongg evening play listed on ACTIVE.com (Oct 6 - Dec 29 2026). $10 yearly membership; players must already know how to play; no lessons. Mah jongg variant not stated.', (SELECT id FROM City WHERE name = 'Naples' AND state = 'FL'), 'East Naples Community Park, 3500 Thomasson Dr, Naples, FL 34112', 'https://www.active.com/naples-fl/mah-jong/classes/encp-mah-jongg-2026', NULL, NULL, NULL, NULL, 0, 0, 1, 1, 0, 0, 10, 'Evening play Oct 6 - Dec 29 2026 (day/time not confirmed); daytime session Jan 5 - May 20 2026 earlier; $10 yearly membership', 'https://www.active.com/naples-fl/mah-jong/classes/encp-mah-jongg-2026', '2026-10-07', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_naples-paradise-coast-mahjong', 'Paradise Coast Mahjong', 'naples-paradise-coast-mahjong', 'Boutique/club listed as opening October 2026 with classes beginner to advanced; waitlist only. Page does not state American/NMJL; no dates yet.', (SELECT id FROM City WHERE name = 'Naples' AND state = 'FL'), 'Naples, FL', 'https://www.paradisecoastmahjong.com', '(239) 496-5889', 'hello@paradisecoastmahjong.com', NULL, NULL, 1, 1, 0, 1, 0, 0, NULL, 'Opening October 2026 (date TBD)', 'https://www.paradisecoastmahjong.com', '2026-10-07', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_naples-mahj-at-mercato-20261013', 'Mahj at Mercato', 'naples-mahj-at-mercato-20261013', '2026-10-13 00:00:00', '18:00', NULL, 'Mercato', (SELECT id FROM City WHERE name = 'Naples' AND state = 'FL'), (SELECT id FROM Club WHERE slug = 'naples-naples-mahjong'), NULL, 'OTHER', 1, NULL, 'https://www.naplesmahjong.com/', 'https://www.naplesmahjong.com/', '2026-10-07', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_naples-morning-mahjong-at-k-a-coastal-design-20261015', 'Morning Mahjong at K&A Coastal Design', 'naples-morning-mahjong-at-k-a-coastal-design-20261015', '2026-10-15 00:00:00', '09:30', NULL, 'K&A Coastal Design', (SELECT id FROM City WHERE name = 'Naples' AND state = 'FL'), (SELECT id FROM Club WHERE slug = 'naples-naples-mahjong'), NULL, 'OTHER', 1, NULL, 'https://www.naplesmahjong.com/', 'https://www.naplesmahjong.com/', '2026-10-07', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_naples-mahjong-open-play-at-pjk-naples-20261019', 'Mahjong Open Play at PJK Naples', 'naples-mahjong-open-play-at-pjk-naples-20261019', '2026-10-19 00:00:00', '12:00', NULL, 'PJK Neighborhood Chinese Restaurant', (SELECT id FROM City WHERE name = 'Naples' AND state = 'FL'), (SELECT id FROM Club WHERE slug = 'naples-naples-mahjong'), NULL, 'OPEN_PLAY', 1, NULL, 'https://www.naplesmahjong.com/', 'https://www.naplesmahjong.com/', '2026-10-07', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_naples-bams-boos-on-the-bay-20261025', 'Bams & Boos on the Bay', 'naples-bams-boos-on-the-bay-20261025', '2026-10-25 00:00:00', '11:00', '13:30', 'Bayside Seafood Grill & Bar', (SELECT id FROM City WHERE name = 'Naples' AND state = 'FL'), (SELECT id FROM Club WHERE slug = 'naples-naples-mahjong'), NULL, 'SOCIAL', 1, NULL, 'https://www.eventbrite.com/e/bams-boos-on-the-bay-at-bayside-tickets-1998783621618', 'https://www.eventbrite.com/e/bams-boos-on-the-bay-at-bayside-tickets-1998783621618', '2026-10-07', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
