INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_sarasota-temple-beth-sholom-mah-jongg', 'Temple Beth Sholom Mah Jongg', 'sarasota-temple-beth-sholom-mah-jongg', 'Weekly Tuesday mah jongg at Temple Beth Sholom; beginners welcome. $3 members / $5 non-members, cash. Page does not state American/NMJL.', (SELECT id FROM City WHERE name = 'Sarasota' AND state = 'FL'), 'Temple Beth Sholom, 1050 S Tuttle Ave, Sarasota, FL 34237', 'https://jfedsrq.org/event/mah-jongg-at-temple-beth-sholom/2027-01-26/', '941-955-8121', 'info@tbssrq.org', NULL, NULL, 1, 0, 1, 1, 0, 0, 5, 'Every Tuesday 12:30-3:30 PM (non-member price shown)', 'https://jfedsrq.org/event/mah-jongg-at-temple-beth-sholom/2027-01-26/', '2026-10-07', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_sarasota-jewish-federation-of-sarasota-manatee-mah-jongg-open-play', 'Jewish Federation of Sarasota-Manatee Mah Jongg Open Play', 'sarasota-jewish-federation-of-sarasota-manatee-mah-jongg-open-play', 'Wednesday open play for experienced players at the Ritter Wolk Hub; $5/person benefits the Federation. Page does not state American/NMJL.', (SELECT id FROM City WHERE name = 'Sarasota' AND state = 'FL'), 'Greenspon Campus for Jewish Life, 602 McIntosh Rd, Sarasota, FL', 'https://jfedsrq.org/resources/community-calendar/', NULL, NULL, NULL, NULL, 0, 0, 1, 1, 0, 0, 5, 'Wednesdays 1-4 PM', 'https://jfedsrq.org/resources/community-calendar/', '2026-10-07', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_sarasota-selby-library-mah-jongg-for-experienced-players', 'Selby Library Mah Jongg for Experienced Players', 'sarasota-selby-library-mah-jongg-for-experienced-players', 'Sarasota County library group for experienced players; listing says ''bring your own NMJL card''. Only a 2024 listing was seen (Wednesdays through June 26 2024); current schedule unconfirmed.', (SELECT id FROM City WHERE name = 'Sarasota' AND state = 'FL'), 'Selby Library, 1331 First St, Sarasota, FL 34236', 'https://scgovlibrary.librarymarket.com/event/mah-jongg-experienced-players-225599', '(941) 861-1110', NULL, NULL, NULL, 0, 0, 1, 1, 0, 1, NULL, 'Wednesdays 1:00-3:30 PM per 2024 listing; current status unknown', 'https://scgovlibrary.librarymarket.com/event/mah-jongg-experienced-players-225599', '2026-10-07', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_sarasota-sarasota-mahjong-club', 'Sarasota Mahjong Club', 'sarasota-sarasota-mahjong-club', 'Club founded by Emily Wilson (about 850 members per SRQ Magazine, Sept 2026); weekly lessons and drop-in games. American/NMJL not stated in the article.', (SELECT id FROM City WHERE name = 'Sarasota' AND state = 'FL'), 'Sarasota, FL', 'https://www.srqmagazine.com/articles/2424/Playing%20for%20Connection', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Weekly lessons and drop-in games; venues unconfirmed', 'https://www.srqmagazine.com/articles/2424/Playing%20for%20Connection', '2026-10-07', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_sarasota-iris-pressman-hi-mahj', 'Iris Pressman (Hi Mahj)', 'sarasota-iris-pressman-hi-mahj', (SELECT id FROM City WHERE name = 'Sarasota' AND state = 'FL'), 'https://www.himahj.com', NULL, 1, 1, 1, 1, NULL, 'Directory (Mahjong 4 Friends / search listing) says teaches American Mah Jongg per National Mah Jongg League rules and is certified by The School of American Mah Jongg; himahj.com homepage wording not confirmed. Contact via website.', 'https://mahjong4friends.com/teachers/fl', '2026-10-07', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_sarasota-ursula-jones-stc-sarasota', 'Ursula Jones (STC Sarasota)', 'sarasota-ursula-jones-stc-sarasota', (SELECT id FROM City WHERE name = 'Sarasota' AND state = 'FL'), 'https://www.campusce.net/acesarasota/course/course.aspx?C=143', '941-361-6590', 0, 1, 0, 1, NULL, 'Teaches Mah Jongg Beginning and Mah Jongg II at STC Sarasota (4748 Beneva Rd); beginning class $175 per course and includes a card. Course page does not state American/NMJL. Contact is the school office.', 'https://www.campusce.net/acesarasota/course/course.aspx?C=143', '2026-10-07', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_sarasota-karen-kent', 'Karen Kent', 'sarasota-karen-kent', (SELECT id FROM City WHERE name = 'Sarasota' AND state = 'FL'), NULL, NULL, 0, 1, 0, 1, NULL, 'Directory listing only: certified teacher; small groups 4 weeks / 2 hours each. American/NMJL not verified; no website or public contact.', 'https://bamgoodtime.com/mahjong-clubs/sarasota-fl', '2026-10-07', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_sarasota-mah-jongg-at-temple-beth-sholom-20261013', 'Mah Jongg at Temple Beth Sholom', 'sarasota-mah-jongg-at-temple-beth-sholom-20261013', '2026-10-13 00:00:00', '12:30', '15:30', 'Temple Beth Sholom', (SELECT id FROM City WHERE name = 'Sarasota' AND state = 'FL'), (SELECT id FROM Club WHERE slug = 'sarasota-temple-beth-sholom-mah-jongg'), NULL, 'OPEN_PLAY', 1, 5, 'https://jfedsrq.org/resources/community-calendar/', 'https://jfedsrq.org/resources/community-calendar/', '2026-10-07', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_sarasota-mah-jongg-at-temple-beth-sholom-20261020', 'Mah Jongg at Temple Beth Sholom', 'sarasota-mah-jongg-at-temple-beth-sholom-20261020', '2026-10-20 00:00:00', '12:30', '15:30', 'Temple Beth Sholom', (SELECT id FROM City WHERE name = 'Sarasota' AND state = 'FL'), (SELECT id FROM Club WHERE slug = 'sarasota-temple-beth-sholom-mah-jongg'), NULL, 'OPEN_PLAY', 1, 5, 'https://jfedsrq.org/resources/community-calendar/', 'https://jfedsrq.org/resources/community-calendar/', '2026-10-07', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_sarasota-mah-jongg-open-play-at-ritter-wolk-hub-20261014', 'Mah Jongg Open Play at Ritter Wolk Hub', 'sarasota-mah-jongg-open-play-at-ritter-wolk-hub-20261014', '2026-10-14 00:00:00', '13:00', '16:00', 'Ritter Wolk Hub - Greenspon Campus for Jewish Life', (SELECT id FROM City WHERE name = 'Sarasota' AND state = 'FL'), (SELECT id FROM Club WHERE slug = 'sarasota-jewish-federation-of-sarasota-manatee-mah-jongg-open-play'), NULL, 'OPEN_PLAY', 0, 5, 'https://jfedsrq.org/resources/community-calendar/', 'https://jfedsrq.org/resources/community-calendar/', '2026-10-07', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_sarasota-mah-jongg-open-play-at-ritter-wolk-hub-20261021', 'Mah Jongg Open Play at Ritter Wolk Hub', 'sarasota-mah-jongg-open-play-at-ritter-wolk-hub-20261021', '2026-10-21 00:00:00', '13:00', '16:00', 'Ritter Wolk Hub - Greenspon Campus for Jewish Life', (SELECT id FROM City WHERE name = 'Sarasota' AND state = 'FL'), (SELECT id FROM Club WHERE slug = 'sarasota-jewish-federation-of-sarasota-manatee-mah-jongg-open-play'), NULL, 'OPEN_PLAY', 0, 5, 'https://jfedsrq.org/resources/community-calendar/', 'https://jfedsrq.org/resources/community-calendar/', '2026-10-07', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_sarasota-mah-jongg-beginning-6-weeks-monday-section-20261109', 'Mah Jongg Beginning (6 weeks) - Monday section', 'sarasota-mah-jongg-beginning-6-weeks-monday-section-20261109', '2026-11-09 00:00:00', '10:00', '12:30', 'STC Sarasota Building 3 Room 3-203', (SELECT id FROM City WHERE name = 'Sarasota' AND state = 'FL'), NULL, (SELECT id FROM Instructor WHERE slug = 'sarasota-ursula-jones-stc-sarasota'), 'LESSON', 1, NULL, 'https://www.campusce.net/acesarasota/course/course.aspx?C=143', 'https://www.campusce.net/acesarasota/course/course.aspx?C=143', '2026-10-07', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_sarasota-mah-jongg-beginning-6-weeks-tuesday-section-20261110', 'Mah Jongg Beginning (6 weeks) - Tuesday section', 'sarasota-mah-jongg-beginning-6-weeks-tuesday-section-20261110', '2026-11-10 00:00:00', '10:00', '12:30', 'STC Sarasota Building 3 Room 3-203', (SELECT id FROM City WHERE name = 'Sarasota' AND state = 'FL'), NULL, (SELECT id FROM Instructor WHERE slug = 'sarasota-ursula-jones-stc-sarasota'), 'LESSON', 1, NULL, 'https://www.campusce.net/acesarasota/course/course.aspx?C=143', 'https://www.campusce.net/acesarasota/course/course.aspx?C=143', '2026-10-07', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
