INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_cleveland-american-mahjong-at-the-red-lantern-open-and-guided-play-20261014', 'American Mahjong at the Red Lantern - Open and Guided Play', 'cleveland-american-mahjong-at-the-red-lantern-open-and-guided-play-20261014', '2026-10-14 00:00:00', '18:30', '21:00', 'Red Lantern Japanese Cuisine, 17446 Lorain Avenue, Cleveland, OH 44111', (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH'), (SELECT id FROM Club WHERE name = 'Cleveland Mahjong Collective' AND cityId = (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH')), NULL, 'OPEN_PLAY', 1, NULL, 'https://www.eventbrite.com/e/american-mahjong-at-the-red-lantern-open-and-guided-play-tickets-2002458888440', 'https://www.eventbrite.com/e/american-mahjong-at-the-red-lantern-open-and-guided-play-tickets-2002458888440', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_cleveland-mahj-o-ween-at-high-low-winery-20261020', 'Mahj-O-Ween at High & Low Winery', 'cleveland-mahj-o-ween-at-high-low-winery-20261020', '2026-10-20 00:00:00', '18:00', '20:30', 'High & Low Winery + Bistro, 588 Medina Road, Medina, OH 44256', (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH'), (SELECT id FROM Club WHERE name = 'Cleveland Mahjong Collective' AND cityId = (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH')), NULL, 'SOCIAL', 1, NULL, 'https://www.eventbrite.com/e/mahj-o-ween-at-high-low-winery-tickets-2001122982710', 'https://www.eventbrite.com/e/mahj-o-ween-at-high-low-winery-tickets-2001122982710', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_cleveland-mahj-o-ween-at-meraki-house-20261029', 'Mahj-O-Ween at Meraki House', 'cleveland-mahj-o-ween-at-meraki-house-20261029', '2026-10-29 00:00:00', '18:30', '21:00', 'Little Meraki Market, 34970 Detroit Road, Suite 250, Avon, OH 44011', (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH'), (SELECT id FROM Club WHERE name = 'Cleveland Mahjong Collective' AND cityId = (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH')), NULL, 'SOCIAL', 1, NULL, 'https://www.eventbrite.com/e/mahj-o-ween-at-meraki-house-tickets-2001398253051', 'https://www.eventbrite.com/e/mahj-o-ween-at-meraki-house-tickets-2001398253051', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
