INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_baltimore-mahjong-lesson-checkerspot-brewery-20261012', 'Mahjong Lesson- Checkerspot Brewery', 'baltimore-mahjong-lesson-checkerspot-brewery-20261012', '2026-10-12 00:00:00', '18:00', NULL, 'Checkerspot Brewery', (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD'), (SELECT id FROM Club WHERE name = 'The Tiles Social Club' AND cityId = (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD')), NULL, 'LESSON', 0, 40, 'https://tilessocialclub.bamgoodtime.com/events/ad245f64-44f0-4947-9c52-a5723c67b086', 'https://tilessocialclub.bamgoodtime.com/events/ad245f64-44f0-4947-9c52-a5723c67b086', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_baltimore-open-play-checkerspot-brewery-20261012', 'Open Play- Checkerspot Brewery', 'baltimore-open-play-checkerspot-brewery-20261012', '2026-10-12 00:00:00', '18:00', NULL, 'Checkerspot Brewery', (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD'), (SELECT id FROM Club WHERE name = 'The Tiles Social Club' AND cityId = (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD')), NULL, 'OPEN_PLAY', 0, 10, 'https://tilessocialclub.bamgoodtime.com/events/e78cb62c-f858-4174-87ce-fb5fffd055e9', 'https://tilessocialclub.bamgoodtime.com/events/e78cb62c-f858-4174-87ce-fb5fffd055e9', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_baltimore-wine-down-wednesdays-10-14-open-play-20261014', 'Wine Down Wednesdays 10/14 Open Play', 'baltimore-wine-down-wednesdays-10-14-open-play-20261014', '2026-10-14 00:00:00', '18:00', NULL, 'Chesapeake Wine Co', (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD'), (SELECT id FROM Club WHERE name = 'The Tiles Social Club' AND cityId = (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD')), NULL, 'OPEN_PLAY', 0, 10, 'https://tilessocialclub.bamgoodtime.com/events/0bcc8690-45f5-4a99-9faf-78d6893b1eae', 'https://tilessocialclub.bamgoodtime.com/events/0bcc8690-45f5-4a99-9faf-78d6893b1eae', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_baltimore-wine-down-wednesdays-10-14-20261014', 'Wine Down Wednesdays 10/14', 'baltimore-wine-down-wednesdays-10-14-20261014', '2026-10-14 00:00:00', '18:00', NULL, 'Chesapeake Wine Co', (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD'), (SELECT id FROM Club WHERE name = 'The Tiles Social Club' AND cityId = (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD')), NULL, 'LESSON', 0, 40, 'https://tilessocialclub.bamgoodtime.com/events/1badf4b2-0102-4507-8ebe-207b8150812c', 'https://tilessocialclub.bamgoodtime.com/events/1badf4b2-0102-4507-8ebe-207b8150812c', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_baltimore-open-play-gift-poke-20261019', 'Open Play @ Gift Poke', 'baltimore-open-play-gift-poke-20261019', '2026-10-19 00:00:00', '18:00', NULL, 'Giftpoke 9618 Deereco Rd Lutherville Timonium, MD 21093 United States', (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD'), (SELECT id FROM Club WHERE name = 'The Tiles Social Club' AND cityId = (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD')), NULL, 'OPEN_PLAY', 0, 35, 'https://tilessocialclub.bamgoodtime.com/events/c9052cfa-c999-4b38-9db1-8208df6f2d35', 'https://tilessocialclub.bamgoodtime.com/events/c9052cfa-c999-4b38-9db1-8208df6f2d35', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_baltimore-lessons-gift-poke-20261019', 'Lessons @ Gift Poke', 'baltimore-lessons-gift-poke-20261019', '2026-10-19 00:00:00', '18:00', NULL, 'Giftpoke 9618 Deereco Rd Lutherville Timonium, MD 21093 United States', (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD'), (SELECT id FROM Club WHERE name = 'The Tiles Social Club' AND cityId = (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD')), NULL, 'LESSON', 0, 65, 'https://tilessocialclub.bamgoodtime.com/events/9e7adafc-89f6-4c7b-a490-4d537ca9d3da', 'https://tilessocialclub.bamgoodtime.com/events/9e7adafc-89f6-4c7b-a490-4d537ca9d3da', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_baltimore-lessons-little-wing-baltimore-peninsula-oct-21-20261021', 'Lessons- - Little Wing Baltimore Peninsula Oct 21', 'baltimore-lessons-little-wing-baltimore-peninsula-oct-21-20261021', '2026-10-21 00:00:00', '18:00', NULL, 'Vessel - 2460 Terrapin Wy Baltimore MD 21230', (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD'), (SELECT id FROM Club WHERE name = 'The Tiles Social Club' AND cityId = (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD')), NULL, 'LESSON', 0, 40, 'https://tilessocialclub.bamgoodtime.com/events/ba88d0a3-82c8-419b-8316-45b6024ce943', 'https://tilessocialclub.bamgoodtime.com/events/ba88d0a3-82c8-419b-8316-45b6024ce943', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_baltimore-open-play-little-wing-baltimore-peninsula-oct-21-20261021', 'Open Play- Little Wing Baltimore Peninsula Oct 21', 'baltimore-open-play-little-wing-baltimore-peninsula-oct-21-20261021', '2026-10-21 00:00:00', '18:00', NULL, 'Vessel - 2460 Terrapin Wy Baltimore MD 21230', (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD'), (SELECT id FROM Club WHERE name = 'The Tiles Social Club' AND cityId = (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD')), NULL, 'OPEN_PLAY', 0, 10, 'https://tilessocialclub.bamgoodtime.com/events/a7b32274-2e5e-4cf8-9aa3-6ad13477a059', 'https://tilessocialclub.bamgoodtime.com/events/a7b32274-2e5e-4cf8-9aa3-6ad13477a059', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_baltimore-stitch-mahjong-sew-another-stitch-20261026', 'Stitch & Mahjong @ Sew Another Stitch', 'baltimore-stitch-mahjong-sew-another-stitch-20261026', '2026-10-26 00:00:00', '18:00', NULL, '433 St John Street Havre De Grace MD', (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD'), (SELECT id FROM Club WHERE name = 'The Tiles Social Club' AND cityId = (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD')), NULL, 'LESSON', 0, 40, 'https://tilessocialclub.bamgoodtime.com/events/4736e275-2e3c-40f8-9561-2297cbb675d9', 'https://tilessocialclub.bamgoodtime.com/events/4736e275-2e3c-40f8-9561-2297cbb675d9', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_baltimore-wine-down-wednesdays-10-28-20261028', 'Wine Down Wednesdays 10/28', 'baltimore-wine-down-wednesdays-10-28-20261028', '2026-10-28 00:00:00', '18:00', NULL, 'Chesapeake Wine Co', (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD'), (SELECT id FROM Club WHERE name = 'The Tiles Social Club' AND cityId = (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD')), NULL, 'LESSON', 0, 40, 'https://tilessocialclub.bamgoodtime.com/events/6c968409-8a7e-484f-9745-90a00e4b3f00', 'https://tilessocialclub.bamgoodtime.com/events/6c968409-8a7e-484f-9745-90a00e4b3f00', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_baltimore-wine-down-wednesdays-10-28-open-play-20261028', 'Wine Down Wednesdays 10/28 Open Play', 'baltimore-wine-down-wednesdays-10-28-open-play-20261028', '2026-10-28 00:00:00', '18:00', NULL, 'Chesapeake Wine Co', (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD'), (SELECT id FROM Club WHERE name = 'The Tiles Social Club' AND cityId = (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD')), NULL, 'OPEN_PLAY', 0, 10, 'https://tilessocialclub.bamgoodtime.com/events/4d3c83d7-390f-4121-bfa2-1b6988fbeb7f', 'https://tilessocialclub.bamgoodtime.com/events/4d3c83d7-390f-4121-bfa2-1b6988fbeb7f', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_baltimore-mahjong-and-movement-10-29-20261029', 'Mahjong and Movement 10/29', 'baltimore-mahjong-and-movement-10-29-20261029', '2026-10-29 00:00:00', '18:00', NULL, 'Potluck Studio- 1019 Cathedral Street Baltimore, MD 21201', (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD'), (SELECT id FROM Club WHERE name = 'The Tiles Social Club' AND cityId = (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD')), NULL, 'OPEN_PLAY', 0, 20, 'https://tilessocialclub.bamgoodtime.com/events/cacd53dd-6e76-41b7-9fad-681079421215', 'https://tilessocialclub.bamgoodtime.com/events/cacd53dd-6e76-41b7-9fad-681079421215', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_baltimore-mischief-mahj-ashley-s-birthday-open-play-20261111', 'Mischief Mahj & Ashley’s Birthday Open Play', 'baltimore-mischief-mahj-ashley-s-birthday-open-play-20261111', '2026-11-11 00:00:00', '18:00', NULL, 'Chesapeake Wine Co 2400 Boston Street Suite 112 Baltimore, MD 21224', (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD'), (SELECT id FROM Club WHERE name = 'The Tiles Social Club' AND cityId = (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD')), NULL, 'OPEN_PLAY', 0, 10, 'https://tilessocialclub.bamgoodtime.com/events/9a2a410d-01e2-4256-a248-64c2bfc676d8', 'https://tilessocialclub.bamgoodtime.com/events/9a2a410d-01e2-4256-a248-64c2bfc676d8', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_baltimore-mat-and-mahj-at-potluck-studio-20261112', 'Mat and Mahj at Potluck Studio', 'baltimore-mat-and-mahj-at-potluck-studio-20261112', '2026-11-12 00:00:00', '18:00', NULL, 'The Potluck Studios - 1019 Cathedral Street Baltimore, MD 21201', (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD'), (SELECT id FROM Club WHERE name = 'The Tiles Social Club' AND cityId = (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD')), NULL, 'OPEN_PLAY', 0, 20, 'https://tilessocialclub.bamgoodtime.com/events/17d27a5a-0ca4-4fe5-888a-eca3d1279f9a', 'https://tilessocialclub.bamgoodtime.com/events/17d27a5a-0ca4-4fe5-888a-eca3d1279f9a', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_baltimore-mahjong-and-pilates-coppermine-harbor-east-20261122', 'Mahjong and Pilates @ Coppermine Harbor East', 'baltimore-mahjong-and-pilates-coppermine-harbor-east-20261122', '2026-11-22 00:00:00', '11:00', NULL, 'Coppermine Harbor East 655 President Street Baltimore MD 21202', (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD'), (SELECT id FROM Club WHERE name = 'The Tiles Social Club' AND cityId = (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD')), NULL, 'OPEN_PLAY', 0, 45, 'https://tilessocialclub.bamgoodtime.com/events/45870dde-bc0a-43bf-ac4c-ae59b75db7d9', 'https://tilessocialclub.bamgoodtime.com/events/45870dde-bc0a-43bf-ac4c-ae59b75db7d9', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_baltimore-advanced-mahjong-skills-chesapeake-wine-co-20261209', 'Advanced Mahjong Skills - Chesapeake Wine Co', 'baltimore-advanced-mahjong-skills-chesapeake-wine-co-20261209', '2026-12-09 00:00:00', '18:00', NULL, 'Chesapeake Wine Co', (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD'), (SELECT id FROM Club WHERE name = 'The Tiles Social Club' AND cityId = (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD')), NULL, 'LESSON', 0, 50, 'https://tilessocialclub.bamgoodtime.com/events/06812b7b-ddb2-46dc-890e-5ad96d081fad', 'https://tilessocialclub.bamgoodtime.com/events/06812b7b-ddb2-46dc-890e-5ad96d081fad', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_baltimore-siamese-mahjong-lesson-coppershark-20270208', 'SIAMESE Mahjong Lesson- Coppershark', 'baltimore-siamese-mahjong-lesson-coppershark-20270208', '2027-02-08 00:00:00', '18:00', NULL, 'Coppershark', (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD'), (SELECT id FROM Club WHERE name = 'The Tiles Social Club' AND cityId = (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD')), NULL, 'LESSON', 0, 75, 'https://tilessocialclub.bamgoodtime.com/events/004f0265-b850-4773-ba1f-a1a6bc215c4b', 'https://tilessocialclub.bamgoodtime.com/events/004f0265-b850-4773-ba1f-a1a6bc215c4b', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_houston-mah-jongg-20261009', 'Mah Jongg', 'houston-mah-jongg-20261009', '2026-10-09 00:00:00', '10:00', NULL, '801 Bering Dr., Houston, TX 77057', (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX'), (SELECT id FROM Club WHERE name = 'Houston Congregation for Reform Judaism Mah Jongg' AND cityId = (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX')), NULL, 'OTHER', 0, NULL, 'https://hcrj.org/event/mah-jongg-2/2026-10-09/', 'https://hcrj.org/event/mah-jongg-2/2026-10-09/', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_houston-mah-jongg-20261014', 'Mah Jongg', 'houston-mah-jongg-20261014', '2026-10-14 00:00:00', '10:00', NULL, 'HCRJ', (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX'), (SELECT id FROM Club WHERE name = 'Houston Congregation for Reform Judaism Mah Jongg' AND cityId = (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX')), NULL, 'OTHER', 0, NULL, 'https://hcrj.org/event/mah-jongg/2026-10-14/', 'https://hcrj.org/event/mah-jongg/2026-10-14/', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_houston-mah-jongg-20261015', 'Mah Jongg', 'houston-mah-jongg-20261015', '2026-10-15 00:00:00', '13:00', NULL, 'HCRJ', (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX'), (SELECT id FROM Club WHERE name = 'Houston Congregation for Reform Judaism Mah Jongg' AND cityId = (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX')), NULL, 'OTHER', 0, NULL, 'https://hcrj.org/event/mah-jongg-215/2026-10-15/', 'https://hcrj.org/event/mah-jongg-215/2026-10-15/', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_houston-mah-jongg-20261016', 'Mah Jongg', 'houston-mah-jongg-20261016', '2026-10-16 00:00:00', '10:00', NULL, '801 Bering Dr., Houston, TX 77057', (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX'), (SELECT id FROM Club WHERE name = 'Houston Congregation for Reform Judaism Mah Jongg' AND cityId = (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX')), NULL, 'OTHER', 0, NULL, 'https://hcrj.org/event/mah-jongg-2/2026-10-16/', 'https://hcrj.org/event/mah-jongg-2/2026-10-16/', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_houston-mah-jongg-20261021', 'Mah Jongg', 'houston-mah-jongg-20261021', '2026-10-21 00:00:00', '10:00', NULL, 'HCRJ', (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX'), (SELECT id FROM Club WHERE name = 'Houston Congregation for Reform Judaism Mah Jongg' AND cityId = (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX')), NULL, 'OTHER', 0, NULL, 'https://hcrj.org/event/mah-jongg/2026-10-21/', 'https://hcrj.org/event/mah-jongg/2026-10-21/', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_houston-mah-jongg-20261022', 'Mah Jongg', 'houston-mah-jongg-20261022', '2026-10-22 00:00:00', '13:00', NULL, 'HCRJ', (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX'), (SELECT id FROM Club WHERE name = 'Houston Congregation for Reform Judaism Mah Jongg' AND cityId = (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX')), NULL, 'OTHER', 0, NULL, 'https://hcrj.org/event/mah-jongg-215/2026-10-22/', 'https://hcrj.org/event/mah-jongg-215/2026-10-22/', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_houston-mah-jongg-20261023', 'Mah Jongg', 'houston-mah-jongg-20261023', '2026-10-23 00:00:00', '10:00', NULL, '801 Bering Dr., Houston, TX 77057', (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX'), (SELECT id FROM Club WHERE name = 'Houston Congregation for Reform Judaism Mah Jongg' AND cityId = (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX')), NULL, 'OTHER', 0, NULL, 'https://hcrj.org/event/mah-jongg-2/2026-10-23/', 'https://hcrj.org/event/mah-jongg-2/2026-10-23/', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_houston-mah-jongg-20261028', 'Mah Jongg', 'houston-mah-jongg-20261028', '2026-10-28 00:00:00', '10:00', NULL, 'HCRJ', (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX'), (SELECT id FROM Club WHERE name = 'Houston Congregation for Reform Judaism Mah Jongg' AND cityId = (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX')), NULL, 'OTHER', 0, NULL, 'https://hcrj.org/event/mah-jongg/2026-10-28/', 'https://hcrj.org/event/mah-jongg/2026-10-28/', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_houston-mah-jongg-20261029', 'Mah Jongg', 'houston-mah-jongg-20261029', '2026-10-29 00:00:00', '13:00', NULL, 'HCRJ', (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX'), (SELECT id FROM Club WHERE name = 'Houston Congregation for Reform Judaism Mah Jongg' AND cityId = (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX')), NULL, 'OTHER', 0, NULL, 'https://hcrj.org/event/mah-jongg-215/2026-10-29/', 'https://hcrj.org/event/mah-jongg-215/2026-10-29/', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_houston-mah-jongg-20261030', 'Mah Jongg', 'houston-mah-jongg-20261030', '2026-10-30 00:00:00', '10:00', NULL, '801 Bering Dr., Houston, TX 77057', (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX'), (SELECT id FROM Club WHERE name = 'Houston Congregation for Reform Judaism Mah Jongg' AND cityId = (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX')), NULL, 'OTHER', 0, NULL, 'https://hcrj.org/event/mah-jongg-2/2026-10-30/', 'https://hcrj.org/event/mah-jongg-2/2026-10-30/', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_kansas-city-mahjong-for-beginners-kansas-city-mo-october-13-20-2026-20261013', 'Mahjong for Beginners - Kansas City, MO October 13 - 20, 2026', 'kansas-city-mahjong-for-beginners-kansas-city-mo-october-13-20-2026-20261013', '2026-10-13 00:00:00', '18:00', NULL, 'Park Hill District Office', (SELECT id FROM City WHERE name = 'Kansas City' AND state = 'MO'), (SELECT id FROM Club WHERE name = 'Park Hill District Office Mahjong' AND cityId = (SELECT id FROM City WHERE name = 'Kansas City' AND state = 'MO')), NULL, 'LESSON', 1, 140, 'https://www.active.com/kansas-city-mo/performing-arts/camp/mahjong-for-beginners-2026', 'https://www.active.com/kansas-city-mo/performing-arts/camp/mahjong-for-beginners-2026', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_miami-adult-services-mah-jongg-20261014', 'Adult Services: Mah Jongg', 'miami-adult-services-mah-jongg-20261014', '2026-10-14 00:00:00', '10:00', NULL, '18900 NE 25th Avenue, North Miami Beach, FL 33180', (SELECT id FROM City WHERE name = 'Miami' AND state = 'FL'), (SELECT id FROM Club WHERE name = 'Michael-Ann Russell JCC Mah Jongg' AND cityId = (SELECT id FROM City WHERE name = 'Miami' AND state = 'FL')), NULL, 'OTHER', 0, NULL, 'https://marjcc.org/event/adult-services-mah-jongg-2/2026-10-14/', 'https://marjcc.org/event/adult-services-mah-jongg-2/2026-10-14/', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_miami-adult-services-mah-jongg-20261021', 'Adult Services: Mah Jongg', 'miami-adult-services-mah-jongg-20261021', '2026-10-21 00:00:00', '10:00', NULL, '18900 NE 25th Avenue, North Miami Beach, FL 33180', (SELECT id FROM City WHERE name = 'Miami' AND state = 'FL'), (SELECT id FROM Club WHERE name = 'Michael-Ann Russell JCC Mah Jongg' AND cityId = (SELECT id FROM City WHERE name = 'Miami' AND state = 'FL')), NULL, 'OTHER', 0, NULL, 'https://marjcc.org/event/adult-services-mah-jongg-2/2026-10-21/', 'https://marjcc.org/event/adult-services-mah-jongg-2/2026-10-21/', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_miami-adult-services-mah-jongg-20261028', 'Adult Services: Mah Jongg', 'miami-adult-services-mah-jongg-20261028', '2026-10-28 00:00:00', '10:00', NULL, '18900 NE 25th Avenue, North Miami Beach, FL 33180', (SELECT id FROM City WHERE name = 'Miami' AND state = 'FL'), (SELECT id FROM Club WHERE name = 'Michael-Ann Russell JCC Mah Jongg' AND cityId = (SELECT id FROM City WHERE name = 'Miami' AND state = 'FL')), NULL, 'OTHER', 0, NULL, 'https://marjcc.org/event/adult-services-mah-jongg-2/2026-10-28/', 'https://marjcc.org/event/adult-services-mah-jongg-2/2026-10-28/', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_miami-adult-services-mah-jongg-20261104', 'Adult Services: Mah Jongg', 'miami-adult-services-mah-jongg-20261104', '2026-11-04 00:00:00', '10:00', NULL, '18900 NE 25th Avenue, North Miami Beach, FL 33180', (SELECT id FROM City WHERE name = 'Miami' AND state = 'FL'), (SELECT id FROM Club WHERE name = 'Michael-Ann Russell JCC Mah Jongg' AND cityId = (SELECT id FROM City WHERE name = 'Miami' AND state = 'FL')), NULL, 'OTHER', 0, NULL, 'https://marjcc.org/event/adult-services-mah-jongg-2/2026-11-04/', 'https://marjcc.org/event/adult-services-mah-jongg-2/2026-11-04/', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_miami-adult-services-mah-jongg-20261111', 'Adult Services: Mah Jongg', 'miami-adult-services-mah-jongg-20261111', '2026-11-11 00:00:00', '10:00', NULL, '18900 NE 25th Avenue, North Miami Beach, FL 33180', (SELECT id FROM City WHERE name = 'Miami' AND state = 'FL'), (SELECT id FROM Club WHERE name = 'Michael-Ann Russell JCC Mah Jongg' AND cityId = (SELECT id FROM City WHERE name = 'Miami' AND state = 'FL')), NULL, 'OTHER', 0, NULL, 'https://marjcc.org/event/adult-services-mah-jongg-2/2026-11-11/', 'https://marjcc.org/event/adult-services-mah-jongg-2/2026-11-11/', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_minneapolis-beginner-american-mah-jongg-2-20261015', 'Beginner American Mah Jongg 2', 'minneapolis-beginner-american-mah-jongg-2-20261015', '2026-10-15 00:00:00', '09:00', NULL, 'New Brighton Community Center', (SELECT id FROM City WHERE name = 'Minneapolis' AND state = 'MN'), (SELECT id FROM Club WHERE name = 'MN Mahjong - St. Anthony Community Center' AND cityId = (SELECT id FROM City WHERE name = 'Minneapolis' AND state = 'MN')), NULL, 'LESSON', 1, 80, 'https://mnmahjong.com/event/beginner-american-mah-jongg-2/', 'https://mnmahjong.com/event/beginner-american-mah-jongg-2/', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_minneapolis-beginner-american-mah-jongg-20261020', 'Beginner American Mah Jongg', 'minneapolis-beginner-american-mah-jongg-20261020', '2026-10-20 00:00:00', '09:00', NULL, 'New Brighton Community Center', (SELECT id FROM City WHERE name = 'Minneapolis' AND state = 'MN'), (SELECT id FROM Club WHERE name = 'MN Mahjong - St. Anthony Community Center' AND cityId = (SELECT id FROM City WHERE name = 'Minneapolis' AND state = 'MN')), NULL, 'LESSON', 1, 80, 'https://mnmahjong.com/event/beginner-mah-jongg-winter-26/', 'https://mnmahjong.com/event/beginner-mah-jongg-winter-26/', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_minneapolis-beginner-american-mah-jongg-20261028', 'Beginner American Mah Jongg', 'minneapolis-beginner-american-mah-jongg-20261028', '2026-10-28 00:00:00', '09:00', NULL, 'New Brighton Community Center', (SELECT id FROM City WHERE name = 'Minneapolis' AND state = 'MN'), (SELECT id FROM Club WHERE name = 'MN Mahjong - St. Anthony Community Center' AND cityId = (SELECT id FROM City WHERE name = 'Minneapolis' AND state = 'MN')), NULL, 'LESSON', 1, 80, 'https://mnmahjong.com/event/beginner-american-mah-jongg/', 'https://mnmahjong.com/event/beginner-american-mah-jongg/', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_minneapolis-beginner-american-mah-jongg-2-20261104', 'Beginner American Mah Jongg 2', 'minneapolis-beginner-american-mah-jongg-2-20261104', '2026-11-04 00:00:00', '09:00', NULL, 'New Brighton Community Center', (SELECT id FROM City WHERE name = 'Minneapolis' AND state = 'MN'), (SELECT id FROM Club WHERE name = 'MN Mahjong - St. Anthony Community Center' AND cityId = (SELECT id FROM City WHERE name = 'Minneapolis' AND state = 'MN')), NULL, 'LESSON', 1, 80, 'https://mnmahjong.com/event/beginner-american-mah-jongg-2-2/', 'https://mnmahjong.com/event/beginner-american-mah-jongg-2-2/', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_oklahoma-city-2026-continental-mahjong-tournament-edmond-ok-20261026', '2026 Continental Mahjong Tournament | Edmond, OK', 'oklahoma-city-2026-continental-mahjong-tournament-edmond-ok-20261026', '2026-10-26 00:00:00', '10:00', NULL, 'Oak Tree Country Club | 700 W. Country Club Drive Edmond, OK 73025', (SELECT id FROM City WHERE name = 'Oklahoma City' AND state = 'OK'), (SELECT id FROM Club WHERE name = 'Mahj & Bougie' AND cityId = (SELECT id FROM City WHERE name = 'Oklahoma City' AND state = 'OK')), NULL, 'TOURNAMENT', 0, NULL, 'https://mahj-bougie.bamgoodtime.com/events/761adb1a-d32e-48c8-9f08-1ba62ed6a788', 'https://mahj-bougie.bamgoodtime.com/events/761adb1a-d32e-48c8-9f08-1ba62ed6a788', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_oklahoma-city-mahj-bougie-tiles-touchdowns-fall-league-full-series-event-7-20261129', 'Mahj & Bougie Tiles & Touchdowns Fall League (Full Series) — Event #7', 'oklahoma-city-mahj-bougie-tiles-touchdowns-fall-league-full-series-event-7-20261129', '2026-11-29 00:00:00', '13:00', NULL, 'Maxwell''s on The Lake | 4491 S Lake Hefner Dr, Oklahoma City, OK 73116', (SELECT id FROM City WHERE name = 'Oklahoma City' AND state = 'OK'), (SELECT id FROM Club WHERE name = 'Mahj & Bougie' AND cityId = (SELECT id FROM City WHERE name = 'Oklahoma City' AND state = 'OK')), NULL, 'TOURNAMENT', 0, 35, 'https://mahj-bougie.bamgoodtime.com/events/acf60d92-719f-407b-895c-db16e79e8bb4', 'https://mahj-bougie.bamgoodtime.com/events/acf60d92-719f-407b-895c-db16e79e8bb4', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_oklahoma-city-mahj-bougie-tiles-touchdowns-fall-league-full-series-event-8-20261213', 'Mahj & Bougie Tiles & Touchdowns Fall League (Full Series) — Event #8', 'oklahoma-city-mahj-bougie-tiles-touchdowns-fall-league-full-series-event-8-20261213', '2026-12-13 00:00:00', '13:00', NULL, 'Maxwell''s on The Lake | 4491 S Lake Hefner Dr, Oklahoma City, OK 73116', (SELECT id FROM City WHERE name = 'Oklahoma City' AND state = 'OK'), (SELECT id FROM Club WHERE name = 'Mahj & Bougie' AND cityId = (SELECT id FROM City WHERE name = 'Oklahoma City' AND state = 'OK')), NULL, 'TOURNAMENT', 0, 35, 'https://mahj-bougie.bamgoodtime.com/events/fdc00e76-2374-41dd-9742-6bbd3d90d4f1', 'https://mahj-bougie.bamgoodtime.com/events/fdc00e76-2374-41dd-9742-6bbd3d90d4f1', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_raleigh-bottlerev-mahjong-101-20261012', 'BottleRev - Mahjong 101', 'raleigh-bottlerev-mahjong-101-20261012', '2026-10-12 00:00:00', '17:30', NULL, '7713 Lead Mine Road, Raleigh, NC 27613', (SELECT id FROM City WHERE name = 'Raleigh' AND state = 'NC'), (SELECT id FROM Club WHERE name = 'Mahj With R+M' AND cityId = (SELECT id FROM City WHERE name = 'Raleigh' AND state = 'NC')), NULL, 'LESSON', 1, 60, 'https://mahj-with-read.bamgoodtime.com/events/3df2676d-3a38-44c0-8c6a-64185d4e9982', 'https://mahj-with-read.bamgoodtime.com/events/3df2676d-3a38-44c0-8c6a-64185d4e9982', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_raleigh-mahj-mondays-at-bottlerev3-20261019', 'Mahj Mondays - at BottleRev3', 'raleigh-mahj-mondays-at-bottlerev3-20261019', '2026-10-19 00:00:00', '18:30', NULL, 'BottleRev3 - 7713 Lead Mine Rd #47, Raleigh, NC 27615', (SELECT id FROM City WHERE name = 'Raleigh' AND state = 'NC'), (SELECT id FROM Club WHERE name = 'Mahj With R+M' AND cityId = (SELECT id FROM City WHERE name = 'Raleigh' AND state = 'NC')), NULL, 'OPEN_PLAY', 0, 15, 'https://mahj-with-read.bamgoodtime.com/events/91f10af9-33d8-44a6-823b-14fe5c0a4f39', 'https://mahj-with-read.bamgoodtime.com/events/91f10af9-33d8-44a6-823b-14fe5c0a4f39', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_raleigh-bottlerev-mahjong-101-20261026', 'BottleRev - Mahjong 101', 'raleigh-bottlerev-mahjong-101-20261026', '2026-10-26 00:00:00', '17:30', NULL, '7713 Lead Mine Road, Raleigh, NC 27613', (SELECT id FROM City WHERE name = 'Raleigh' AND state = 'NC'), (SELECT id FROM Club WHERE name = 'Mahj With R+M' AND cityId = (SELECT id FROM City WHERE name = 'Raleigh' AND state = 'NC')), NULL, 'LESSON', 1, 60, 'https://mahj-with-read.bamgoodtime.com/events/75a1b019-b51b-48a3-8ef4-9d4df3561fe5', 'https://mahj-with-read.bamgoodtime.com/events/75a1b019-b51b-48a3-8ef4-9d4df3561fe5', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_raleigh-mahj-mondays-at-bottlerev3-20261026', 'Mahj Mondays - at BottleRev3', 'raleigh-mahj-mondays-at-bottlerev3-20261026', '2026-10-26 00:00:00', '18:30', NULL, 'BottleRev3 - 7713 Lead Mine Rd #47, Raleigh, NC 27615', (SELECT id FROM City WHERE name = 'Raleigh' AND state = 'NC'), (SELECT id FROM Club WHERE name = 'Mahj With R+M' AND cityId = (SELECT id FROM City WHERE name = 'Raleigh' AND state = 'NC')), NULL, 'OPEN_PLAY', 0, 15, 'https://mahj-with-read.bamgoodtime.com/events/c756ba74-6614-4e82-8430-330bb546a9c0', 'https://mahj-with-read.bamgoodtime.com/events/c756ba74-6614-4e82-8430-330bb546a9c0', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_san-antonio-mahjong-103-am-20261010', 'Mahjong 103 AM', 'san-antonio-mahjong-103-am-20261010', '2026-10-10 00:00:00', '10:00', NULL, '511 W French Place, San Antonio, TX 78212', (SELECT id FROM City WHERE name = 'San Antonio' AND state = 'TX'), (SELECT id FROM Club WHERE name = 'The Polished Tile' AND cityId = (SELECT id FROM City WHERE name = 'San Antonio' AND state = 'TX')), NULL, 'LESSON', 0, NULL, 'https://play.thepolishedtile.com/events/22dc9b35-0f69-4875-b843-77d42fdf2bed', 'https://play.thepolishedtile.com/events/22dc9b35-0f69-4875-b843-77d42fdf2bed', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_san-antonio-mahjong-101-pm-20261010', 'Mahjong 101 PM', 'san-antonio-mahjong-101-pm-20261010', '2026-10-10 00:00:00', '15:00', NULL, '511 W French Place, San Antonio, TX 78212', (SELECT id FROM City WHERE name = 'San Antonio' AND state = 'TX'), (SELECT id FROM Club WHERE name = 'The Polished Tile' AND cityId = (SELECT id FROM City WHERE name = 'San Antonio' AND state = 'TX')), NULL, 'LESSON', 1, NULL, 'https://play.thepolishedtile.com/events/627f5307-5556-44a3-a476-e6a5a1b94a03', 'https://play.thepolishedtile.com/events/627f5307-5556-44a3-a476-e6a5a1b94a03', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_san-antonio-mahjong-102-am-20261013', 'Mahjong 102 AM', 'san-antonio-mahjong-102-am-20261013', '2026-10-13 00:00:00', '10:30', NULL, '511 W French Place, San Antonio, TX 78212', (SELECT id FROM City WHERE name = 'San Antonio' AND state = 'TX'), (SELECT id FROM Club WHERE name = 'The Polished Tile' AND cityId = (SELECT id FROM City WHERE name = 'San Antonio' AND state = 'TX')), NULL, 'LESSON', 0, NULL, 'https://play.thepolishedtile.com/events/4acd3396-c3a8-4ad8-b6bb-9102a4fd073f', 'https://play.thepolishedtile.com/events/4acd3396-c3a8-4ad8-b6bb-9102a4fd073f', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_san-antonio-mahjong-103-pm-20261013', 'Mahjong 103 PM', 'san-antonio-mahjong-103-pm-20261013', '2026-10-13 00:00:00', '18:00', NULL, '511 W French Place, San Antonio, TX 78212', (SELECT id FROM City WHERE name = 'San Antonio' AND state = 'TX'), (SELECT id FROM Club WHERE name = 'The Polished Tile' AND cityId = (SELECT id FROM City WHERE name = 'San Antonio' AND state = 'TX')), NULL, 'LESSON', 0, NULL, 'https://play.thepolishedtile.com/events/01f540e5-817d-4761-a1de-154bc1b4b32b', 'https://play.thepolishedtile.com/events/01f540e5-817d-4761-a1de-154bc1b4b32b', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_san-antonio-mahjong-101-am-20261015', 'Mahjong 101 AM', 'san-antonio-mahjong-101-am-20261015', '2026-10-15 00:00:00', '10:30', NULL, '511 W French Place, San Antonio, TX 78212', (SELECT id FROM City WHERE name = 'San Antonio' AND state = 'TX'), (SELECT id FROM Club WHERE name = 'The Polished Tile' AND cityId = (SELECT id FROM City WHERE name = 'San Antonio' AND state = 'TX')), NULL, 'LESSON', 1, NULL, 'https://play.thepolishedtile.com/events/3da7dc49-bf33-40df-8251-507c26b72de0', 'https://play.thepolishedtile.com/events/3da7dc49-bf33-40df-8251-507c26b72de0', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_san-antonio-mahjong-102-pm-20261015', 'Mahjong 102 PM', 'san-antonio-mahjong-102-pm-20261015', '2026-10-15 00:00:00', '18:00', NULL, '511 W French Place, San Antonio, TX 78212', (SELECT id FROM City WHERE name = 'San Antonio' AND state = 'TX'), (SELECT id FROM Club WHERE name = 'The Polished Tile' AND cityId = (SELECT id FROM City WHERE name = 'San Antonio' AND state = 'TX')), NULL, 'LESSON', 0, NULL, 'https://play.thepolishedtile.com/events/c876c8b6-0eea-482f-8117-4ec3224439bb', 'https://play.thepolishedtile.com/events/c876c8b6-0eea-482f-8117-4ec3224439bb', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_seattle-daytime-american-mahjong-free-play-20261012', 'Daytime American Mahjong Free Play', 'seattle-daytime-american-mahjong-free-play-20261012', '2026-10-12 00:00:00', '13:00', NULL, 'SJCC Makom', (SELECT id FROM City WHERE name = 'Seattle' AND state = 'WA'), (SELECT id FROM Club WHERE name = 'American Mahjong at the J' AND cityId = (SELECT id FROM City WHERE name = 'Seattle' AND state = 'WA')), NULL, 'OPEN_PLAY', 0, NULL, 'https://sjcc.org/event/daytime-drop-in-mahjong/2026-10-12/', 'https://sjcc.org/event/daytime-drop-in-mahjong/2026-10-12/', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_seattle-evening-mahjong-free-play-20261012', 'Evening Mahjong Free Play', 'seattle-evening-mahjong-free-play-20261012', '2026-10-12 00:00:00', '18:00', NULL, 'SJCC Makom', (SELECT id FROM City WHERE name = 'Seattle' AND state = 'WA'), (SELECT id FROM Club WHERE name = 'American Mahjong at the J' AND cityId = (SELECT id FROM City WHERE name = 'Seattle' AND state = 'WA')), NULL, 'OPEN_PLAY', 0, NULL, 'https://sjcc.org/event/evening-mahjong-free-play/2026-10-12/', 'https://sjcc.org/event/evening-mahjong-free-play/2026-10-12/', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_seattle-october-beginner-mahjong-class-20261012', 'October Beginner Mahjong Class', 'seattle-october-beginner-mahjong-class-20261012', '2026-10-12 00:00:00', '18:00', NULL, 'SJCC Makom', (SELECT id FROM City WHERE name = 'Seattle' AND state = 'WA'), (SELECT id FROM Club WHERE name = 'American Mahjong at the J' AND cityId = (SELECT id FROM City WHERE name = 'Seattle' AND state = 'WA')), NULL, 'LESSON', 1, NULL, 'https://sjcc.org/event/october-beginner-mahjong-class/', 'https://sjcc.org/event/october-beginner-mahjong-class/', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_seattle-daytime-american-mahjong-free-play-20261019', 'Daytime American Mahjong Free Play', 'seattle-daytime-american-mahjong-free-play-20261019', '2026-10-19 00:00:00', '13:00', NULL, 'SJCC Makom', (SELECT id FROM City WHERE name = 'Seattle' AND state = 'WA'), (SELECT id FROM Club WHERE name = 'American Mahjong at the J' AND cityId = (SELECT id FROM City WHERE name = 'Seattle' AND state = 'WA')), NULL, 'OPEN_PLAY', 0, NULL, 'https://sjcc.org/event/daytime-drop-in-mahjong/2026-10-19/', 'https://sjcc.org/event/daytime-drop-in-mahjong/2026-10-19/', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_seattle-evening-mahjong-free-play-20261019', 'Evening Mahjong Free Play', 'seattle-evening-mahjong-free-play-20261019', '2026-10-19 00:00:00', '18:00', NULL, 'SJCC Makom', (SELECT id FROM City WHERE name = 'Seattle' AND state = 'WA'), (SELECT id FROM Club WHERE name = 'American Mahjong at the J' AND cityId = (SELECT id FROM City WHERE name = 'Seattle' AND state = 'WA')), NULL, 'OPEN_PLAY', 0, NULL, 'https://sjcc.org/event/evening-mahjong-free-play/2026-10-19/', 'https://sjcc.org/event/evening-mahjong-free-play/2026-10-19/', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_seattle-daytime-american-mahjong-free-play-20261026', 'Daytime American Mahjong Free Play', 'seattle-daytime-american-mahjong-free-play-20261026', '2026-10-26 00:00:00', '13:00', NULL, 'SJCC Makom', (SELECT id FROM City WHERE name = 'Seattle' AND state = 'WA'), (SELECT id FROM Club WHERE name = 'American Mahjong at the J' AND cityId = (SELECT id FROM City WHERE name = 'Seattle' AND state = 'WA')), NULL, 'OPEN_PLAY', 0, NULL, 'https://sjcc.org/event/daytime-drop-in-mahjong/2026-10-26/', 'https://sjcc.org/event/daytime-drop-in-mahjong/2026-10-26/', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_seattle-evening-mahjong-free-play-20261026', 'Evening Mahjong Free Play', 'seattle-evening-mahjong-free-play-20261026', '2026-10-26 00:00:00', '18:00', NULL, 'SJCC Makom', (SELECT id FROM City WHERE name = 'Seattle' AND state = 'WA'), (SELECT id FROM Club WHERE name = 'American Mahjong at the J' AND cityId = (SELECT id FROM City WHERE name = 'Seattle' AND state = 'WA')), NULL, 'OPEN_PLAY', 0, NULL, 'https://sjcc.org/event/evening-mahjong-free-play/2026-10-26/', 'https://sjcc.org/event/evening-mahjong-free-play/2026-10-26/', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_seattle-daytime-american-mahjong-free-play-20261102', 'Daytime American Mahjong Free Play', 'seattle-daytime-american-mahjong-free-play-20261102', '2026-11-02 00:00:00', '13:00', NULL, 'SJCC Makom', (SELECT id FROM City WHERE name = 'Seattle' AND state = 'WA'), (SELECT id FROM Club WHERE name = 'American Mahjong at the J' AND cityId = (SELECT id FROM City WHERE name = 'Seattle' AND state = 'WA')), NULL, 'OPEN_PLAY', 0, NULL, 'https://sjcc.org/event/daytime-drop-in-mahjong/2026-11-02/', 'https://sjcc.org/event/daytime-drop-in-mahjong/2026-11-02/', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_seattle-evening-mahjong-free-play-20261102', 'Evening Mahjong Free Play', 'seattle-evening-mahjong-free-play-20261102', '2026-11-02 00:00:00', '18:00', NULL, 'SJCC Makom', (SELECT id FROM City WHERE name = 'Seattle' AND state = 'WA'), (SELECT id FROM Club WHERE name = 'American Mahjong at the J' AND cityId = (SELECT id FROM City WHERE name = 'Seattle' AND state = 'WA')), NULL, 'OPEN_PLAY', 0, NULL, 'https://sjcc.org/event/evening-mahjong-free-play/2026-11-02/', 'https://sjcc.org/event/evening-mahjong-free-play/2026-11-02/', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_seattle-november-beginner-mahjong-class-20261102', 'November Beginner Mahjong Class', 'seattle-november-beginner-mahjong-class-20261102', '2026-11-02 00:00:00', '18:00', NULL, 'SJCC Makom', (SELECT id FROM City WHERE name = 'Seattle' AND state = 'WA'), (SELECT id FROM Club WHERE name = 'American Mahjong at the J' AND cityId = (SELECT id FROM City WHERE name = 'Seattle' AND state = 'WA')), NULL, 'LESSON', 1, NULL, 'https://sjcc.org/event/november-beginner-mahjong-class/', 'https://sjcc.org/event/november-beginner-mahjong-class/', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
