INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_cleveland-mahjong-mondays-at-ninja-city-20261012', 'Mahjong Mondays at Ninja City', 'cleveland-mahjong-mondays-at-ninja-city-20261012', '2026-10-12 00:00:00', '18:00', NULL, 'Ninja City Kitchen & Bar, 6706 Detroit Avenue, Cleveland, OH 44102', (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH'), (SELECT id FROM Club WHERE name = 'Cleveland Mahjong Collective' AND cityId = (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH')), NULL, 'OTHER', 0, 0, 'https://www.eventbrite.com/e/mahjong-mondays-at-ninja-city-tickets-2003112456279', 'https://www.eventbrite.com/e/mahjong-mondays-at-ninja-city-tickets-2003112456279', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_cleveland-sunday-session-at-meraki-20261018', 'Sunday Session at Meraki', 'cleveland-sunday-session-at-meraki-20261018', '2026-10-18 00:00:00', '13:00', NULL, 'Little Meraki Market, 34970 Detroit Road, Avon, OH 44011', (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH'), (SELECT id FROM Club WHERE name = 'Cleveland Mahjong Collective' AND cityId = (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH')), NULL, 'OTHER', 0, 9, 'https://www.eventbrite.com/e/sunday-session-at-meraki-tickets-2003136030791', 'https://www.eventbrite.com/e/sunday-session-at-meraki-tickets-2003136030791', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_cleveland-american-mahjong-at-the-red-lantern-open-and-guided-play-20261021', 'American Mahjong at the Red Lantern - Open and guided play', 'cleveland-american-mahjong-at-the-red-lantern-open-and-guided-play-20261021', '2026-10-21 00:00:00', '18:30', NULL, 'Red Lantern Japanese Cuisine, 17446 Lorain Avenue, Cleveland, OH 44111', (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH'), (SELECT id FROM Club WHERE name = 'Cleveland Mahjong Collective' AND cityId = (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH')), NULL, 'OPEN_PLAY', 0, 8, 'https://www.eventbrite.com/e/american-mahjong-at-the-red-lantern-open-and-guided-play-tickets-2003136297589', 'https://www.eventbrite.com/e/american-mahjong-at-the-red-lantern-open-and-guided-play-tickets-2003136297589', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_cleveland-sunday-session-at-meraki-20261025', 'Sunday Session at Meraki', 'cleveland-sunday-session-at-meraki-20261025', '2026-10-25 00:00:00', '13:00', NULL, 'Little Meraki Market, 34970 Detroit Road, Avon, OH 44011', (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH'), (SELECT id FROM Club WHERE name = 'Cleveland Mahjong Collective' AND cityId = (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH')), NULL, 'OTHER', 0, 9, 'https://www.eventbrite.com/e/sunday-session-at-meraki-tickets-2003136111031', 'https://www.eventbrite.com/e/sunday-session-at-meraki-tickets-2003136111031', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_cleveland-american-mahjong-at-the-red-lantern-open-and-guided-play-20261028', 'American Mahjong at the Red Lantern - Open and guided play', 'cleveland-american-mahjong-at-the-red-lantern-open-and-guided-play-20261028', '2026-10-28 00:00:00', '18:30', NULL, 'Red Lantern Japanese Cuisine, 17446 Lorain Avenue, Cleveland, OH 44111', (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH'), (SELECT id FROM Club WHERE name = 'Cleveland Mahjong Collective' AND cityId = (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH')), NULL, 'OPEN_PLAY', 0, 8, 'https://www.eventbrite.com/e/american-mahjong-at-the-red-lantern-open-and-guided-play-tickets-2003136774014', 'https://www.eventbrite.com/e/american-mahjong-at-the-red-lantern-open-and-guided-play-tickets-2003136774014', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_cleveland-american-mahjong-101-and-open-play-at-meraki-20261101', 'American Mahjong 101 and Open Play at Meraki', 'cleveland-american-mahjong-101-and-open-play-at-meraki-20261101', '2026-11-01 00:00:00', '13:00', NULL, 'Little Meraki Market, 34970 Detroit Road, Avon, OH 44011', (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH'), (SELECT id FROM Club WHERE name = 'Cleveland Mahjong Collective' AND cityId = (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH')), NULL, 'LESSON', 1, 11.44, 'https://www.eventbrite.com/e/american-mahjong-101-and-open-play-at-meraki-tickets-2003017248510', 'https://www.eventbrite.com/e/american-mahjong-101-and-open-play-at-meraki-tickets-2003017248510', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_cleveland-tiles-at-tabletop-learn-and-play-american-mahjong-with-cleveland-mahjong-20261105', 'Tiles at Tabletop: Learn and Play American Mahjong with Cleveland Mahjong', 'cleveland-tiles-at-tabletop-learn-and-play-american-mahjong-with-cleveland-mahjong-20261105', '2026-11-05 00:00:00', '18:30', NULL, 'Tabletop Board Game Cafe, 1810 West 25th Street, Cleveland, OH 44113', (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH'), (SELECT id FROM Club WHERE name = 'Cleveland Mahjong Collective' AND cityId = (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH')), NULL, 'LESSON', 1, 10.38, 'https://www.eventbrite.com/e/tiles-at-tabletop-learn-and-play-american-mahjong-with-cleveland-mahjong-tickets-2002750683206', 'https://www.eventbrite.com/e/tiles-at-tabletop-learn-and-play-american-mahjong-with-cleveland-mahjong-tickets-2002750683206', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_cleveland-mahjong-at-high-and-low-learn-the-game-and-find-your-table-20261117', 'Mahjong at High and Low - Learn the Game and Find Your Table', 'cleveland-mahjong-at-high-and-low-learn-the-game-and-find-your-table-20261117', '2026-11-17 00:00:00', '18:30', NULL, 'High & Low Winery + Bistro, 588 Medina Road, Medina, OH 44256', (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH'), (SELECT id FROM Club WHERE name = 'Cleveland Mahjong Collective' AND cityId = (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH')), NULL, 'LESSON', 1, 12.51, 'https://www.eventbrite.com/e/mahjong-at-high-and-low-learn-the-game-and-find-your-table-tickets-2002357635590', 'https://www.eventbrite.com/e/mahjong-at-high-and-low-learn-the-game-and-find-your-table-tickets-2002357635590', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_cleveland-mahjong-101-or-open-play-20261017', 'Mahjong 101 or Open Play', 'cleveland-mahjong-101-or-open-play-20261017', '2026-10-17 00:00:00', '12:00', NULL, 'Nourishing Nook, 14150 Pearl Road, Strongsville, OH 44136', (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH'), (SELECT id FROM Club WHERE name = 'Southwest Cleveland Mahjong' AND cityId = (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH')), NULL, 'LESSON', 1, 10, 'https://www.eventbrite.com/e/mahjong-101-or-open-play-tickets-2002747453546', 'https://www.eventbrite.com/e/mahjong-101-or-open-play-tickets-2002747453546', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_cleveland-mahjong-guided-play-or-open-play-20261020', 'Mahjong Guided Play or Open Play', 'cleveland-mahjong-guided-play-or-open-play-20261020', '2026-10-20 00:00:00', '18:00', NULL, 'Market 42, 2099 Pearl Road, Brunswick, OH 44212', (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH'), (SELECT id FROM Club WHERE name = 'Southwest Cleveland Mahjong' AND cityId = (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH')), NULL, 'OPEN_PLAY', 0, 12.51, 'https://www.eventbrite.com/e/mahjong-guided-play-or-open-play-tickets-1997269498836', 'https://www.eventbrite.com/e/mahjong-guided-play-or-open-play-tickets-1997269498836', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_cleveland-mahjong-open-play-20261021', 'Mahjong Open Play', 'cleveland-mahjong-open-play-20261021', '2026-10-21 00:00:00', '17:30', NULL, 'Kelly''s Cafe, 1661 Pearl Road, Brunswick, OH 44212', (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH'), (SELECT id FROM Club WHERE name = 'Southwest Cleveland Mahjong' AND cityId = (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH')), NULL, 'OPEN_PLAY', 0, 7.18, 'https://www.eventbrite.com/e/mahjong-open-play-tickets-2001708519065', 'https://www.eventbrite.com/e/mahjong-open-play-tickets-2001708519065', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_cleveland-mahjong-101-beginner-lesson-or-open-play-20261117', 'Mahjong 101 (Beginner Lesson) or Open Play', 'cleveland-mahjong-101-beginner-lesson-or-open-play-20261117', '2026-11-17 00:00:00', '18:00', NULL, 'Market 42, 2099 Pearl Road, Brunswick, OH 44212', (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH'), (SELECT id FROM Club WHERE name = 'Southwest Cleveland Mahjong' AND cityId = (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH')), NULL, 'LESSON', 1, 12.51, 'https://www.eventbrite.com/e/mahjong-101-beginner-lesson-or-open-play-tickets-1999723016373', 'https://www.eventbrite.com/e/mahjong-101-beginner-lesson-or-open-play-tickets-1999723016373', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_cleveland-mahjong-101-or-open-play-at-market-42-20261201', 'Mahjong 101 or Open Play at Market 42', 'cleveland-mahjong-101-or-open-play-at-market-42-20261201', '2026-12-01 00:00:00', '18:00', NULL, 'Market 42, 2099 Pearl Road, Brunswick, OH 44212', (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH'), (SELECT id FROM Club WHERE name = 'Southwest Cleveland Mahjong' AND cityId = (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH')), NULL, 'LESSON', 1, 12.51, 'https://www.eventbrite.com/e/mahjong-101-or-open-play-at-market-42-tickets-2000029304489', 'https://www.eventbrite.com/e/mahjong-101-or-open-play-at-market-42-tickets-2000029304489', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_cleveland-mahjong-guided-play-or-open-play-at-market-42-20261215', 'Mahjong Guided Play or Open Play at Market 42', 'cleveland-mahjong-guided-play-or-open-play-at-market-42-20261215', '2026-12-15 00:00:00', '18:00', NULL, 'Market 42, 2099 Pearl Rd, Brunswick, OH 44212', (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH'), (SELECT id FROM Club WHERE name = 'Southwest Cleveland Mahjong' AND cityId = (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH')), NULL, 'OPEN_PLAY', 0, 12.51, 'https://www.eventbrite.com/e/mahjong-guided-play-or-open-play-at-market-42-tickets-2000032938358', 'https://www.eventbrite.com/e/mahjong-guided-play-or-open-play-at-market-42-tickets-2000032938358', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_columbus-let-s-get-mahj-d-mahjong-101-20261013', 'Let’s Get Mahj’d: Mahjong 101', 'columbus-let-s-get-mahj-d-mahjong-101-20261013', '2026-10-13 00:00:00', '19:00', NULL, 'BASH! By Young + Wild, 679 High Street, Worthington, OH 43085', (SELECT id FROM City WHERE name = 'Columbus' AND state = 'OH'), (SELECT id FROM Club WHERE name = 'Let''s Get Mahj''d' AND cityId = (SELECT id FROM City WHERE name = 'Columbus' AND state = 'OH')), NULL, 'LESSON', 1, 55.2, 'https://www.eventbrite.com/e/lets-get-mahjd-mahjong-101-tickets-1993541174317', 'https://www.eventbrite.com/e/lets-get-mahjd-mahjong-101-tickets-1993541174317', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_columbus-let-s-get-mahj-d-mahjong-102-20261014', 'Let’s Get Mahj’d: Mahjong 102', 'columbus-let-s-get-mahj-d-mahjong-102-20261014', '2026-10-14 00:00:00', '19:00', NULL, 'BASH! By Young + Wild, 679 High Street, Worthington, OH 43085', (SELECT id FROM City WHERE name = 'Columbus' AND state = 'OH'), (SELECT id FROM Club WHERE name = 'Let''s Get Mahj''d' AND cityId = (SELECT id FROM City WHERE name = 'Columbus' AND state = 'OH')), NULL, 'LESSON', 0, 55.2, 'https://www.eventbrite.com/e/lets-get-mahjd-mahjong-102-tickets-1993541949636', 'https://www.eventbrite.com/e/lets-get-mahjd-mahjong-102-tickets-1993541949636', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_naples-mahj-at-mercato-november-20261110', 'Mahj at Mercato November', 'naples-mahj-at-mercato-november-20261110', '2026-11-10 00:00:00', '18:00', NULL, 'Mercato, 9110 Strada Place, Naples, FL 34108', (SELECT id FROM City WHERE name = 'Naples' AND state = 'FL'), (SELECT id FROM Club WHERE name = 'Naples Mahjong' AND cityId = (SELECT id FROM City WHERE name = 'Naples' AND state = 'FL')), NULL, 'OTHER', 0, 75.48, 'https://www.eventbrite.com/e/mahj-at-mercato-november-tickets-2003019551398', 'https://www.eventbrite.com/e/mahj-at-mercato-november-tickets-2003019551398', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
