INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_boise-curious-about-mahjong-learn-to-play-in-a-2-part-beginner-series-10-8-20261015', 'Curious About Mahjong? Learn to Play in a 2-Part Beginner Series 10.8', 'boise-curious-about-mahjong-learn-to-play-in-a-2-part-beginner-series-10-8-20261015', '2026-10-15 00:00:00', '10:30', NULL, 'LOCAL Boise, 250 East Myrtle Street, Boise, ID 83702', (SELECT id FROM City WHERE name = 'Boise' AND state = 'ID'), NULL, (SELECT id FROM Instructor WHERE name = 'Mahjong at the Local' AND cityId = (SELECT id FROM City WHERE name = 'Boise' AND state = 'ID')), 'LESSON', 1, 58.51, 'https://www.eventbrite.com/e/curious-about-mahjong-learn-to-play-in-a-2-part-beginner-series-108-tickets-2000010017802', 'https://www.eventbrite.com/e/curious-about-mahjong-learn-to-play-in-a-2-part-beginner-series-108-tickets-2000010017802', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_boise-curious-about-mahjong-learn-to-play-in-a-2-part-beginner-series-sat-10-17-20261017', 'Curious About Mahjong? Learn to Play in a 2-Part Beginner Series Sat 10.17', 'boise-curious-about-mahjong-learn-to-play-in-a-2-part-beginner-series-sat-10-17-20261017', '2026-10-17 00:00:00', '10:00', NULL, 'LOCAL Boise, 250 East Myrtle Street, Boise, ID 83702', (SELECT id FROM City WHERE name = 'Boise' AND state = 'ID'), NULL, (SELECT id FROM Instructor WHERE name = 'Mahjong at the Local' AND cityId = (SELECT id FROM City WHERE name = 'Boise' AND state = 'ID')), 'LESSON', 1, 58.51, 'https://www.eventbrite.com/e/curious-about-mahjong-learn-to-play-in-a-2-part-beginner-series-sat-1017-tickets-2000962836709', 'https://www.eventbrite.com/e/curious-about-mahjong-learn-to-play-in-a-2-part-beginner-series-sat-1017-tickets-2000962836709', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_fort-lauderdale-mahjong-101-joe-picasso-s-20261012', 'Mahjong 101 @ Joe Picasso''s', 'fort-lauderdale-mahjong-101-joe-picasso-s-20261012', '2026-10-12 00:00:00', '18:30', NULL, 'Joe Picasso''s', (SELECT id FROM City WHERE name = 'Fort Lauderdale' AND state = 'FL'), NULL, (SELECT id FROM Instructor WHERE name = 'Your Mahjong Mama' AND cityId = (SELECT id FROM City WHERE name = 'Fort Lauderdale' AND state = 'FL')), 'LESSON', 1, NULL, 'https://calendly.com/your-mahjong-mama/mahjong-101-joe-picasso/2026-10-12T18', 'https://calendly.com/your-mahjong-mama/mahjong-101-joe-picasso/2026-10-12T18', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_fort-lauderdale-mahjong-101-joe-picasso-s-20261019', 'Mahjong 101 @ Joe Picasso''s', 'fort-lauderdale-mahjong-101-joe-picasso-s-20261019', '2026-10-19 00:00:00', '09:30', NULL, 'Joe Picasso''s', (SELECT id FROM City WHERE name = 'Fort Lauderdale' AND state = 'FL'), NULL, (SELECT id FROM Instructor WHERE name = 'Your Mahjong Mama' AND cityId = (SELECT id FROM City WHERE name = 'Fort Lauderdale' AND state = 'FL')), 'LESSON', 1, NULL, 'https://calendly.com/your-mahjong-mama/mahjong-101-joe-picasso/2026-10-19T09', 'https://calendly.com/your-mahjong-mama/mahjong-101-joe-picasso/2026-10-19T09', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_fort-lauderdale-mahjong-101-hilton-miami-aventura-20261015', 'Mahjong 101 @ Hilton Miami Aventura', 'fort-lauderdale-mahjong-101-hilton-miami-aventura-20261015', '2026-10-15 00:00:00', '18:30', NULL, 'Hilton Miami Aventura', (SELECT id FROM City WHERE name = 'Fort Lauderdale' AND state = 'FL'), NULL, (SELECT id FROM Instructor WHERE name = 'Your Mahjong Mama' AND cityId = (SELECT id FROM City WHERE name = 'Fort Lauderdale' AND state = 'FL')), 'LESSON', 1, NULL, 'https://calendly.com/your-mahjong-mama/mahjong-101-hilton-miami-aventura/2026-10-15T18', 'https://calendly.com/your-mahjong-mama/mahjong-101-hilton-miami-aventura/2026-10-15T18', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_fort-lauderdale-mahjong-102-joe-picasso-s-20261026', 'Mahjong 102 @ Joe Picasso''s', 'fort-lauderdale-mahjong-102-joe-picasso-s-20261026', '2026-10-26 00:00:00', '18:30', NULL, 'Joe Picasso''s', (SELECT id FROM City WHERE name = 'Fort Lauderdale' AND state = 'FL'), NULL, (SELECT id FROM Instructor WHERE name = 'Your Mahjong Mama' AND cityId = (SELECT id FROM City WHERE name = 'Fort Lauderdale' AND state = 'FL')), 'LESSON', 0, NULL, 'https://calendly.com/your-mahjong-mama/mahjong-102-joe-picasso/2026-10-26T18', 'https://calendly.com/your-mahjong-mama/mahjong-102-joe-picasso/2026-10-26T18', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_fort-lauderdale-mahjong-102-joe-picasso-s-20261102', 'Mahjong 102 @ Joe Picasso''s', 'fort-lauderdale-mahjong-102-joe-picasso-s-20261102', '2026-11-02 00:00:00', '09:30', NULL, 'Joe Picasso''s', (SELECT id FROM City WHERE name = 'Fort Lauderdale' AND state = 'FL'), NULL, (SELECT id FROM Instructor WHERE name = 'Your Mahjong Mama' AND cityId = (SELECT id FROM City WHERE name = 'Fort Lauderdale' AND state = 'FL')), 'LESSON', 0, NULL, 'https://calendly.com/your-mahjong-mama/mahjong-102-joe-picasso/2026-11-02T09', 'https://calendly.com/your-mahjong-mama/mahjong-102-joe-picasso/2026-11-02T09', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
