INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_denver-centennial-littleton-mahjong', 'Centennial Littleton Mahjong', 'denver-centennial-littleton-mahjong', 'American/NMJL not stated on the club''s page.', (SELECT id FROM City WHERE name = 'Denver' AND state = 'CO'), NULL, 'https://clm.bamgoodtime.com', NULL, NULL, NULL, NULL, 1, 1, 0, 1, 0, 0, NULL, 'No upcoming sessions listed', 'https://clm.bamgoodtime.com', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_denver-north-end-tile-pile', 'North End Tile Pile', 'denver-north-end-tile-pile', 'American/NMJL not stated on the club''s page.', (SELECT id FROM City WHERE name = 'Denver' AND state = 'CO'), NULL, 'https://north-end-tile-pile.bamgoodtime.com', NULL, NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, NULL, 'No upcoming sessions listed', 'https://north-end-tile-pile.bamgoodtime.com', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_denver-south-denver-mahjong-collective', 'South Denver Mahjong Collective', 'denver-south-denver-mahjong-collective', 'American/NMJL not stated on the club''s page.', (SELECT id FROM City WHERE name = 'Denver' AND state = 'CO'), NULL, 'https://south-denver-mahjong-collective.bamgoodtime.com', NULL, NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, NULL, 'No upcoming sessions listed', 'https://south-denver-mahjong-collective.bamgoodtime.com', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_denver-flatirons-flowers-mahjong', 'Flatirons Flowers Mahjong', 'denver-flatirons-flowers-mahjong', 'Site says: "Broomfield, Thornton, Brighton, Northglenn, Westminster, Colorado American Mahjong Community"', (SELECT id FROM City WHERE name = 'Denver' AND state = 'CO'), NULL, 'https://flatironsflowersmahjong.bamgoodtime.com', NULL, NULL, NULL, NULL, 1, 1, 0, 1, 0, 0, NULL, '50 upcoming session(s) listed, next 2026-10-11', 'https://flatironsflowersmahjong.bamgoodtime.com', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_denver-nmjl-open-play-at-dogooder-games-in-thornton-20261011', 'NMJL Open Play at DoGooder Games in Thornton', 'denver-nmjl-open-play-at-dogooder-games-in-thornton-20261011', '2026-10-11 00:00:00', '10:00', NULL, 'DoGooder 16639 Washington St, Thornton, CO 80023', (SELECT id FROM City WHERE name = 'Denver' AND state = 'CO'), (SELECT id FROM Club WHERE slug = 'denver-flatirons-flowers-mahjong'), NULL, 'OPEN_PLAY', 0, NULL, 'https://flatironsflowersmahjong.bamgoodtime.com/events/d15dc7b2-57ce-4598-b6d1-6118887c9abd', 'https://flatironsflowersmahjong.bamgoodtime.com/events/d15dc7b2-57ce-4598-b6d1-6118887c9abd', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_denver-american-mahjong-open-play-at-chicken-n-pickle-20261012', 'American Mahjong Open Play at Chicken N Pickle', 'denver-american-mahjong-open-play-at-chicken-n-pickle-20261012', '2026-10-12 00:00:00', '18:00', NULL, 'Chicken N Pickle in Thornton, CO', (SELECT id FROM City WHERE name = 'Denver' AND state = 'CO'), (SELECT id FROM Club WHERE slug = 'denver-flatirons-flowers-mahjong'), NULL, 'OPEN_PLAY', 0, NULL, 'https://flatironsflowersmahjong.bamgoodtime.com/events/b0a27119-d32d-4125-bcd9-5f3aadd48b8c', 'https://flatironsflowersmahjong.bamgoodtime.com/events/b0a27119-d32d-4125-bcd9-5f3aadd48b8c', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_denver-daytime-open-play-at-cottonwood-lodge-restaurant-20261013', 'Daytime Open Play at Cottonwood Lodge Restaurant', 'denver-daytime-open-play-at-cottonwood-lodge-restaurant-20261013', '2026-10-13 00:00:00', '12:00', NULL, 'Cottonwood Lodge at Hyland Hills -9650 Sheridan Blvd', (SELECT id FROM City WHERE name = 'Denver' AND state = 'CO'), (SELECT id FROM Club WHERE slug = 'denver-flatirons-flowers-mahjong'), NULL, 'OPEN_PLAY', 0, NULL, 'https://flatironsflowersmahjong.bamgoodtime.com/events/57e58ef2-72c4-4987-a2b2-cc08f3d2f528', 'https://flatironsflowersmahjong.bamgoodtime.com/events/57e58ef2-72c4-4987-a2b2-cc08f3d2f528', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_denver-wheat-ridge-prost-biergarten-american-mahjong-open-play-20261013', 'Wheat Ridge Prost Biergarten American Mahjong Open Play', 'denver-wheat-ridge-prost-biergarten-american-mahjong-open-play-20261013', '2026-10-13 00:00:00', '18:00', NULL, 'Prost Wheat Ridge 3801 Crossing Dr (wheat ridge)', (SELECT id FROM City WHERE name = 'Denver' AND state = 'CO'), (SELECT id FROM Club WHERE slug = 'denver-flatirons-flowers-mahjong'), NULL, 'OPEN_PLAY', 0, NULL, 'https://flatironsflowersmahjong.bamgoodtime.com/events/ea875d33-8ef4-4419-b2e6-1ecbccffb882', 'https://flatironsflowersmahjong.bamgoodtime.com/events/ea875d33-8ef4-4419-b2e6-1ecbccffb882', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_denver-american-mahjong-open-play-at-prost-biergarten-in-northglenn-20261014', 'American Mahjong Open Play at Prost Biergarten in Northglenn', 'denver-american-mahjong-open-play-at-prost-biergarten-in-northglenn-20261014', '2026-10-14 00:00:00', '18:00', NULL, 'Prost Biergarten in Northglenn', (SELECT id FROM City WHERE name = 'Denver' AND state = 'CO'), (SELECT id FROM Club WHERE slug = 'denver-flatirons-flowers-mahjong'), NULL, 'OPEN_PLAY', 0, NULL, 'https://flatironsflowersmahjong.bamgoodtime.com/events/5285de1f-08ce-4740-a6c0-d86365afa7f4', 'https://flatironsflowersmahjong.bamgoodtime.com/events/5285de1f-08ce-4740-a6c0-d86365afa7f4', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_denver-american-mahjong-open-play-at-county-road-social-20261015', 'American Mahjong Open Play at County Road Social', 'denver-american-mahjong-open-play-at-county-road-social-20261015', '2026-10-15 00:00:00', '18:00', NULL, 'County Road Social 7865 County Rd 2, Brighton, CO 80603', (SELECT id FROM City WHERE name = 'Denver' AND state = 'CO'), (SELECT id FROM Club WHERE slug = 'denver-flatirons-flowers-mahjong'), NULL, 'OPEN_PLAY', 0, NULL, 'https://flatironsflowersmahjong.bamgoodtime.com/events/47d0c084-096a-4b58-ad1a-c8e439c900b4', 'https://flatironsflowersmahjong.bamgoodtime.com/events/47d0c084-096a-4b58-ad1a-c8e439c900b4', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_denver-nmjl-open-play-at-dogooder-games-in-thornton-20261018', 'NMJL Open Play at DoGooder Games in Thornton', 'denver-nmjl-open-play-at-dogooder-games-in-thornton-20261018', '2026-10-18 00:00:00', '10:00', NULL, 'DoGooder 16639 Washington St, Thornton, CO 80023', (SELECT id FROM City WHERE name = 'Denver' AND state = 'CO'), (SELECT id FROM Club WHERE slug = 'denver-flatirons-flowers-mahjong'), NULL, 'OPEN_PLAY', 0, NULL, 'https://flatironsflowersmahjong.bamgoodtime.com/events/55881a7d-66f2-408c-81ce-72444b075439', 'https://flatironsflowersmahjong.bamgoodtime.com/events/55881a7d-66f2-408c-81ce-72444b075439', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_denver-chicken-n-pickle-american-mahjong-open-play-20261019', 'Chicken N Pickle American Mahjong Open Play', 'denver-chicken-n-pickle-american-mahjong-open-play-20261019', '2026-10-19 00:00:00', '18:00', NULL, 'Chicken N Pickle in Thornton, CO', (SELECT id FROM City WHERE name = 'Denver' AND state = 'CO'), (SELECT id FROM Club WHERE slug = 'denver-flatirons-flowers-mahjong'), NULL, 'OPEN_PLAY', 0, NULL, 'https://flatironsflowersmahjong.bamgoodtime.com/events/cbbfbfa6-2690-4092-84d6-0a4e2181ebf4', 'https://flatironsflowersmahjong.bamgoodtime.com/events/cbbfbfa6-2690-4092-84d6-0a4e2181ebf4', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_denver-mahjong-101-with-marie-hennecart-in-thornton-20261020', 'Mahjong 101 with Marie Hennecart in Thornton', 'denver-mahjong-101-with-marie-hennecart-in-thornton-20261020', '2026-10-20 00:00:00', '11:00', NULL, 'Do Gooder Games Cafe 16639 Washington St, Thornton, CO 80023, United States', (SELECT id FROM City WHERE name = 'Denver' AND state = 'CO'), (SELECT id FROM Club WHERE slug = 'denver-flatirons-flowers-mahjong'), NULL, 'LESSON', 1, 60, 'https://flatironsflowersmahjong.bamgoodtime.com/events/a075bb94-6979-41e0-9c95-6ee8f79db21d', 'https://flatironsflowersmahjong.bamgoodtime.com/events/a075bb94-6979-41e0-9c95-6ee8f79db21d', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_denver-daytime-open-play-at-cottonwood-lodge-restaurant-20261020', 'Daytime Open Play at Cottonwood Lodge Restaurant', 'denver-daytime-open-play-at-cottonwood-lodge-restaurant-20261020', '2026-10-20 00:00:00', '12:00', NULL, 'Cottonwood Lodge at Hyland Hills -9650 Sheridan Blvd', (SELECT id FROM City WHERE name = 'Denver' AND state = 'CO'), (SELECT id FROM Club WHERE slug = 'denver-flatirons-flowers-mahjong'), NULL, 'OPEN_PLAY', 0, NULL, 'https://flatironsflowersmahjong.bamgoodtime.com/events/f0f3338b-7775-4f0c-941d-9e7215e9fee2', 'https://flatironsflowersmahjong.bamgoodtime.com/events/f0f3338b-7775-4f0c-941d-9e7215e9fee2', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_denver-american-mahjong-open-play-at-prost-biergarten-in-northglenn-20261021', 'American Mahjong Open Play at Prost Biergarten in Northglenn', 'denver-american-mahjong-open-play-at-prost-biergarten-in-northglenn-20261021', '2026-10-21 00:00:00', '18:00', NULL, 'Prost Biergarten in Northglenn', (SELECT id FROM City WHERE name = 'Denver' AND state = 'CO'), (SELECT id FROM Club WHERE slug = 'denver-flatirons-flowers-mahjong'), NULL, 'OPEN_PLAY', 0, NULL, 'https://flatironsflowersmahjong.bamgoodtime.com/events/db3773ff-f4ce-476f-9074-bd3c90652e89', 'https://flatironsflowersmahjong.bamgoodtime.com/events/db3773ff-f4ce-476f-9074-bd3c90652e89', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_denver-denver-open-play-at-molly-brown-distillery-20261023', 'Denver: Open Play at Molly Brown Distillery', 'denver-denver-open-play-at-molly-brown-distillery-20261023', '2026-10-23 00:00:00', '18:30', NULL, '2300 E 77th Ave, Unit 300A Denver, CO 80229', (SELECT id FROM City WHERE name = 'Denver' AND state = 'CO'), (SELECT id FROM Club WHERE slug = 'denver-flatirons-flowers-mahjong'), NULL, 'OPEN_PLAY', 0, NULL, 'https://flatironsflowersmahjong.bamgoodtime.com/events/5b86e5c1-1e38-4946-8f7e-49e5151b912a', 'https://flatironsflowersmahjong.bamgoodtime.com/events/5b86e5c1-1e38-4946-8f7e-49e5151b912a', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_denver-chicken-n-pickle-american-mahjong-open-play-20261026', 'Chicken N Pickle American Mahjong Open Play', 'denver-chicken-n-pickle-american-mahjong-open-play-20261026', '2026-10-26 00:00:00', '18:00', NULL, 'Chicken N Pickle in Thornton, CO', (SELECT id FROM City WHERE name = 'Denver' AND state = 'CO'), (SELECT id FROM Club WHERE slug = 'denver-flatirons-flowers-mahjong'), NULL, 'OPEN_PLAY', 0, NULL, 'https://flatironsflowersmahjong.bamgoodtime.com/events/39095daa-4870-46d2-b460-db841a5140e9', 'https://flatironsflowersmahjong.bamgoodtime.com/events/39095daa-4870-46d2-b460-db841a5140e9', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_denver-daytime-open-play-at-cottonwood-lodge-restaurant-20261027', 'Daytime Open Play at Cottonwood Lodge Restaurant', 'denver-daytime-open-play-at-cottonwood-lodge-restaurant-20261027', '2026-10-27 00:00:00', '12:00', NULL, 'Cottonwood Lodge at Hyland Hills -9650 Sheridan Blvd', (SELECT id FROM City WHERE name = 'Denver' AND state = 'CO'), (SELECT id FROM Club WHERE slug = 'denver-flatirons-flowers-mahjong'), NULL, 'OPEN_PLAY', 0, NULL, 'https://flatironsflowersmahjong.bamgoodtime.com/events/b8dfd19a-8ec4-4cde-afdd-ea2413aa687a', 'https://flatironsflowersmahjong.bamgoodtime.com/events/b8dfd19a-8ec4-4cde-afdd-ea2413aa687a', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_denver-american-mahjong-open-play-at-prost-biergarten-in-northglenn-20261028', 'American Mahjong Open Play at Prost Biergarten in Northglenn', 'denver-american-mahjong-open-play-at-prost-biergarten-in-northglenn-20261028', '2026-10-28 00:00:00', '18:00', NULL, 'Prost Biergarten in Northglenn', (SELECT id FROM City WHERE name = 'Denver' AND state = 'CO'), (SELECT id FROM Club WHERE slug = 'denver-flatirons-flowers-mahjong'), NULL, 'OPEN_PLAY', 0, NULL, 'https://flatironsflowersmahjong.bamgoodtime.com/events/91c4e5d1-0e11-4607-80f5-365fd0bc9aa2', 'https://flatironsflowersmahjong.bamgoodtime.com/events/91c4e5d1-0e11-4607-80f5-365fd0bc9aa2', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_denver-mahjong-101-with-marie-hennecart-in-thornton-20261029', 'Mahjong 101 with Marie Hennecart in Thornton', 'denver-mahjong-101-with-marie-hennecart-in-thornton-20261029', '2026-10-29 00:00:00', '17:00', NULL, 'Do Gooder Games Cafe 16639 Washington St, Thornton, CO 80023, United States', (SELECT id FROM City WHERE name = 'Denver' AND state = 'CO'), (SELECT id FROM Club WHERE slug = 'denver-flatirons-flowers-mahjong'), NULL, 'LESSON', 1, 60, 'https://flatironsflowersmahjong.bamgoodtime.com/events/e01be380-4411-4fec-9710-7e419d3b6cf5', 'https://flatironsflowersmahjong.bamgoodtime.com/events/e01be380-4411-4fec-9710-7e419d3b6cf5', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_denver-bewitched-by-mahjong-a-halloween-themed-open-play-20261029', 'Bewitched by Mahjong: A Halloween themed open play', 'denver-bewitched-by-mahjong-a-halloween-themed-open-play-20261029', '2026-10-29 00:00:00', '18:00', NULL, '12716 Lowell Blvd. Broomfield, CO 80020 at Planks & Paint DIY Workshop', (SELECT id FROM City WHERE name = 'Denver' AND state = 'CO'), (SELECT id FROM Club WHERE slug = 'denver-flatirons-flowers-mahjong'), NULL, 'OPEN_PLAY', 0, 20, 'https://flatironsflowersmahjong.bamgoodtime.com/events/1a606b85-ca25-45b4-b6fa-241645648367', 'https://flatironsflowersmahjong.bamgoodtime.com/events/1a606b85-ca25-45b4-b6fa-241645648367', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_denver-american-mahjong-open-play-at-county-road-social-20261029', 'American Mahjong Open Play at County Road Social', 'denver-american-mahjong-open-play-at-county-road-social-20261029', '2026-10-29 00:00:00', '18:00', NULL, 'County Road Social 7865 County Rd 2, Brighton, CO 80603', (SELECT id FROM City WHERE name = 'Denver' AND state = 'CO'), (SELECT id FROM Club WHERE slug = 'denver-flatirons-flowers-mahjong'), NULL, 'OPEN_PLAY', 0, NULL, 'https://flatironsflowersmahjong.bamgoodtime.com/events/f3696d6b-3ceb-457b-9a22-8fbfdadde180', 'https://flatironsflowersmahjong.bamgoodtime.com/events/f3696d6b-3ceb-457b-9a22-8fbfdadde180', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_denver-advanced-mahjong-strategy-class-with-audrey-irwin-hosted-by-colorado-mah-jongg-flatirons-flowers-mahjong-superior-20261101', 'Advanced Mahjong Strategy Class with Audrey Irwin hosted by Colorado Mah Jongg & Flatirons Flowers Mahjong (Superior)', 'denver-advanced-mahjong-strategy-class-with-audrey-irwin-hosted-by-colorado-mah-jongg-flatirons-flowers-mahjong-superior-20261101', '2026-11-01 00:00:00', '09:00', NULL, 'Blue Sport Stable 1 Superior Drive, Superior, Colorado', (SELECT id FROM City WHERE name = 'Denver' AND state = 'CO'), (SELECT id FROM Club WHERE slug = 'denver-flatirons-flowers-mahjong'), NULL, 'LESSON', 0, 25, 'https://flatironsflowersmahjong.bamgoodtime.com/events/2f279859-4e88-40fa-ba57-8029e57e5a5d', 'https://flatironsflowersmahjong.bamgoodtime.com/events/2f279859-4e88-40fa-ba57-8029e57e5a5d', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_denver-advanced-mahjong-strategy-class-with-audrey-irwin-hosted-by-colorado-mah-jongg-flatirons-flowers-mahjong-westminster-20261101', 'Advanced Mahjong Strategy Class with Audrey Irwin hosted by Colorado Mah Jongg & Flatirons Flowers Mahjong (Westminster)', 'denver-advanced-mahjong-strategy-class-with-audrey-irwin-hosted-by-colorado-mah-jongg-flatirons-flowers-mahjong-westminster-20261101', '2026-11-01 00:00:00', '13:30', NULL, 'The Bradburn Clubhouse, 4050 W 118th Pl, Westminster, CO 80031', (SELECT id FROM City WHERE name = 'Denver' AND state = 'CO'), (SELECT id FROM Club WHERE slug = 'denver-flatirons-flowers-mahjong'), NULL, 'LESSON', 0, 25, 'https://flatironsflowersmahjong.bamgoodtime.com/events/63b5f7c0-216a-4185-850b-bc0a4ce08b52', 'https://flatironsflowersmahjong.bamgoodtime.com/events/63b5f7c0-216a-4185-850b-bc0a4ce08b52', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_denver-flatirons-flowers-american-mah-jongg-rookie-tournament-benefiting-the-bodhi-battalion-20261107', 'Flatirons Flowers: American Mah Jongg Rookie Tournament Benefiting the Bodhi Battalion', 'denver-flatirons-flowers-american-mah-jongg-rookie-tournament-benefiting-the-bodhi-battalion-20261107', '2026-11-07 00:00:00', '10:45', NULL, 'Anythink Nature Library 6811 E 136th Ave, Thornton, CO 80602', (SELECT id FROM City WHERE name = 'Denver' AND state = 'CO'), (SELECT id FROM Club WHERE slug = 'denver-flatirons-flowers-mahjong'), NULL, 'TOURNAMENT', 0, 65, 'https://flatironsflowersmahjong.bamgoodtime.com/events/8cabe8fc-295c-4f37-bb8f-ae56c51e7c39', 'https://flatironsflowersmahjong.bamgoodtime.com/events/8cabe8fc-295c-4f37-bb8f-ae56c51e7c39', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_dallas-mahj-my-day', 'Mahj My Day', 'dallas-mahj-my-day', 'American/NMJL not stated on the club''s page.', (SELECT id FROM City WHERE name = 'Dallas' AND state = 'TX'), NULL, 'https://mahj-my-day.bamgoodtime.com', NULL, NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, NULL, 'No upcoming sessions listed', 'https://mahj-my-day.bamgoodtime.com', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_dallas-rack-and-rollers', 'Rack and Rollers', 'dallas-rack-and-rollers', 'American/NMJL not stated on the club''s page.', (SELECT id FROM City WHERE name = 'Dallas' AND state = 'TX'), NULL, 'https://rack-and-rollers.bamgoodtime.com', NULL, NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, NULL, 'No upcoming sessions listed', 'https://rack-and-rollers.bamgoodtime.com', '2026-10-09', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
