INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_naples-paradise-coast-mahjong', 'Paradise Coast Mahjong', 'naples-paradise-coast-mahjong', 'Mahjong venue in North Naples (Vanderbilt Beach Rd) with lessons and open play; membership options. Official site: "Our American Mahjong lessons take you from ''What''s a Bam?'' to calling your first ''Mahjong!'' in no time." Site says the venue opens Friday Oct 16 (year not stated). The NMJL card is not named explicitly.', (SELECT id FROM City WHERE name = 'Naples' AND state = 'FL'), '2371 Vanderbilt Beach Rd, Unit 705, Naples, FL 34109', 'https://www.paradisecoastmahjong.com', '(239) 496-5889', 'hello@paradisecoastmahjong.com', NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Open play schedule loads dynamically (calendar.html); not readable', 'https://www.paradisecoastmahjong.com', '2026-10-10', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_naples-naples-mahjong', 'Naples Mahjong', 'naples-naples-mahjong', 'Event-based mahjong group hosting open play and socials at Naples restaurants and shops (tickets via Eventbrite). Official site header: "Bringing American Mahjong to Naples". NMJL card not named explicitly.', (SELECT id FROM City WHERE name = 'Naples' AND state = 'FL'), 'Naples, FL', 'https://www.naplesmahjong.com/', NULL, NULL, NULL, NULL, 0, 0, 1, 1, 0, 0, NULL, 'Multiple events per month; see events', 'https://www.naplesmahjong.com/', '2026-10-10', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_naples-good-pour-event-20261029', 'Good Pour Event', 'naples-good-pour-event-20261029', '2026-10-29 00:00:00', '18:00', NULL, 'Good Pour', (SELECT id FROM City WHERE name = 'Naples' AND state = 'FL'), (SELECT id FROM Club WHERE slug = 'naples-naples-mahjong'), NULL, 'SOCIAL', 0, NULL, 'https://www.naplesmahjong.com/', 'https://www.naplesmahjong.com/', '2026-10-10', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_cleveland-mahjong-halloween-open-play-20261031', 'Mahjong Halloween Open Play', 'cleveland-mahjong-halloween-open-play-20261031', '2026-10-31 00:00:00', '11:30', NULL, 'Nourishing Nook, 14150 Pearl Road, Strongsville, OH 44136', (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH'), (SELECT id FROM Club WHERE name = 'Southwest Cleveland Mahjong' AND cityId = (SELECT id FROM City WHERE name = 'Cleveland' AND state = 'OH')), NULL, 'OPEN_PLAY', 0, 10, 'https://www.eventbrite.com/e/mahjong-halloween-open-play-tickets-2003206222737', 'https://www.eventbrite.com/e/mahjong-halloween-open-play-tickets-2003206222737', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_san-antonio-mahj-and-mingle-bingo-20261015', 'Mahj and Mingle Bingo!', 'san-antonio-mahj-and-mingle-bingo-20261015', '2026-10-15 00:00:00', '11:00', NULL, 'The Polished Tile', (SELECT id FROM City WHERE name = 'San Antonio' AND state = 'TX'), (SELECT id FROM Club WHERE name = 'The Polished Tile' AND cityId = (SELECT id FROM City WHERE name = 'San Antonio' AND state = 'TX')), NULL, 'OTHER', 0, 25, 'https://play.thepolishedtile.com/events/1fc39840-aa85-4833-bd09-6217efeac1ec', 'https://play.thepolishedtile.com/events/1fc39840-aa85-4833-bd09-6217efeac1ec', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_tampa-intermediate-advanced-open-play-mah-jongg-20261021', 'Intermediate/Advanced Open Play Mah Jongg', 'tampa-intermediate-advanced-open-play-mah-jongg-20261021', '2026-10-21 00:00:00', '13:00', NULL, 'Life Enrichment Center, 9704 North Boulevard, Tampa, FL', (SELECT id FROM City WHERE name = 'Tampa' AND state = 'FL'), (SELECT id FROM Club WHERE name = 'Life Enrichment Center - Open Play Mah Jongg' AND cityId = (SELECT id FROM City WHERE name = 'Tampa' AND state = 'FL')), NULL, 'OPEN_PLAY', 0, NULL, 'https://www.meetup.com/lectampa/events/316800009/', 'https://www.meetup.com/lectampa/events/316800009/', '2026-10-09', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
