INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_birmingham-mah-jongg-meet-up-20261019', 'Mah Jongg Meet Up', 'birmingham-mah-jongg-meet-up-20261019', '2026-10-19 00:00:00', '10:00', '12:00', 'Mountain Brook Baptist Church', (SELECT id FROM City WHERE name = 'Birmingham' AND state = 'AL'), (SELECT id FROM Club WHERE name = 'O''Neal Library Mah Jongg Meetup' AND cityId = (SELECT id FROM City WHERE name = 'Birmingham' AND state = 'AL')), NULL, 'OPEN_PLAY', 1, NULL, 'https://oneallibrary.org/event/16690967', 'https://oneallibrary.org/event/16690967', '2026-10-11', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_baltimore-mahj-and-stitch-night-hillside-needlearts-20261119', 'Mahj and Stitch Night Hillside Needlearts', 'baltimore-mahj-and-stitch-night-hillside-needlearts-20261119', '2026-11-19 00:00:00', '18:00', NULL, 'Hillside Needlearts- 10437 Stevenson Rd Stevenson, MD 21153 United States', (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD'), (SELECT id FROM Club WHERE name = 'The Tiles Social Club' AND cityId = (SELECT id FROM City WHERE name = 'Baltimore' AND state = 'MD')), NULL, 'LESSON', 0, 25, 'https://tilessocialclub.bamgoodtime.com/events/79cad535-1c48-4b7c-a3fb-b0e560ce5ff8', 'https://tilessocialclub.bamgoodtime.com/events/79cad535-1c48-4b7c-a3fb-b0e560ce5ff8', '2026-10-10', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_houston-mah-jongg-20261209', 'Mah Jongg', 'houston-mah-jongg-20261209', '2026-12-09 00:00:00', '10:00', NULL, 'HCRJ, 801 Bering Dr. , Houston, TX', (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX'), (SELECT id FROM Club WHERE name = 'Houston Congregation for Reform Judaism Mah Jongg' AND cityId = (SELECT id FROM City WHERE name = 'Houston' AND state = 'TX')), NULL, 'OTHER', 0, NULL, 'https://hcrj.org/event/mah-jongg/2026-12-09/', 'https://hcrj.org/event/mah-jongg/2026-12-09/', '2026-10-10', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_phoenix-mahjong-at-fate-brewing-20261209', 'Mahjong at Fate Brewing', 'phoenix-mahjong-at-fate-brewing-20261209', '2026-12-09 00:00:00', '17:00', NULL, 'Fate Brewing Company, 4445 N 7th Street, Phoenix, AZ', (SELECT id FROM City WHERE name = 'Phoenix' AND state = 'AZ'), (SELECT id FROM Club WHERE name = 'Mahjong for People who Work' AND cityId = (SELECT id FROM City WHERE name = 'Phoenix' AND state = 'AZ')), NULL, 'OTHER', 0, NULL, 'https://www.meetup.com/american-mahjong-for-people-who-work/events/bjzbztyjcqbmb/', 'https://www.meetup.com/american-mahjong-for-people-who-work/events/bjzbztyjcqbmb/', '2026-10-10', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
