-- New cities from the club discovery crawler, added unpublished until their groups are confirmed as American.
INSERT OR IGNORE INTO "City" ("id", "name", "state", "slug", "published", "createdAt", "updatedAt") VALUES
('city_cumming', 'Cumming', 'GA', 'cumming', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('city_dayton', 'Dayton', 'OH', 'dayton', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('city_little-elm', 'Little Elm', 'TX', 'little-elm', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_cumming-evenings-at-the-table', 'Evenings at the Table', 'cumming-evenings-at-the-table', 'Site says: "Ready to learn American Mahjong in a welcoming, beginner-friendly setting? Mahjong Foundations is designed to take you from “I’ve always wanted to learn” to confidently joining a table."', (SELECT id FROM City WHERE name = 'Cumming' AND state = 'GA'), NULL, 'https://evenings-at-the-table.bamgoodtime.com', NULL, NULL, NULL, NULL, 1, 1, 0, 1, 0, 0, NULL, '5 upcoming session(s) listed, next 2026-10-12', 'https://evenings-at-the-table.bamgoodtime.com', '2026-10-10', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_cumming-10-12-open-play-20261012', '10/12 Open Play', 'cumming-10-12-open-play-20261012', '2026-10-12 00:00:00', '17:00', NULL, 'Talk of the Table', (SELECT id FROM City WHERE name = 'Cumming' AND state = 'GA'), (SELECT id FROM Club WHERE slug = 'cumming-evenings-at-the-table'), NULL, 'OPEN_PLAY', 0, 15, 'https://evenings-at-the-table.bamgoodtime.com/events/11a9cf8a-df5c-4490-8284-0fe7a218fc19', 'https://evenings-at-the-table.bamgoodtime.com/events/11a9cf8a-df5c-4490-8284-0fe7a218fc19', '2026-10-10', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_cumming-10-12-league-makeup-20261012', '10/12 League Makeup', 'cumming-10-12-league-makeup-20261012', '2026-10-12 00:00:00', '17:30', NULL, NULL, (SELECT id FROM City WHERE name = 'Cumming' AND state = 'GA'), (SELECT id FROM Club WHERE slug = 'cumming-evenings-at-the-table'), NULL, 'TOURNAMENT', 0, NULL, 'https://evenings-at-the-table.bamgoodtime.com/events/9c796039-5a08-4e98-8417-e37676811c92', 'https://evenings-at-the-table.bamgoodtime.com/events/9c796039-5a08-4e98-8417-e37676811c92', '2026-10-10', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_cumming-10-19-open-play-20261019', '10/19 Open Play', 'cumming-10-19-open-play-20261019', '2026-10-19 00:00:00', '17:00', NULL, 'Talk of the Table', (SELECT id FROM City WHERE name = 'Cumming' AND state = 'GA'), (SELECT id FROM Club WHERE slug = 'cumming-evenings-at-the-table'), NULL, 'OPEN_PLAY', 0, 15, 'https://evenings-at-the-table.bamgoodtime.com/events/0671c649-afb5-49f9-92df-2838f5dcc8c7', 'https://evenings-at-the-table.bamgoodtime.com/events/0671c649-afb5-49f9-92df-2838f5dcc8c7', '2026-10-10', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_cumming-10-26-open-play-20261026', '10/26 Open Play', 'cumming-10-26-open-play-20261026', '2026-10-26 00:00:00', '17:00', NULL, 'Talk of the Table', (SELECT id FROM City WHERE name = 'Cumming' AND state = 'GA'), (SELECT id FROM Club WHERE slug = 'cumming-evenings-at-the-table'), NULL, 'OPEN_PLAY', 0, 15, 'https://evenings-at-the-table.bamgoodtime.com/events/80345470-acc7-402b-8496-171e88ca6fa6', 'https://evenings-at-the-table.bamgoodtime.com/events/80345470-acc7-402b-8496-171e88ca6fa6', '2026-10-10', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_cumming-11-2-open-play-20261102', '11/2 Open Play', 'cumming-11-2-open-play-20261102', '2026-11-02 00:00:00', '17:00', NULL, 'Talk of the Table', (SELECT id FROM City WHERE name = 'Cumming' AND state = 'GA'), (SELECT id FROM Club WHERE slug = 'cumming-evenings-at-the-table'), NULL, 'OPEN_PLAY', 0, 15, 'https://evenings-at-the-table.bamgoodtime.com/events/845794ec-a8e8-4bcc-8384-ee18d2480123', 'https://evenings-at-the-table.bamgoodtime.com/events/845794ec-a8e8-4bcc-8384-ee18d2480123', '2026-10-10', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_dayton-dayton-ohio-mah-jongg', 'Dayton Ohio Mah Jongg', 'dayton-dayton-ohio-mah-jongg', 'Site says: "Introduction to American Mah Jongg"', (SELECT id FROM City WHERE name = 'Dayton' AND state = 'OH'), NULL, 'https://dayton-ohio-mah-jongg.bamgoodtime.com', NULL, NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, NULL, '1 upcoming session(s) listed, next 2026-10-10', 'https://dayton-ohio-mah-jongg.bamgoodtime.com', '2026-10-10', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_dayton-introduction-to-american-mah-jongg-20261010', 'Introduction to American Mah Jongg', 'dayton-introduction-to-american-mah-jongg-20261010', '2026-10-10 00:00:00', '10:30', NULL, 'Dayton Metro Main Library, Conference Rm. 1B, 211 E. Third St., Dayton OH', (SELECT id FROM City WHERE name = 'Dayton' AND state = 'OH'), (SELECT id FROM Club WHERE slug = 'dayton-dayton-ohio-mah-jongg'), NULL, 'LESSON', 1, NULL, 'https://dayton-ohio-mah-jongg.bamgoodtime.com/events/d6b324ca-aa43-4615-831a-827f57977b72', 'https://dayton-ohio-mah-jongg.bamgoodtime.com/events/d6b324ca-aa43-4615-831a-827f57977b72', '2026-10-10', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_little-elm-north-texas-mahjong', 'North Texas Mahjong', 'little-elm-north-texas-mahjong', 'Site says: "NTX Mahjong Academy: American Mahjong Foundations Workshop (TinMan Social Little Elm, TX)"', (SELECT id FROM City WHERE name = 'Little Elm' AND state = 'TX'), NULL, 'https://ntxmahjong.bamgoodtime.com', NULL, NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, NULL, '6 upcoming session(s) listed, next 2026-10-12', 'https://ntxmahjong.bamgoodtime.com', '2026-10-10', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_little-elm-ntx-mahjong-open-play-tinman-social-little-elm-tx-20261012', 'NTX Mahjong Open Play (TinMan Social Little Elm, TX)', 'little-elm-ntx-mahjong-open-play-tinman-social-little-elm-tx-20261012', '2026-10-12 00:00:00', '18:00', NULL, 'TinMan Social Little Elm, TX', (SELECT id FROM City WHERE name = 'Little Elm' AND state = 'TX'), (SELECT id FROM Club WHERE slug = 'little-elm-north-texas-mahjong'), NULL, 'OPEN_PLAY', 0, 20, 'https://ntxmahjong.bamgoodtime.com/events/b330c9ef-2e35-4927-83de-5c478c62c603', 'https://ntxmahjong.bamgoodtime.com/events/b330c9ef-2e35-4927-83de-5c478c62c603', '2026-10-10', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_little-elm-ntx-mahjong-academy-american-mahjong-foundations-workshop-tinman-social-little-elm-tx-20261013', 'NTX Mahjong Academy: American Mahjong Foundations Workshop (TinMan Social Little Elm, TX)', 'little-elm-ntx-mahjong-academy-american-mahjong-foundations-workshop-tinman-social-little-elm-tx-20261013', '2026-10-13 00:00:00', '18:00', NULL, 'TinMan Social Little Elm, TX', (SELECT id FROM City WHERE name = 'Little Elm' AND state = 'TX'), (SELECT id FROM Club WHERE slug = 'little-elm-north-texas-mahjong'), NULL, 'LESSON', 0, 45, 'https://ntxmahjong.bamgoodtime.com/events/0cdd8294-b8cf-45ed-bb0b-899a3bc9a1c6', 'https://ntxmahjong.bamgoodtime.com/events/0cdd8294-b8cf-45ed-bb0b-899a3bc9a1c6', '2026-10-10', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_little-elm-ntx-mahjong-academy-american-mahjong-foundations-workshop-bella-mia-winery-pilot-point-tx-register-on-bella-mia-winery-s-website-20261014', 'NTX Mahjong Academy: American Mahjong Foundations Workshop (Bella Mia Winery, Pilot Point, TX) Register on Bella Mia Winery''s website', 'little-elm-ntx-mahjong-academy-american-mahjong-foundations-workshop-bella-mia-winery-pilot-point-tx-register-on-bella-mia-winery-s-website-20261014', '2026-10-14 00:00:00', '18:00', NULL, 'Bella Mia Winery (Pilot Point, TX)', (SELECT id FROM City WHERE name = 'Little Elm' AND state = 'TX'), (SELECT id FROM Club WHERE slug = 'little-elm-north-texas-mahjong'), NULL, 'LESSON', 0, NULL, 'https://ntxmahjong.bamgoodtime.com/events/60f3ec81-ce26-40e3-8fbc-3fbf7dc809de', 'https://ntxmahjong.bamgoodtime.com/events/60f3ec81-ce26-40e3-8fbc-3fbf7dc809de', '2026-10-10', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_little-elm-ntx-mahjong-open-play-tinman-social-little-elm-tx-20261019', 'NTX Mahjong Open Play (TinMan Social Little Elm, TX)', 'little-elm-ntx-mahjong-open-play-tinman-social-little-elm-tx-20261019', '2026-10-19 00:00:00', '18:00', NULL, 'TinMan Social Little Elm, TX', (SELECT id FROM City WHERE name = 'Little Elm' AND state = 'TX'), (SELECT id FROM Club WHERE slug = 'little-elm-north-texas-mahjong'), NULL, 'OPEN_PLAY', 0, 20, 'https://ntxmahjong.bamgoodtime.com/events/4cccc2d3-c43f-41ca-abbd-448f96666c7c', 'https://ntxmahjong.bamgoodtime.com/events/4cccc2d3-c43f-41ca-abbd-448f96666c7c', '2026-10-10', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_little-elm-ntx-mahjong-open-guided-play-bella-mia-winery-pilot-point-tx-register-on-bella-mia-winery-s-website-20261021', 'NTX Mahjong Open/Guided Play (Bella Mia Winery Pilot Point, TX) Register on Bella Mia Winery''s website', 'little-elm-ntx-mahjong-open-guided-play-bella-mia-winery-pilot-point-tx-register-on-bella-mia-winery-s-website-20261021', '2026-10-21 00:00:00', '18:00', NULL, 'Bella Mia Winery (Pilot Point, TX)', (SELECT id FROM City WHERE name = 'Little Elm' AND state = 'TX'), (SELECT id FROM Club WHERE slug = 'little-elm-north-texas-mahjong'), NULL, 'OPEN_PLAY', 0, NULL, 'https://ntxmahjong.bamgoodtime.com/events/e9fc1f60-1468-4885-9507-598bee8146fa', 'https://ntxmahjong.bamgoodtime.com/events/e9fc1f60-1468-4885-9507-598bee8146fa', '2026-10-10', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_little-elm-ntx-mahjong-boom-bams-jokers-open-play-tinman-social-little-elm-tx-20261026', 'NTX Mahjong Boom, Bams & Jokers Open Play (TinMan Social Little Elm, TX)', 'little-elm-ntx-mahjong-boom-bams-jokers-open-play-tinman-social-little-elm-tx-20261026', '2026-10-26 00:00:00', '18:00', NULL, 'TinMan Social Little Elm, TX', (SELECT id FROM City WHERE name = 'Little Elm' AND state = 'TX'), (SELECT id FROM Club WHERE slug = 'little-elm-north-texas-mahjong'), NULL, 'OPEN_PLAY', 0, 20, 'https://ntxmahjong.bamgoodtime.com/events/ea258181-e7d8-478d-bf8c-ce8f60d3207f', 'https://ntxmahjong.bamgoodtime.com/events/ea258181-e7d8-478d-bf8c-ce8f60d3207f', '2026-10-10', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
