INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_boston-bay-state-bam', 'Bay State Bam', 'boston-bay-state-bam', 'American Mahjong instruction and hosted events across Massachusetts, run by OMM-certified instructor Brittany Ela; home of the Troop Mahjong Boston/Worcester chapter (leagues, socials, open plays).', (SELECT id FROM City WHERE name = 'Boston' AND state = 'MA'), NULL, 'https://www.baystatebam.com/', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Monthly Troop Mahjong league, social and open play events; also hosted private parties.', 'https://www.baystatebam.com/troop-mahjong', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_boston-go-team-pink-and-green-open-play-league-20260929', 'Go Team Pink and Green! Open Play @ League', 'boston-go-team-pink-and-green-open-play-league-20260929', '2026-09-29 00:00:00', '19:00', '22:00', 'Sol De Mexico, Milford, MA', (SELECT id FROM City WHERE name = 'Boston' AND state = 'MA'), (SELECT id FROM Club WHERE slug = 'boston-bay-state-bam'), NULL, 'OPEN_PLAY', 0, NULL, NULL, 'https://www.baystatebam.com/upcoming-events', '2026-09-28', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_boston-pung-kong-pep-rally-open-play-fall-league-20261006', 'Pung, Kong, Pep Rally! Open Play @ Fall League', 'boston-pung-kong-pep-rally-open-play-fall-league-20261006', '2026-10-06 00:00:00', '19:00', '22:00', 'Sol De Mexico, Milford, MA', (SELECT id FROM City WHERE name = 'Boston' AND state = 'MA'), (SELECT id FROM Club WHERE slug = 'boston-bay-state-bam'), NULL, 'OPEN_PLAY', 0, NULL, NULL, 'https://www.baystatebam.com/upcoming-events', '2026-09-28', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
