INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_chicago-the-mahjong-society', 'The Mahjong Society', 'chicago-the-mahjong-society', 'Chicago American Mahjong community offering lessons, open play, leagues and events at rotating venues.', (SELECT id FROM City WHERE name = 'Chicago' AND state = 'IL'), NULL, 'https://themahjongsociety.com/', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Recurring Mahjong 101/102, open play and leagues.', 'https://themahjongsociety.com/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_chicago-mahj-mingle-social-club', 'Mahj & Mingle Social Club', 'chicago-mahj-mingle-social-club', 'Chicago American Mahjong social club offering 101 lessons, guided play, open play and leagues.', (SELECT id FROM City WHERE name = 'Chicago' AND state = 'IL'), NULL, 'https://www.mahjongandminglesocialclub.com/', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, 30, 'Open play events and beginner lessons at Chicago venues.', 'https://www.mahjongandminglesocialclub.com/events', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_chicago-the-mahjong-society', 'The Mahjong Society', 'chicago-the-mahjong-society', (SELECT id FROM City WHERE name = 'Chicago' AND state = 'IL'), 'https://themahjongsociety.com/', 'hello@themahjongsociety.com', 1, 1, 0, 1, NULL, 'American Mahjong 101/102, guided play, private lessons and events.', 'https://themahjongsociety.com/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_chicago-mahj-with-stacey', 'Mahj with Stacey', 'chicago-mahj-with-stacey', (SELECT id FROM City WHERE name = 'Chicago' AND state = 'IL'), NULL, '773-369-8207; [email protected]', 1, 1, 0, 1, NULL, 'Mahjong 101/102/103, private group lessons, corporate events and Monday social club.', 'https://mahjongplaza.com/learning/mahj-with-stacey/', '2026-09-28', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_chicago-lucky-league-drop-in-open-play-at-park-field-20261001', 'Lucky League Drop-In — Open Play at Park & Field', 'chicago-lucky-league-drop-in-open-play-at-park-field-20261001', '2026-10-01 00:00:00', '18:30', '20:30', 'Park & Field, 3509 W Fullerton Ave', (SELECT id FROM City WHERE name = 'Chicago' AND state = 'IL'), (SELECT id FROM Club WHERE slug = 'chicago-the-mahjong-society'), NULL, 'OPEN_PLAY', 0, NULL, NULL, 'https://themahjongsociety.com/event-calendar/fall-lucky-league-single-night-101', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_chicago-open-play-mahjong-x-altar-home-20261008', 'Open Play Mahjong x Altar Home', 'chicago-open-play-mahjong-x-altar-home-20261008', '2026-10-08 00:00:00', '18:00', '20:30', 'Altar Home, 1858 W Chicago Ave', (SELECT id FROM City WHERE name = 'Chicago' AND state = 'IL'), (SELECT id FROM Club WHERE slug = 'chicago-mahj-mingle-social-club'), NULL, 'OPEN_PLAY', 0, 30, NULL, 'https://www.mahjongandminglesocialclub.com/services-store-kduw8/open-play', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_chicago-mahjong-101-at-miru-restaurant-20261026', 'Mahjong 101 at Miru Restaurant', 'chicago-mahjong-101-at-miru-restaurant-20261026', '2026-10-26 00:00:00', '17:30', '20:00', 'Miru Restaurant - The St. Regis, 401 E Wacker Dr', (SELECT id FROM City WHERE name = 'Chicago' AND state = 'IL'), (SELECT id FROM Club WHERE slug = 'chicago-the-mahjong-society'), NULL, 'LESSON', 1, 90, NULL, 'https://themahjongsociety.com/event-calendar/mahjong-101-at-miru-october', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
