INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_dallas-dallas-mahj-club', 'Dallas Mahj Club', 'dallas-dallas-mahj-club', 'American Mahjong club offering private and group lessons and social play in Dallas.', (SELECT id FROM City WHERE name = 'Dallas' AND state = 'TX'), NULL, 'https://www.dallasmahjclub.com/', NULL, NULL, NULL, NULL, 1, 1, 0, 1, 0, 0, NULL, NULL, 'https://www.dallasmahjclub.com/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_dallas-modern-day-mahj', 'Modern Day Mahj', 'dallas-modern-day-mahj', 'Dallas-area American Mahjong organization offering beginner courses, open play, leagues and special events.', (SELECT id FROM City WHERE name = 'Dallas' AND state = 'TX'), NULL, 'https://www.moderndaymahj.com/', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, 180, 'Beginner''s Mahjong Course: $180.', 'https://www.moderndaymahj.com/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_dallas-j-mahj-aaron-family-jewish-community-center-of-dallas', 'J Mahj - Aaron Family Jewish Community Center of Dallas', 'dallas-j-mahj-aaron-family-jewish-community-center-of-dallas', 'American Mahjong program at the Aaron Family Jewish Community Center of Dallas, with scheduled play, theme nights, lessons and leagues.', (SELECT id FROM City WHERE name = 'Dallas' AND state = 'TX'), '7900 Northaven Rd, Dallas, TX 75230', 'https://www.jccdallas.org/j-mahj', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, 40, 'Scheduled play: $40/table for 3 hours; theme nights: $36.', 'https://www.jccdallas.org/j-mahj', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_dallas-mahj-all-day', 'MAHJ ALL DAY', 'dallas-mahj-all-day', 'Dallas American Mahjong instructor and social club offering private and social lessons/play.', (SELECT id FROM City WHERE name = 'Dallas' AND state = 'TX'), NULL, NULL, NULL, NULL, NULL, NULL, 1, 1, 0, 1, 0, 0, 80, '$80/hour per person for lessons.', NULL, '2026-09-28', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_dallas-dallas-mahj-club', 'Dallas Mahj Club', 'dallas-dallas-mahj-club', (SELECT id FROM City WHERE name = 'Dallas' AND state = 'TX'), 'https://www.dallasmahjclub.com/', NULL, 1, 1, 0, 1, NULL, 'American Mahjong instruction; private and group lessons.', 'https://www.dallasmahjclub.com/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_dallas-modern-day-mahj', 'Modern Day Mahj', 'dallas-modern-day-mahj', (SELECT id FROM City WHERE name = 'Dallas' AND state = 'TX'), 'https://www.moderndaymahj.com/', NULL, 0, 1, 0, 1, 180, 'Beginner''s Mahjong Course: $180.', 'https://www.moderndaymahj.com/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_dallas-mahj-all-day', 'MAHJ ALL DAY', 'dallas-mahj-all-day', (SELECT id FROM City WHERE name = 'Dallas' AND state = 'TX'), NULL, NULL, 1, 1, 0, 1, 80, 'Private/small-group American Mahjong lessons; $80/hour per person.', NULL, '2026-09-28', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_dallas-j-dallas-competitive-mahj-league-monday-evenings-20261012', 'J Dallas Competitive Mahj League (Monday Evenings)', 'dallas-j-dallas-competitive-mahj-league-monday-evenings-20261012', '2026-10-12 00:00:00', '18:00', '20:00', 'Aaron Family Jewish Community Center of Dallas', (SELECT id FROM City WHERE name = 'Dallas' AND state = 'TX'), (SELECT id FROM Club WHERE slug = 'dallas-j-mahj-aaron-family-jewish-community-center-of-dallas'), NULL, 'TOURNAMENT', 0, 140, NULL, 'https://www.jccdallas.org/j-mahj', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_dallas-get-your-mahjon-beginner-class-series-october-20261020', 'Get Your MahjON! Beginner Class Series - October', 'dallas-get-your-mahjon-beginner-class-series-october-20261020', '2026-10-20 00:00:00', NULL, NULL, 'Aaron Family Jewish Community Center of Dallas', (SELECT id FROM City WHERE name = 'Dallas' AND state = 'TX'), (SELECT id FROM Club WHERE slug = 'dallas-j-mahj-aaron-family-jewish-community-center-of-dallas'), NULL, 'LESSON', 1, NULL, NULL, 'https://www.jccdallas.org/j-mahj', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_dallas-mah-jongg-supervised-play-20261201', 'Mah Jongg Supervised Play', 'dallas-mah-jongg-supervised-play-20261201', '2026-12-01 00:00:00', NULL, NULL, 'Aaron Family Jewish Community Center of Dallas', (SELECT id FROM City WHERE name = 'Dallas' AND state = 'TX'), (SELECT id FROM Club WHERE slug = 'dallas-j-mahj-aaron-family-jewish-community-center-of-dallas'), NULL, 'OPEN_PLAY', 1, NULL, NULL, 'https://www.jccdallas.org/j-mahj', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
