INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_los-angeles-mahjong-smiles', 'Mahjong Smiles', 'los-angeles-mahjong-smiles', 'Los Angeles American Mahjong teaching and events organization offering hosted classes, private experiences and guided play.', (SELECT id FROM City WHERE name = 'Los Angeles' AND state = 'CA'), NULL, 'https://mahjongsmiles.com/', NULL, NULL, NULL, NULL, 1, 1, 0, 1, 0, 0, NULL, 'Hosted group beginner series, private classes and guided play.', 'https://mahjongsmiles.com/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_los-angeles-la-la-mahjong', 'LA LA Mahjong', 'los-angeles-la-la-mahjong', 'Los Angeles American Mahjong community offering beginner classes, events and league play under NMJL rules.', (SELECT id FROM City WHERE name = 'Los Angeles' AND state = 'CA'), NULL, 'https://lalamahjong.com/', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Beginner 101, 102 guided play, events and leagues.', 'https://lalamahjong.com/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_los-angeles-mahjong-smiles', 'Mahjong Smiles', 'los-angeles-mahjong-smiles', (SELECT id FROM City WHERE name = 'Los Angeles' AND state = 'CA'), 'https://mahjongsmiles.com/', 'mahjongsmiles@gmail.com', 1, 1, 0, 1, NULL, 'Georgina & Sheri; private and hosted group American Mahjong instruction.', 'https://mahjongsmiles.com/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_los-angeles-la-la-mahjong', 'LA LA Mahjong', 'los-angeles-la-la-mahjong', (SELECT id FROM City WHERE name = 'Los Angeles' AND state = 'CA'), 'https://lalamahjong.com/', NULL, 0, 1, 0, 1, NULL, 'American Mahjong classes and guided play under NMJL rules.', 'https://lalamahjong.com/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_los-angeles-american-mahjong-beginner-101-20261003', 'American Mahjong - Beginner 101', 'los-angeles-american-mahjong-beginner-101-20261003', '2026-10-03 00:00:00', '09:30', '12:00', 'Lafayette Square', (SELECT id FROM City WHERE name = 'Los Angeles' AND state = 'CA'), (SELECT id FROM Club WHERE slug = 'los-angeles-la-la-mahjong'), NULL, 'LESSON', 1, NULL, NULL, 'https://lalamahjong.com/classes/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_los-angeles-american-mahjong-refresh-guided-play-class-102-20261004', 'American Mahjong Refresh/Guided Play Class 102', 'los-angeles-american-mahjong-refresh-guided-play-class-102-20261004', '2026-10-04 00:00:00', '09:30', '12:00', 'Lafayette Square', (SELECT id FROM City WHERE name = 'Los Angeles' AND state = 'CA'), (SELECT id FROM Club WHERE slug = 'los-angeles-la-la-mahjong'), NULL, 'LESSON', 0, NULL, NULL, 'https://lalamahjong.com/classes/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_los-angeles-intro-to-american-mahjong-class-series-20261005', 'Intro to American Mahjong Class Series', 'los-angeles-intro-to-american-mahjong-class-series-20261005', '2026-10-05 00:00:00', '19:00', '21:00', 'Venice Area', (SELECT id FROM City WHERE name = 'Los Angeles' AND state = 'CA'), (SELECT id FROM Club WHERE slug = 'los-angeles-mahjong-smiles'), NULL, 'LESSON', 1, NULL, NULL, 'https://mahjongsmiles.com/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
