INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_new-york-sparrow-s-nest-studio', 'Sparrow''s Nest Studio', 'new-york-sparrow-s-nest-studio', 'Manhattan mahjong studio offering American Mah Jongg beginner lessons and open play.', (SELECT id FROM City WHERE name = 'New York' AND state = 'NY'), '35 W 35th St, 12th Floor, New York, NY 10001', 'https://sparrowsneststudio.com/', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, 60, 'Open play Thu-Sun 4-10pm; American Mah Jongg beginner lesson $60.', 'https://sparrowsneststudio.com/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_new-york-congregation-habonim', 'Congregation Habonim', 'new-york-congregation-habonim', 'Upper West Side community offering American Mah Jongg beginner classes and regular open play.', (SELECT id FROM City WHERE name = 'New York' AND state = 'NY'), '103 West End Avenue, New York, NY 10023', 'https://www.habonim.net/mah-jongg', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, 10, 'Open play $10 non-members daytime / $15 evening; members free.', 'https://www.habonim.net/mah-jongg', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_new-york-ues-mahjong', 'UES Mahjong', 'new-york-ues-mahjong', (SELECT id FROM City WHERE name = 'New York' AND state = 'NY'), 'https://uesmahjong.com/', 'luskiashley@gmail.com', 1, 1, 0, 1, 100, 'Private $100/90 min; group $300/90 min.', 'https://uesmahjong.com/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_new-york-so-bam-fun-new-york', 'So Bam Fun New York', 'new-york-so-bam-fun-new-york', (SELECT id FROM City WHERE name = 'New York' AND state = 'NY'), 'https://sobamfun.com/', 'hello@sobamfun.com', 1, 1, 0, 1, NULL, 'Beginner-friendly American Mahjong lessons, private lessons and public events.', 'https://sobamfun.com/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_new-york-carnegie-hill-mahjong-20261015', 'Carnegie Hill Mahjong', 'new-york-carnegie-hill-mahjong-20261015', '2026-10-15 00:00:00', '12:00', '14:00', 'House of the Redeemer, 7 East 95th Street', (SELECT id FROM City WHERE name = 'New York' AND state = 'NY'), (SELECT id FROM Club WHERE slug = 'new-york-congregation-habonim'), NULL, 'OPEN_PLAY', 0, 55, NULL, 'https://happeningnext.com/event/carnegie-hill-mahjong-eid1ef0l69m7lra', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
