INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_phoenix-mahjong-for-people-who-work', 'Mahjong for People who Work', 'phoenix-mahjong-for-people-who-work', 'Phoenix Meetup group (534 members) with recurring games where American Mahjong may be played when enough players attend; beginners explicitly welcome.', (SELECT id FROM City WHERE name = 'Phoenix' AND state = 'AZ'), 'Fate Brewing Company, 4445 N 7th St, Phoenix, AZ 85014', 'https://www.meetup.com/american-mahjong-for-people-who-work/', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Wednesdays 5:00 PM at Fate Brewing Company (Phoenix); also Chandler-area sessions on other days.', 'https://www.meetup.com/american-mahjong-for-people-who-work/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_phoenix-mahj-mind', 'Mahj Mind', 'phoenix-mahj-mind', (SELECT id FROM City WHERE name = 'Phoenix' AND state = 'AZ'), 'https://mahjmindaz.com/', '480-239-8877; mahjmind@gmail.com', 1, 1, 0, 1, NULL, 'American Mahjong classes beginner to advanced, open play and private group parties; NMJL standard. Instructor Katie Petrine (Mahj Life Instructor Guild).', 'https://mahjmindaz.com/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_phoenix-maj-by-daron', 'Maj by Daron', 'phoenix-maj-by-daron', (SELECT id FROM City WHERE name = 'Phoenix' AND state = 'AZ'), 'https://www.majbydaron.com/', NULL, 1, 1, 0, 1, 70, 'Private $70/hr; group lessons (4-12 players) $225/person for a 4-5 lesson series; supervised play $25-35/person per 2-hour class. NMJL rules.', 'https://www.majbydaron.com/classes', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_phoenix-mod-mahj', 'Mod Mahj', 'phoenix-mod-mahj', (SELECT id FROM City WHERE name = 'Phoenix' AND state = 'AZ'), 'https://www.modmahj.com/pages/take-a-class-in-phoenix', NULL, 1, 1, 0, 1, NULL, 'Beginner, intermediate and advanced/strategy courses in Arcadia & Central Phoenix; instructor Jen serves the greater Phoenix area.', 'https://www.modmahj.com/pages/take-a-class-in-phoenix', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_phoenix-so-bam-fun-phoenix', 'So Bam Fun Phoenix', 'phoenix-so-bam-fun-phoenix', (SELECT id FROM City WHERE name = 'Phoenix' AND state = 'AZ'), 'https://www.sobamfun.com/phoenix', 'hello@sobamfun.com', 1, 1, 0, 1, 300, 'Private group lessons, 2-hour sessions, from $300; instructors travel to client''s home/office/venue across the Phoenix metro.', 'https://www.sobamfun.com/phoenix', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_phoenix-joan-s', 'Joan S.', 'phoenix-joan-s', (SELECT id FROM City WHERE name = 'Phoenix' AND state = 'AZ'), NULL, 'joansitver@aol.com', 1, 0, 0, 1, NULL, 'Listed as an American Mah Jongg teacher in Central Phoenix on a third-party instructor directory; no personal site to independently verify lesson format or pricing.', 'https://wherethewindsblow.com/teachers/', '2026-09-28', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_phoenix-mahjong-at-fate-brewing-20260930', 'Mahjong at Fate Brewing', 'phoenix-mahjong-at-fate-brewing-20260930', '2026-09-30 00:00:00', '17:00', '19:00', 'Fate Brewing Company, 4445 N 7th St', (SELECT id FROM City WHERE name = 'Phoenix' AND state = 'AZ'), (SELECT id FROM Club WHERE slug = 'phoenix-mahjong-for-people-who-work'), NULL, 'OPEN_PLAY', 1, NULL, NULL, 'https://www.meetup.com/american-mahjong-for-people-who-work/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_phoenix-american-mahjong-open-play-20261107', 'American Mahjong Open Play', 'phoenix-american-mahjong-open-play-20261107', '2026-11-07 00:00:00', '12:30', '15:30', 'Desert Ridge Marketplace, 21001 North Tatum Boulevard, Phoenix, AZ 85050', (SELECT id FROM City WHERE name = 'Phoenix' AND state = 'AZ'), NULL, (SELECT id FROM Instructor WHERE slug = 'phoenix-mahj-mind'), 'OPEN_PLAY', 0, 0, 'https://www.eventbrite.com/e/american-mahjong-open-play-tickets-1994956125474', 'https://www.eventbrite.com/e/american-mahjong-open-play-tickets-1994956125474', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
