INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_phoenix-mahjong-for-people-who-work', 'Mahjong for People who Work', 'phoenix-mahjong-for-people-who-work', 'Phoenix Meetup group with recurring games where American Mahjong may be played when enough players attend.', (SELECT id FROM City WHERE name = 'Phoenix' AND state = 'AZ'), 'Fate Brewing Company, 4445 N 7th St, Phoenix, AZ 85014', 'https://www.meetup.com/american-mahjong-for-people-who-work/', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Recurring Phoenix-area games; multiple mahjong variants.', 'https://www.meetup.com/american-mahjong-for-people-who-work/', '2026-09-28', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_phoenix-mahj-mind', 'Mahj Mind', 'phoenix-mahj-mind', (SELECT id FROM City WHERE name = 'Phoenix' AND state = 'AZ'), 'https://mahjmindaz.com/', NULL, 1, 1, 0, 1, NULL, 'American Mahjong classes beginner to advanced, open play and private group parties; NMJL standard.', 'https://mahjmindaz.com/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_phoenix-maj-by-daron', 'Maj by Daron', 'phoenix-maj-by-daron', (SELECT id FROM City WHERE name = 'Phoenix' AND state = 'AZ'), NULL, NULL, 1, 1, 0, 1, 70, 'Beginner through advanced lessons by appointment; private $70/hr; NMJL rules.', 'https://www.bambuddies.org/mahjong-near-me/phoenix-scottsdale-az', '2026-09-28', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_phoenix-mahjong-at-fate-brewing-20260930', 'Mahjong at Fate Brewing', 'phoenix-mahjong-at-fate-brewing-20260930', '2026-09-30 00:00:00', '17:00', '19:00', 'Fate Brewing Company, 4445 N 7th St', (SELECT id FROM City WHERE name = 'Phoenix' AND state = 'AZ'), (SELECT id FROM Club WHERE slug = 'phoenix-mahjong-for-people-who-work'), NULL, 'OPEN_PLAY', 1, NULL, NULL, 'https://www.meetup.com/american-mahjong-for-people-who-work/', '2026-09-28', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
