INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_san-francisco-jccsf-mahjong-social-play', 'JCCSF Mahjong – Social Play', 'san-francisco-jccsf-mahjong-social-play', 'San Francisco Jewish Community Center hosting American Mah Jongg social play and beginner classes.', (SELECT id FROM City WHERE name = 'San Francisco' AND state = 'CA'), '3200 California St, San Francisco, CA 94118', 'https://www.jccsf.org/event/mahjong-social-play/2026-09-24/', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, 36, 'Social play $36; beginner class series also offered; Oct 22 recurring session.', 'https://www.jccsf.org/event/mahjong-social-play/2026-09-24/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_san-francisco-mahjong-with-kim', 'Mahjong with Kim', 'san-francisco-mahjong-with-kim', (SELECT id FROM City WHERE name = 'San Francisco' AND state = 'CA'), 'https://sites.google.com/view/mahjongwithkim/home', NULL, 1, 1, 1, 1, 450, 'Private lessons up to four players; American Mah Jongg series; online lessons also available.', 'https://sites.google.com/view/mahjongwithkim/home', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_san-francisco-so-bam-fun-san-francisco', 'So Bam Fun San Francisco', 'san-francisco-so-bam-fun-san-francisco', (SELECT id FROM City WHERE name = 'San Francisco' AND state = 'CA'), 'https://sobamfun.com/san-francisco/', 'hello@sobamfun.com', 1, 1, 0, 1, NULL, 'American Mahjong private lessons, social events and corporate team building.', 'https://sobamfun.com/san-francisco/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_san-francisco-mahjong-tuesday-at-united-dumplings-san-francisco-20261006', 'Mahjong Tuesday at United Dumplings San Francisco', 'san-francisco-mahjong-tuesday-at-united-dumplings-san-francisco-20261006', '2026-10-06 00:00:00', '17:30', '20:30', 'United Dumplings SF - Bernal Heights, 525 Cortland Ave', (SELECT id FROM City WHERE name = 'San Francisco' AND state = 'CA'), (SELECT id FROM Club WHERE name = 'So Bam Fun / Play Mahjong SF' AND cityId = (SELECT id FROM City WHERE name = 'San Francisco' AND state = 'CA')), NULL, 'OPEN_PLAY', 1, NULL, NULL, 'https://www.playmahjongsf.com/events', '2026-09-28', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_san-francisco-mahjong-tuesday-at-united-dumplings-san-francisco-20261020', 'Mahjong Tuesday at United Dumplings San Francisco', 'san-francisco-mahjong-tuesday-at-united-dumplings-san-francisco-20261020', '2026-10-20 00:00:00', '17:30', '20:30', 'United Dumplings SF - Bernal Heights, 525 Cortland Ave', (SELECT id FROM City WHERE name = 'San Francisco' AND state = 'CA'), (SELECT id FROM Club WHERE name = 'So Bam Fun / Play Mahjong SF' AND cityId = (SELECT id FROM City WHERE name = 'San Francisco' AND state = 'CA')), NULL, 'OPEN_PLAY', 1, NULL, NULL, 'https://www.playmahjongsf.com/events', '2026-09-28', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
