INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_scottsdale-phoenix-mahjong-club', 'Phoenix Mahjong Club', 'scottsdale-phoenix-mahjong-club', 'American Mah Jongg storefront club in Old Town Scottsdale with open play, socials, lessons and leagues.', (SELECT id FROM City WHERE name = 'Scottsdale' AND state = 'AZ'), '4821 N Scottsdale Road, Unit 106, Scottsdale, AZ 85251', 'https://phoenixmahjongclub.com/', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, 115, 'Beginner 3-hour lessons $115; weekly open play/drop-in/social blocks.', 'https://phoenixmahjongclub.com/join-the-club/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Club" ("id", "name", "slug", "description", "cityId", "address", "website", "phone", "email", "latitude", "longitude", "beginnerFriendly", "lessonsAvailable", "openPlay", "socialPlay", "womenOnly", "free", "price", "schedule", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('club_scottsdale-scottsdale-mahjong-society', 'Scottsdale Mahjong Society', 'scottsdale-scottsdale-mahjong-society', 'Scottsdale American Mahjong community offering open play, beginner/intermediate lessons and seasonal leagues.', (SELECT id FROM City WHERE name = 'Scottsdale' AND state = 'AZ'), NULL, 'https://scottsdalemahjongsociety.com/', NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, NULL, 'Open play, Mahj 101/102 lessons and seasonal leagues using NMJL rules.', 'https://scottsdalemahjongsociety.com/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "description" = excluded."description", "cityId" = excluded."cityId", "address" = excluded."address", "website" = excluded."website", "phone" = excluded."phone", "email" = excluded."email", "latitude" = excluded."latitude", "longitude" = excluded."longitude", "beginnerFriendly" = excluded."beginnerFriendly", "lessonsAvailable" = excluded."lessonsAvailable", "openPlay" = excluded."openPlay", "socialPlay" = excluded."socialPlay", "womenOnly" = excluded."womenOnly", "free" = excluded."free", "price" = excluded."price", "schedule" = excluded."schedule", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_scottsdale-phoenix-mahjong-club', 'Phoenix Mahjong Club', 'scottsdale-phoenix-mahjong-club', (SELECT id FROM City WHERE name = 'Scottsdale' AND state = 'AZ'), 'https://phoenixmahjongclub.com/', 'info@phoenixmahjongclub.com', 1, 1, 0, 1, 115, 'Beginner 3-hour lesson $115 including NMJL card on the 2026 check date.', 'https://phoenixmahjongclub.com/events/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Instructor" ("id", "name", "slug", "cityId", "website", "contact", "privateLesson", "groupLesson", "onlineLesson", "beginnerLesson", "price", "notes", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('instructor_scottsdale-scottsdale-mahjong-society', 'Scottsdale Mahjong Society', 'scottsdale-scottsdale-mahjong-society', (SELECT id FROM City WHERE name = 'Scottsdale' AND state = 'AZ'), 'https://scottsdalemahjongsociety.com/', 'support@scottsdalemahjongsociety.com', 1, 1, 0, 1, NULL, 'Mahj 101 beginner lessons, higher-level sessions, open play and seasonal leagues.', 'https://scottsdalemahjongsociety.com/', '2026-09-28', 'ACTIVE')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "cityId" = excluded."cityId", "website" = excluded."website", "contact" = excluded."contact", "privateLesson" = excluded."privateLesson", "groupLesson" = excluded."groupLesson", "onlineLesson" = excluded."onlineLesson", "beginnerLesson" = excluded."beginnerLesson", "price" = excluded."price", "notes" = excluded."notes", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Event" ("id", "name", "slug", "eventDate", "startTime", "endTime", "venue", "cityId", "clubId", "instructorId", "eventType", "beginnerFriendly", "price", "registrationUrl", "sourceUrl", "lastVerifiedAt", "status")
VALUES ('event_scottsdale-mahj-monday-open-play-20260928', 'Mahj Monday - Open Play', 'scottsdale-mahj-monday-open-play-20260928', '2026-09-28 00:00:00', '17:30', '19:30', 'Pinnacle Brewing Company, Scottsdale, AZ', (SELECT id FROM City WHERE name = 'Scottsdale' AND state = 'AZ'), (SELECT id FROM Club WHERE name = 'Scottsdale Mahjong House' AND cityId = (SELECT id FROM City WHERE name = 'Scottsdale' AND state = 'AZ')), NULL, 'OPEN_PLAY', 0, NULL, NULL, NULL, '2026-09-28', 'NEEDS_REVIEW')
ON CONFLICT("slug") DO UPDATE SET "name" = excluded."name", "eventDate" = excluded."eventDate", "startTime" = excluded."startTime", "endTime" = excluded."endTime", "venue" = excluded."venue", "cityId" = excluded."cityId", "clubId" = excluded."clubId", "instructorId" = excluded."instructorId", "eventType" = excluded."eventType", "beginnerFriendly" = excluded."beginnerFriendly", "price" = excluded."price", "registrationUrl" = excluded."registrationUrl", "sourceUrl" = excluded."sourceUrl", "lastVerifiedAt" = excluded."lastVerifiedAt", "status" = excluded."status", "updatedAt" = CURRENT_TIMESTAMP;
